### ISSUE TITLE
[i18n] Migrate to the Crowdin platform

### ISSUE THREAD

**Issue by MS-PC** [pi-hole/web#107]
I was wondering if you can migrate to the Crowdin platform for translations. I think it is much more effective since there are many more translators in Crowdin. I would help as proofreader with the Spanish language.
It should be noted that this is only a suggestion.

**Comment by Mcat12** [comment]
Thank you for the suggestion. We will look into the platform. It looks like they do support open source projects, which is good: https://crowdin.com/page/open-source-project-setup-request

**Comment by Mcat12** [comment]
We have migrated to Crowdin: https://crowdin.com/project/pi-hole

**Comment by MS-PC** [comment]
Thanks. :+1:
