### ISSUE TITLE
Settings Manipulation Framework

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#11]
Create a framework for reading and modifying various Pi-hole settings.

The API will handle the actual reading, validating, and modification of settings, but the web interface should also do some validation before sending the data off to the API.

The tab-layout of the PHP interface seems to work pretty well, so that is a possible layout we can use.

The actual input should be simple, just fancy forms.

This issue tracks the framework and guidelines for creating settings pages. Individual settings pages may or may not get their own tracking issue.

**Comment by walter-exit** [comment]
Displaying settings in the webinterface in a tabbed fashion sounds effective. Tabs at the top, tabs at the left, as long as its properly gathered per subject.

JS validation of user input is always smart, and easiest for incorporating direct feedback to a user when problems with the input arise. Yet, backend validation if the same input is an absolute must in my opinion. Double work, yet double safe ;-)

There are plenty of JS scripts around that offer decent validation functions for the GUI.
