### ISSUE TITLE
[i18n] Change localization management

### ISSUE THREAD

**Issue by Manfre98** [pi-hole/web#111]
I am still a beginner when it comes to code, so I can't really help with that, I'm only requesting a change in the localization management. By this I mean to _ditch_ the current implementation of strings and use a library based on the ICU standard for plural strings: Yahoo's [Intl MessageFormat](https://github.com/yahoo/intl-messageformat).
By using this new string management the translators would be able to have language specific rules such as:
- Display numbers with separators.
- Display dates and times correctly.
- Display dates relative to "now".
- Pluralize labels in strings.

All of this is explained on Yahoo's [website](https://formatjs.io/).

**Comment by Mcat12** [comment]
This project uses [i18next[(https://www.i18next.com/), which supports the ICU standard and seems to support all the feature you list.

**Comment by Manfre98** [comment]
It's not that easy to handle multiple variables in a string, for instance, on Intl MessageFormat we have this string:
```{numUsers, plural, one{# person} other{# people}} entered the bar and bought {numWater, plural, one{# bottle} other{# bottles}} of water. They leaved after {timeInside, plural, one{# minute} other{# minutes}}.```
_209 chars in length_

If we are going to translate this sentence, for example in Italian (my native language) it would be like this:
`{numUsers, plural, one{# persona è entrata} other{# persone sono entrate}} in un bar e {numUsers, plural, one{ha} other{hanno}} comprato {numWater, plural, one{# bottiglia} other{# bottiglie}} d'acqua. {numUsers, plural, one{È uscito} other{Sono usciti}} dopo {timeInside, plural, one{# minuto} other{# minuti}}`
_311 chars in length_
(numUsers is used 3 times because of Italian language rules, many different verbs can change based on the number of people)

On i18next it would be like this:
```
{
  "numUsers": "{{count}} person entered the bar and bought $t(numWater, {'count': {{numWater}} }) $t(timeInside, {'count': {{timeInside}} })",
  "numUsers_plural": "{{count}} people entered the bar and bought $t(numWater, {'count': {{numWater}} }) $t(timeInside, {'count': {{timeInside}} })",
  "numWater": "{{count}} bottle of water.",
  "numWater_plural": "{{count}} bottles of water.",
  "timeInside": "They leaved after {{count}} minute.",
  "timeInside_plural": "They leaved after {{count}} minutes."
}
```
_516 chars in length_

Translated it would be like this:
```
{
  "numUsers": "{{count}} persona è entrata in un bar e ha comprato $t(numWater, {'count': {{numWater}} }) È uscito $t(timeInside, {'count': {{timeInside}} })",
  "numUsers_plural": "{{count}} persone sono entrate in un bar e hanno comprato $t(numWater, {'count': {{numWater}} }) Sono usciti $t(timeInside, {'count': {{timeInside}} })",
  "numWater": "{{count}} bottiglia d'acqua.",
  "numWater_plural": "{{count}} bottiglie d'acqua.",
  "timeInside": "dopo {{count}} minuto.",
  "timeInside_plural": "dopo {{count}} minuti."
}
```
_535 chars in length_

You can see that the strings are much longer, and it's also very difficult to adapt the strings in other languages.

**Comment by Mcat12** [comment]
Changing the localization system is not a top priority compared to actually finishing the MVP of the web interface. The current system works well, though if you think it should work differently, you're welcome to make a pull request to change it.

**Comment by Mcat12** [comment]
Closing, as this issue is only seen if you edit the translation data files manually (which is not how we handle translations). Editing the translations on a web interface is as easy as the web interface lets it be. With the move to Crowdin (#107), editing translations should be very easy.
