### ISSUE TITLE
Display Actual Versions

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#12]
Display versions and branches of Pi-hole components in the settings page:
- Core
- Web
- FTL
- API

This data will be obtained from the API. The version will be displayed when on a stable release, while on development versions the `git describe` output along with the branch will be displayed.

The footer will contain the status of the installation, such as "Up to Date", "Update Available", or "Development Version". The text will link to the settings page so the user can view the versions.

**Comment by Mcat12** [comment]
Good idea. The footer could be empty when up to date and show an update message when there's an update, then link to a page in the settings page which shows what needs to be updated. When on a development branch, we might want to put in a small message like `Development Version` into the footer.

**Comment by walter-exit** [comment]
Well, if there is room, I find the "Up to date" text very reassuring to see. More so than nothing at all. But this is of course just my personal preference. I'd love for it to be a democratic decision.

**Comment by PromoFaux** [comment]
Perhaps we could display more detailed version information on the `System` tab of the `Settings` page here:

![image](https://user-images.githubusercontent.com/1998970/39896926-1b7a4c5a-54a8-11e8-9575-3d70064edecd.png)

Something like commit id, branch name, local location (`/etc/.pihole` or `/var/www/html/admin`)

**Comment by Mcat12** [comment]
Closed by #62
