### ISSUE TITLE
devel: checkboxes look bad for the default theme

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#1317]
Maybe it's possible to skip using that JS plugin with the default theme?

I didn't quite follow the progress there, so I'm not sure why it was needed.

**Comment by DL6ER** [comment]
How does it look like when you skip the JS plugin?

**Comment by XhmikosR** [comment]
You mean just skip loading scripts/vendor/iCheck.min.js? How about its CSS files? I should be able to try in the next days.

**Comment by DL6ER** [comment]
We can add an `if` for empty `checkbox_theme_name` around

https://github.com/pi-hole/AdminLTE/blob/9809cfee9dba3b6c521f25f02727d13a4e5ad98a/scripts/pi-hole/php/header.php#L232-L233

and similarly skip

https://github.com/pi-hole/AdminLTE/blob/9809cfee9dba3b6c521f25f02727d13a4e5ad98a/scripts/pi-hole/js/footer.js#L126-L130

if `checkbox_theme` is empty.

Both will happen when you have the last two fields empty here:
https://github.com/pi-hole/AdminLTE/blob/9809cfee9dba3b6c521f25f02727d13a4e5ad98a/scripts/pi-hole/php/theme.php#L18
