### ISSUE TITLE
Teleporter import does not include comments

### ISSUE THREAD

**Issue by infinitytec** [pi-hole/web#1331]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

When importing from teleporter any comments (for example, the comments on a whitelist entry) should appear on the Pi-hole that is getting the teleporter input.

I run two Pi-holes and have notes on my whitelists on one of them. I would expect that the notes would be imported to the other Pi-hole via teleporter, and in fact the json for the whitelist has the comments in it.

**Actual behaviour:**

The teleporter import replaces all comments with something along the lines of "Migrated from /etc/pihole/whitelist.txt" rather than pulling the comment from the whitelist json file in the teleporter export.

**Steps to reproduce:**

1. On one Pi-hole make comments in the whitelist using the web console
2. Run the teleporter export on the web console on the Pi-hole
3. On a second Pi-hole import the first's export and the comments will not be what was on the first's.
4. Extract the teleporter file an investigate the json for the whitelist. It will show the comments that did not get imported.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
xiasumc1ll

**Troubleshooting undertaken, and/or other relevant information:**

None really. It's more of a minor inconvenience, but I would like to synchronize the comments.

**Comment by DL6ER** [comment]
> "Migrated from /etc/pihole/whitelist.txt"

Do you have a file `whitelist.txt` in the exported file?

**Comment by infinitytec** [comment]
> > "Migrated from /etc/pihole/whitelist.txt"
> 
> Do you have a file `whitelist.txt` in the exported file?

Nope. 
![image](https://user-images.githubusercontent.com/13670462/82342863-bef4ca80-99b7-11ea-9e45-8b07bf1bb0e2.png)

**Comment by infinitytec** [comment]
It looks like the adlist import includes comments.

**Comment by yubiuser** [comment]
Tried it today. Teleporter exported and imported comments from white/blacklist successfully. Re-open if issue persists

**Comment by infinitytec** [comment]
Ah, must have been fixed and I didn't notice!

Thanks!
