### ISSUE TITLE
Update Chart.js to the latest version

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#1345]
I initially attempted to do it in #1115, but https://github.com/pi-hole/AdminLTE/pull/1115#issuecomment-627561372:

>This changes the animation for the charts.
>
> **devel**
> ![ezgif-1-4aa28875e195](https://user-images.githubusercontent.com/16748619/81739553-d7d31c80-949b-11ea-9cbd-c5e1dbdb7c25.gif)
>
> **your branch**
> ![ezgif-1-1e4070ceb80d](https://user-images.githubusercontent.com/16748619/81739572-df92c100-949b-11ea-8721-31cd53ba32bc.gif)

Being that Chart.js has quite a few improvements so far, including performance ones, we should update it.

Unfortunately, from a quick look I had, I couldn't make the loading animation the same. I tried `animation.duration = 0` and even `animation: false`.

**Comment by XhmikosR** [comment]
So, I tried some Chart.js versions [here](https://github.com/pi-hole/AdminLTE/compare/devel...update-chartjs) and it seems this issue appears since v2.7.2. Currently we are using v2.7.1 in devel.

https://github.com/chartjs/Chart.js/releases/tag/v2.7.2

So, it leads me to believe we are probably doing something wrong in our code.

**EDIT:**

After further investigation, maybe we are calling `update()` too much or the options aren't properly set hence Chart.js animates the chart on each `update()` call. 

Found [this patch](https://github.com/chartjs/Chart.js/pull/4198/files?file-filters%5B%5D=.js#diff-de7249441169d0e646c53d8220e8b0c5) which was added in 2.7.2, and here are the docs: https://www.chartjs.org/docs/latest/developers/updates.html#updating-options

**Comment by XhmikosR** [comment]
After further investigation, maybe we are calling `update()` too much or the options aren't properly set hence Chart.js animates the chart on each `update()` call. 

Found [this patch](https://github.com/chartjs/Chart.js/pull/4198/files?file-filters%5B%5D=.js#diff-de7249441169d0e646c53d8220e8b0c5) which was added in 2.7.2, and here are the docs: https://www.chartjs.org/docs/latest/developers/updates.html#updating-options

**Comment by DL6ER** [comment]
This seems to be a bug (one could also say unintended side-effect) they introduced. We're not the only once making errors. Disabling the animation altogether feels like a bandaid fix compared to the smooth animations we had before.

As their documentation how to add stacked bar data changed slightly, I added these changes to our code and voila, it seems to work. Please check my changes pushed to #1424

**Comment by XhmikosR** [comment]
Fixed in #1424
