### ISSUE TITLE
Stop using `window.open` when possible

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#1353]
https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Usability_issues

Now, from a quick look, it seems we can easily fix this at least for the tables. I'll take a stab at it later.

For charts is a different case because we currently misuse their built-in left click to remove items from charts. I'm open to suggestions about this. We could go with a combination of keys, but I'm not sure how to handle devices without a mouse.

**Comment by paul-man** [comment]
I think `window.open(url, '_blank')` is still acceptable, but the other usages would need to be updated.

As for the charts, how does this look?
![image](https://user-images.githubusercontent.com/10479093/144326334-2447e7cf-ed90-4d28-9b33-dd45dc9dc3e8.png)
Clicking the eye would perform the current logic of the middle mouse button (hide from the chart) and clicking the rest of the list item would perform the current left click logic (navigate to the queries page).

**Comment by yubiuser** [comment]
@paul-man 

I like it a lot as it makes the somehow "hidden" feature of the middle-mouse button more obvious and can be performed on touchscreen only devices as well.

**Comment by paul-man** [comment]
I honestly didn't know about hiding parts of the pie until I looked into this issue!
I tested my mockup on mobile and the eye-con feels a tiny bit small, but I also have large fingers lol. I'll play around with the icon sizes and put up a PR

**Comment by paul-man** [comment]
This was resolved in #1996 which was included in the most recent release, should this be closed?

**Comment by yubiuser** [comment]
The fixed was released with
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
