### ISSUE TITLE
Attempting to whitelist a blacklisted domain fails, but produces a success message

### ISSUE THREAD

**Issue by daprice** [pi-hole/web#1355]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Domain should be removed from blacklist and added to whitelist. Also, success/failure messages should accurately reflect whether the operation succeeded or failed.

**Actual behaviour:**

The message “[domain] successfully added to the Whitelist” is displayed, but the domain remains in the blacklist and does not appear in the whitelist like the message claims.

**Steps to reproduce:**

1. Add a domain to the blacklist
2. Attempt to query the domain so that it appears in the Query Log with status “Blocked (exact blacklist)”
3. On the Query Log page, press the “Whitelist” button for the domain

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/6vupkg6vso`

**Troubleshooting undertaken, and/or other relevant information:**

Worked around by manually removing the domain from the blacklist and then manually adding it to the whitelist.

**Comment by PromoFaux** [comment]
Thanks for the report, this was spotted shortly after release and we have a fix already for the next release :) See https://github.com/pi-hole/AdminLTE/pull/1286/

![blackwhitelist](https://user-images.githubusercontent.com/1998970/82725935-77807e00-9cd8-11ea-90c0-90c80bb7e369.gif)

**Comment by KommX** [comment]
This one should be fixed in the meanwhile:
https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577

Can this issue be closed?
