### ISSUE TITLE
Feature request: Configure clients by MAC address instead of IP address?

### ISSUE THREAD

**Issue by simX** [pi-hole/web#1364]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

When going to client group management, I can add and edit a list of clients by IP address.  However, often on my network, individual devices don't have the same IP address when they browse the network the next day, since my router uses DHCP to dynamically give out IP addresses to clients.

Pi-hole knows about MAC addresses, which are far more stable (though sometimes not totally) than IP addresses.  I can see in the Network Overview tab that Pi-hole has the ability to see hardware MAC addresses, and checking those with what I see on the devices themselves confirms that the MAC addresses seen by Pi-hole are accurate.

So: can we instead be allowed to configure clients by MAC address in addition to by IP address?  That way, people with networks that use DHCP dynamic addressing can still use clients and groups in a natural way, without having to fix the IPs of the devices they want to have separate configurations for?

**Actual behaviour:**

Clients can only be configured by IP address.

1.  Log in to the Pi-hole Web UI.
2.  Reveal the Group Management submenu.
3.  Click on the "Clients" tab.
4.  Click on the Known Clients dropdown -- observe that only IPv4 and IPv6 addresses are populated here.  Also note that the custom address field specifically says "IPv4 or IPv6".

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/wllu177f38`

**Troubleshooting undertaken, and/or other relevant information:**

I've only searched through the issues and pull requests on Github to see if anybody else has requested this feature.  I don't know how difficult it is, and I haven't delved into the codebase yet.  I may be able to create a pull request if someone can point me in the right direction about where to look, but this seems like a not simple change, since it would require work in both the Core and the Web UI.

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/feedback-for-allow-defining-clients-by-their-mac-address-host-name-and-networking-interface/

https://github.com/pi-hole/AdminLTE/pull/1285

Feature requests should be raised on discourse.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
