### ISSUE TITLE
Tables: make sure we use a `thead`

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#1378]
There are some tables that don't have a `thead`. We should make sure every table has a `thead` assuming it's needed, instead of adding a `tr` in `tbody` that behaves like a `thead`.

**Comment by paul-man** [comment]
This was resolved in #1991 which was included in the most recent release, should this be closed?

**Comment by yubiuser** [comment]
Yes :)

The fixed was released with
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
