### ISSUE TITLE
CPU temperature not aligned when using firefox.

### ISSUE THREAD

**Issue by ruscogit** [pi-hole/web#140]
##### Expected Behaviour:

Microsoft Edge seems to be able to display it properly.

![edge](https://cloud.githubusercontent.com/assets/13407145/18528515/5409e1c6-7a97-11e6-9742-21168b9dbb85.PNG)
##### Actual Behaviour:

Firefox seems to have issues. The temperature is listed, but just out of view. 
![firefox](https://cloud.githubusercontent.com/assets/13407145/18528516/540a2adc-7a97-11e6-98c9-c721112a0b5a.PNG)
##### Steps to reproduce this issue:

Open firefox and navigate to pi.hole/admin
##

**Comment by codebucketdev** [comment]
+1

**Comment by Mcat12** [comment]
I believe this is a problem with how Firefox handles SVG images.

**Comment by codebucketdev** [comment]
Not really, because it handles the other one correctly.

**Comment by Mcat12** [comment]
I remember reading something about firefox and wanting svgs with CSS sizes instead of in the html, so maybe that's it?

**Comment by TylonHH** [comment]
And as you see in the references mentioned above it's not just the temperature.

**Comment by PromoFaux** [comment]
OK, i've had a little look into this, but I'm no CSS wizard.. Someone like @brantje may have more luck! (maybe @Mcat12 too!)

It seems to be an issue with the `pull-left` style. To test, remove `pull-left` from lines 126 and 129 in `/var/www/html/admin/header.php`

It's still not showing correctly, but it's a start...

**Comment by PromoFaux** [comment]
OK, removing it from line 129 breaks chrome, too.

**Comment by PromoFaux** [comment]
Getting closer, but it's still not there:

![image](https://cloud.githubusercontent.com/assets/1998970/18617541/dfef4282-7dc9-11e6-97ac-1dd052ecd310.png)

**Comment by PromoFaux** [comment]
Got it! 

![image](https://cloud.githubusercontent.com/assets/1998970/18617557/36f6f912-7dca-11e6-80b5-bd444168bcc0.png)


But now the slide in/out menu does not work on firefox.... 😫

**Comment by PromoFaux** [comment]
Actually, going back to the base code, it looks like the slide in/out menu never worked on Firefox... can somebody else confirm, please?

**Comment by PromoFaux** [comment]
Scratch that.. I was on the wrong page, the JS had not loaded.... 

OK, so this can be fixed with the following changes:

Line 126 to ` <div class="col-xs-4 image">`

Line 129 to ` <div class="col-xs-7 info">`

But I am sure a more elegant solution can be found by someone who knows what they're doing....

**Comment by PromoFaux** [comment]
Wrapping those two `<div>`s in a `<div class="row">` is closer still, but the status box does not disappear when you collapse the sidebar

**Comment by cybergrimes** [comment]
I'm having a hard time determining if this issue is supposed to be fixed-- a lot of duplicate issues, this one appears to be closed most recently. New user to PH today but not seeing these icons in Firefox v50 however they do show in Opera. Thanks!

**Comment by Mcat12** [comment]
Sorry, I meant to add a label to this issue.
