### ISSUE TITLE
Feature request: Show IP addresses on DNS Settings page -> DNS tab -> Upstream DNS Servers

### ISSUE THREAD

**Issue by edhedges** [pi-hole/web#141]
I'm willing to add this feature sometime in the near future, but it's something I would enjoy as a user. I noticed in the screenshot below the data is already there on the client, but it'd be good to put it in the table, probably right by the checkbox it's correlated to.

![image](https://user-images.githubusercontent.com/825537/51634794-c23e8a00-1f1a-11e9-9549-4042de039dbf.png)

If you approve this feature request and you'd like me contribute, let me know if there's contribution guideline docs and I'll get started.

**Comment by Mcat12** [comment]
This repo is the upcoming React version of the web interface. It already has this feature. You seem to be asking about the PHP web interface, which is located here: https://github.com/pi-hole/AdminLTE

**Comment by edhedges** [comment]
@Mcat12 Ah, okay. I just setup my pi-hole a few days ago and incorrectly assumed it was the React version. Would it make sense for me to close this issue and open a replica issue in the AdminLTE repo or just go ahead an implement it there?

**Comment by Mcat12** [comment]
Feature requests should be made on discourse.pi-hole.net. I'll close the issue here, and you can open a feature request there. If you want to implement it, you could start working on it and open a PR instead.
