### ISSUE TITLE
Sorting Query Log by IP should be numerical instead of lexicographic.

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1450]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Sorting Query Log (and probably Long term database/Query Log) by IP should be numerical.

**Actual behaviour:**

Sorting Query Log (and probably Long term database/Query Log) by IP should is lexicographic.
![Bildschirmfoto zu 2020-06-06 21-30-59](https://user-images.githubusercontent.com/26622301/83953842-2d54dc00-a844-11ea-8d00-9f3e9135cdd4.png)

**Steps to reproduce:**

Suppress RESOLVE_IPV4 in `/etc/pihole/pihole-FTL.conf`, send DNS requests from clients with suitable IP addresses. Sort by IP in Query Log.

Behavior seen on current `devel`

**Comment by PromoFaux** [comment]
Please try `pihole checkout web ip-sorting-query`

My main concern about using the same approach as other tables is that this there _could_ be hostnames mixed into this column, too, but from a brief test with a mixture it does appear to still sort properly.

**Comment by yubiuser** [comment]
Thanks. Works well without hostname resolution.

![Bildschirmfoto zu 2020-06-07 12-48-04](https://user-images.githubusercontent.com/26622301/83966924-9e84a580-a8bd-11ea-92ee-74c1a3e2083b.png)

I tried to create a mixed IP&hostname environment by deleting some entries in Local DNS records and flush network table. Unfortunately flushing resulted in php error
`PHP error (2): implode(): Invalid arguments passed in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:716`

**Comment by yubiuser** [comment]
@PromoFaux Any progress on that?

**Comment by PromoFaux** [comment]
Oh.. did this not make it into 5.1? I could have sworn....

**Comment by yubiuser** [comment]
I haven't see a PR ;-)

**Comment by PromoFaux** [comment]
Gosh, I'm a scatterbrain

**Comment by yubiuser** [comment]
Linking for reference
https://github.com/pi-hole/AdminLTE/pull/1498

**Comment by yubiuser** [comment]
Fixed with the release of web v5. 1.1
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-2-released/36964
Closing
