### ISSUE TITLE
The teleporter.php does not correctly validate the extension when uploading the file

### ISSUE THREAD

**Issue by niebardzo** [pi-hole/web#1455]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

9

---
**Expected behaviour:**

The teleporter.php should allow to only upload the files with the extension ".tar.gz".

**Actual behaviour:**

The teleporter code [LINK](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/teleporter.php), first takes the "name" and splits it based on "." (LINE 300), then the second name[1] and third name[2] part is checked - (LINE 310). Someone can upload the file with the following name:

test.tar.gz.php

, which is going to be accepted as only the second and third part are validated. The real extension on file system would be a php.

**Steps to reproduce:**

1. Rename your file e.g. test.tar.gz extension to test.tar.gz.php.
2. Upload the file to the teleporter.php

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
