### ISSUE TITLE
HTML code visible in tooltip in black/whitelist

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1457]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No HTML in tooltip.

**Actual behaviour:**

HTML in tooltip.

![Bildschirmfoto zu 2020-06-12 10-40-43](https://user-images.githubusercontent.com/26622301/84485111-f6dfec80-ac9b-11ea-9b3a-1a031b9a5d6d.png)

**Steps to reproduce:**

  AdminLTE version is devel v5.0-387-g557bd858 (Latest: v5.

**Comment by XhmikosR** [comment]
Fixed by #1460.
