### ISSUE TITLE
Inconsistent API types

### ISSUE THREAD

**Issue by Scratchcat1** [pi-hole/web#1459]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

Expect `admin/api.php?topClientsBlocked` on a fresh install to return `{"top_sources_blocked":{}}`

**Actual behaviour:**

Instead `{"top_sources_blocked":[]}` is returned (a list instead of a map). 

**Steps to reproduce:**

Request `admin/api.php?topClientsBlocked` while signed in. This probably applies to any endpoint which initially creates an empty array and then adds mapped values.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

This appears to occur because each returned object is built from an initial call to `array()` to which each mapped value is added. If there are no mapped values this is encoded as an array rather than a map. If there are values it is correctly converted to a map.

This causes issues for deserializers such as Serde in Rust which differentiate between an empty map and array.

**Comment by DL6ER** [comment]
The current API grew both organically and with outside contributions which were not really all streamlined to ensure the output will always have a guaranteed form. For Pi-hole v6.0, we're currently redesigning the API from scratch (a REST approach is taken this time) in https://github.com/pi-hole/FTL/pull/659. There isn't all that much documentation available at the moment, however, this will come as soon as time allows.

It still isn't clear how a documentation should look like. Maybe similar to  https://docs.readthedocs.io/en/stable/api/v3.html#resources
