### ISSUE TITLE
This should be simplified later. There's no reason for us not to use unique classes in the buttons.

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#1461]
This should be simplified later. There's no reason for us not to use unique classes in the buttons.

_Originally posted by @XhmikosR in https://github.com/pi-hole/AdminLTE/pull/1284#issuecomment-636289733_

**Comment by rdwebdesign** [comment]
@XhmikosR
Is this still needed?

**Comment by rdwebdesign** [comment]
Closed by #1952
