### ISSUE TITLE
Repairing installation overwrites customizations to web admin server settings

### ISSUE THREAD

**Issue by chucksense** [pi-hole/web#1463]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`pihole -r` repairing installation detects lighttpd configuration deviation from default and asks how to proceed.

**Actual behaviour:**

`pihole -r` reverts all settings.

**Steps to reproduce:**

1. Adjust the lighttpd.conf to change the port.
2. Run `pihole -r`
3. Select repair

lighttpd.conf is moved to lighttpd.conf.org and new lighttpd.conf is put in place, but it's back to the default port when I've overridden to a new port.

**Troubleshooting undertaken, and/or other relevant information:**

After repairing I manually reverted back to my change.

**Comment by yubiuser** [comment]
> but it's back to the default port when I've overridden to a new port.

This is the reason the file clearly state on top

```
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################
```

https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian
