### ISSUE TITLE
Dashboard "Queries answered by" still list blocklist despite the term was omitted in v5.0

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1468]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Dashboard "Queries answered by - blocklist" should be renamed to "adlists" (like in Settings/Group Management) or "gravity" (like in query log)

**Actual behaviour:**

Dashboard "Queries answered by" still list blocklist despite the term was omitted in v5.0.

![Bildschirmfoto zu 2020-06-22 12-17-20](https://user-images.githubusercontent.com/26622301/85277015-f6f1a080-b482-11ea-8232-7bfb99dffc8f.png)

**Steps to reproduce:**

Go to dashboard

**Comment by yubiuser** [comment]
Still an issue

**Comment by rdwebdesign** [comment]
Maybe this should be modified to "blocked".

**Comment by yubiuser** [comment]
Would be fixed by https://github.com/pi-hole/FTL/pull/1299 and https://github.com/pi-hole/AdminLTE/pull/2119

**Comment by yubiuser** [comment]
Fixed in https://github.com/pi-hole/FTL/releases/tag/v5.14
