### ISSUE TITLE
DB write issue since update to 5.0

### ISSUE THREAD

**Issue by Xalio** [pi-hole/web#1469]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
1
---

**[BUG | ISSUE] Expected Behaviour:**
Trying to add or delete entry from whitelist is performed through the UI

**[BUG | ISSUE] Actual Behaviour:**
When trying to add/delete URL to the whitelist from the UI I get a DB write issue (saying my Database is read only).
It works from the Command line.

**[BUG | ISSUE] Steps to reproduce:**
- Try to add an URL in the whitelist
- Get the error message
- Same error message when trying to remove URL from whitelist
- Works via CLI with pihole -w url.domain.tld

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: rPi v3

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by firewiremb** [comment]
I have got the same issue.

![Auswahl_077](https://user-images.githubusercontent.com/63193396/85540866-c42ce100-b617-11ea-9743-e4d3efe63760.jpg)
![Auswahl_076](https://user-images.githubusercontent.com/63193396/85540898-cbec8580-b617-11ea-8edf-0c21cdef0285.jpg)

**Comment by yubiuser** [comment]
.. and probably the same fix applies here. What webserver do you use?

**Comment by dschaper** [comment]
As yubiuser notes, only `lighttpd` is supported. Other webservers are community supported at https://discourse.pi-hole.net
