### ISSUE TITLE
Login button is not the strongest "call to action" on the login screen

### ISSUE THREAD

**Issue by muffinresearch** [pi-hole/web#1471]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The login button at `/admin/index.php?login` should be the most prominent "call to action" on the login screen. 

Suggested fix would be to increase the login button to full width, and to use a less bright colour for the forgotten password div, it would also be nice to fix the forgotten password to have a larger click target at the same time (or this could be handled independently).

**Actual behaviour:**

The login button is tiny compared to the brighter more prominent div that contains the forgotten password button. This means the forgotten password area draws more attention than the login button. I nearly always try to click that rather than the login button every time. 

Because the actual forgot password button is tiny and only on the right hand-side this fortunately  doesn't start the forgotten password flow, because I'm generally clicking the div not the button. That could be filed as a separate issue.

<img width="617" alt="Pi-hole_Admin_Console" src="https://user-images.githubusercontent.com/1514/85702284-26e4b200-b6d6-11ea-97e4-06ea7ff517a1.png">

**Steps to reproduce:**

Go to the login screen on v5.0

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

If you'd take a patch for this, I'd be interested in taking at look at contributing one.

**Comment by yubiuser** [comment]
Relevant feature requests:
https://discourse.pi-hole.net/t/higher-usability-change-the-size-of-the-buttons-for-login-forgot-pw/3750

https://discourse.pi-hole.net/t/put-login-button-above-forgot-password/28887

**Comment by XhmikosR** [comment]
I plan to tackle all this in the AdminLTE 3 branch.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/pull/1583

Released in https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909/1
