### ISSUE TITLE
Don't expose password/API key in the URL

### ISSUE THREAD

**Issue by ghost** [pi-hole/web#1474]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

----
**Note:** Not a bug per se, this should be considered as feature request :)

----

At the moment authentication at the API (if configured) requires the API token (`WEBPASSWORD` in `setupVars.conf` to be
transmitted by a HTTP GET request (`.../admin/api.php?auth=....`) as a query.

Because this API token enables full access to the PiHole interface it must be considered as an administrator token.

This may expose the API token / password in the URL to other services like proxies / reverse proxies, loadbalancers and will be logged.

Additionally web crawlers, robots or other tools may index those logs (especially if the don't honor `robots.txt`)

To lower the risk of accidental exposure it should be passed as a HTTP header variable instead, e.g.

```
curl -H 'X-PiHole-AdminLTE-Token: whateverfloatsyourboat` .... https://your.pi.hole/admin/api.php?rawSummary
```

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
