### ISSUE TITLE
WebUI: Date labels on the Chart overlap each other [All Time range]

### ISSUE THREAD

**Issue by rrradev** [pi-hole/web#1477]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

---

**Actual behaviour:**
![img](https://user-images.githubusercontent.com/25829240/86229129-f0a4a800-bb97-11ea-987d-4b0ec5f5c02f.png)

**Steps to reproduce:**

1. Main Navigation -> Long Term Data -> Graphics
2. Choose **"All Time"** on _Date and time range_

**Info:**
Pi-hole Version v5.0 Web Interface Version v5.0 FTL Version v5.0

**Comment by DL6ER** [comment]
Question 1: Have you updated only recently? If so, try a force-refresh / browser cache flushing first. If this doesn't help:
Question 2: Which browser are you using?

**Comment by yubiuser** [comment]
The date labels have been revised by https://github.com/pi-hole/AdminLTE/pull/1969
