### ISSUE TITLE
Add default or add setting for Client Name display

### ISSUE THREAD

**Issue by manakill** [pi-hole/web#1482]
Went to Group Management and I added names to the Clients list of phones, tablets, computer names, etc.

What I expected:
Seeing the Client Name in place of IPs on the Dashboard and Query Log for easy device recognition.

**Comment by yubiuser** [comment]
You mean you added it to "Comment"? This is not going to be used for IP -> name resolution. You can archive this by setting entries in "Local DNS Records".

If this is a feature request, please report here:
https://discourse.pi-hole.net/c/feature-requests/8

**Comment by manakill** [comment]
I'm not sure if it's a bug or new feature.. The Group Management Client Names is built in but is not having Expected Behavior - no it's not DNS Resolution/Records - it would be Client Identification by IP/MAC, to display in an easy to read way, the Client "Comment" as the "Name" so you can show the Main Dashboard to a senior manager and they're seeing Device Names/Client Names and not 10.0.0.124 etc

**Comment by manakill** [comment]
I set names here:
![pih-1](https://user-images.githubusercontent.com/9597295/86809241-ac0e8600-c049-11ea-9c67-fe1707434b4d.jpg)

Then I should see the assigned Client Names here:
![pih-2](https://user-images.githubusercontent.com/9597295/86809289-b9c40b80-c049-11ea-9b99-3e830feb82c2.jpg)
![pih-3](https://user-images.githubusercontent.com/9597295/86809324-c21c4680-c049-11ea-84d8-7888a89a0848.jpg)
