### ISSUE TITLE
5.1 Url can be on whitelist and blacklist at the same time

### ISSUE THREAD

**Issue by badsgahhl** [pi-hole/web#1490]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---

**Expected behavior:**

Adding an url to the whitelist should add the url to the list. Adding it then to the blacklist or vice versa, should remove it from the whitelist and add it to the blacklist.

**Actual behavior:**

Adding an url to the whitelist and then adding it to the blacklist, will add the url to both lists.

**Steps to reproduce:**

Add a url to the whitelist, then add it to the blacklist. v5.1

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/knxmymkvem

**Comment by yubiuser** [comment]
It's the intended behavior. See here:
https://github.com/pi-hole/pi-hole/pull/3466 and 
https://discourse.pi-hole.net/t/slight-bug-in-blacklist-uniqueness-constraint/33791/6?u=yubiuser

for the use case.
