### ISSUE TITLE
Flushing network table in v5.1 gives PHP error

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1493]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---

**Expected behavior:**

No error should appear.

**Actual behavior:**

Flushing network table via Settings/System gives a PHP error:
` PHP error (2): implode(): Invalid arguments passed in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:741`

The flush itself is successful.

**Steps to reproduce:**
Flushing network table via Settings/System.

*

**Comment by superevr** [comment]
This appears to be because the command "arpflush quiet" does not return any output. When implode is ran on an empty string in the next line, it generates the PHP error

https://github.com/pi-hole/AdminLTE/blob/d8d3f316061ba60e0b1dfc6a11f6e917380aca5f/scripts/pi-hole/php/savesettings.php#L739-L747

test:
```php
php > $xyz = implode("<br>","");

Warning: implode(): Invalid arguments passed in php shell code on line 1
```

**Comment by yubiuser** [comment]
Maybe it is related to the `pihole_execute` function not returning an output causing the failure of `implode`?
Before the wrapper was used, there was a direct call of `exec("sudo pihole arpflush quiet", $output);` and we haven't seen the error.

https://github.com/pi-hole/AdminLTE/commit/39ec67829b2aa54f81ba141f138dda05c28ae3f5

**Comment by ne0ark** [comment]
I am also seeing this error. Debug token is: https://tricorder.pi-hole.net/d7rkipmcpt

**Comment by MichalisDBA** [comment]
In the pihole_execute function the $output = null;

The flush network tables $error variable expects an array and not null.

You can solve by adding

$output = array();

in 

/var/www/html/admin/scripts/pi-hole/php/savesettings.php

in line 741

above 

pihole_execute("arpflush quiet", $output);

**Comment by DL6ER** [comment]
I agree that the commit mentioned by @yubiuser broke this: https://github.com/pi-hole/AdminLTE/commit/39ec67829b2aa54f81ba141f138dda05c28ae3f5#diff-a93c1ad771067e0f3d2e9dbfb4a62375L716

Unfortunately, the fix is not as simple as @MichalisDBA suggests as `pihole_execute` has not been designed as a drop-in replacement for `exec()`. Instead, it should be
``` php
$output = pihole_execute("arpflush quiet");
```

Please try whether
```
pihole checkout web fix/arpflush
```
fixes this for you.

**Comment by yubiuser** [comment]
Confirm 
> pihole checkout web fix/arpflush

fixes the issue

**Comment by X4Applegate** [comment]
> 
> 
> I agree that the commit mentioned by @yubiuser broke this: [39ec678#diff-a93c1ad771067e0f3d2e9dbfb4a62375L716](https://github.com/pi-hole/AdminLTE/commit/39ec67829b2aa54f81ba141f138dda05c28ae3f5#diff-a93c1ad771067e0f3d2e9dbfb4a62375L716)
> 
> Unfortunately, the fix is not as simple as @MichalisDBA suggests as `pihole_execute` has not been designed as a drop-in replacement for `exec()`. Instead, it should be
> 
> ```
> $output = pihole_execute("arpflush quiet");
> ```
> 
> Please try whether
> 
> ```
> pihole checkout web fix/arpflush
> ```
> 
> fixes this for you.

confirm this had fixed my issues. 

Thank  you, 
Richard Applegate

**Comment by zeus86** [comment]
by the way, if you (like me) get this error, but the network-table is NOT flushed, you are missing the "net-utils" package. Even tough `su -c pihole -c "sudo pihole arpflush quiet"` gives me no error, it does not flush the arp-cache. My Pihole instance is based upon an ubuntu cloud-image for arm 64bit, and `net-utils`does not seem to be included there. Because this is a standard-functionality, which can be called from the Web-UI, `net-utils` shall be adopted to the default dependencies of the pihole-installer, because it is not included by default in each and every ubuntu "flavour".

**Comment by yubiuser** [comment]
@zeus86 

Thanks for your observation. However, the arpflush does not flush the arp any more since this PR (https://github.com/pi-hole/pi-hole/pull/3242). It only deletes the network table from the database.

So the network table should be flushed, but not the cache. Therefore, I'm surprised `net-utils` was required for you.

**Comment by dschaper** [comment]
Why such a convoluted way to calling the `pihole` commands? `su -c pihole -c "sudo pihole arpflush quiet"` changes environments at least 2 times.

**Comment by zeus86** [comment]
@dschaper 
> Why such a convoluted way to calling the `pihole` commands? `su -c pihole -c "sudo pihole arpflush quiet"` changes environments at least 2 times.

you're right, but 
a) from `sudo`on is this, what exactly the webinterface used to trigger when flushing the cache, if i got this right.
b) user pihole has `/usr/sbin/nologin` as shell, and no pw set (which is the way it should be)
c) already hat something similar in my history :-)

---

@yubiuser
> So the network table should be flushed, but not the cache. Therefore, I'm surprised `net-utils` was required for you.
Yes, i was not sure about how this would be going to work, but I 
1)clicked the flush button: no effect, all networkclients still present in list. 
2) manually tried to execure the cmd: ran sucessfully, but still all clients there after refreshing the web-ui.
3) wanted to double-check with `arp` -> `net-utils` not installed -> installed it
4) tried command again : list is empty now. 
5) button on website still gives an error, but **_does_** now flush the table indeed.

...so yes, `net-utils`was indeed requires for me. 
My Instance should be recent enought, but in doubt, here some versions & specs:
```
root@pihole:~# pihole -v
  Pi-hole version is v5.1.1 (Latest: v5.1.1)
  AdminLTE version is v5.1 (Latest: v5.1)
  FTL version is v5.1 (Latest: v5.1)
root@pihole:~# uname -a
Linux pihole 4.14.187 #0 SMP Tue Jul 7 03:35:29 2020 aarch64 aarch64 aarch64 GNU/Linux
root@pihole:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
root@pihole:~#
```

**Comment by yubiuser** [comment]
Yes it is recent enough. But still `piholeARPTable.sh` does not modify the arp/neight cache anymore.

Maybe it was rather an disply/database error?

Do you see any errors in `/var/log/pihole-FTL` ?

**Comment by zeus86** [comment]
> Do you see any errors in `/var/log/pihole-FTL` ?

nope, nothing at all in the log on an flush-attempt.
but I can show you the error-message the Web-UI gives me:
![Screenshot_20200801_101126](https://user-images.githubusercontent.com/11415964/89097486-8d4ca680-d3df-11ea-8efd-f810bc8f6b8b.png)

**Comment by DL6ER** [comment]
> https://github.com/pi-hole/AdminLTE/pull/1514/files

This is exactly what is fixed by #1514

**Comment by zeus86** [comment]
uhm, interesting. is this already in the branch which the stable-version would check out (sorry, don't know much about the package/versioning-process here), because i am on 5.1.1, and `pihole -up` claims everything is up to date:
```
root@pihole:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date
```
...but anyhow, my `savesettings.php`is definately in "pre-fixed" state...

**Comment by DL6ER** [comment]
Yes, this will be release in Pi-hole v5.2. See #1535 for the progress. There is still some more testing going on but it should not take much longer. We're not directly releasing new features/bugfixes to users as they may contain regressions so tests will always be mandatory. Other projects have different philosophies, however, the past has shown that our approach prevents a lot of user frustration.

**Comment by zeus86** [comment]
> Yes, this will be release in Pi-hole v5.2. See #1535 for the progress. There is still some more testing going on but it should not take much longer. We're not directly releasing new features/bugfixes to users as they may contain regressions so tests will always be mandatory. Other projects have different philosophies, however, the past has shown that our approach prevents a lot of user frustration.


i see, thanks for the explanation. i do not bother with one philosophy nor the other, i just did not know, which one apllies here ^^.
okay, then i'll wait for the next minor update.

**Comment by yubiuser** [comment]
Fix has been merged into master.
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-2-released/36964
Closing.
