### ISSUE TITLE
Unable to use  "::1#5335" as local ipv6 dns server on pihole v5.1

### ISSUE THREAD

**Issue by FusionPlmH** [pi-hole/web#1499]
![Screenshot_20200717-020522_Chrome](https://user-images.githubusercontent.com/16817768/87706515-3c7b6200-c7d2-11ea-8603-179258b082d8.jpg)
![Screenshot_20200717-020528_Chrome](https://user-images.githubusercontent.com/16817768/87706518-3e452580-c7d2-11ea-8a43-06f5e541efb6.jpg)

After i update to v5.1 , i was not able to input my local ipv6 dns server  ::1#5335 address at the pihole webadmin

so any solution of it ?

**Comment by PromoFaux** [comment]
I don't think anything changed in the IP validation code for the interface in 5.1... but I can't be 100% on that.

What if you use the full link-local address? (I may not know what I'm talking about.. IPv6 is all voodoo magic to me)

**Comment by FusionPlmH** [comment]
> I don't think anything changed in the IP validation code for the interface in 5.1... but I can't be 100% on that.
> 
> What if you use the full link-local address? (I may not know what I'm talking about.. IPv6 is all voodoo magic to me)

can use full link local ipv6 address like : 2404:c805:4026:8a00:ba27:ebff:fe56:f14c

but the question is my unbound dns port is 5335

how can i insert the port with the full ipv6 address

**Comment by FusionPlmH** [comment]
> > I don't think anything changed in the IP validation code for the interface in 5.1... but I can't be 100% on that.
> > What if you use the full link-local address? (I may not know what I'm talking about.. IPv6 is all voodoo magic to me)
> 
> can use full link local ipv6 address like : 2404:c805:4026:8a00:ba27:ebff:fe56:f14c
> 
> but the question is my unbound dns port is 5335



> > I don't think anything changed in the IP validation code for the interface in 5.1... but I can't be 100% on that.
> > What if you use the full link-local address? (I may not know what I'm talking about.. IPv6 is all voodoo magic to me)
> 
> can use full link local ipv6 address like : 2404:c805:4026:8a00:ba27:ebff:fe56:f14c
> 
> but the question is my unbound dns port is 5335
> 
> how can i insert the port with the full ipv6 address

Or actually ipv6 is unnecessary for port forwarding

**Comment by PromoFaux** [comment]
It's a good question, and unfortunately one I do not know the answer to. On the IPv4 inputs, you can add a port with as e.g `#5353`... but I have never personally used IPv6, let alone tried hosting anything so I am not sure. 

Looking at the code, I'm not sure it was ever possible to add a port to an IPv6 in the input box...

**Comment by dschaper** [comment]
If you are using `::1` then why not `127.0.0.1` instead? No need for the IPv6 loopback when IPv4 is available.

**Comment by FusionPlmH** [comment]
So actucutlly i dont need to set ipv6 ::1 as 127.0.0.1 do the smae job right?

**Comment by dschaper** [comment]
Points to the same exact place in the kernel.

**Comment by DL6ER** [comment]
I'll look at the validator. Even when bot are effectively the same, not allowing `::1#5353` still smells like a bug somehow. Probably an easy to fix one, but something I can only do when having returned to my development environment. So Monday at the earliest.

**Comment by compuguy** [comment]
There is a related issue in https://github.com/pi-hole/pi-hole/issues/3571 & https://github.com/pi-hole/FTL/issues/855

**Comment by yubiuser** [comment]
Fixed with the release of Core v5.1.2
https://github.com/pi-hole/pi-hole/releases/tag/v5.1.2
