### ISSUE TITLE
Update fron V5 to V5.1

### ISSUE THREAD

**Issue by Fallout476** [pi-hole/web#1502]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behavior:**

`{Client activity, Query types, and Queries Answered by to provide a visual representation of the logs}`

**Actual behavior:**

`{spinning loading circles}`

**Steps to reproduce:**

`{pihole -up from V5 to V5.1}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{https://tricorder.pi-hole.net/av36wwsiro}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Pihole -r, rebooted, with no change}`

**Comment by klentz-12** [comment]
I as well have had the issues with the upgrade. Also the temp monitoring is also broken.

Thanks

**Comment by Fallout476** [comment]
disabled ABP, even though it said 0 items, same results.

**Comment by dschaper** [comment]
If the problem is with a specific browser and not all browsers then Pi-hole is functioning correctly and it's the browser that is the root cause.

@klentz-12 Open a new issue please.

**Comment by Fallout476** [comment]
> If the problem is with a specific browser and not all browsers then Pi-hole is functioning correctly and it's the browser that is the root cause.
> 
> @klentz-12 Open a new issue please.

Chrome is the only one thats not working as expected, Firefox, New MS Edge, and Safari works as expected

**Comment by Fallout476** [comment]
reinstalled vanilla chrome with no plugins at all, same issue

**Comment by dschaper** [comment]
Don't know what to say. It's something in Chrome then and not something we can fix.

**Comment by klentz-12** [comment]
> Don't know what to say. It's something in Chrome then and not something we can fix.

Can confirm it works in Edge.

**Comment by DL6ER** [comment]
@Fallout476 I will try Chrome in a sandbox as soon as possible (Monday at the earliest). Can you give some more details like Chrome version and operating system (and version thereof) you installed Chrome on?

**Comment by JyriT** [comment]
Same problem here: 
Chrome version: 
Google Chrome | 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.6 (Build 19G73)
JavaScript | V8 8.3.110.13
Flash | 32.0.0.403 /Users/<userid>/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.403/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by Fallout476** [comment]
this appears to be a Chrome on the Mac issue, as my Windows box can see it just fine. 

13" MacBook Pro 10.14
Chrome 84.0.4147.89 official build 64bit
java and flash are built into chrome, none installed on top of that

**Comment by DL6ER** [comment]
Hmm, this makes it somewhat more complicated as I don't think we have Apple hardware for testing. The error description doesn't really give any hints. Can you open Chrome's developer tools under Mac OS? It's pressing <kbd>F12</kbd> under Linux (and Windows as well, maybe).

If you can get in there, are there any errors on the Console ?

**Edit** It doesn't appear to give a shortcut on MacOS, however:

> To open the developer console in Google Chrome, open the Chrome Menu in the upper-right-hand corner of the browser window and select More Tools > Developer Tools.

**Comment by Fallout476** [comment]
These are the errors that i see in chrome console 

```
Failed to decode downloaded font: <URL>
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Regular.ttf
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Semibold.ttf
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Bold.ttf
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Regular.ttf
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Semibold.ttf
index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Bold.ttf
6OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.php:1 OTS parsing error: invalid version tag
index.js:284 Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.success (index.js:284)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
index.js:382 Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.success (index.js:382)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
index.js:460 Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.success (index.js:460)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

**Comment by M0dEx** [comment]
> These are the errors that i see in chrome console
> 
> ```
> Failed to decode downloaded font: <URL>
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Regular.ttf
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Semibold.ttf
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Bold.ttf
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Regular.ttf
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Semibold.ttf
> index.php:1 Failed to decode downloaded font: http://192.168.1.XX/admin/style/vendor/SourceSansPro/SourceSansPro-Bold.ttf
> 6OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.php:1 OTS parsing error: invalid version tag
> index.js:284 Uncaught TypeError: Cannot read property 'options' of undefined
>     at Object.success (index.js:284)
>     at j (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at x (jquery.min.js:4)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:4)
> index.js:382 Uncaught TypeError: Cannot read property 'options' of undefined
>     at Object.success (index.js:382)
>     at j (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at x (jquery.min.js:4)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:4)
> index.js:460 Uncaught TypeError: Cannot read property 'options' of undefined
>     at Object.success (index.js:460)
>     at j (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at x (jquery.min.js:4)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:4)
> ```

To add to this, this is the response for the font requests:
```
<!doctype html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>XXX.XXX.XXX.XXX</title>
        <link rel='stylesheet' href='pihole/blockingpage.css'>
        <link rel='shortcut icon' href='admin/img/favicons/favicon.ico' type='image/x-icon'>
    </head>
    <body id='splashpage'>
        <img src='admin/img/logo.svg' alt='Pi-hole logo' width='256' height='377'>
        <br>
        <p>Pi-<strong>hole</strong>: Your black hole for Internet advertisements</p>
        <a href='/admin'>Did you mean to go to the admin panel?</a>
    </body>
</html>
```

**Comment by EvilWays1** [comment]
I was having this issue as well with Brave (x64 Windows version 1.11.97), along with the temperature not showing up. After "dropping shields" and going to Settings -> Additional Settings -> Privacy and security -> Clear browsing data and only deleting Cached images and files, I no longer had either issue.

**Comment by thambley** [comment]
I had this issue too.  Chrome had a cached copy of scripts/pi-hole/js/index.js that was referring to $.AdminLTE.options.colors.  Cleared my cache and refreshed.  It works now.

**Comment by non-compos-mentis** [comment]
I also had this issue, Chrome on Windows, same js error logs, and a cached copy of the previous version of scripts/pi-hole/js/index.js referring to $.AdminLTE.options.colors. Clearing the cached files resolved it.

**Comment by miharekar** [comment]
Had same issue. Came here to complain. shift+refresh fixed it. Thanks! 😅️

**Comment by yubiuser** [comment]
Should be fixed by https://github.com/pi-hole/AdminLTE/pull/1550
