### ISSUE TITLE
ipaddress in one lan does not get resolved

### ISSUE THREAD

**Issue by MrHappy** [pi-hole/web#1504]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---

**Expected behavior:**
All ipaddresses replaced by hostnames

**Actual behavior:**
for one lan/dhcp-range it shows only ipaddresses, other lan (with different iprange) on same router works fine.

**Steps to reproduce:**
Configuration is same, except for name and iprange. So don't know

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**
changed ip range to trigger new resolve:
`2020-07-17 08:25:00 	PTR	223.4.168.192.in-addr.arpa	localhost	OK (cached)	NXDOMAIN (0.5ms)`
evaluated all settings on router, but there's no difference between two lan's...

**Comment by zeus86** [comment]
check if pihole can resolve the hostnames (from the shell with `host <ip>`). I had the same problem, that for my clients only IPs have been showed, but the underlying issue was, that my router refused to handle reverse records correctly.
