### ISSUE TITLE
The arrows on the dashboard have been rotating since the update from 5.0 to 5.1

### ISSUE THREAD

**Issue by LevelOne2k** [pi-hole/web#1506]
Hello everybody!

Since the update from 5.0 to 5.1

The arrows in the dashboard only run in circles, why?
<img width="1584" alt="Bildschirmfoto 2020-07-17 um 12 27 30" src="https://user-images.githubusercontent.com/25386824/87776958-e84f9c80-c828-11ea-9b7e-243581c14044.png">

**Comment by yubiuser** [comment]
Try clearing your browser's cache.

**Comment by LevelOne2k** [comment]
Thx, it works
