### ISSUE TITLE
Dashboard Query Type Issue (wrong link to query logs)

### ISSUE THREAD

**Issue by ChrisFromCologne** [pi-hole/web#1508]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

=========================

If I click on one of the query types at the dashboard it leads to the wrong query log:

PTR --> SOA
TXT --> PTR
SOA --> SRV

I've already cleared the browser cache several times and tested it on a variety of devices... but always with the same result.

Issue came after the upgrade from 5.0 to 5.1 (5.0 was fine before)

Any ideas how to solve it?

P.S.: Only A and AAAA leads to the right query logs...

==========================

Pi-hole v5.1.1
Web Interface v5.1
FTL v5.1

**Comment by will6789** [comment]
For me clicking `PTR `returns `SRV `records (link goes to "queries.php?querytype=4") 
Clicking `OTHER `returns `PTR `records (link goes to "queries.php?querytype=6")
The other options on the graph are `SRV `and `TXT `(links to querytype 3&5 respectively) but clicking these doesn't return any results. I'm assuming this is because I don't have any of whatever record type its actually looking for in my query log

It looks like the links are fixed and don't update to point to the relevant query type

**Comment by DL6ER** [comment]
Thanks for your report. This is indeed really broken. We're working on a fix.

**Comment by Kapot** [comment]
Is this still open? I see it merged into v5.1.1.

Running v5.2.1 now and when i click 'OTHER' it redirects to '?querytype=13' (wrong type) instead of '?querytype=14' (correct type).

**Comment by Daxtorim** [comment]
This was fixed by https://github.com/pi-hole/FTL/pull/1007.

**Comment by ChrisFromCologne** [comment]
> This was fixed by [pi-hole/FTL#1007](https://github.com/pi-hole/FTL/pull/1007).

I think Kapot is right: It was fixed some time ago but now back for "OTHERS"

**Comment by yubiuser** [comment]
The fix @Daxtorim mentioned has not been merged in the `master` branch yet, but in `development`.It is very likely it will be part of the next pihole release.

**Comment by yubiuser** [comment]
This has been fixed a long time ago.
