### ISSUE TITLE
WebAdmin Panels not functioning

### ISSUE THREAD

**Issue by cmdshft** [pi-hole/web#1511]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behavior:**

Normal operations.

**Actual behavior:**

Queries blocked and percentage are empty even though graph is showing blocks.

![Annotation 2020-07-18 200342](https://user-images.githubusercontent.com/8571823/87864111-2b496700-c932-11ea-9f13-851acd6dbf92.png)

**Steps to reproduce:**

Just open up the web admin.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

9mnociqlyx

**Troubleshooting undertaken, and/or other relevant information:**

Unable to fix myself.

**Comment by jwellhouse** [comment]
I had the same issue. Try opening the web admin in a private browsing window (temporary solution). If that works try clearing your browser cache. There should be no need to clear cookies, only the cache. (permanent solution if it works)

**Comment by jfb-pihole** [comment]
This is typically caused by an adblocker.  Disable your adblocker for this domain.

**Comment by petaren** [comment]
I have this same issue. I've found that the issue only happens in Safari (my main browser), but works fine in Firefox. 

I have tried clearing website data (cache, cookies etc) in Safari, used a new private window and disabled content blockers for that website to no avail.
