### ISSUE TITLE
HTML code escaping into GUI

### ISSUE THREAD

**Issue by arfbarky** [pi-hole/web#1513]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

`A couple of places in the GUI should display normal text; in one case, the font should be italicized and in the other case it should display a single quote`

**Actual behavior:**

`In Settings -> DHCP under Current Leases, I see "<i>unknown</i>" ... for the other, under Group Management -> Clients, after adjusting an entries group membership and applying, the single quote is replaced by "&#039;" when the next entry still correctly displays the single quote.`

[Screenshots of the two issues in the GUI](https://postimg.cc/gallery/sS4NYb0)

**Steps to reproduce:**

`It started behaving this way as soon as I updated to 5.1`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/8wxv08x886`

**Troubleshooting undertaken, and/or other relevant information:**

`I have not attempted to fix this issue`

**Comment by yubiuser** [comment]
This first issue (regarding the unknown) is addressed here
https://github.com/pi-hole/AdminLTE/pull/1509

**Comment by yubiuser** [comment]
Adding `bug` because the `<i>unknown</i>` is back in the recent versions. And ` the single quote is replaced by "&#039;"` should remind us that the whole escaping/unescaping needs a re-work

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
