### ISSUE TITLE
much (order of magnitude) lower PercentageBlocked % shown in web interface on version 5

### ISSUE THREAD

**Issue by rdslw** [pi-hole/web#1516]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behavior:**

Web Interface is showing clients which do NOT reverse resolve to name (e.g. 192.168.1.12 not resolving as 'smarttv.lan' (example only) ) and pihole shall show such clients simply as IPs.

It was working OK in pihole 4.x, so this is regresion?

**Actual behavior:**

Since version 5 (or 5.1 as I upgraded directly from 4.x to 5.1) if:
1. you use CONDITIONAL_FORWARDING
2. pihole is NOT dhcp server
3. some of the clients resolve to names and some do NOT

Pihole webinterface is NOT showing any client (and not counting in stats) which is IP only (meaning dns query send from pihole to my dhcp/dns server does not return name (which can be proper behaviour, so pihole should not ignore such entries)).

FTL works ok (answers requests from client).

**Steps to reproduce:**

as described above.

**Troubleshooting undertaken, and/or other relevant information:**

Checked /var/log/pihole.log and queries from such clients reach pihole, and pihole answers properly to them (some requests are blocked, some not, as usual).

**Comment by DL6ER** [comment]
We have to clarify some things. We are talking about the web interface in general, not the long-term pages, right? If so, the web interface does not compute *any* statistics. This is all done by FTL. And when they are included in the database, then they are also included in the computed statistics.

If any of these points is violated, everything works as expected?

>   1. you use CONDITIONAL_FORWARDING
>   2. pihole is NOT dhcp server
>   3. some of the clients resolve to names and some do NOT

or is this just the particular test setup you tried? If so, have you tried something else? I imagine turning of conditional forwarding which would make all clients IP-only. What happens?

**Comment by rdslw** [comment]
Thanks for answering @DL6ER !
Right. I'm talking about starting page, which if I'm logged in, shows Dashboard. 
When I said 'statistics' I have in mind top row (total queries, queries blocked etc). Currently numbers DO NOT include elements from unresolvable clients. 
_Unresolvable clients are also NOT being shown in 'query log' which for sure is wrong, as they are in pihole-ftl.db queries table (sqlite file)._

Unfortunately I do not have possiblity to disable and check point no 2, I will check point no 1 and let you know in separate msg. Point no 3 is not checkable as this is a result. 

This is my pihole production setup. I use it for 10 months or so. It worked fine before I upgraded to v5.1 last week. By worked fine I mean: unresolvable clients where shown properly on version 4.x 
I also suspect CONDITIONAL_FORWARDING as version 5 introduced changes here. That being said I also used simplified version of this settting which was available in version 4.

**Comment by ghost** [comment]
I'm having the same issue as described. Also on v5.1
Temp also not showing in Status frame

EDIT: Nvm. Ctrl+F5 fixed it for me.

**Comment by rdslw** [comment]
I finally had some time to analyse it, and here are preliminary conclusions:

1. This is probably not pihole BUG
2. I'm seeing MUCH smaller 'Percentage blocked' number (currently 0.8%) and smaller total queries number (around 60k) then previously. Previously (version 4) the numbers where at 20..30% and total queries at higher level.
3. This is NOT about resolved/non resolved entries.

I'd like to concentrate on 'Percentage blocked' as this is the number I'm very sure to have in order of magnituted higher on 4.x version.

A. Can you help me @DL6ER by confirming that 24h period used to show data (I'm talking about 4 top rectangle blocks on dashoard) was NOT introduced in 5.0/5.1/5.2 but was actually also the silent default in 4.x version?
B. Can you confirm me that forwarded and cached entries are calculated in the same way in 5.x version in regard to 'Percentage blocked' ? I'm asking as I have forwarded entries at 37% and cached at 51%, and while thinking about why PercentageBlocked is so low, I'm asking myself MAYBE it's because other values are now larger.

**Comment by DL6ER** [comment]
> A. Can you help me @DL6ER by confirming that 24h period used to show data (I'm talking about 4 top rectangle blocks on dashoard) was NOT introduced in 5.0/5.1/5.2 but was actually also the silent default in 4.x version?

Confirmed. It has always been like that, the new user interface just makes it clearer.

> B. Can you confirm me that forwarded and cached entries are calculated in the same way in 5.x version in regard to 'Percentage blocked' ? I'm asking as I have forwarded entries at 37% and cached at 51%, and while thinking about why PercentageBlocked is so low, I'm asking myself MAYBE it's because other values are now larger.

Confirmed as well. No numbers changed for me at all. I am - and have always been - hovering around 3% blocked. This is in a network with no IoT devices or whatsoever. The only blocked content is apps trying to send telemetry data home and some (few) ads on the web. I'm mostly accessing content that does not host ads, so a 3% blocking rate is somewhat expected for me.

---

> smaller total queries number (around 60k) then previously

That may the strongest point here. Speculation: You "lost" some device(s) that used to get a lot of content blocked. This would similarly affect the total number of queries and the percentage. With "lost" I do not necessarily mean physically lost the device but maybe it "learned" how to communicate around Pi-hole in order to get the advertisement content it is looking fore. Thinking about DNS-over-HTTPS, etc.

**Comment by rdslw** [comment]
Thank you kindly for information.

> That may the strongest point here. Speculation: You "lost" some device(s) that used to get a lot of content blocked. This would similarly affect the total number of queries and the percentage. With "lost" I do not necessarily mean physically lost the device but maybe it "learned" how to communicate around Pi-hole in order to get the advertisement content it is looking fore. Thinking about DNS-over-HTTPS, etc.

yep. thats what I'm checking now, as two devices migrated to nextdns.io so I'm doing real test today and tomorrow with them back using pihole.

I'll update with final conclusions.

**Comment by rdslw** [comment]
looks like change I observed was due to external factor (much bigger number of total requests), and this is NOT a bug in pihole. 
Thank you for helping me to verify it @DL6ER !!
