### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by jsutton** [pi-hole/web#1523]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---

**Expected behavior:**

On the conditional forwarding page the sentence, "Exemplary inout is given below as placeholder in the text boxes (if empty)." should read, "Exemplary input is given below as placeholder in the text boxes (if empty)."

**Actual behavior:**

"Exemplary inout is given below as placeholder in the text boxes (if empty).", is displayed.

**Steps to reproduce:**

1. Open pi.hole/admin/settings.php?tab=dns and browse to the "Conditional forwarding" header.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I browsed the source code to find the offending line.
https://github.com/pi-hole/AdminLTE/blob/d8d3f316061ba60e0b1dfc6a11f6e917380aca5f/settings.php#L997

**Comment by yubiuser** [comment]
Thanks for the report, already fixed in
https://github.com/pi-hole/AdminLTE/pull/1522
