### ISSUE TITLE
Wrong formatting in DHCP leases with unknown host names 

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/web#1526]
The list of DHCP leases shows "<i>unknown</i>" in column "Hostname" for entries without hostnames. This is a minor but confusing formatting issue.

![2020-07-22 09_10_08-Pi-hole - raspberrypi1](https://user-images.githubusercontent.com/1275166/88145733-2d921680-cbfb-11ea-8dc3-8510c6592330.png)

Using Pi-hole v5.1.1, Web Interface v5.1.

**Comment by danielo515** [comment]
In which release is this expected to be shipped?

**Comment by PromoFaux** [comment]
The next one. No ETA 😉

**Comment by yubiuser** [comment]
Should be fixed since
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909/1
