### ISSUE TITLE
Use 24 hour format for ranges in charts

### ISSUE THREAD

**Issue by zeus86** [pi-hole/web#1528]
**In raising this issue, I confirm the following:** 
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
not applicable

---
**Expected behavior:**

Configurable display-range for Charts in 24-hour format or at least configurable

**Actual behavior:**

Configurable display-range for Charts is in 12-hour AM/PM format

**Steps to reproduce:**

Pi-Hole-Webinterface -> Long-Term data -> Graphics ->click to select time range -> Custom Range -> choose timeframe

**Troubleshooting undertaken, and/or other relevant information:**
Computer Systems in general i think shall either be using a Timeformat given by the User (or in this case: the user's browser), or - if not - at least default to not missleading 24-hour-format, because the 12 hour format drives everyone nuts not located in the US. is 12AM in the night or at noon? noone knows, always have to double check this......

In my Opinion all of the following settings should be user-overridable:
* Temperature Unit (in fact, it is!)
* Time-/Date-Format
* UI-Language (but anyways, i understand, that this would require a lot of extra work, but even having the Project i18n-ready would be okay, if users and community provide their translation [like they always do])

**Comment by yubiuser** [comment]
>Pi-Hole-Webinterface -> Long-Term data -> Graphics ->click to select time range -> Custom Range -> choose timeframe

Doing that gives me 24h time format. Actually, pihole uses 24h format everywhere as far as I  know. Can you provide a screenshot please?

**Comment by zeus86** [comment]
> > Pi-Hole-Webinterface -> Long-Term data -> Graphics ->click to select time range -> Custom Range -> choose timeframe
> 
> Doing that gives me 24h time format. Actually, pihole uses 24h format everywhere as far as I know. Can you provide a screenshot please?

uhm, interesting, in my case this is clearly different. screenshot attached...
![Screenshot_20200725_004908](https://user-images.githubusercontent.com/11415964/88441252-d1084480-ce10-11ea-93ea-a001acd1c215.png)

so may this be configurable by the users locale or $LANG ? my pihole version should be somewhat current though:
`Pi-hole v5.1.1 Web Interface v5.1 FTL v5.1`

**Comment by yubiuser** [comment]
Ah, I see. I was looking at the wrong spot - I was reading to fast and just looked at the scale on the final graph.
Your're right, I see it too.

Actually it is not only on Long-Term - > Graphics, but on all Time/Date selectors withing Long-Term Data

**Add**

Creates a PR that should change to 24h format

**Comment by yubiuser** [comment]
This has been fixed a long time ago.
