### ISSUE TITLE
Static DHCP hostname should be checked for validity

### ISSUE THREAD

**Issue by jnko** [pi-hole/web#153]
When entering a hostname in pihole-web Settings->DHCP->"Static DHCP Leases" the name should be checked for validity.

Currently it is possibe to enter a dot within the hostname, for example "Nokia7.1" which will result in a not resolvable dns entry. 

[a-zA-Z0-9\-]

**Comment by Mcat12** [comment]
This is an issue on the PHP web interface (repo at [pi-hole/AdminLTE](https://github.com/pi-hole/AdminLTE)), not an issue on this web interface. Please open an issue there instead.
