### ISSUE TITLE
Number of network queries hardcoded to 10

### ISSUE THREAD

**Issue by freebrowser1** [pi-hole/web#1531]
I am talking about the low number of network queries:

http://[Pi-hole domain]/admin/queries.php?client=[IP of queried device]

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
4

---
**Expected behavior:**

Default value of number of log lines should be configurable.

**Actual behavior:**

Default number of log lines is hardcoded to 10. It can be cahnged up to 100, but it is only once. After refreshing the page it is reverted to only 10.

**Steps to reproduce:**

Select 25, 50 or 100 and show. More than 10 will be shown.
Refresh the page and only ten results will be shown.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Checked the code and in admin/api-db.php there is a hardcoded value of 10 (line 200)
	// Extract only the first ten entries
	$clientnums = array_slice($clientnums, 0, 10);
I changed this number to 100 and that works, but that is obviously a dirty hack.
So a configuration setting should be available to change this number.

Ten results is in modern internet (or even local LAN) a bit outdated, does remind of the old dial in modems speed .....

**Comment by freebrowser1** [comment]
Indeed, but the local storage setting to 100 items is lost after a day and reverts to 10.

**Comment by yubiuser** [comment]
>Indeed, but the local storage setting to 100 items is lost after a day and reverts to 10.

I suspect this is a browser issue then. Does it revert to 10 also after closing/reopening the browser? What cookie/cache clearing policy do you apply in your browser? 

See here also: https://stackoverflow.com/a/37105645
