### ISSUE TITLE
API overTimeData10mins values inconsistent with Web UI

### ISSUE THREAD

**Issue by tomswartz07** [pi-hole/web#1534]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** `3`

---
**Expected behavior:**

Data from the overTimeData10mins endpoint should match the values for the web UI.

**Actual behavior:**

Data from the overTimeData10mins endpoint is inconsistent with the values from the web UI.
`ads_over_time` values match the respective time periods in the web UI, but it appears that the `domains_over_time` values are 'split' between previous and next time buckets.

It appears that the calculations for the domains_over_time are incorrect in the web UI, leading to a discrepancy between the API values and what is shown in the web UI.

e.g.

`overTimeData10mins`:
1595943300: 211
1595943900: 152

`Web UI`:
1595943300: 172
1595943900: 192

**Steps to reproduce:**

In the most simple reproduction case:
1. Open two side-by side browser tabs
2. In one tab, view the web UI with the `Total queries over last 24 hours` graph
3. In the other tab, navigate to the API endpoint for overTimeData10mins
4. Compare the values for each of the time stamps and observe that the count for `ads_over_time` is accurate, but the `domains_over_time` are not.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
 https://tricorder.pi-hole.net/nbrjpcuatu

**Troubleshooting undertaken, and/or other relevant information:**
I've manually compared the data presented by the web UI to the data from the API endpoint, and validated that the `ads_over_time` values do indeed display correctly on the web UI.

I've also attempted to compare the `domains_over_time` values to neighboring time slots (implying that there's an off-by-one issue), but this was unsuccessful. 

There does seem to be some correlation between the difference in numbers- as in, the previous value will be 'off by' a similar-but-not-exact amount of the current value.

**Comment by yubiuser** [comment]
The explanation for the behavior is given in https://github.com/pi-hole/pi-hole/issues/3624
