### ISSUE TITLE
Unable to use blacklist button

### ISSUE THREAD

**Issue by phil-ide** [pi-hole/web#1536]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behavior:**

After upgrading from v5.0 to v5.1.1:
Pressing 'Blacklist' button in the Query Log should add a doman to the blacklist.

**Actual behavior:**
The popup message informing the domain has been added is displayed as usual. However, checking the blacklist shows it has not been added. From another machine, surfing to the supposedly blacklisted domain shows (in the log) that it has not been blacklisted and has been forwarded.

**Steps to reproduce:**
Press the blacklist button for a domain in the Query Log, then try to surf to the domain. Checkin the Blacklist for the entry.

**Troubleshooting undertaken, and/or other relevant information:**
I have performed the "echo 4711 > /var/run/pihole-FTL.port" and "pihole -c" now reports FTL running properly. The issue being reported occurs both before and after these steps.

**Comment by jfb-pihole** [comment]
Have you cleared the browser cache and reloaded the Pi-hole web GUI?

**Comment by phil-ide** [comment]
I have tried that, but that wouldn't actually make any difference to the pi-hole forwarding domains and giving them the green light *after* the blacklist button had been pressed on them from an earlier request. Neither would it make any difference to a force-reload (ctrl-F5) on the blacklist in the GUI, which should show the backlisted item. The fact is, pressing the blacklist button in the query log doesn't do anything except display a message saying the item has been blacklisted.

My workaround is to head straight to the blacklist and manually enter domains I want blacklisted, so it's not a mission critical failure, it's just erroneous behaviour.

**Comment by vossilius** [comment]
+1
