### ISSUE TITLE
Multiple MAC addresses for single host incorrectly rendered in DHCP settings

### ISSUE THREAD

**Issue by sysophost** [pi-hole/web#1543]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

I haven't dug into the code to resolve this myself, but I'd assume the problem arises when the static leases file is read in [here](https://github.com/pi-hole/AdminLTE/blob/d8d3f316061ba60e0b1dfc6a11f6e917380aca5f/scripts/pi-hole/php/savesettings.php#L117)

---

**Expected behavior:*

Multiple MAC addresses assigned to a single host in `/etc/dnsmasq.d/04-pihole-static-dhcp.conf` should be rendered in the web interface with a newline or comma delimiter in the MAC address column. 

**Actual behavior:**

Due to the addition of a MAC address in `/etc/dnsmasq.d/04-pihole-static-dhcp.conf`, the web interface is off by one column. So the MAC address column displays the first MAC, the IP address column displays the second MAC, and the Hostname column displays the IP address.

I'm assuming this is because `dhcp-host` entries are read in and split at comma, where the assumption is only one MAC address will be configured. The web interface doesn't allow multiple MACs to be entered for a single host, so these must be manually entered by editing `/etc/dnsmasq.d/04-pihole-static-dhcp.conf`

e.g. `dhcp-host=AA:AA:AA:AA:AA:AA,BB:BB:BB:BB:BB:BB,192.168.1.1,myhost`

Using the above example, `AA:AA:AA:AA:AA:AA` would be displayed in the MAC address column, `BB:BB:BB:BB:BB:BB` would be displayed in the IP address column, and `192.168.1.1` would be displayed in the hostname column. 

**Steps to reproduce:**

1. Add a second MAC address to an existing static reservation by editing `/etc/dnsmasq.d/04-pihole-static-dhcp.conf`
2. View static DHCP lease config in Settings > DHCP

**Comment by yubiuser** [comment]
Thanks for the report.
The relevant feature request is: https://discourse.pi-hole.net/t/show-static-leases-with-more-mac-addresses-in-line-correctly-in-ui/11584
