### ISSUE TITLE
CPU Temperature Unit Reverts to Celsius

### ISSUE THREAD

**Issue by jasonsrobbins** [pi-hole/web#1547]
### Versions

- Pi-hole:  5.1.1
- AdminLTE:  5.1
- FTL:  5.1

### Platform

- OS and version:  Linux raspberrypi4 5.4.51-v7l+

- Platform:  Raspberry Pi 4

### Expected behavior

CPU Temperature Unit should change to selected value and stay.

### Actual behavior / bug

CPU Temperature Unit is set to Fahrenheit in the GUI settings, but reverts to Celsius at some point.
 

### Steps to reproduce

1. Go to settings
2. Click on API tab
3. Select Fahrenheit from drop down menu
4. Wait 24 hours and see portal reporting Celsius

## Debug Token

- URL:  https://tricorder.pi-hole.net/e2y2lnltqf

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
The setting for the temperature unit is saved in your browser's local storage. 
![Bildschirmfoto zu 2020-08-04 09-40-54](https://user-images.githubusercontent.com/26622301/89266871-bf0b7a80-d636-11ea-9216-12d73cfc38a7.png)

It should sustain >24h. If not, you likely have to configured your browser to delete the cache every 24h?
