### ISSUE TITLE
"Top Blocked Domains" contains empty/invisible domain

### ISSUE THREAD

**Issue by KommX** [pi-hole/web#1549]
### Versions

- Pi-hole:  v5.1.1
- AdminLTE:  v5.1
- FTL:  5.1

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

The "Top Blocked Domains" should contain domain names in the first column.

### Actual behavior / bug

Sometimes I have empty/invisible domain names in there. "Hits" and "Frequency" are there, so it's not an empty row. In the screenshot below look at the last row.

### Steps to reproduce

**Update:**
1. Generate queries for `www14.smartadserver.com` until it's in the "Top Blocked Domains".

## Debug Token

- URL:  https://tricorder.pi-hole.net/36u5h0aq9r

### Screenshots

![image](https://user-images.githubusercontent.com/7859245/89459907-bff0f900-d769-11ea-8000-2186bf973d93.png)

**Comment by KommX** [comment]
Just a quick update:
I can now reproduce this behavior by issuing requests to `www14.smartadserver.com`, until it hits the "Top Blocked Domains" list.

And it's still there with:
Pi-hole version is v5.1.2
AdminLTE version is v5.1.1
FTL version is v5.2

**Comment by yubiuser** [comment]
I can confirm the behavior.

![Bildschirmfoto zu 2020-08-10 22-56-54](https://user-images.githubusercontent.com/26622301/89830681-e5f90d80-db5c-11ea-8f2d-a6ba9a612638.png)

**Comment by yubiuser** [comment]
Ok, I figured it out. 

It's an issue with browser-level addon filtering (uBlock origin in my case). The data is all there and if you disable the addon, the domain will appear.

![Bildschirmfoto zu 2020-08-10 23-03-25](https://user-images.githubusercontent.com/26622301/89831658-7edc5880-db5e-11ea-88d0-c44d841f336a.png)

![Bildschirmfoto zu 2020-08-10 23-05-47](https://user-images.githubusercontent.com/26622301/89831647-797f0e00-db5e-11ea-88a3-f29e2e25f244.png)

**Comment by PromoFaux** [comment]
Amazing, so uBlock is filtering out even the mention of the url on the page?

**Comment by yubiuser** [comment]
Yes. It's the link containing the domain that triggers the filtering

(editing the link in developer mode makes the entrie re-appear)

![Bildschirmfoto zu 2020-08-10 23-27-49](https://user-images.githubusercontent.com/26622301/89833355-31151f80-db61-11ea-88c8-42d18a83b16f.png)

**Comment by KommX** [comment]
Thank you for having a look @yubiuser, you're right. I also use uBlock Origin and can see that the filters `##[href*=".smartadserver.com"]` and `##a[href*=".smartadserver.com"]` apply here.

So, it's no bug in pi-hole and I'll close this issue.
