### ISSUE TITLE
Regex GUI Missing "Group Assignment"

### ISSUE THREAD

**Issue by Gill-Bates** [pi-hole/web#1553]
**Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2**

![image](https://user-images.githubusercontent.com/25774289/89899450-9d843300-dbe2-11ea-8c6f-80a5c31d42f2.png)

**Pi-hole v5.1.1 · Web Interface v5.1 · FTL v5.1**
![image](https://user-images.githubusercontent.com/25774289/89899516-b68ce400-dbe2-11ea-81cf-b6a3d8dc0454.png)

Regex-Function not working! Blocked Domains still resolved!

**Comment by Bugbavka** [comment]
> 
> 
> You'r looking at the wrong spot.
> 
> If you click "Blacklist", **Group assignment has never been there**. Only if you go to "Group Management/Domains" the column is visible.

I can clearly see **Group assignment** in **Blacklist** in v5.0
![PH5 0_blacklist_groups](https://user-images.githubusercontent.com/65173213/90038115-4dca6800-dcc5-11ea-9d5d-640528abfdc2.png)
EDIT:
It is only visible for first load of the page, then the "Group assignment" column is hidden.
After deleting "groups-domains-table" from Local Storage it is visible again for one page load.



But it is also in **Domain management**
![PH5 0_groups_domains](https://user-images.githubusercontent.com/65173213/90038914-43f53480-dcc6-11ea-8455-57c4d9db9aad.png)

**Comment by yubiuser** [comment]
Not showing Group assignment is the intended behavior
https://github.com/pi-hole/pi-hole/blob/6b536b7428a1f57ff34ddc444ded6d3a62b00a38/gravity.sh#L173

I don't recall exactly, but there might have been an improvement from v5, not even show it on first load.

**Comment by beporter** [comment]
I too am missing the `Group` column on the blacklist and whitelist pages from my installation (Pi-hole v5.6, FTL v5.11, Web Interface v5.8). 

The docs seem to indicate it _should_ be there: https://docs.pi-hole.net/database/gravity/example/#example-3-blacklisting

Still poking around for leads...

**Comment by beporter** [comment]
See also #1608 maybe?

**Comment by PromoFaux** [comment]
> Not showing Group assignment is the intended behavior

This is the answer here. The blacklist and whitelist pages are designed to be simple and automatically add entries to the default group (for those who don't just groups)

Group assignment is only shown on the group management -> domains page.
