### ISSUE TITLE
Change to filtering for non-mobile browsers has broken mobile browsers functionality

### ISSUE THREAD

**Issue by reinstej-sci** [pi-hole/web#1561]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  

- Platform:  RPi

### Expected behavior

In a mobile browser, I should be able to click on an item in the query list to filter with. This was previous behavior prior to AdminLTE 5.1

### Actual behavior / bug

Clicking does nothing on mobile now. This is a consequence of this change: https://github.com/pi-hole/AdminLTE/pull/1222

### Steps to reproduce

1. On a MOBILE device, go to admin portal > Query Log > try to click anything as you could before to filter by that item.
2. Clicking does nothing other than highlight the item.

## Debug Token

- URL:  https://tricorder.pi-hole.net/83rew407ff

### Screenshots

<img width="940" alt="Screen Shot 2020-08-14 at 2 00 09 PM" src="https://user-images.githubusercontent.com/41453087/90293325-aff7aa00-de38-11ea-807c-fe8346bdb8ec.png">

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
The reason to use Ctrl+ Click was to combine two functions and get rid of the "Apply click to ..." checkbox: be able to click/select an entry (e.g. domain) for copy&pasting and Ctrl+Click for filtering.

But mobile users might have been a bit out of focus when changing the behavior.

Do you have suggestion how 1) selecting the text 2) apply filtering 3) on desktop&mobile 4) without checkbox could be combined from a UI perspective? Which key+click combinations would you prefer?

**Comment by yubiuser** [comment]
Potential fix
https://github.com/pi-hole/AdminLTE/pull/1568

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/AdminLTE/pull/1602
