### ISSUE TITLE
Conditional forwarding subnet only accepts /8/16/24/32 subnets, wont accept /23 for example

### ISSUE THREAD

**Issue by marl-scot** [pi-hole/web#1567]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform
Linux pihole 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
Debian Buster
PiHole IP : 192.168.4.229/23
Router IP : 192.168.4.254/23
Local DNS server (with DHCP) : 192.168.4.248/23
PiHole configured with 192.168.4.248 as its first and second Upstream DNS servers.
DHCP server configured to issue PiHole IP as DNS server to clients
- Platform:  

### Expected behavior

Under Settings -> DNS
Enable conditional forwarding
Local network in CIDR notation : 192.168.4.0/23
IP address of your DHCP server : 192.168.4.253
Click SAVE
Expect settings to be saved

### Actual behavior / bug

You get an error : 
 Error
Conditional forwarding subnet ("192.168.8.0/23") is invalid!
This field requires CIDR notation for local subnets (e.g., 192.168.0.0/16).
Please use only subnets /8, /16, /24, and /32.
The settings have been reset to their previous values

### Steps to reproduce

Under Settings -> DNS
Enable conditional forwarding
Local network in CIDR notation : 192.168.4.0/23
IP address of your DHCP server : 192.168.4.253
Click SAVE

**Comment by yubiuser** [comment]
Thanks for the report.
It's a known limitation of the underlying dnsmasq and needs to be fixed there. 

See discussion
https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975
