### ISSUE TITLE
Ctrl + Click on query page isn't OS friendly

### ISSUE THREAD

**Issue by DalenW** [pi-hole/web#1570]
https://github.com/pi-hole/AdminLTE/blob/a03d1bddf74f0164f637126b06705bb659dfa4e7/scripts/pi-hole/js/queries.js#L510

Currently this displays "Ctrl + Click" on all systems. On macOS this behavior is really "Cmd + Click". A simple if statement using navigator.platform can check if the website is on macOS or Windows or Linux, and return the correct key combo.

**Comment by yubiuser** [comment]
Your're right, the tooltip only says "Ctrl+Click" but below the table it's already macOS friendly :)

![Bildschirmfoto zu 2020-08-31 08-06-24](https://user-images.githubusercontent.com/26622301/91687795-ee8fa300-eb60-11ea-9e43-7ff981634df5.png)

Pinging @PromoFaux as he drafted a modified version that makes the filtering a bit more user friendly. He might change the tooltip as well.

**Comment by PromoFaux** [comment]
I didn't even notice the tooltip (shows how often I actually use the ui!) Will take a look

**Comment by DL6ER** [comment]
`navigator.platform` isn't necessarily reliable. Firefox adopted anti-fingerprinting from the Tor Browser, causing the screen resolution to be randomized for the website. Similarly, the local time zone can be shuffled. It wouldn't wonder if this does also involve randomizing the `navigator` object to avoid identification of the user by browser version, operating system or maybe even platform.

Just a word of caution here. I intentionally put both into the table @yubiuser showed above.

**Comment by PromoFaux** [comment]
This is no longer an issue in newer versions of Pi-hole:

![image](https://user-images.githubusercontent.com/1998970/149009351-e8a499b3-a41b-4feb-a744-93857b52be93.png)
