### ISSUE TITLE
Light dialogs when using dark mode

### ISSUE THREAD

**Issue by ghost** [pi-hole/web#1571]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Ubuntu 20.04.1 LTS

- Platform:  Raspberry Pi

### Expected behavior

When dark mode is enabled also the dialogs should appear in their dark scheme.

### Actual behavior / bug

The dialogs are using light scheme.

### Steps to reproduce

1. Go to Admin Interface -> 'Settings'
2. Select dark mode and save ('API / Web interface' -> 'Web interface settings')
3. Click on any of the buttons available in the 'System' tab

### Screenshots

![light_dialog](https://user-images.githubusercontent.com/28714277/91712472-19d9b880-eb88-11ea-8041-24d438df5945.png)

**Comment by kevlg** [comment]
What do you think about this variant? 
![Dialog](https://user-images.githubusercontent.com/68795862/103319184-7d6cd900-49f6-11eb-838d-f4d8d98df975.PNG)

**Comment by DL6ER** [comment]
@kevlg that looks fine, would you open a PR for it? We just seem to have forgotten dialogs at all when designing the dark mode CSS

**Comment by kevlg** [comment]
> @kevlg that looks fine, would you open a PR for it? We just seem to have forgotten dialogs at all when designing the dark mode CSS

Yes, I will
