### ISSUE TITLE
Apostrophe ' turning into &#039;

### ISSUE THREAD

**Issue by coldfire7** [pi-hole/web#1584]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform
- OS and version:  Ubuntu 20.04.1 LTS
- Platform:  VM (Proxmox LXC)

### Expected behavior
Apostrophe `'` in comment saving as apostrophe `'`

### Actual behavior / bug
Apostrophe `'` turning into `&#039;`

### Steps to reproduce
1. Go to http://pi.hole/admin/groups-adlists.php
2. Click on any adlist comment
3. Type anything with an apostrophe **'** in comment and save

## Debug Token
- URL:  https://tricorder.pi-hole.net/0zl5zo2l3u

### Screenshots
GIF: https://i.imgur.com/XPtnMVB.gif

### Additional context
n/a

**Comment by yubiuser** [comment]
Fixed in 
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909/1
