### ISSUE TITLE
Web Interface: make the boxes foldable to gain rendering speed after login  

### ISSUE THREAD

**Issue by phenomeus** [pi-hole/web#1589]
hi everybody, 

can we get a button to collapse and expand the boxes on the dashboard to gain render time after login? of course all are open by default but can be modified to close boxes and the system remembers that. 

![Bildschirmfoto 2020-09-18 um 11 40 05](https://user-images.githubusercontent.com/5281493/93583441-2772a900-f9a4-11ea-8e62-fcf5f59f23bd.png)

**Comment by PromoFaux** [comment]
Per the links given when opening a new issue, we ask that all feature requests are opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests/8)

![image](https://user-images.githubusercontent.com/1998970/93584379-1d997780-f99d-11ea-8e38-4fb582d6ea11.png)

(Appreciate this/issue template may not have shown if you opened the issue from a mobile app)

Of course, Pull Requests are always considered, too.

**Comment by phenomeus** [comment]
done https://discourse.pi-hole.net/t/foldable-boxes-on-dashboard-for-better-rendering-time/39590
