### ISSUE TITLE
CORS issue in Webinterface when used with reverse proxy

### ISSUE THREAD

**Issue by dosera** [pi-hole/web#1592]
### Versions
- Pi-hole:  5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Arch Linux
- Platform:  Docker

### Expected behavior
I would expect being able to update the settings when using a reverse proxy `http://mydomain/pihole` the same as when using `http://pi.hole` directly.

### Actual behavior / bug
I run pihole in docker and everything works fine except a reverse proxy to the web interface. When updating any setting I receive 

```
White page with this message:
“Failed CORS: null vs 192.168.178.5, , myhostname, pi.hole, localhost, 192.168.178.5”
and the settings are not saved.
```

### Steps to reproduce

1. Install in docker
2. Setup a nginx reverse proxy, e.g. something like

```
    location ^~ /pihole/ {
        proxy_pass http://localhost:80;
	proxy_set_header Host $host;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Upgrade $http_upgrade;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $remote_addr;
    }
    
    location /pihole/admin {
        return 301 /pihole/admin/;
    }

    location ~ ^/pihole/admin/(.*)$ {
        rewrite /pihole/(.*) /$1 break;
	proxy_pass http://localhost:80;
	proxy_set_header Host $host;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Upgrade $http_upgrade;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $remote_addr;
    }
```
3. Navigate to the website and try to save any setting.

### Additional context

I narrowed it down to the `/var/www/html/admin/scripts/pi-hole/php/auth.php` to line 74:
```
if (!isset($_SERVER['HTTP_ORIGIN'])) {
    ...
}
```

For some reason the value of that variable is `null` (as a string!) and therefore the check fails. 
If I replace the `isset` with something like

```
function is_null_or_empty($str){
    return (!isset($str) || trim($str) === '' || trim($str) === 'null');
}
```

everything works fine, yet I am not sure whether this would circumvent any necessary CORS check.

**Comment by dschaper** [comment]
This would render the CORS check moot. It would not actually be a CORS check anymore.

**Comment by dschaper** [comment]
What is the actual URL you are using? `http://pi.hole/admin/` being redirected from `http://pi.hole` only works if you actually use `http://pi.hole` as the domain. Any other domain needs to be `http://new.domain/admin/`.

I think this was discussed on reddit? The answer here is the same as the answer I provided there. https://www.reddit.com/r/pihole/comments/iz8sai/reverse_proxy_into_admin_interface/

**Comment by dosera** [comment]
Hi, first of all thanks for your quick reply!

> This would render the CORS check moot. It would not actually be a CORS check anymore.

Yeh that's what I suspected - I am still confused on why the variable is 'null' (as string) though.

> What is the actual URL you are using? http://pi.hole/admin/ being redirected from http://pi.hole only works if you actually use http://pi.hole as the domain. Any other domain needs to be http://new.domain/admin/.

The URL I am using is `http://mydomain/pihole/admin` (which is just redirected to my pihole container).

> I think this was discussed on reddit? The answer here is the same as the answer I provided there. https://www.reddit.com/r/pihole/comments/iz8sai/reverse_proxy_into_admin_interface/

Thanks for the link, I didn't find it for some reason when I googled.

`Access-Control-Allow-Origin' '*';` wouldnt this make the CORS moot as well? Also the second comment just suggests what I did.

**Comment by dschaper** [comment]
> `Access-Control-Allow-Origin' '*';` wouldnt this make the CORS moot as well? Also the second comment just suggests what I did.

The CORS check may not be what you want for your use case. It was originally designed as a way to prevent advertisers from trying to trick users in to whitelisting their domains via a crafted advertisement. The original error message shows you the list of the domain names that will pass through the CORS check without issue. 

> Yeh that's what I suspected - I am still confused on why the variable is 'null' (as string) though.

Empty string is one of the passing configurations. Not passing anything at all in the proxy pass block is what sends a null value and blows up the process.

> The URL I am using is `http://mydomain/pihole/admin` (which is just redirected to my pihole container).

Make sure the URL you redirect to is `http://pi.hole/admin/` exactly, including the trailing slashes. `pi.hole` can be substituted with the IP, the main goal is to make sure `/admin/` is the target. The `lighttpd` configuration helps users by redirecting `http://pi.hole` or `http://pi-hole/admin` to `http:/pi-hole/admin/` so use the final actual URL as your proxy pass destination.

**Comment by dosera** [comment]
This works fine - thanks a bunch for your help!
