### ISSUE TITLE
Unable to add or manipulate clients/group management

### ISSUE THREAD

**Issue by codejitsu117** [pi-hole/web#1605]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Pi

### Expected behavior

_A clear and concise description of what you expected to happen._
Upon update to newest version all known IP addresses do not show within lists
### Actual behavior / bug

_A clear and concise description of what the bug is._

cannot add or manipulate new clients or groups.

### Steps to reproduce

1. Go to '...' :Group Management
2. Click on '....' Groups or Clients
3. Scroll down to '....' Add client
4. See error: Drop down lists IP's but none that are known clients from previous version

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Have you flushed all the caches in your browser?

**Comment by codejitsu117** [comment]
Yes. When I update gravity on command line I see the links for all the add lists as well but they do not show on the web gui

**Comment by dschaper** [comment]
Debug token please, as the template requested.

**Comment by dschaper** [comment]
And please clarify why you mention the `gravity` command when this issue is about group management?

**Comment by codejitsu117** [comment]
It’s more on web gui 
Im unable to see or manipulate client lists/groups/adlists 

I put the debug token in the form. Don’t have it off hand at the moment but can send once Im able.

**Comment by dschaper** [comment]
> I put the debug token in the form.

It's not on the form I see, I would not have asked for it otherwise.

**Comment by dschaper** [comment]
I've found a debug log from about this same time range. If this is your log then remove the URLs for sites from your adlists, they are incorrect. Gravity should have warned you.

```plain
*** [ DIAGNOSING ]: Adlists
   id    enabled  group_ids     address                                                                                               date_added           date_modified        comment                                           
   ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   1           1  0,2,3         https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts                                      2020-07-06 12:43:56  2020-10-17 12:07:18  Migrated from /etc/pihole/adlists.list            
   2           1  0,2,3         https://mirror1.malwaredomains.com/files/justdomains                                                  2020-07-06 12:43:56  2020-10-17 12:07:20  Migrated from /etc/pihole/adlists.list            
   3           1  0,2,3         https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt                                      2020-07-06 12:43:56  2020-10-17 12:07:21  Migrated from /etc/pihole/adlists.list            
   4           1  0,2,3         https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt                                            2020-07-06 12:43:56  2020-10-17 12:07:23  Migrated from /etc/pihole/adlists.list            
   5           1  0,2,3         http://www.dshield.org/feeds/suspiciousdomains_High.txt                                               2020-07-06 13:26:49  2020-10-17 12:07:24                                                    
   6           1  0,2,3         https://isc.sans.edu/block.txt                                                                        2020-07-06 13:30:09  2020-10-17 12:07:27                                                    
   7           1  3             Http://www.facebook.com                                                                               2020-09-11 22:06:52  2020-10-17 12:07:28                                                    
   8           1  3             Http://www.Pinterest.com                                                                              2020-09-11 22:07:57  2020-10-17 12:07:26                                                    
   9           1  3             Http://www.snapchat.com                                                                               2020-09-11 22:08:38  2020-10-17 12:07:25                                                    
   11          1  0,2,3         https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt                      2020-10-17 11:39:35  2020-10-17 12:07:28                                                    
   12          1  0,2,3         https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt              2020-10-17 11:40:17  2020-10-17 12:07:30                                                    
   13          1  0,2,3         https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt                    2020-10-17 11:41:27  2020-10-17 12:07:24                                                    
   14          1  0,2,3         https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.b  2020-10-17 11:43:00  2020-10-17 12:07:31                                                    

```

**Comment by dschaper** [comment]
Also, I see 3 groups with 9 clients. The log is showing attempts to add IP address for clients that already exist.
```plain
   2020-10-18 15:10:32: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: client.ip in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 279
   2020-10-18 15:10:38: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: client.ip in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 279
   2020-10-18 15:12:44: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: client.ip in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 27
```

**Comment by codejitsu117** [comment]
Correct.
But they aren’t visible on the web Interface. 
I can see them through command line.

**Comment by dschaper** [comment]
Does it do the same with a different browser and/or incognito mode?

**Comment by codejitsu117** [comment]
Yes. Usually use edge but have tried with firefox/chrome.

**Comment by onkelenno** [comment]
I'm not sure if it's the same issue, but since upgrading to new pihole (Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7), there comes up an error when loading the group management/clients web site. The reason is, now it is possible to add MAC-Addresses but in groups.php it still searches for the ip. If the result is empty, $result === false -> FastCGI-stderr: PHP Notice:  Trying to access array offset on value of type bool.

/var/www/html/admin/scripts/pi-hole/php/groups.php
$stmt = $FTLdb->prepare('SELECT name FROM network_addresses WHERE ip = :ip;');
...
 $name_result = $result->fetchArray(SQLITE3_ASSOC); -> ERROR

temporary solved it with:
$stmt = $FTLdb->prepare('select network_addresses.name from network_addresses left join network on network_addresses.network_id=network.id where upper(network.hwaddr)=upper(:ip) or network_addresses.ip=:ip');
...
if ($name_result!==false) {
    $res['name'] = $name_result['name'];
} else {
    $res['name'] = 'address_not_found';
}
