### ISSUE TITLE
Whitelist/Blacklist entries are not displayed

### ISSUE THREAD

**Issue by BamButz** [pi-hole/web#1606]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2
- Chrome: 86.0.4240.80

### Platform

- OS and version:  Raspbian 9

- Platform:  Docker

### Expected behavior

Whitelist/Blacklist shows list of entries.

### Actual behavior / bug

Whitelist/Blacklist shows empty list of entries.

### Steps to reproduce

1. Go to 'Whitelist'
2. Add an Entry
3. List is empty even after a full page refresh

#### JavaScript Stacktrace (Chrome)

```
Uncaught TypeError: utils.bsSelect_defaults is not a function
    at HTMLDocument.<anonymous> (groups-domains.js:58)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.I (jquery.min.js:2)
```

**Comment by wixaw** [comment]
i have same issue after update :/

**Comment by PromoFaux** [comment]
It's likely a cache issue in the browser.

Try clearing the cache (e.g `ctrl+f5` on chrome) and trying again. You can also confirm this issue by trying in another browser, or in incognito mode.

**Comment by wixaw** [comment]
Yeah , i force clear cache and it's work
Sorry

**Comment by PromoFaux** [comment]
No problem, this is actually something that has been addressed for the next release:

https://github.com/pi-hole/AdminLTE/pull/1550

**Comment by yubiuser** [comment]
Closing as https://github.com/pi-hole/AdminLTE/pull/1550 has been released into master.
