### ISSUE TITLE
The group assignments column is disappearing intermittently under certain conditions

### ISSUE THREAD

**Issue by nielsranosch** [pi-hole/web#1608]
When in blacklist or whitelist view, the group assignments column will disappear under the following conditions:

1. After clearing the browser cache, navigate to blacklist. The group assignments column is visible.
2. Reload the page. The group assignments column is hidden.

Or:

1. After clearing the browser cache, navigate to Group Management --> Domains. The group assignments column is visible.
2. Navigate to blacklist. The group assignments column is hidden.

I am unsure what the inteded behaviour is beacause there is a lot of misinformation floating aruond in similar issues and the forum. But intermittent disappearing cannot be intended. The end result for the user is that they have to clear the browser cache whenever they want to change a group assignment of a black- or whitelisted entry.

The problem is in the file `scripts/pi-hole/js/groups-domains.js` in the function `initTable`--> `stateLoadCallback` (others have claimed that other parts of this file are responsible, but I respectfully disagree; turn on a debugger and see for yourself):

```javascript
    stateLoadCallback: function () {
      var data = utils.stateLoadCallback("groups-domains-table");
      // Return if not available
      if (data === null) {
        return null;
      }

      // Reset visibility of ID column
      data.columns[0].visible = false;
      // Show group assignment column only on full page
      data.columns[5].visible = showtype === "all";
      // Apply loaded state to table
      return data;
    },
```

When initTable is called for the first time, `data` is `null` and `stateLoadCallback` will exit early. On subsequent calls, the rest of the function is executed, including `data.columns[5].visible = showtype === "all";`. This line is - in my opinion - wrong or at least misplaced.

Is it truly desired that the group assignments column is always hidden in black- and whitelist view? I hope that this is not the case, since I quite enjoy the possibility of white- and blacklisting domains per device/group. However, if the intended behaviour is that the group assignments columns is _always_ hidden, then it would be better (and less confusing) if this also worked when the browser cache is empty.

I have prepared a pull request that I will attach to this issue.

**Comment by yubiuser** [comment]
>Is it truly desired that the group assignments column is always hidden in black- and whitelist view? I hope that this is not the case, since I quite enjoy the possibility of white- and blacklisting domains per device/group.

It is the intention. The idea is to make it easier for novice pihole users which might not even use Group Management.
See (paragraph above Tl;DR) https://discourse.pi-hole.net/t/about-unassociated/31633/18

The issue you mentioned (being visible if cache is empty) is addressed in the development brachn already.
https://github.com/pi-hole/AdminLTE/pull/1393

**Comment by nielsranosch** [comment]
I agree that merging #1393 would also fix this issue.
