### ISSUE TITLE
GZip causes http sync and  admin interface to Fails to load on Mac & iOS

### ISSUE THREAD

**Issue by Dlat** [pi-hole/web#1621]
### Versions

- Pi-hole:   v5.1.2
- AdminLTE:   v5.1.1
- FTL:   v5.2

### Platform

- OS and version:  Mac OS

- Platform: Asus Tinkerboard debian

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
CSP header causes certain javascript libraries to fail to load due to CSP violation. This causes the page to time out or never load fully, in safari some pages load but pages are not functional, no graphs work. In the attached Screenshot, there are list of the Javascript files that fail to load. This appears to be present regardless of which browser you use but instead dependent upon what OS is installed on the host. Tested on Mac OS Catalina 10.15.7 Safari 14, Chrome 86.0.4240.183, and both iOS 13 & 14 on Safari, Chrome and Firefox mobile browsers. 

Windows hosts do not exhibit this behavior regardless of which browser once of browser again. Tested with Windows 10 IE, Edge, Chrome, FireFox
_A clear and concise description of what the bug is._
CSP Header policy  for javascript in the admin interface called via script-src-elem nothin in /admin/script and admin/style directories. 

### Steps to reproduce

1. Go to the admin interface using any Mac device, if you use chrome you may need to disable javascript in order to get any the page to render
2. Click on just try going to /admin
3. Scroll down to the browser console in developer mode
4. See error which javascript files fail to load due to CSP violation in header policy

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

<img width="1230" alt="Screen Shot 2020-11-06 at 1 05 21 PM" src="https://user-images.githubusercontent.com/6132540/98451930-df504700-2107-11eb-9d1e-d067c67b0287.png">

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
@jfb-pihole Can you confirm?

**Comment by jfb-pihole** [comment]
I can confirm that I have no problems with MacOS Mojave or Catalina (edit: and also Big Sur) with any of Chrome, Firefox or Safari.  Nor in IOS 14 with Safari or Firefox Focus. Web GUI works normally on all.

**Comment by PromoFaux** [comment]
I'm unable to reproduce this on Browserstack. @Dlat do you have some additional security settings/tweaks on your devices?

![image](https://user-images.githubusercontent.com/1998970/98452697-9f11b880-2149-11eb-9f6a-b51bf89a5628.png)

![image](https://user-images.githubusercontent.com/1998970/98452701-a769f380-2149-11eb-8359-4b4cb52025c3.png)

![image](https://user-images.githubusercontent.com/1998970/98452730-d54f3800-2149-11eb-8953-2c5620d468d5.png)

![image](https://user-images.githubusercontent.com/1998970/98452732-d8e2bf00-2149-11eb-90c3-d945ce76a83b.png)

![image](https://user-images.githubusercontent.com/1998970/98452760-0b8cb780-214a-11eb-84ae-6a890257ce58.png)

**Comment by Dlat** [comment]
if I put this through a proxy like burp  to see what's going on, it works perfectly suddenly. When I look at the wire share I see random responses from the server on the files that either fail to load to get case the server to send rst  Here is the HTTP conversation 

 GET /admin/scripts/vendor/adminlte.min.js HTTP/1.1

Host: 192.168.1.5
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
Accept: */*
Referer: http://192.168.1.5/admin/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: PHPSESSID=grplhg3cpekl43og3ntf48lku0

Response: 

?=.+..(..D|.	....?.........=V.a.m..ek........].'...%.....W..A.c
.c.....G.Y..>..np@.O..p........u.8,D..e{T.:.H[.R,./p..{*.tmw...-=....1.....*/?.#.)1...<)chC...~.=....b....0i&..Q........d
..]."..<....$...?C!.u..ti.~.C.:.._.|..)....O...\..l;......3Zx...I......0.t..Z...."....>.d..H..~.E28k......C......`.0.$ y.h..<....C.y....0.;LX...m6......H...e..a|{....x.U.P..*	.A..@4X..J.K....h.&..R.P..*...l....m.w}.X..x.].WG....~}7.....)S..Q+X..Bz..M...3...z..~.yTlu..F5[E..J.i.r...$}...F.;S......-.K.kp.e.K.C....t@?..zV....x..G^8.....]...U...<....&r.
..'S..lf...l..7....K....
.......J[..o...`...Q..g...J	...T.N..v.N.
KX*CPw. ....Z..\........!4Q.u.*:1.;X..../_.
k..2Fw=....4.........o.;.....$..H......6..|....[.g........
....oo#t.=...T.@....(....D......Xo.X~..[.~;.].zD.7d:%.	/...3.]\T.A...|..A.'..-....0x...z...@..
...../.K. U...........@..1.............|$k`....h\...1......`B.....Xy4d....G.}....)S.Y..@@4...$l..rc@T.l.t.?..e...}..}...9G...}.8j..g.N.$3\..g3.jPd_..8.0..R.Y....K.we...~...;....)G..........p.<.QLt.Z.~g.d.......6...C~.Y.:.....n..)~._..nN+5..

**Comment by PromoFaux** [comment]
Can we get a debug token from your Pi-hole device, please? `pihole -d`

**Comment by Dlat** [comment]
yeah 1 sec

**Comment by Dlat** [comment]
***********************************
[✓] Your debug token is: https://tricorder.pi-hole.net/i0zfj5le4z
***********************************
***********************************

**Comment by PromoFaux** [comment]
Thanks, That all looks OK - nothing obviously wrong with the config there.  I'm not sure what else to say at the moment, being unable to reproduce points this at a configuration difference somewhere...

**Comment by Dlat** [comment]
I reinstalled it from from scratch once as sudo, once a root from a fresh os image and made no config changes. I can recreate the issues consistenantly but the root cause seems to be hard to pin down. I am analyzing the pcap which I can share if you like. I'll let you know what I find

**Comment by PromoFaux** [comment]
Do you have any other systems you can check from, or is this exclusively something you're seeing on MacOS/iOS>

**Comment by Dlat** [comment]
I've narrowed it down to a HTTP desync caused by GZIP in the server response 
Setting the accept-Encoding header from "gzip, deflate" to [blank] causes the server to respond on a page that consistently fails to load for its its "/admin/scripts/pi-hole/js/footer.js" 
I am not sure why this happens but I can recreate it consistently.

**Comment by Dlat** [comment]
it appears to be present only on Mac and iOS 
although it's reproducible on everything

**Comment by laken** [comment]
Seeing the same symptom on MacOS 10.15.7 / Safari 14.0 - I upgraded Pi-Hole and suddenly admin borked as described in OP. Works fine in Chrome.
