### ISSUE TITLE
Graph is hard to understand.

### ISSUE THREAD

**Issue by lue30499** [pi-hole/web#1628]
### Versions
Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2

### Platform
Ubuntu 20.04
LXC

### Expected behavior

The graphs shows the data in a meaningful way.
### Actual behavior / bug

The graph represents the data so that it is hard to see the relative sizes between each query.
Is this ok? Or can this be changed so it scales the data to fit the graph?

### Steps to reproduce

There is no steps.

## Debug Token

- URL:  https://tricorder.pi-hole.net/ryn7i3d04m

### Screenshots

![piholegraph](https://user-images.githubusercontent.com/63104612/99144149-793f6300-26b7-11eb-90c2-14987e6d39ab.jpg)

**Comment by dschaper** [comment]
You have very few hits so far, with those numbers everything is effectively the same value.
