### ISSUE TITLE
Blacklist missing webinterface feature 

### ISSUE THREAD

**Issue by ingmarkleine** [pi-hole/web#1631]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Rasbian

- Platform:  Raspberry Pi

### Expected behavior

Functionality to add a list to block multiple websites in the blacklist

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

Adlist (blocks ads only) only here to provide to block the ads on the website

_A clear and concise description of what the bug is._

## Debug Token

- URL:  https://tricorder.pi-hole.net/4x71mdzod4

### Additional context

There are some warnings and executed commands not found in the `pihole -a -h` or `pihole -h`

**Comment by PromoFaux** [comment]
The blacklist is for blocking _individual_ domains entered.

The adlist page is for adding lists of domains to block - not only ads

**Comment by ingmarkleine** [comment]
> The blacklist is for blocking _individual_ domains entered.
> 
> The adlist page is for adding lists of domains to block - not only ads

solved i guess
