### ISSUE TITLE
Retried DNS querys shows status unknown in query log

### ISSUE THREAD

**Issue by dnhp** [pi-hole/web#1643]
### Versions
- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.3.1

### Platform
- OS and version:  DietPi
- Platform:  Raspberry Pi Zero W

### Expected behavior
Retried DNS queries show in query log correctly, with status 'retried' or 'retried (ignore)'

### Actual behavior / bug
Retried querys have status 'Unknown (12)'.

### Steps to reproduce
1. Disable 'Show permitted domain entries' in Settings -> API/Web Interface
2. Use pihole as normal - load some pages
3. Check query log - some queries appear with status: unknown (12)

## Debug Token
- URL:  https://tricorder.pi-hole.net/x7dv00jvya

### Screenshots
![unknown12](https://user-images.githubusercontent.com/34394848/100722283-5e0f6b80-33b8-11eb-9c8e-09a944342c0e.PNG)

### Additional context
After digging through some Javascript, I believe bug is lines 188-202 of queries.js at commit 2c2d9f5f - numbers 12 and 13 should be quoted with "" like the rest of the numbers in the switch statement. If they're not, switch falls through to default case and prints "Unknown (number)".

**Comment by KommX** [comment]
This issue has been solved in the meanwhile:
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-2-and-ftl-v5-3-4-released/41998

I think this issue should be closed.
