### ISSUE TITLE
Transactions do not appear to be used properly in groups.php

### ISSUE THREAD

**Issue by fhriley** [pi-hole/web#1659]
When editing an adlist, [the transaction begins](https://github.com/pi-hole/AdminLTE/blob/c32bcd3715091ff16937180d52c01a49ccddb5b2/scripts/pi-hole/php/groups.php#L973) after all of the groups for the adlist have been deleted. This means if a failure occurs while adding the groups, the transaction does not get committed and we're left with an adlist that is not in any groups. Is that really the intent? It looks like the transaction placement in other places in `groups.php` have the same issues.

**Comment by DL6ER** [comment]
This has been fixed on Dec 23, 2020 in #1664. Note that in v6.0, `groups.php` is gone and the process has been implemented into FTL as our long-term goal is to remove PHP altogether (PHP-SQLite3 support has already been removed for v6.0). We properly abstracted the differences between the individual list types away to be able to achieve the same with muss less lines of code.
