### ISSUE TITLE
Privacy Level on hide domains but you get the responsible blacklist entry for a query (only for regex entries)

### ISSUE THREAD

**Issue by jonaszr** [pi-hole/web#1684]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v.5.3.4

### Platform

- OS and version:  DietPi v6.34.3

- Platform:  RPi 3 Model B

### Expected behavior

If the privacy level is set to hide the domains you shouldn't be able to see the regex blacklist entry responsible for blocking the Query.

### Actual behavior / bug

In the Query log you can click the Status value of Queries blocked by regex blacklist entries and get the responsible blacklist entry highlighted.

### Steps to reproduce

1. Set the privacy level to Hide domains (and clients)
2. Create an example regex blacklist entry
3. Try opening the domain in your browser
4. Go to the Query Log
5. Click on the Status value "Blocked (regex blacklist)"
6. Now you get to the Domain management page and see the responsible entry  highlighted 

### Screenshots

![Query blocked by blacklisted regex domain](https://user-images.githubusercontent.com/35535400/104008296-8eada680-51a9-11eb-9a76-1120e564a834.png) Query blocked by blacklisted regex domain

![regex blacklist entry highlighted](https://user-images.githubusercontent.com/35535400/104008291-8a818900-51a9-11eb-95f6-f03ceee1ab18.png) regex blacklist entry highlighted

**Comment by DL6ER** [comment]
Thanks for your report. I agree.
This will be fixed by https://github.com/pi-hole/FTL/pull/1016

**Comment by KommX** [comment]
The fix has been released:
https://discourse.pi-hole.net/t/pi-hole-core-v5-2-3-web-v5-3-and-ftl-v5-4-released/43009

@DL6ER This issue can be closed, right?
