### ISSUE TITLE
Lag in the main interface

### ISSUE THREAD

**Issue by Gontier-Julien** [pi-hole/web#1696]
### Versions
- Pi-hole:  v5.2.2
- AdminLTE: v5.2.2  
- FTL:  v5.3.4

### Platform
- OS and version:  Any
- Platform:  Any

### Expected behavior

No lag when opening/closing the side bar.

### Actual behavior / bug

Lag when opening/closing the side bar while having the interface in a similar way from the screenshot.

### Steps to reproduce

Just use any browser and open/close the side-bar, while having the interface in a similar way from the screenshot.

## Debug Token

- URL:  Not needed

### Screenshots

![Screenshot_2021-01-12 Pi-hole - arch-raspberry-dns-server](https://user-images.githubusercontent.com/52894530/104374714-33b5df80-551a-11eb-9ed8-eaf141a0e45f.png)

### Additional context

I've found two solution to stop this bug :

1/ Changing the value of `.chartjs-size-monitor-expand` from `1000000px` to `100%` in the `/div` section of `chartjs-size-monitor-expand`(width only making a difference but idk from height).

2/ Changing the value of `.chartjs-size-monitor, .chartjs-size-monitor-expand, .chartjs-size-monitor-shrink` from `ltr` to `rtl`.

I just can't figure out if the `1000000px` of the chart is needed or not because it not changing anything to the graph, apart of lagging the U.I.

I've also tested this on multiple PC/Laptop/Mobile and all of them have the same strange behavior even on powerful PC and any browsers.

Edit: I've also just look and the `.chartjs-size-monitor-shrink` is only set at `200%` on both widht and height.

Edit 2: After some searching it comes with a solution with `admin/style/pi-hole.css` so it is not a Pi-Hole bug, but it a simple fix so adding this while be great to stop the lap of the interface.

**Comment by Benji-cmd** [comment]
I doesn't work ! please help me

**Comment by DL6ER** [comment]
> After some searching it comes with a solution with `admin/style/pi-hole.css` so it is not a Pi-Hole bug, but it a simple fix so adding this while be great to stop the lap of the interface.

Sorry for the long delay since your first post but what do you mean by that? Do you suggest we should overwrite `chartjs-size-monitor-expand` in `admin/style/pi-hole.css` to become `100%` ?

I'm not seeing this on any device, not even on very low-end hardware and I don't recall anyone else having reported this, so far.

**Comment by Gontier-Julien** [comment]
Don't worry i understand that you are very busy ^^
I don't really know of to explain this, but when you open and close the side-menu there some lag to it when you have the window the same as the screenshot.
It really a minor issue really so it not really important, and i think people didn't really look at it.
I had multiple people that had a pi-hole deploy and experience the same issue but didn't notice it.
And yes i've already have the fix in place in my pi-hole with overwrite that i've mention.
Hope that i've explained it clear ^^'

**Comment by Gontier-Julien** [comment]
I'm closing this since it not important and something is coming Soon™
