### ISSUE TITLE
Broken links in legend for "Queries answered by" pie chart in Dashboard

### ISSUE THREAD

**Issue by spinofdoom** [pi-hole/web#1699]
### Versions
- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.4

### Platform
- OS and version:  macOS 10.15.7 Catalina (viewing Pi-Hole Dashboard via Google Chrome)
- Platform:  Raspberry Pi 4 2GB (running DietPi v6.34.3)

### Expected behavior

On the main Dashboard, if you click on either the colored box next to an element of the legend for the "Query Types" pie chart or the name of the element itself, you are linked to a set of queries that meet that query type (e.g. If you click  'AAAA (IPv6)' or the colored box beside it you are linked to `http://[pihole-ip-address].admin/queries.php?querytype=2`). One would expect the "Queries answered by" pie chart legend to behave the same.

### Actual behavior / bug

The elements of the "Queries answered by" legend forward to their correct destinations (e.g. clicking the word "cache" links to a list of queries at `http://[pihole-ip-address]/admin/queries.php?forwarddest=cache`), but clicking the colored box next to any element links to an empty query page at `http://[pihole-ip-address]/admin/queries.php?forwarddest=`.

### Steps to reproduce

1. Go to Dashboard
2. Scroll down to the "Queries answered by" pie chart
3. Click on any of the colored boxes next to the forward destinations (e.g, blocklist, cache, DNS resolver) listed there
4. See blank query page

## Debug Token

- URL:  https://tricorder.pi-hole.net/6bxqwebod2

**Comment by yubiuser** [comment]
Can confirm the issue.

**Comment by churchofnoise** [comment]
This behaviour has been the case for a while: https://github.com/pi-hole/pi-hole/issues/3418

**Comment by yubiuser** [comment]
Closing as duplicate
