### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#17]
Users should be able to view the web interface in their own language.
There is a POEditor page for the web interface, but the strings are out of date and need to be redone for the new web interface:
https://poeditor.com/projects/view?id=66305

While the strings are being redone, the web interface can start internationalizing its output.

Most likely, we will use the [react-i18next](https://react.i18next.com/overview/introduction) library.
The library supports separating strings into different namespaces, which we can accomplish by adding tags to strings in POEditor and [filtering them by tag when exporting](https://poeditor.com/docs/api#projects_export).

**Comment by PromoFaux** [comment]
<strike>Internationalization</strike> Internationalisation

😉

**Comment by Mcat12** [comment]
Yes, there are libraries which will ease adding this, such as https://react.i18next.com/

**Comment by walter-exit** [comment]
Perfect. So this issue is more like a todo item then?

**Comment by Mcat12** [comment]
Yes, this issue is labeled with the `tracking` label, which signifies:
> An issue used to track a feature, bug, or something else of note.

**Comment by Mcat12** [comment]
You should be able to see the status of the project here: https://github.com/pi-hole/web/projects/1

**Comment by Mcat12** [comment]
No problem, glad to help show people around.

**Comment by Mcat12** [comment]
I updated the strings on POEditor. The tagged strings are the ones that will be used. There will be a script to download them by tag and update the repo with the latest strings.

**Comment by develmts** [comment]
@Mcat12 I helped to translate de Old AdminLTE to Catalan language, but cannot find that language in POEditor project that's linked above, nor can request it through the  POEditor "Suggest" interface. 

Could somebody tell me when Catalan language is allowed ? I'll be glad to help on it

**Comment by Mcat12** [comment]
Weird, I can see it listed as a language, and it's at 99%, even opening it in incognito mode.

**Comment by Mcat12** [comment]
Just the project link from the Issue description: https://poeditor.com/join/project/7LnOlpfC3o
![image](https://user-images.githubusercontent.com/4417660/40735069-3283efb8-6408-11e8-8b8e-5cd5dad618d3.png)

**Comment by develmts** [comment]
OK. My mistake . I was unable to see Catalan until i joined the project using another language for collaboration.

Working on the last string to translate right now ...

**Comment by DL6ER** [comment]
How can a user change the language of the preview?

**Comment by Mcat12** [comment]
Currently, it gets the language from the browser, but there will be a drop-down to select the language.

**Comment by develmts** [comment]
Updated Catalan Translations to 100%
