### ISSUE TITLE
Pie chart percentage is wrong if items are hidden

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1706]
### Versions
```
  Pi-hole version is new/gravity_adlist_infos v5.2.2-10-ga2625df (Latest: v5.2.3)
  AdminLTE version is new/gravity_adlist_infos v5.2.2-11-gab2bb606 (Latest: v5.3)
  FTL version is release/v5.4 vDev-a5cb6f0 (Latest: v5.4)
``` 

### Platform

- OS and version:  Debian Buster (Armbinan)

- Platform:  NanoPi Neo 2 Plus

### Expected behavior

One can hide items from the dashboard pie charts (Query Types and Forward destinations) by middle mouse click. The pie chart is re-drawn and the percentages of each items are re-calculate to the "new" 100%.

### Actual behavior / bug

The percentage of each item still reflects the fraction as if all items have been used to calculate the denominator.

### Steps to reproduce

Go to dashboard, hover over one item of one pie chart, middle click on one item of the legend (hide it), hover again over the oi chart.

![Bildschirmfoto zu 2021-01-19 06-18-07](https://user-images.githubusercontent.com/26622301/104991102-4189ca00-5a1e-11eb-96e7-93ab06c1e6f4.png)
![Bildschirmfoto zu 2021-01-19 06-18-50](https://user-images.githubusercontent.com/26622301/104991103-42226080-5a1e-11eb-9e63-48bab222a0c1.png)

**Comment by DL6ER** [comment]
Is this really a bug? Even when hiding some others, it is still that 9.1% of all queries are HTTPS queries (I'm actually surprised *and* shocked at the same time that Apple's new toy is *that* chatty...).

I can see both interpretations, but I still think the existing behavior is correct. Always showing "the share of the total" seems more meaningful to me as "the share of the remaining".

**Comment by yubiuser** [comment]
The bug for me is the discordance between the chart (showing something like 60%) and the numbers.
I agree, the fraction of the total is more meaningful, but if the tool offers to exclude one item it should draw and calculate the same things. 
In the current implementation I don't see any value in the possibility to exclude items - new nice graph, but without the corresponding numbes no new information.

**Comment by yubiuser** [comment]
Actually I have just one (!) apple device..

**Comment by DL6ER** [comment]
Implemented and already released
