### ISSUE TITLE
Error when whitelisting domain: While executing INSERT OT IGNORE: attempt to write a readonly database Added 0 out of 1 domains 

### ISSUE THREAD

**Issue by ericlathrop** [pi-hole/web#1719]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.3

### Platform

- OS and version:  Ubuntu 20.04.1

- Platform:  Docker

### Expected behavior

I went to `https://.../admin/groups-domains.php?type=white`, filled out a domain, and pushed the button. I expected the domain to be added to the whitelist.

### Actual behavior / bug

A red error message popped up in the upper-right corner of the page with this message: `While executing INSERT OT IGNORE: attempt to write a readonly database Added 0 out of 1 domains`

### Steps to reproduce

1. Go to `/admin/groups-domains.php?type=white` in the web admin
2. Enter a domain in the text box
3. Click the "add to whitelist" button

### Additional Context

Whitelisting the same domain with the `pihole -w` command worked fine.

**Comment by fangebee** [comment]
Similar problem here.  After upgrading (`pihole -up`), we were unable to add domains to the whitelist.
I had to manually fix permissions like this:

    chmod g+w /var/lib/pihole

Now permissions look like this and everything seem fine:
```
$ getent group | grep pihole
pihole:x:998:www-data

$ ls -ld /var/lib/pihole/
drwxrwxr-x 3 pihole pihole 4096 nov.  16 10:18 /var/lib/pihole/

$ ls -l /var/lib/pihole/
total 4557848
-rw-rw-r-- 1 pihole pihole   44871680 nov.  16 08:43 gravity.db
-rw-r--r-- 1 pihole pihole    2691072 juil. 12 17:23 macvendor.db
-rw-rw-r-- 1 pihole pihole 4574781440 nov.  16 10:18 pihole-FTL.db
```

FYI we installed pihole 4 months ago on Debian Buster using https://install.pi-hole.net
