### ISSUE TITLE
DHCP hostname unknown

### ISSUE THREAD

**Issue by wobbo** [pi-hole/web#1723]
There are problems with the hostname. I don't know how best to explain. Therefore the screenshot.

![2021-01-29](https://user-images.githubusercontent.com/12646389/106318953-020a7b80-6271-11eb-8d9e-b32e5bd442e6.png)

**Comment by dschaper** [comment]
`unknown` means the client didn't send a hostname with the lease request. The static lease hostname is what you set on the DHCP server but that hostname doesn't have to be accepted by the client.

**Comment by wobbo** [comment]
Where can I get the file where I have all DHCP hostname? Then I can do everything at once `.` replace to `_`. Otherwise I have to delete one by one and create a new one.

**Comment by wobbo** [comment]
`sudo nano /etc/dnsmasq.d/04-pihole-static-dhcp.conf`
