### ISSUE TITLE
 Adlists are not administrable via web after upgrade

### ISSUE THREAD

**Issue by nfontan** [pi-hole/web#1726]
### Versions
root@raspberrypi:~# pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.2 (Latest: v5.3.2)
  FTL version is v5.6 (Latest: v5.6)

### Platform
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch

- Platform:  
 Raspberry pi 3+

### Expected behavior

add and delete lists from the web platform is no longer possible after updating the 3 modules

## Debug Token

- URL:  
[✓] Your debug token is: **https://tricorder.pi-hole.net/o6oyai7nsl**

### Screenshots

![image](https://user-images.githubusercontent.com/51861356/106393699-69dad680-63d7-11eb-8fbd-9b6bb0c6e6f8.png)
![image](https://user-images.githubusercontent.com/51861356/106393816-df46a700-63d7-11eb-9ad5-16735d54e3f6.png)

[pihole_debug.log](https://github.com/pi-hole/pi-hole/files/5900416/pihole_debug.log)

**Comment by dschaper** [comment]
Have you cleared the browser cache or rebooted the Pi-hole device?

**Comment by nfontan** [comment]
> Have you cleared the browser cache or rebooted the Pi-hole device?

yes, I have already done both actions and tested with different browsers.

I have also tried adding a list from there and the browser does not show any action

![image](https://user-images.githubusercontent.com/51861356/106394700-a230e380-63dc-11eb-9dd5-1a9238a8fbaa.png)

![ss](https://user-images.githubusercontent.com/51861356/106395786-e4f5ba00-63e2-11eb-8018-82e379538f6f.gif)

**Comment by dschaper** [comment]
There seems to be some errors or modifications to the web interface:

```plain
   2021-01-31 14:51:55: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:52:01: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:52:33: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:52:45: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:53:00: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:53:29: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 14:53:42: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
   2021-01-31 15:03:06: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined index: run in /var/www/html/panel/index.php on line 18
   2021-01-31 15:03:06: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined index: run2 in /var/www/html/panel/index.php on line 23
```

The last two lines are for files that we do not use or provide.

**Comment by nfontan** [comment]
I 

> There seems to be some errors or modifications to the web interface:
> 
> ```
>    2021-01-31 14:51:55: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:52:01: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:52:33: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:52:45: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:53:00: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:53:29: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 14:53:42: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 5, database is locked in /var/www/html/admin/scripts/pi-hole/php/gravity.php on line 14
>    2021-01-31 15:03:06: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined index: run in /var/www/html/panel/index.php on line 18
>    2021-01-31 15:03:06: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined index: run2 in /var/www/html/panel/index.php on line 23
> ```
> 
> The last two lines are for files that we do not use or provide.

I have 2 php web running on local
/var/www/html/panel
/var/www/html/cam

but I don't think this impacts the pihole. This one worked fine until the pihole update.
I also update the system's php. Maybe the problem comes this way

**Comment by dschaper** [comment]
Remember, any changes made to `lighttpd.conf` will be overwritten:
https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L10-L16

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by nfontan** [comment]
Hi, I was finally able to solve the problem.
I took the groups-adlists.js file from the official pihole git (https://raw.githubusercontent.com/pi-hole/AdminLTE/master/scripts/pi-hole/js/groups-adlists.js)  and replaced it with the one from my system in /var/www/html/admin/scripts/pi-hole/js
It seems that in this update the file was not replaced correctly

**Comment by DL6ER** [comment]
Can you run
```
cd /var/www/html/admin
git status
```
and give us the output?

Just to ensure there are no more errors around.

**Comment by nfontan** [comment]
Now , detect the change

![image](https://user-images.githubusercontent.com/51861356/106781912-5a060100-6628-11eb-8541-12e31a0161e1.png)

**Comment by DL6ER** [comment]
Okay, so what does
```
git describe
git diff
```
say in this directory?

**Comment by nfontan** [comment]
Ini this release
https://github.com/pi-hole/AdminLTE/releases/tag/v5.3.2
The groups-adlists.js file has an empty line at the end.
This caused the problem.

![image](https://user-images.githubusercontent.com/51861356/106783077-a867cf80-6629-11eb-9067-c66f56044d34.png)
![image](https://user-images.githubusercontent.com/51861356/106783171-c03f5380-6629-11eb-979e-85eac0e8b106.png)

**Comment by dschaper** [comment]
> The groups-adlists.js file has an empty line at the end.
> This caused the problem.

Not likely. Your changes probably cleared the `lighttpd` cache and that is what resolved the issue.
