### ISSUE TITLE
Configuring a "catch-all" blacklist doesn't work as expected

### ISSUE THREAD

**Issue by DrEsteban** [pi-hole/web#1727]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  pihole/pihole:latest Docker image, so whatever base OS you use :)

- Platform:  Docker on Synology

### Expected behavior

I have a client group called "lockdown" which is intended to block ALL DNS requests for the group. So, I specify a Regex Blacklist rule and assign it _only_ to the "lockdown" group.

On the Group Management > Domains page, if I enter `*` as the Domain, click the checkbox for "Add domain as wildcard", and add it and configure it as described above, I would expect _all_ DNS queries from the configured group to be blocked.

### Actual behavior / bug

Using the checkbox, the actual generated Regex is `(\.|^)*$`. This does not work, and DNS queries from these clients continue to go through.

### Steps to reproduce

1. Create a client group and assign a machine to it
2. Go to Group Management > Domains
3. Enter `*` as a domain, click the checkbox for "Add domain as wildcard", then click "Add to Blacklist"
4. Update the group assignment to apply only to the client group created in step 1

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I am able to workaround the problem by using the "RegEx filter" tab instead of the domain tab:
![image](https://user-images.githubusercontent.com/1495037/106557196-26b35d00-64d6-11eb-9456-4095d1eb27b0.png)

There, if I enter `.*` and configure it as described above, I get the desired behavior and all "locked down" clients are blocked from making any DNS queries.  So to my eye, this appears to be a bug in how the web UI generates Regex based on the input.

**NOTE**: The repro steps above used to work on previous versions of PiHole. I recently upgraded my Docker image and started seeing this behavior. Unfortunately I'm not sure what version I upgraded _from_, though :(

**Comment by DL6ER** [comment]
The reason for this is that domains actually never supported any kind of wildcard behavior. There is this special checkbox that replaces `something.com` (and also `*.something.com`) by `(\.|^)something\.com$`, however, as you entered only `*`, this didn't result in a working regex for you. I think the proper solution would be to check if something like `*` remains in the generated "regex'ed" domain and reject it. In the end, it will be beneficial for users to check out how to define regular expressions.

As side note. When you'd have tried to enter `*.*` this should actually have worked.

**Comment by DL6ER** [comment]
As this can surely be improved on, however, it also doesn't seem really like a bug that needs urgent fixing, I decided to put it into the ongoing v6.0 development branch. We try to keep changes to the existing web interface code as small as possible to reduce merge conflicts and more administrative work down the road.

The relevant code changes are in df871a72b7115569ab347562f39df65cf094ceac and ensure that adding a domain with `*` in it will not be accepted (a hint to using regex is given in this case):

![Screenshot at 2021-02-02 08-52-22](https://user-images.githubusercontent.com/16748619/106569271-9821f880-6534-11eb-8af7-40832104e045.png)

Adding domains that can be converted using the checkbox still works:

![Screenshot at 2021-02-02 08-52-41](https://user-images.githubusercontent.com/16748619/106569279-9a845280-6534-11eb-8aef-40e0da37ed24.png)
![Screenshot at 2021-02-02 08-52-54](https://user-images.githubusercontent.com/16748619/106569280-9b1ce900-6534-11eb-897b-32312f624a24.png)

**Comment by DrEsteban** [comment]
Awesome! Thanks @DL6ER. All makes sense and appreciate the consideration for v6.
