### ISSUE TITLE
PiHole Dashboard icons sit on top of white text (z-index off)

### ISSUE THREAD

**Issue by mrballistic** [pi-hole/web#1732]
### Versions

  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.2 (Latest: v5.3.2)
  FTL version is v5.6 (Latest: v5.6)

### Platform

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Raspberry Pi

### Expected behavior

On the top heading icon set for the dashboard, there are a series of four semitransparent icons. They sit on top of the text, but should be integrated into the background padding, rather than on top of the whole lozenge. This is a visual bug.

### Actual behavior / bug

The icon sits on top of the text, rather than under it.

### Steps to reproduce

1. Go to dashboard in the web ui.
2. Note that the icons sit on top of the text, rather than under it.

## Debug Token

- URL:  https://tricorder.pi-hole.net/lhaloa0atz

### Screenshots

![Screen Shot 2021-02-03 at 3 01 29 PM](https://user-images.githubusercontent.com/88927/106820737-b9680f00-6630-11eb-8137-8b3ccceccb2a.png)

### Additional context

_Add any other context about the problem here._

**Comment by mrballistic** [comment]
new token: https://tricorder.pi-hole.net/hlt78iycsh

**Comment by PromoFaux** [comment]
Ah yes, I can see this on my own, though I probably don't know enough about CSS to being to say where to fix it :)

![image](https://user-images.githubusercontent.com/1998970/107256517-80b1a680-6a31-11eb-96af-edd27ddadbc6.png)

Changing the `z-index` value does not appear to make any difference

**Comment by dschaper** [comment]
It may be in the AdminLTE itself. Though you'd have to set the z-index for the text, the icon and the box. Or set the z-index for the text and make it a position (relative).

`.small-box .icon` already is set to `z-index: 0`. 

Setting `.small-box .inner` to `z-index: 1` and `position: relative` seems to work but I haven't checked if that breaks anything else.

**Comment by PromoFaux** [comment]
Yeah it's in the vendor file, so if we were to do anything we'd need to do it as an override (I guess in `pihole.css`)

**Comment by rdwebdesign** [comment]
Adding **z-index: 0** to the `.small-box` and **z-index: -1** to the `.small-box .icon` should work:

_pi-hole.css_:
```diff css
.box, .small-box {
    border-radius: 10px;
+    z-index: 0;
}
+.small-box .icon {
+    z-index: -1;
+}
```

**Comment by yubiuser** [comment]
@rdwebdesign 
Would you mind setting up a pull request

**Comment by rdwebdesign** [comment]
@yubiuser
I'll try, if I have time to do it.

**Comment by yubiuser** [comment]
The fix has been released to master
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-11-web-v5-8-and-core-v5-6-released/50566
