### ISSUE TITLE
Teleporter modifies regex blacklist domain on export

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1733]
### Versions

rockpi@rockpi-4b:~$ pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is devel v5.3.2-1-g6ff083a (Latest: v5.3.2)
  FTL version is development vDev-c355e85 (Latest: v5.6)

### Platform

- OS and version:  NanoPi Neo Plus2

- Platform:  Armbian Buster

### Expected behavior

Exporting domains (blacklist regex) should be unmodfied.

### Actual behavior / bug

Exporting regex blacklist modifies the domain

### Steps to reproduce

I found a strange regex in my blacklist and wondered where it came from. 

`^(www[0-9].)?xn&ndash;`

I left it there but noticed on a re-import via teleporter that the regex was further modified to 
`^(www[0-9].)?xn&amp;ndash;`

Exporting it again, already the archive (resp. json) contained
`^(www[0-9].)?xn&amp;amp;ndash;`

**Comment by DL6ER** [comment]
This comes from 
https://github.com/pi-hole/AdminLTE/blob/1521dfe3f46eb7bfd87a0644a1fadcf5bfd0f7f9/scripts/pi-hole/php/teleporter.php#L199
which could be removed. Another question would be, though, why you had the `&` in there at all? This is not a valid domain (nor regex) character so this regex will never match anything (as there will never be a literal `&` in the domain name).

**Comment by yubiuser** [comment]
I have no idea. I strongly suspect the regex was different initially but copy&pasting error (or teleporter im/export) modified it to it actual form.

**Comment by dschaper** [comment]
Likely it was `^(www[0-9].)?xn-` and the htmlescape changed it to `^(www[0-9].)?xn&dash;` and then it all cascaded from there.

**Comment by DL6ER** [comment]
@dschaper I was just about to say the same. It still doesn't make much sense as the source for `&ndash;` must have been https://www.compart.com/en/unicode/U+2013 which would neither have been found in any real domain name.

**Comment by dschaper** [comment]
Somebody copied `xn--` and it pasted as `xn–`

Edit: Fun with font ligatures.

**Comment by DL6ER** [comment]
The good ol copy-pasta making something useful entirely useless (as this regex would *never* match anything). We can at least fix the issue that should not have appeared if there wouldn't have been illegal characters :upside_down_face:

**Comment by DL6ER** [comment]
@PromoFaux added this escaping last year https://github.com/pi-hole/AdminLTE/commit/c949516ee15fa6a9b0c8511cc4c4d6b0893f3e69 andm thinking again about it, I don't think we should remove it:

1. It does not change any valid domain nor regex
2. It prevents being able to add malicious code into the database.

We intentionally added it so imported Teleporter files cannot create "dangerous" entries in the database. Think of a teleporter file you found on the web that claims to improve your Pi-hole. In fact, it contains some domains with stuff like `<script>....</script>` and the next time you visit the dashboard bad things happen (like device shutting down, etc.).

Even if the "fix" would be simple, I'm inclined to mark this issue ticket `won't fix` for the mentioned reasons.

**Comment by yubiuser** [comment]
Agree with you due to the mentioned reasons. As long it does not modify valid regex, there is no point in remove the function an loose security.

**Comment by yubiuser** [comment]
Found the source
https://github.com/mmotti/pihole-regex/commit/90e765571e63409fd975f88374fa46a51917a31b#diff-edd2aa78d0b2e016f94aa75fb201205fd821095d2453efe835afd205c89f5059
