### ISSUE TITLE
Custom nameserver issue (2692 feature/api)

### ISSUE THREAD

**Issue by gh-jamesmontgomery** [pi-hole/web#174]
I came across an issue in the build trying to use a custom name server.

`pihole -v`
 > Pi-hole version is v4.2.2-81-g4ae113a (Latest: v4.2.2)
  AdminLTE version is -1 (Latest: v4.2)
  FTL version is vDev-320a9c8 (Latest: v4.2.3)

Followed build steps on [PR 2692](https://github.com/pi-hole/pi-hole/pull/2692)

Error when trying to use 127.0.0.1#5300 as nameserver:
![image](https://user-images.githubusercontent.com/24221446/55707210-f33b4080-59da-11e9-88e5-a8d9a9910e8e.png)

`cat /etc/dnsmasq.d/pihole.conf`
>localise-queries
local-ttl=2
cache-size=10000
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list
log-queries
log-facility=/var/log/pihole.log
log-async
domain-needed
bogus-priv
local-service

Workaround:
Update `/etc/dnsmasq.conf` and `pihole restartdns`
>conf-dir=/etc/dnsmasq.d
server=127.0.0.1#5300

**Comment by gh-jamesmontgomery** [comment]
I tried via direct API call and it will accept `127.0.0.1:5300`. However, the resulting file `/etc/dnsmasq.d/pihole.conf` does not permit pihole-FTL to start.

>localise-queries
local-ttl=2
cache-size=10000
server=127.0.0.1:5300
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list
log-queries
log-facility=/var/log/pihole.log
log-async
domain-needed
bogus-priv
local-service

I modified the file manually to the following which allows FTL to start and use the loop back resolver.

>localise-queries
local-ttl=2
cache-size=10000
server=127.0.0.1#5300
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list
log-queries
log-facility=/var/log/pihole.log
log-async
domain-needed
bogus-priv
local-service

**Comment by Mcat12** [comment]
Thanks for testing! I've opened PRs in web and API to fix this.

The reason for using `#` was to more easily plug the servers into the dnsmasq config, as it requires `#` to separate the address from the port. However, addresses and ports are more commonly split by `:`. Using `#` may not be intuitive to many users, especially new ones, so it is better to use `:`.

This means that as part of the migration to the new API and web interface, we will have to automatically fix the servers in setupVars.
