### ISSUE TITLE
Error while trying to enable DNSSEC

### ISSUE THREAD

**Issue by schorschfunke** [pi-hole/web#1744]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---

**Expected behavior:**

`Enable or disable DNSSEC`

**Actual behavior:**

`It reports the following error: There was a problem applying your settings.
Debugging information:
PHP error (2): Undefined array key "v6_2" in /srv/http/pihole/admin/scripts/pi-hole/php/savesettings.php:276 `

**Steps to reproduce:**

`Enable/disable DNSSEC from the settings page`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`no (unsupported archlinux aur build)`

**Troubleshooting undertaken, and/or other relevant information:**

`-`

**Comment by dschaper** [comment]
>no (unsupported archlinux aur build)

You'll have to ask the AUR maintainers. The output specifically says to not open issues here.

**Comment by max72bra** [comment]
Hi dschaper (i'm the AUR maintainer). Sorry for the opened issue.
The issue is generated by PHP8 adoption in archlinux distro.
validIP function at line 14 in savesettings.php is and will not be PHP8 compatible.

**Comment by PromoFaux** [comment]
Ah. As a heads up, we're moving away from PHP and lighttpd for v6.0 - rather we will be embedding the webserver and API into FTL, so we're not really looking to be supporting PHP8

You can follow progress [here](https://github.com/pi-hole/ftl/tree/new/http) and [here](https://github.com/pi-hole/adminlte/tree/new/FTL_is_my_new_home)

Some of this might even make your life easier on the AUR side, thinking about it :)

**Comment by max72bra** [comment]
Oh! Nice. It's surely a good idea. Lots of (Archlinux) people are messing up with multiple web servers trying to make their needs coexist with those of pi-hole, maybe this will address all.
