### ISSUE TITLE
"Query status" check boxes in "Long-term data" --> "Query Log" don't have any effect

### ISSUE THREAD

**Issue by KommX** [pi-hole/web#1750]
### Versions

Pi-hole version is v5.2.4 (Latest: v5.2.4)
AdminLTE version is v5.4 (Latest: v5.4)
FTL version is v5.7 (Latest: v5.7)

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

Unchecking the "Query status" boxes updates the results in the "Recent Queries" section.

### Actual behavior / bug

Checking or unchecking has no effect at all.
I don't see any button to refresh the results after (un)checking the boxes.

### Steps to reproduce

1. Go to <IP>/admin/db_queries.php (Long-term data --> Query Log)
2. Check and uncheck any check box, e.g. Permitted: forwarded

## Debug Token

- URL:  https://tricorder.pi-hole.net/qsn37j2h0r

### Screenshots

![image](https://user-images.githubusercontent.com/7859245/109121753-f6af5080-7747-11eb-9506-08173bbb4849.png)

**Comment by yubiuser** [comment]
I agree the behavior is not intuitive.
You need to first check the boxes and then select the desired time frame.

**Comment by KommX** [comment]
Ah, I see. That didn't even come to my mind because the time frame picker is above the boxes.

**Comment by jgrisham** [comment]
So, we should put the date picker _below_ the checkbox section?

**Comment by KommX** [comment]
> 
> 
> So, we should put the date picker _below_ the checkbox section?

I guess, either that or give the user the possibility to execute a query after (un)checking boxes.

**Comment by rdwebdesign** [comment]
Fixed by #1957
