### ISSUE TITLE
Make QR code generation fast by using client-side JS library instead of PHP

### ISSUE THREAD

**Issue by bershanskiy** [pi-hole/web#1752]
### Versions

- Pi-hole:  v5.2.4 (Latest: v5.2.4)
- AdminLTE:  devel v5.4-15-g1195920 (Latest: v5.4)
- FTL:  v5.7 (Latest: v5.7)

### Platform

- OS and version:  Reaspbian 10 Buster

- Platform:  Raspberry Pi Zero W

### Expected behavior

API token QR code page opens quickly, QR code displays quickly.

### Actual behavior / bug

When I reload API token QR code page, it takes over 1.8 seconds.

### Steps to reproduce

1. Login into AdminLTE
2. Go to API token QR code page at `[pi-hole host]/admin/scripts/pi-hole/php/api_token.php`
3. Measure page load time (open browser developer tools "Network" tab, reload the tab and look at load time).
4. See value over 1 second.

## Debug Token

Not applicable, since it is a known issue.

### Screenshots

Not applicable.

### Additional context

This is a known issue, since it's the Settings UI even says "Note that the generation of the QR code will take some time.": https://github.com/pi-hole/AdminLTE/blob/1195920211e89c9205851556b9794fa980134804/scripts/pi-hole/js/settings.js#L125

This slow-down is caused by the PHP implementation of [QRCode](https://github.com/pi-hole/AdminLTE/blob/master/scripts/vendor/qrcode.php). When I remove QR code generation from [scripts/pi-hole/php/api_token.php](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/php/api_token.php#L11) (lines 11-13), the page loads almost immediately. There are many many fast JS libraries with great browser support, e.g. [`qrcode.js`](https://davidshimjs.github.io/qrcodejs/).

If you are interested in reviewing such a PR, I'd like to replace PHP library with `qrcode.js`. It's licensed under MIT and has wide browser support (all the way back to IE 6).

**Comment by DL6ER** [comment]
Generating the QR code in PHP is the typical version of `nothing is more definitive than the temporary`. We're currently actively developing Pi-hole v6.0 and reduce the usage of PHP wherever possible. However, we also have a new challenge-response authentication scheme which will make the QR code obsolete anyway. So I'd say it's not worth changing the QR code generation given that we'd soon remove the JS generator as well (as we won't use any QR codes at all).

**Comment by bershanskiy** [comment]
Thank you for a prompt reply!

> We're currently actively developing Pi-hole v6.0

I saw FTL [`new/http`](https://github.com/pi-hole/FTL/tree/new/http) branch, is it part of the Pi-hole 6.0? How can I learn more?

> So I'd say it's not worth changing the QR code generation given that we'd soon remove the JS generator as well (as we won't use any QR codes at all).

I'll close this issue now, then.

**Comment by dschaper** [comment]
For my curiosity, how often are you creating QR codes?

**Comment by DL6ER** [comment]
> I saw FTL new/http branch, is it part of the Pi-hole 6.0?

Yes, it's the core of Pi-hole v6.0. There is also an AdminLTE branch https://github.com/pi-hole/AdminLTE/tree/new/FTL_is_my_new_home matching this development. There is no related core branch, however, the backwards compatibility w preserved so far starts to become a limiting factor.

**Comment by bershanskiy** [comment]
> For my curiosity, how often are you creating QR codes?

Not often at all, I just was playing with the UI and noticed that QR code part was very sluggish amid otherwise pretty neat controls.
