### ISSUE TITLE
DHCP - Invalid MAC address?

### ISSUE THREAD

**Issue by mooleshacat** [pi-hole/web#1756]
### Versions

  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

### Platform

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

- Platform:  RASPI 3

### Expected behavior

I clicked to add a static listing and it pre-populated the form. When I clicked on SAVE I expected it to save and add the entry into the static leases table.

### Actual behavior / bug

I get invalid mac address error (screenshot below)

### Steps to reproduce

1. Go to settings
2. Click on 'DHCP' tab
3. Scroll down to 'DHCP leases'
4. Find a DHCP lease and click the orangy button beside it to pre-populate the form
5. Edit the IP address and click the plus sign to add it to the static leases table
6. See the error (MAC address ######## is invalid)

Alternatively enter the same information manually, same error shows.

## Debug Token

- URL:  https://tricorder.pi-hole.net/mpqs75nhnv

### Screenshots

![Screenshot 1](https://i.ibb.co/94945wS/Screenshot-2021-03-03-19-32-13.png)

### Additional context

None

**Comment by mooleshacat** [comment]
I have found more information because I left the DHCP server running.

![Image 2](https://imgur.com/ys5eR1m.png)

You can see that the issue is only with IPV6 clients the IPv4 clients are fine...

Is there a software fix I can make ? Or just wait I guess.

`nor really something you should be doing.`

I disagree here, IPV6 is where everything is going. You need to have it enabled because a lot of services are already using IPV6.

You need IPV6 support. If it doesnot have IPV6 support I will have to disable DHCP server and go back to my router DHCP server.

**Comment by dschaper** [comment]
We won't be supporting DHCPv6.

**Comment by mooleshacat** [comment]
> We won't be supporting DHCPv6.

Then I will stop donating to pihole because V6 is a feature I need and you don't support it. V6 is where the internet is going, whether you like it or not. You need to be prepared for the internet of tomorrow. V4 is running out of space and V6 is coming online already ISP's are assigning V6 now.

**Comment by dschaper** [comment]
> I disagree here, IPV6 is where everything is going. You need to have it enabled because a lot of services are already using IPV6.
> 
> You need IPV6 support. If it doesnot have IPV6 support I will have to disable DHCP server and go back to my router DHCP server.

DHCPv6 is a kludgy hack. If you want to use IPv6 then use it and let it configure as IPv6 was designed to do.

**Comment by dschaper** [comment]
> Then I will stop donating to pihole because V6 is a feature I need and you don't support it.

Then stop using Pi-hole.

**Comment by dschaper** [comment]
>  V4 is running out of space and V6 is coming online already ISP's are assigning V6 now.

We fully support IPv6. We don't, and won't, support DHCPv6. You're talking to different things and you need to learn the difference.

**Comment by mooleshacat** [comment]
> DHCPv6 is a kludgy hack. If you want to use IPv6 then use it and let it configure as IPv6 was designed to do.

Let it configure? What do you mean? I used whatever defaults I never changed anything I just clicked the checkbox

**Comment by dschaper** [comment]
> Let it configure? What do you mean? I used whatever defaults I never changed anything I just clicked the checkbox

Learn what SLAAC is.

**Comment by mooleshacat** [comment]
> Then stop using Pi-hole.

Hey jackass, that's what I was implying. I will also contact about refunding the donation because I don't donate to jackasses, nor do I donate to projects that are not looking far enough into the future.
