### ISSUE TITLE
Reverse DNS Lookup Forwarding Logic Backwards

### ISSUE THREAD

**Issue by charles-vomacka** [pi-hole/web#1757]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform

- OS and version:  Debian 10

- Platform: PC 

### Expected behavior
In Advanced DNS settings, checking the 'Never forward reverse lookups for private IP ranges' check box should cause Pihole to not forward reverse lookups to upstream DNS. 

### Actual behavior / bug
In Advanced DNS settings, checking the '_Never forward reverse lookups for private IP ranges_' check box causes Pihole to forward reverse lookups to upstream DNS (my local network DNS server). Unchecking the box causes Pihole to **not** forward lookups. Pihole does the opposite of what the label describes.

### Steps to reproduce

1. In Advanced DNS settings, **check** the '_Never forward reverse lookups for private IP ranges_' check box 
2. Save Settings
3. Do a DNS reverse lookup - lookup to upstream (local network) DNS server will succeed.
4. In Advanced DNS settings, **uncheck** the '_Never forward reverse lookups for private IP ranges_' check box
5. Save Settings
6. Do a DNS reverse lookup - lookup to upstream (local network) DNS server will fail with  "no such domain"

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Check your `/etc/dnsmasq.d/01-pihole.conf` and see if `bogus-priv` is shown when the box is checked, and not shown when the box is unchecked.

**Comment by dschaper** [comment]
And provide a debug token as requested or we'll close the issue.

**Comment by dschaper** [comment]
![Screenshot_2021-03-05 Pi-hole - raspberrypi](https://user-images.githubusercontent.com/2782850/110154786-82a12800-7d99-11eb-8a09-57cf63ecb0fd.png)

**Comment by charles-vomacka** [comment]
You can close this issue. It seems to be working correctly today. Something must have gotten out of sync, but would be difficult to debug now.
