### ISSUE TITLE
Whitespace in input fields should be trimmed before validation

### ISSUE THREAD

**Issue by Yrlish** [pi-hole/web#1758]
### Versions
- Pi-hole version is v5.2.4 (Latest: v5.2.4)
- AdminLTE version is v5.4 (Latest: v5.4)
- FTL version is v5.7 (Latest: v5.7)

### Platform
- OS and version: Ubuntu 18.04
- Platform: VM

### Expected behavior

Domain input fields in Local A/CNAME records should trim whitespace before validation.

### Actual behavior / bug

When hastily copy-pasting full FQDNs from the table below into the input fields, tab characters can come with the clipboard before or after the pasted FQDN. This turns the value in the field invalid. Less noticeable when it is in the end, spaces and tabs are "invisible".

### Steps to reproduce

1. Go to `/admin/cname_records.php`
2. Enter `	hostname.local	` (whitespace around; tabs or spaces)
3. Press `Add`
4. Error

### Screenshots

![image](https://user-images.githubusercontent.com/3358782/110171436-fffd8480-7dfb-11eb-807e-21de2c04e71c.png)

### Additional context

This bug is for user convivence. Trimming input fields are usually a good idea, normally spaces/tabs in the beginning or end of a value can be removed. This would also help mobile users where keyboards normally adds a space behind words.

**Comment by Yrlish** [comment]
I checked through the code and it seems A entries get trimmed. [scripts/pi-hole/php/func.php#L131-L135](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/func.php#L131-L135)

Apparently, for the case of CNAMEs, one can type multiple domains separated with a comma and gets split and trimmed before validation. [scripts/pi-hole/php/func.php#L309-L313](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/func.php#L309-L313)
So this part needs a trim, like the A example above. [scripts/pi-hole/php/func.php#L296-L297](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/func.php#L296-L297)

**Comment by Yrlish** [comment]
I created a pull request for the missing trim.

**Comment by PromoFaux** [comment]
Should be fixed with 5.5
