### ISSUE TITLE
Settings page has multiple elements with broken functionality

### ISSUE THREAD

**Issue by ghost-in-the-zsh** [pi-hole/web#1771]
### Summary

There're several broken widgets in the Settings page.

On the **System tab**, buttons at the bottom of the page no longer do anything. For example, clicking the "Restart system" or "Restart DNS resolver" buttons does nothing. Other buttons may have the same issue, but I've not exhaustively tested every single one of them. (I've not seen errors in the browser's console log.)

The following widgets also show empty values instead of their actual numbers:

- DNS cache size
- DNS cache insertions
- DNS cache evictions

On the **DNS tab**, the "Upstream DNS Servers" table shows a checkbox on the last row, but nothing associated with it. (If I recall correctly, there also used to be some additional fields under this tab that are no longer present.)

Lastly, the following tabs no longer show their respective UIs when clicked:

- API / Web Interface
- Privacy
- Teleporter

### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi Zero W

### Expected behaviors

- When the buttons under the System tab are clicked, they perform their functions (e.g., "Restart system" actually restarts the system).
- When the tabs are clicked, the tab-specific UIs are displayed with their associated options and functionality.
- Label widgets with associated values actually have their values displayed.

### Actual behavior / bug

- Clicking the buttons does not trigger the associated functions (e.g., "Restart system" does nothing).
- When the tabs in question are clicked, the UI does not update to show their specific UIs.
- Some label widgets show empty/no values.

### Steps to reproduce

1. Log in to your Pi-Hole
2. Click on "Settings" in the left-hand menu
3. Click the buttons in under the System tab, the tabs mentioned above, etc.
4. Notice the actual behaviors instead of the expected behaviors.

### Screenshots

**System Tab:** Empty Widgets
![pihole-00](https://user-images.githubusercontent.com/81123101/111928522-857a6900-8a79-11eb-803e-ed43ace81ad2.png)

**DNS Tab:** Broken Row
![pihole-01](https://user-images.githubusercontent.com/81123101/111928523-857a6900-8a79-11eb-8443-9b8c32e77904.png)

**Other Tabs:** No UI Updates. Notice that the actual UI displayed is from the **System** tab instead of the selected ones.
![pihole-02](https://user-images.githubusercontent.com/81123101/111928524-8612ff80-8a79-11eb-9400-b8d1bb2d5761.png)
![pihole-03](https://user-images.githubusercontent.com/81123101/111928526-8612ff80-8a79-11eb-97f3-4014c6e495f8.png)
![pihole-04](https://user-images.githubusercontent.com/81123101/111928527-8612ff80-8a79-11eb-935b-ef3bfd88b7d8.png)

### Additional context

I have the `pihole -up` command running as a cron job, so I'm not sure when these first became an issue. A few other things I tried, which made no difference:

- disabling browser plugins (Firefox 86 under Ubuntu) to make sure they weren't causing conflicts (has never been an issue before, but still checked);
- tried using a different browser

**Comment by ghost-in-the-zsh** [comment]
> Don't do that. Really, don't do that.

Reason being?... I'd like to avoid going off-topic, but briefly, why is that even a "problem"?

**Comment by dschaper** [comment]
First time you get an incompatible update and it torches your installation you'll understand.

**Comment by ghost-in-the-zsh** [comment]
> First time you get an incompatible update and it torches your installation you'll understand.

Please, avoid the seemingly snide/unhelpful remarks... in any case, from what I understand, the `pihole -up` command only gets the official releases, not the most recent commits, so how would manual updates be any different here? If an "incompatible" release is made (whatever "incompatible" means in this context), then wouldn't manually running `pihole -up` also screw things up?

**Comment by dschaper** [comment]
We harp, and harp, and harp on telling people to "Read the release notes BEFORE you update". Changes are not always backwards compatible, we have breaking changes that happen.

**Comment by dschaper** [comment]
Reviewing your debug logs for this issue and for the other issue you opened shows me that you're most likely going to have to wipe everything and start over again. You have a lot of problems with your current setup.

**Comment by ghost-in-the-zsh** [comment]
> We harp, and harp, and harp on telling people to "Read the release notes BEFORE you update". Changes are not always backwards compatible, we have breaking changes that happen. Reviewing your debug logs for this issue and for the other issue you opened shows me that you're most likely going to have to wipe everything and start over again. You have a lot of problems with your current setup.

After all this fuss, the only thing you were close to being "correct" on was the database "corruption" claim. I found the cause of the problem and fixed it... and it was not DB corruption, or network configuration, or incompatibility.

Basically, the `pihole-FTL.log` included a message saying the disk had become full:
```
[2021-03-21 22:14:47.029 32689/T32693] parse_neighbor_cache() - Database is not available
[2021-03-21 22:14:47.039 32689/T32693] SQLite3 message: statement aborts at 1: [DELETE FROM message;] database or disk is full (13)
[2021-03-21 22:14:47.040 32689/T32693] ERROR: SQL query "DELETE FROM message;" failed: database or disk is full
```
A disk becoming full will cause problems such as making the DB "unavailable" and so on, but you probably already knew that. What made the disk full in the first place was the Apt cache, which was ~4.5GBs in size already.

I cleared the cache with `sudo apt clean`, renamed/restored the old "corrupted" DB back to its original name/path (to undo the previous set of steps I had been asked to run) and restarted the pi-hole. The system is working fine again, just like before.

Unfortunately, weird browser widget behavior does not immediately scream "disk is full", so I forgot to check disk usage during my initial troubleshooting.

At the end of the day, I ended with the impression that some here may've simply skimmed the log files for excuses to dismiss the issue and/or make unnecessary remarks, whereas, had you looked more carefully, you wouldn't have missed this detail, which is pretty important. (It would've also been a more helpful and productive thing to do.) In any case, I'll be closing both of them in a few moments.

Regards.

**Comment by dschaper** [comment]
Glad you solved your own issue by reading the logs.

**Comment by PromoFaux** [comment]
> At the end of the day, I ended with the impression that some here may've simply skimmed the log files for excuses to dismiss the issue and/or make unnecessary remarks, whereas, had you looked more carefully, you wouldn't have missed this detail,

Try taking a look over the debug log yourself. There is nothing in there that indicates that the disk is full.

It does, however, indicate some other oddities that need looking at.

```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the wlan0 interface:
   192.168.0.7/24 matches the IP found in /etc/pihole/setupVars.conf
```

The default gateway, which should be your router, is not responding to a ping...

```
[i] Default IPv4 gateway: 192.168.0.1
192.168.0.1
   * Pinging 192.168.0.1
192.168.0.1...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

However, it _is_ acting as your DHCP server, and telling clients that the DNS IP address is `192.168.0.5` (not that this is a different IP address from that of your Pi-hole device)

```
   DHCP options:
    Message type: DHCPOFFER (2)
    server-identifier: 192.168.0.1
    lease-time: 3600 ( 1h )
    renewal-time: 1800 ( 30m )
    rebinding-time: 3150 ( 52m 30s )
    netmask: 255.255.255.0
    broadcast: 192.168.0.255
    domain-name: "skynet.lan"
    hostname: "pi-hole"
     
   -------------> dns-server: 192.168.0.5 <------------
     
    wpad-server: <cntrl sequence> (length 1)
    router: 192.168.0.1
    --- end of options ---
```

Dan was right to mention these things.

Really, do not have `pihole -up` on a cron job. That's just asking for something to go wrong - or for an irreversible change to happen. If we thought auto updating was a good idea - we would include a way to do it by default ;) (hint: We don't, and wont)

**Comment by ghost-in-the-zsh** [comment]
> Try taking a look over the debug log yourself. There is nothing in there that indicates that the disk is full.

It seems you're right. I guess I expected error messages that are actually present in other logs to be included. My bad 🤷‍♂️


> It does, however, indicate some other oddities that need looking at.
> 
> ```
> *** [ DIAGNOSING ]: Networking
> [✓] IPv4 address(es) bound to the wlan0 interface:
>    192.168.0.7/24 matches the IP found in /etc/pihole/setupVars.conf
> ```

The odd thing that I find there is that the router keeps assigning the `.7` address to `wlan0` instead of the `.6` address that's specified for it in its MAC-based DHCP lease config/entry. (The `.7` is meant for different RPi board. I double-checked this again earlier today. I've not observed this oddity in any other of my LAN systems.)

The intent behind having both `eth0` and `wlan0` online was to have 2 DNS server entries on the router, one for each interface. IIRC, that didn't work out so well when I first tried b/c it was also the 1st time I was doing the setup, but I may try again in the future just to play around with it. (I've considered NIC Teaming with `teamd`, but I'd like to avoid installing too many things to preserve very limited disk space.)


> The default gateway, which should be your router, is not responding to a ping...

The router *is* the gateway. While the router is configured to not respond to pings, that's supposed to be only from the WAN side, not the LAN side. (It's a built-in DD-WRT config option.) Not sure why the Pihole wasn't able to ping it while generating the debug log; I can ping the router just fine if I SSH into the pihole:

```
$ ping atc
PING atc.skynet.lan (192.168.0.1) 56(84) bytes of data.
64 bytes from atc (192.168.0.1): icmp_seq=1 ttl=64 time=0.543 ms
64 bytes from atc (192.168.0.1): icmp_seq=2 ttl=64 time=0.604 ms
64 bytes from atc (192.168.0.1): icmp_seq=3 ttl=64 time=0.545 ms
64 bytes from atc (192.168.0.1): icmp_seq=4 ttl=64 time=0.595 ms
```

I think that hiccup must've been caused by something else while the log was being generated.


> However, it _is_ acting as your DHCP server

The pihole's DHCP server option is not enabled and never has been. The `setupVars.conf` file does have `DHCP_ACTIVE=false`, which I think is the relevant part. (Yes, I had added some config values for the fields, but I didn't activate its DHCP service itself. Only the router runs the DHCP service.)


> and telling clients that the DNS IP address is `192.168.0.5` (not that this is a different IP address from that of your Pi-hole device)

The Pi board's IP address (for `eth0`) is `192.168.0.5`. The one for `wlan0` currently is `192.168.0.7` and it's the only one displayed on the pihole GUI.

Note that the above remains true even if I run `sudo ip link set down wlan0`.


> Dan was right to mention these things.

There was more to that interaction, but sure.


> If we thought auto updating was a good idea - we would include a way to do it by default ;) (hint: We don't, and wont)

I've removed it, but that's just... unfortunate :c

**Comment by PromoFaux** [comment]
Sorry, yeah, the part where I mentioned "it _is_ acting as your DHCP server", the "It" in this case was your router, not Pi-hole. I could see in setupVars that DHCP was switched off on Pi-hole.

> I've removed it, but that's just... unfortunate :c

Pi-hole is a _critical_ part of your network infrastructure. If it goes down, you lose DNS resolution. Sure - you know about it pretty quickly, but you might not have time to deal with the fallout caused by allowing it to update automatically. We don't intentionally mess things up when we make new releases, but we're only human - and humans make mistakes from time to time. Not only that, sometimes we might release a breaking change which fundamentally changes how a process works- which we are allowed to do, following [semantic versioning](https://semver.org/) - Hypothetically, we may even make changes that _require_ user intervention at the point of upgrade.... Best practice with these things - follow the release announcements (blog, github, wherever) and schedule a maintenance window to make the upgrade. Things are less likely to bite you in the ass that way


PS.
General advice (this is not a discussion point as it's WAY off topic): Respond to the content of a comment/post, not the (perceived) tone. It makes it easier for everyone to at least _try_ to get along.
