### ISSUE TITLE
Web Interface Admin (Translate)

### ISSUE THREAD

**Issue by Tom362-a** [pi-hole/web#1775]
Hello everyone.
I translated the Pi-Hole administration page (in part) and I wonder why there are many languages ​​on the Crowdin website and only English in the interface ?? Is something not working properly or maybe it concerns something else ..?
There are "php" and ".js" files in Pi-Hole's resources, and only .js on Crowdin's website

**Comment by yubiuser** [comment]
The development of a rust-based Pi-hole web interface (including the ability to change the interface's language) has been discontinued. That's why it says "abandoned" on the  crowdin site's header
https://crowdin.com/project/pi-hole
