### ISSUE TITLE
"Remember me for 7 days" doesn't work if you log in from Recent Queries

### ISSUE THREAD

**Issue by squeak9** [pi-hole/web#1777]
### Versions

- Pi-hole:   v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7 

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi 2

### Expected behavior

I tend to mainly visit the **Recent Queries** of the web interface, I get there by typing pi-hole into my browser history and then it suggests the url to that page and that's how I get there.

If you go to `http://192.168.x.x/admin/queries.php`, enter your password and check the "Remember me for 7 days" checkbox and log in it should remember you for 7 days.

### Actual behavior / bug

If you go to `http://192.168.x.x/admin/queries.php` and log in then it won't remember you for 7 days, you will only be logged in during the session.

[As this reddit post says](https://www.reddit.com/r/pihole/comments/epwnux/remember_me_for_7_days_not_working/feng7ki/) it works fine if you log in to  `http://192.168.x.x/admin/index.php?login`

### Steps to reproduce

1. Open Firefox 87.0 (64-bit) and [make a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) just to be safe.
1. Enter the URL to to directly to the Recent Queries page of your pi-hole, example: `http://192.168.x.x/admin/queries.php`
1. Enter your password.
1. Check the "Remember me for 7 days" box.
1. Close Firefox and open it again.
1. Visit the pi-hole page again. It didn't remember you.

**Comment by chrismiceli** [comment]
I have created https://github.com/pi-hole/AdminLTE/pull/1870 to attempt to address this. It appears that the cookie was only set if the query contained login, which only happens in the home page login flow which results in a 302 redirect. I don't see why setting this on any login is ill advised.

**Comment by chrismiceli** [comment]
Can we close this issue now that the merge request was accepted? Or do we wait for devel to be merged to master for an official release @yubiuser , @DL6ER, @PromoFaux? (https://github.com/pi-hole/AdminLTE/pull/1870)

**Comment by yubiuser** [comment]
I would wait until master

**Comment by yubiuser** [comment]
The fix has been released to master
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-11-web-v5-8-and-core-v5-6-released/50566

**Comment by lutfor-diu** [comment]
i'm also facing this same issue in latest version.

**Comment by chrismiceli** [comment]
@lutfor-diu I am not able to repro what you suggest. What steps do you take to recreate this issue?
