### ISSUE TITLE
Problems with adlist page on new v5.8

### ISSUE THREAD

**Issue by MPeti1** [pi-hole/web#1780]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8

### Platform

- OS and version:  Raspbian Buster

- Platform:  Docker on Raspberry Pi

### Expected behavior

No alert message, and no missing values for the new attributes of adlist entities.

### Actual behavior / bug

On opening the adlists page (/groups-adlists.php), I get 2 alert windows:
-  [the first one](https://user-images.githubusercontent.com/9215491/114793036-0bd45300-9d79-11eb-841a-c85ed1ec6e4f.png)
- [the second one](https://user-images.githubusercontent.com/9215491/114793078-1db5f600-9d79-11eb-874d-90a700397e63.png)

I also get a [similar alert window](https://user-images.githubusercontent.com/9215491/114793178-5bb31a00-9d79-11eb-8a99-22ef15bb19e9.png) on enabling  or disabling an adlist, but not always, and sometimes I get 2 alert windows here too.

An other symptom is that [some attributes are missing](https://user-images.githubusercontent.com/9215491/114793305-974de400-9d79-11eb-907a-606fa6a931b9.png) for every adlist entity:
- health status
- number of valid domains
- number of invalid domains

### Steps to reproduce

1. Go to the adlist management page ([server domain or ip]/groups-adlists.php)
2. See first native browser alert dialog when the table element is emtpy
3. Click OK to close the dialog
4. See second native browser alert dialog when the table is filled with adlist entities
5. Click OK to close the dialog
6. The table column sizes gets changed a bit, but that's probably not important.

## Debug Token

- URL:  https://tricorder.pi-hole.net/oos8zgof9p

### Screenshots

Above included as links.

### Additional context

I've just updated from pihole/pihole:5.6 to pihole/pihole:5.8.
I haven't used v5.7, but #1745 seems similar

**Comment by dschaper** [comment]
```plain
   [✗] Apr 15 00:51:26 dnsmasq[406]: bad address at /etc/pihole/local.list line 2 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Apr 15 00:51:26 dnsmasq[406]: bad address at /etc/pihole/local.list line 4 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
```

**Comment by dschaper** [comment]
Can you please post the `docker run` command or `docker-compos.yml` file that you are using?

**Comment by PromoFaux** [comment]
Do a manual run of gravity (either from the web interface or with `docker exec -it [container name] pihole -g` (Guessing you have gravity disabled on container startup)

**Comment by MPeti1** [comment]
The problematic lines in local.list are assigning `0:0:0:0:0:0` to pi.hole and to the container's hostname.

Here is my docker-compsoe.yml: https://gist.github.com/MPeti1/51aef84a726d6c0b69d169536b7d18d2

> Guessing you have gravity disabled on container startup

Yes, I have it so.

**Comment by MPeti1** [comment]
After updating gravity everything is ok. Well, I should've figured this out by myself

**Comment by PromoFaux** [comment]
>Well, I should've figured this out by myself

Don't worry about it.. it stumped me for a little while too!
