### ISSUE TITLE
Web Interface not working on non standard port

### ISSUE THREAD

**Issue by davidscherf** [pi-hole/web#1781]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8 (Latest: v5.8)

### Platform
Windows 10 Works Fine

Android 11 not working

### Expected behavior
Site should complete loading and display the site, just like it does on Windows

### Actual behavior / bug

Pihole is running on port 8080, Any android browser never completes loading, its just blank with a progress that is stuck

### Steps to reproduce

1. Set your pihole to port 8080
2. Web browse from your phone in my case http://192.168.1.220:8080/admin/

## Debug Token

- URL:   https://tricorder.pi-hole.net/auhaunvz5b

### Additional context

Works fine on Windows
Pihole is a Clean install and has only just had 1 update, still not working though
Pihole is running on port 8080

**Comment by PromoFaux** [comment]
I think this is more likely an issue on the android end rather than Pi-hole. Do you have any other devices you can try from?

**Comment by davidscherf** [comment]
Tried another phone, Android 10, same result

**Comment by PromoFaux** [comment]
I was rather hoping you could try maybe an iPhone or something :) I've tried to reproduce this here to no avail... I can't really think what might be causing it...

**Comment by davidscherf** [comment]
I just tires it on an IPod touch 6th gen using Safari, same result

Could this be an issue the other way around, although seems strange to only affect mobile devices

Pihole specs
The Device im using is a Tinkerboard
Armbian 21.02.3 Buster
Kernel 5.10.21

**Comment by PromoFaux** [comment]
I'm going to ask a really silly question, but sometimes silly things can happen....

When you try to browse to `http://192.168.1.220:8080/admin/` from your phone, are you definitely on the same network as the pi-hole?

Another thing to test - set back the `lighttpd` config to be stock - and then attempt to load on your phone via `http://192.18.1.220/admin/`

**Comment by davidscherf** [comment]
Same Network

Have changed it back to port 80, Still having the same issue

Had no issue with the Dot Net core website I was running on port 80, disabled for this test.

**Comment by davidscherf** [comment]
I tied from a virtual Pixel C Android 10, Admin site seems to work from that.
No idea why real devices get blocked

**Comment by PromoFaux** [comment]
As this appears to be a configuration issue, rather than one with the code (honestly - if the admin interface didn't load on android phones we'd have heard by now!), Can I please ask that you open a thread on our forums, the wider community may have a better idea of what is going on?

Thanks for your understanding

Forums: https://discourse.pi-hole.net
