### ISSUE TITLE
Removing IPV*_ADDRESS from setupVars.conf

### ISSUE THREAD

**Issue by Anuskuss** [pi-hole/web#1784]
### Versions
- **Pi-hole:** v5.3.1
- **AdminLTE:** v5.5
- **FTL:** v5.8

### Platform
- **OS and version:** Raspbian GNU/Linux 10 (buster)
- **Platform:** Raspbian GNU/Linux

### Expected behavior
As per https://github.com/pi-hole/FTL/pull/965, I've removed `IPV4_ADDRESS` and `IPV6_ADDRESS` from `setupVars.conf` (previously I had a script which would update those) but it looks like the web interface still needs them.

### Actual behavior / bug
[Network Information](http://pi.hole/admin/settings.php) | |
--- | ---
**Pi-hole Ethernet Interface:** | eth0
**Pi-hole IPv4 address:** | unknown
**Pi-hole IPv6 address:** | unknown
**Pi-hole hostname:** | pihole

### Additional context
This is just a reminder; it's not important at all.

**Comment by yubiuser** [comment]
This has been resolved with
https://github.com/pi-hole/AdminLTE/commit/cf917a6391a6a309be9dfdf87f0bde7c66d698b4

**Comment by Anuskuss** [comment]
Yeah, I removed my script when v5.6 dropped and totally forgot that I had opened this. Thanks for closing!
