### ISSUE TITLE
Can't login (properly) on a fresh install

### ISSUE THREAD

**Issue by florian-str** [pi-hole/web#1806]
### Versions
- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
- OS and version:  Oracle Linux 8.3 (CentOS 8.3)
- Platform:  Raspberry Pi
- Web server:  nginx
- PHP: 7.4

### Expected behavior

After logging in it should display the status or main page.

### Actual behavior / bug

After logging in it redirects to the login page.
It is validating the password (it detects a wrong one).
If you go to [http://ip/admin/settings.php](http://ip/admin/settings.php), it wants you to login, but this time it redirects to the correct page.

### Steps to reproduce

1. Install Pi-hole
2. Visit the Pi-hole admin
3. Try to log in
## Debug Token

- URL:  https://tricorder.pi-hole.net/8qcrgk2dx0

**Comment by yubiuser** [comment]
`nginx` is not a supported webserver.

Please use https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36 for community help.

**Comment by florian-str** [comment]
I'm sorry, I should've checked. I was able to run Pi-hole with nginx on a different machine, though. It turns out that it is a duplicate of #1615.
