### ISSUE TITLE
Deleting single local DNS record removes all local DNS records with same IP-address

### ISSUE THREAD

**Issue by FibreFoX** [pi-hole/web#1811]
### Versions
- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
- OS and version:  Using Docker-Image (pihole/pihole:latest)
- Platform:  Docker (on Raspberry Pi 32bit)

### Expected behavior

When clicking the delete-icon of the Action-column of a single entry, only that entry gets removed.

### Actual behavior / bug

When clicking the delete-icon of the Action-column of a single entry, all entries with the same IP-address get removed.

### Steps to reproduce

1. Go to 'Local DNS > DNS Records'
2. Enter some domain/IP-combination in "Add a new domain/IP combination"
3. Then click 'Add'
4. Then enter the same IP but for a different domain
5. Then click 'Add'
6. Then refresh the page (to avoid any javascript caching issue)
7. Try to delete only one of them

### Additional context

I'm a software developer, that tinkers in my local network with some virtual machines and multiple docker-containers on the same machine, therefor I need to be able to adjust my local DNS records pointing to the same IP more often. Probably just a minor edge-case.

**Comment by FibreFoX** [comment]
First of all: sorry for posting the issue on the wrong project ;) thanks @PromoFaux for the transfer

Thats pretty strange, that this uses REGEXP anyway, as the format is pretty know. Is it possible to use some kind of array-index or something?

**Comment by DL6ER** [comment]
Regex matching isn't used here, matching can just happen anywhere on the line. I agree that ~~switching to regex (`sed -e`) and~~ adding anchors should fix it.

*edit* Anchors should be supported even without adding `-e`

**Comment by DL6ER** [comment]
Bug fix in progress here: https://github.com/pi-hole/pi-hole/pull/4178

**Comment by yubiuser** [comment]
Fixed:
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544/1
