### ISSUE TITLE
Red LOAD icon on LXC install

### ISSUE THREAD

**Issue by ghost** [pi-hole/web#1818]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Ubuntu 20.04
- Platform: LXC with 2cores, 2GB RAM on a 24core intel server.

Hi there, first things first. Pi-hole is just an amazing and perfect working solution for all i've ever looked for. Thanks for it.

But installed in an LXC it showes the cpu load from the core server. On my machine it's currently 2.5,2.7,2.6 what's totaly normal for it but pi-hole shows a red light because it compares the values with the raspberry values.

Is there an option or may I edit a file where i can adjust the upper limits before it showes a red LOAD?

Best regards
Michael

P.S.: I realy looked for similar issue but did'nt found one so iv'e created this one.

**Comment by ghost** [comment]
nproc --> 2

Yep the light goes red above 2.0
So a dirty solution is to set the nproc variable = 5 right?

**Comment by dschaper** [comment]
Loads higher than the number of processors indicates a load higher than 100%.

Your dirty solution is just putting a piece of tape over the indicator. If you don't really care what the system load is then I'd just ignore it. Making manual changes to any of the files will break the update process and cause you more headache than it's worth.

**Comment by DL6ER** [comment]
> LXC with 2cores, 2GB RAM on a 24core intel server

> But installed in an LXC it showes the cpu load from the core server.

It certainly looks like an `lxc` issues (not wanting to say "bug" here). If it shows only a subset of cores, it should also only show a vm-local load.

May I ask a question from another angle: Why do you limit the numbers of core at all in the LXC container? If `nproc` would be correct, this problem would not exist. Otherwise, with `lxc` behaving as it does, I don't think there is much we could do about it.

**Comment by ghost** [comment]
I just need one core for this container with squid, squidguard and privoxy running on. So i decided when adding pi-hole with all its services I just give them one core more. In a VM the problem not exists because it counts only the load from the VM itself. The lxc issue is that the host just push the load values through the lxc's. So every container shows up the hosts load. 
I have reversed my dirty solution btw ^^

**Comment by DL6ER** [comment]
Yes, but that's not my point: Why limit the number of cores at all in the lxc environment?

**Comment by ghost** [comment]
I'm quiet new on containering systems so my thoughts are even vm like. I think when i give a VM 2 cores and move the VM System to a lxc i asign just the same amount of cores.
