### ISSUE TITLE
No way to bypass CORS

### ISSUE THREAD

**Issue by adyanth** [pi-hole/web#1820]
### Versions

- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A

### Platform

- OS and version:  ALL

- Platform:  ALL

### Expected behavior

_A clear and concise description of what you expected to happen._
There should be a way to enable CORS for specified domains to be able to use the API.

### Actual behavior / bug

_A clear and concise description of what the bug is._
No way to bypass CORS other than manually editing files which are lost on upgrade.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by adyanth** [comment]
Refer pi-hole/docker-pi-hole#864

**Comment by adyanth** [comment]
PR: https://github.com/pi-hole/AdminLTE/pull/1822

**Comment by yubiuser** [comment]
Fixed:
https://discourse.pi-hole.net/t/hotfix-pi-hole-web-v5-5-1-released/48708/1
