### ISSUE TITLE
Bar graphs on main admin page state 72 hours but each shows only 24 

### ISSUE THREAD

**Issue by jgrisham** [pi-hole/web#1825]
### Versions

- Pi-hole:  v5.3.1 (Latest: v5.3.1)
- AdminLTE:  v5.5 (Latest: v5.5)
- FTL:  v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version: Raspbian GNU/Linux 10 (buster) _[Debian variant]_
> Linux pihole-mark0mod0 5.10.17-v7l+ 1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
- Platform:  Raspberry Pi

### Expected behavior

At http://pi.hole/admin/index.php, there are two headings:

> Total queries over last **72 hours**
> Client activity over last **72 hours**

Each has a graph below it, but the graphs are labeled to **only show 24 hours of data**.

1. The _heading_ of the graph should match the _content_ of that graph

### Actual behavior / bug

1. Only 24 hours of data appear to be shown, while the heading promises 72

Either:

- the graphs should be changed to match the heading, or
- the headings (or other text) should be updated to clarify what is being shown
  - e.g., depending on what data is actually intended to be presented to the viewer:
    - "Total queries over last 24 hours"
    - "Queries for each 10-minute period during the past 24 hours"
    - "Total queries over last 24 hours (for each 10-minute period)"
    - "Total queries per time period"
    - "Total queries over last 72 hours (aggregated for each time period in a single day)"
    - "Average queries over last 72 hours (averaged over each time period)"

### Steps to reproduce

1. View the page at http://pi.hole/admin/index.php

## Debug Token

- URL:  https://tricorder.pi-hole.net/ugcs0vb9au

### Screenshots

![image](https://user-images.githubusercontent.com/1781752/121698150-bc21b780-ca9b-11eb-8cc7-17e0f3e875e0.png)

### Additional context

After I started this, I thought, "perhaps the graph is _actually_ showing either the average or total number requests *of each time period* but across three days". 

This _does not seem to be the case,_ however, since when viewing the query log by clicking on a time period bar, only the queries from the most recent occurrence of that time period are shown.

**Comment by PromoFaux** [comment]
Please submit a debug token by running `pihole -d` on the command line and choosing `y` to upload, and then paste the token in here.

Thanks!

**Comment by jgrisham** [comment]
@PromoFaux Here you go: https://tricorder.pi-hole.net/ugcs0vb9au

The only place where "`72`" appeared by itself in the `pihole -d` console output was:

> /etc/pihole/pihole-FTL.conf

...
>    ;# Max Log Age
>    ;# Up to how many hours of queries should be imported from the database and logs [hours]?
>    ;# Maximum is 744 (31 days)
>    ;# Options: number of days
>    ;MAXLOGAGE=24.0
>    MAXLOGAGE=72.0

**Comment by PromoFaux** [comment]
Ah, so you have overridden the default 24hrs in ftl config (you mentioned this was a fresh install - therefore I assumed stock)

Per documentation:

https://docs.pi-hole.net/ftldns/configfile/#maxlogage

```
Up to how many hours of queries should be imported from the database and logs? Maximum is 24.0
```

Explanation why 24hrs is max here:

https://discourse.pi-hole.net/t/pihole-ignores-maxlogage-parameter-in-pihole-ftl-conf/18193/5?u=promofaux

**Comment by PromoFaux** [comment]
@jgrisham - your custom config file (with all the comments and defaults) is out of date which is likely why it's not providing expected results. I vaguely recall you submitting and issue/PR around comments in the config file before.

**Comment by jgrisham** [comment]
Ah, the perils of text-based configuration files. ;)

One of my sources of configuration templates must have indeed been from an earlier version. _(I find commented log files especially useful when using full-screen text-only terminals, since I’m old and have a poor memory.)_

 - - - - -

So, this issue might be re-phrased as:

- If the running build of `pihole-FTL` _(4.2.3 or later)_ wasn’t compiled with the appropriate options *(as @DL6ER mentioned in the [second link](https://discourse.pi-hole.net/t/pihole-ignores-maxlogage-parameter-in-pihole-ftl-conf/18193/5) from your above [reply](https://github.com/pi-hole/AdminLTE/issues/1825#issuecomment-861234706))*, then any `MAXLOGAGE` value above the limit _(currently `24.0` hours)_ should be ignored when parsing the configuration file; further, any out-of-range value should not passed to other components _(such as AdminLTE)_ or retained for any other purpose _(except perhaps for logging that a configuration value was ignored)_.

 - - - - -

Thank you for all of your work on this project!

\- Jim

*(P.S. Apologies if I gave the impression that I was using a fresh install; that was not my intent.)*

**Comment by PromoFaux** [comment]
@jgrisham is this still an issue in newer versions? Please close if not

**Comment by jgrisham** [comment]
@PromoFaux I haven’t upgraded to a newer version yet, and likely won’t until recovering from offline covid-related backlogs.

(I guess it should be simple to test in a VM … perhaps I can find the time to do that sometime this month.)

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
