### ISSUE TITLE
pihole web interface not displaying properly

### ISSUE THREAD

**Issue by mash8336** [pi-hole/web#1826]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be _replicated_.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---

**Expected behavior:**

pihole web interface display normally

**Actual behavior:**

pihole web interface is functional but displayed format is a mess

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

https://tricorder.pi-hole.net/upky3o714m

`{Alphanumeric token}`

Rebooted server, already at latest version or would upgrade

`{Steps of what you have done to fix this}`

Just reboot really
![pihole](https://user-images.githubusercontent.com/44288297/121744138-5a446a80-cafa-11eb-86f4-312e8d3c7f27.png)

**Comment by cakgok** [comment]
I have the same issue. I'm using nginx as a webserver. It all works fine with lighttpd but I don't want to run 2 webservers for no good reason.

https://tricorder.pi-hole.net/8ix1oobk5j

**Comment by yubiuser** [comment]
@somewherebutnothere
nginx is not a supported browser. You might find some hint in the community guide here 
https://docs.pi-hole.net/guides/webserver/nginx/

**Comment by mash8336** [comment]
My attention turned back to this and I spotted the repair option in the cli options.

Ran that and it's back to normal
