### ISSUE TITLE
Not possible to modify hardcoded AUTHORIZED_HOSTNAMES in /php/auth.php

### ISSUE THREAD

**Issue by mgrybyk** [pi-hole/web#1831]
### Versions

  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Ubuntu 20.04.2 LTS

- Platform:  VPS

### Expected behavior
- it should be possible to configure AUTHORIZED_HOSTNAMES array
- it should be possible to remove the hardcoded values, ex `pi.hole`

it might be good idea to just add `AUTHORIZED_HOSTNAMES` that accepts comma separated hostnames list to `/etc/pihole/setupVars.conf` with the default value set to `pi.hole`

`/php/auth.php`
```
    $AUTHORIZED_HOSTNAMES = array_merge(array(
        $ipv4,
        $ipv6,
        str_replace(array("[","]"), array("",""), $_SERVER["SERVER_NAME"]),
        "localhost"),
        array_map('trim', explode(",", $setupVars["AUTHORIZED_HOSTNAMES"]))
    );
```
### Actual behavior / bug

there is a hardcoded not configurable list in `/php/auth.php`
```
    $AUTHORIZED_HOSTNAMES = array(
        $ipv4,
        $ipv6,
        str_replace(array("[","]"), array("",""), $_SERVER["SERVER_NAME"]),
        "pi.hole",
        "localhost"
    );
```

### Additional context

it prevents some functionality of web admin (like blacklist and whitelist pages) to work properly if pihole is hosted on multiple hostnames protected with reverse proxy.

ex: 
https://my.host1.com -> load balancer -> lighttpd on http://localhost
https://my.host2.com -> load balancer -> lighttpd on http://localhost

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
