### ISSUE TITLE
Pihole need after 24h a restart

### ISSUE THREAD

**Issue by Wipperland** [pi-hole/web#1840]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  openHABian v3.0.2

- Platform:  Raspberry Pi 4

Hello,

every day I have to restart the DNS resolver. Every Day at the same time I can not use the internet because the DNS-Request didn't get solved. A restart of the Raspberry Pi 4 didn't helped. After a restart the service of Pihole didn't start and I have to start the DNS Resolver manually.

- Token URL:  https://tricorder.pi-hole.net/sqhqfsfoo7

**Comment by yubiuser** [comment]
I can't spot any obvious errors in your debug log.

If it is the same time every day, it sounds like a cron job or anything else that is executed on a daily base.
