### ISSUE TITLE
Conditional forwarding does not accept IPv6 addresses

### ISSUE THREAD

**Issue by domrim** [pi-hole/web#1841]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Raspbian 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

Conditional Forwarding with IPv6-Adresses is configurable.

### Actual behavior / bug

IPv6 Configuration is not accepted with following error:
```
Conditional forwarding subnet ("fd00::/64") is invalid!
This field requires CIDR notation for local subnets (e.g., 192.168.0.0/16).
Please use only subnets /8, /16, /24, and /32.
The settings have been reset to their previous values 
```

### Steps to reproduce

In the Admin-Panel under 'Settings' -> 'DNS' when i enter my local network IPv6 configuration for local forwarding, e.g.:
- Local network in CIDR notation: `fd00::/64`
- IP address of your DHCP server (router): `fd00::abcd:1234:5678:4321` (replaced my actual address with pseudo-address)
- Local domain name (optional): `fritz.box`

## Debug Token

- URL:  https://tricorder.pi-hole.net/3qog5rf2fb

**Comment by DL6ER** [comment]
Yes, `rev-server` can take IPv6 addresses, the CIDR needs to be a multiple of 4.

The test is just generating an incomplete warning:
https://github.com/pi-hole/AdminLTE/blob/7e602e0df4c28e093afeedee27a205209f1f5104/scripts/pi-hole/php/savesettings.php#L357-L362

as the test also checks IPv6
https://github.com/pi-hole/AdminLTE/blob/7e602e0df4c28e093afeedee27a205209f1f5104/scripts/pi-hole/php/savesettings.php#L22-L44

Other input such as `fd00::0/64` should match. See https://regexr.com/6166p

I'm not sure we should change this now, do you think so?. Pi-hole v6.0 will move the entire input parsing into the API where we can take care of this with just two lines of C code and no need for any complex regular expressions at all.

(fixed regex would look like this (assuming I did not introduce a new hidden bug now)):
```
^((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:))))\/(4|8|12|16|20|24|28|32|36|40|44|48|52|56|60|64|68|72|76|80|84|88|92|96|100|104|108|112|116|120|124|128)$
```

**Comment by yubiuser** [comment]
This should be fixed by https://github.com/pi-hole/AdminLTE/pull/1897
