### ISSUE TITLE
Broken "Group management" view in Safari 14.1.1

### ISSUE THREAD

**Issue by ghost** [pi-hole/web#1849]
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8.1 (Latest: v5.8.1)
### Platform
4.18.0-315.el8.x86_64 pi-hole/pi-hole#1 SMP Mon Jun 28 19:09:44 UTC 2021 x86_64 GNU/Linux PRETTY_NAME="CentOS Stream 8"
### Actual behavior / bug
Big green block instead list of goups list - details in scr.
<img width="1680" alt="Screenshot 2021-07-23 at 22 15 36" src="https://user-images.githubusercontent.com/40626626/126831587-99af3abf-40c9-43a2-987d-160736ef4495.png">

**Comment by dschaper** [comment]
@jfb-pihole Do you see the same?

@ViktorasPe Can you please provide the debug token as requested in the template?

**Comment by ghost** [comment]
https://tricorder.pi-hole.net/pdbtplplnq

**Comment by jfb-pihole** [comment]
I see the same thing on that same version of Safari (and on 14.1.2), but not on an older version (12.1.2).  Using 14.1.x Safari, I also see this using the beta and dev versions of Pi-hole.

What is the web inspector showing for that element?  Right click the green box and select **Inspect Element.**

**Comment by yubiuser** [comment]
Fixed with 

https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
