### ISSUE TITLE
Allow comma-separated VIRTUAL_HOST names

### ISSUE THREAD

**Issue by jetvillegas** [pi-hole/web#1853]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Ubunto 20.04 LTS
- Platform:  Docker

### Expected behavior

Allow VIRTUAL_HOST names as comma-separated fully-qualified domain names. E.g.:
dns.example.org, dns.example.com

### Actual behavior / bug

CORS checks fail when using multiple VIRTUAL_HOST names:
Failed CORS: dns.example.org vs 0.0.0.0, 0:0:0:0:0:0, 192.168.1.1, pi.hole, localhost, dns.example.org, dns.example.com

### Steps to reproduce
1. Set an environment variable:
VIRTUAL_HOST = dns.example.org, dns.example.com
2. Browse to a page that requires CORS check. E.g.:
https://dns.example.org/pi-hole/dns_records.php
3. See CORS error

### Additional context

Using nginx as a reverse-proxy with https to multiple domain names.

**Comment by PromoFaux** [comment]
Coming soon™ to a new release near you:

https://github.com/pi-hole/AdminLTE/pull/1822

(Soon™ is about as close as I can give you 😉)

**Comment by jetvillegas** [comment]
Thanks! CORS_HOSTS will do the trick quite nicely. Thanks @PromoFaux & @adyanth

**Comment by yubiuser** [comment]
Fixed:
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544/1
