### ISSUE TITLE
Unable to whitelist/blacklist traffic in realtime

### ISSUE THREAD

**Issue by yanniedog** [pi-hole/web#1866]
### Versions

  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

Because Query-Log does not automatically refresh, there is no way to add traffic to a whitelist or blacklist at the 'instant' they occur. Furthermore, when users refresh Query log, all previous filters they set up in Query Log become reset. If you network has dozens of devices, it then becomes very difficult to identify a specific request sent by a specific device. It takes up to 10 seconds to refresh the web interface and re-type the Query Log filter....in this time, hundreds of new queries can be added to the query log, which can be extremely difficult. There is no way to immediately response to a realtime query.

Please allow the Query Log to update in realtime

Please retain the Query Log "filters" when the user refreshes the web interface

Thank you

**Comment by yubiuser** [comment]
> If you network has dozens of devices, it then becomes very difficult to identify a specific request sent by a specific device. 

If you have a lot of devices with a lot of queries, it will be hard to identify a specific query in a fast rushing query log also.

What you propose, are feature requests. Please use https://discourse.pi-hole.net/ for that. 

E.g. https://discourse.pi-hole.net/t/add-refresh-and-or-live-option-to-query-log/20262

**Comment by DL6ER** [comment]
Furthermore, filtering via the URL works across reloads, e.g.

http://pi.hole/admin/queries.php?client=192.168.1.123&type=blocked
