### ISSUE TITLE
pi.hole/admin/queries.php has lost the coloring of the lines

### ISSUE THREAD

**Issue by stefanostatuti** [pi-hole/web#1890]
### Versions
Pi-hole version is v5.4 (Latest: v5.4)
AdminLTE version is v5.6 (Latest: v5.6)
FTL version is v5.9 (Latest: v5.9)

### Platform
OS and version: Raspberry Pi OS
Release date: May 7th 2021
Kernel version: 5.10

### Expected behavior

the interface should show all the row coloured and not only the result of filtering

### Actual behavior / bug

after the update to v5.6 the interface shows only the result of the filtering (example: ok, Retried ...) coulored.

### Steps to reproduce

1. Go to 'http://pi.hole/admin/queries.php'

## Debug Token

- URL:   https://tricorder.pi-hole.net/oBwOtJk5/

### Screenshots
OLD;
![immagine](https://user-images.githubusercontent.com/4499372/133205497-913deb8d-5748-4fb3-8ff6-d491507f6979.png)
NEW:
![immagine](https://user-images.githubusercontent.com/4499372/133205742-bc096c11-ebd0-4494-ba7e-164fe8481d24.png)

### Additional context
i tried to clean cache or login from another device and thin not solve the problem.
There is a option to come back to old view?

**Comment by yubiuser** [comment]
That's by design: https://github.com/pi-hole/AdminLTE/pull/1872

Current PR to allow the old design https://github.com/pi-hole/AdminLTE/pull/1888
