### ISSUE TITLE
Many Clients causes Dashboard to hangs itsself

### ISSUE THREAD

**Issue by Pingger** [pi-hole/web#1896]
### Versions

- Pi-hole:  5.4 (and 5.3.1)
- AdminLTE:  f5292a3f
- FTL:  5.9 (and 5.8.1)

### Platform

- OS and version:  Debian 11

- Platform:  VPS (4 Core, 16GB)

### Expected behavior

The Dashboard loads properly and doesn't hang the Browser-Tab

### Actual behavior / bug

The Dashboard only loads and Displays "Total queries over last 24 hours", but then hangs.

### Steps to reproduce

1. Have >600 Clients (the `/api.php?overTimeDataClients=&getClientNames=`-Response is ~230KB)
2. Try to open Dashboard while logged in.

## Debug Token

- URL:  https://tricorder.pi-hole.net/ej6yu8yU/

### Screenshots

![image](https://user-images.githubusercontent.com/4761298/133942460-daa7f545-9d07-4d16-932e-032e117d59e2.png)
![image](https://user-images.githubusercontent.com/4761298/133942484-db8f0408-d15a-4552-a89c-700254665832.png)

### Additional context

specifically the 'Client activity over last 24 hours'-Table causes the issue

**Comment by dschaper** [comment]
You're running an open resolver. 

As general policy we do not provide any support for open resolvers.

**Comment by Pingger** [comment]
I see ... Still doesn't change, that issue with the WebUI exists.
