### ISSUE TITLE
long term data query log data always shows red color , web interface version 5.7

### ISSUE THREAD

**Issue by Sassafras76** [pi-hole/web#1905]
Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is release v5.10.1 (Latest: v5.10.1)

Raspberry OS = 5.10.60-v8+
Raspberry PI

the long term data should not have been affected by the colorful query log, I now see all rows as background color red with just OK in green

1. Go to http://pi.hole/admin/db_queries.php 
2. Click on data, select "today"

see the screen

![image](https://user-images.githubusercontent.com/89309860/135360803-f1009bce-011f-4393-b593-e9e130f75e42.png)

**Comment by yubiuser** [comment]
The fix has been released
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-11-web-v5-8-and-core-v5-6-released/50566
