### ISSUE TITLE
Load indicators are stuck at 0

### ISSUE THREAD

**Issue by zigapovhe** [pi-hole/web#1918]
### Versions

Pi-hole version is v5.5 (Latest: v5.5)                                                                                  
AdminLTE version is v5.7 (Latest: v5.7)                                                                                 
FTL version is v5.10.2 (Latest: v5.10.2) 

### Platform

- OS and version:  Rasbian 10 buster

- Platform:  Raspberry Pi

### Expected behavior
On previous versions, the load indicators worked as expected. 

### Actual behavior / bug

Since I've updated Web interface to the current latest version (v5.7) the load indicators are always stuck at 0.

### Steps to reproduce
Should be reproducable at normal usage. 
## Debug Token

- URL:  https://tricorder.pi-hole.net/Abf9SpUf/

### Screenshots
[
Screenshoot](https://i.imgur.com/MkRsgd6.png)

**Comment by dschaper** [comment]
What does the command `uptime` show for load average?

**Comment by zigapovhe** [comment]
> 
> 
> What does the command `uptime` show for load average?

` 08:50:57 up 4 days, 21:59,  1 user,  load average: 0.00, 0.02, 0.04   `

**Comment by dschaper** [comment]
The web interface is correct.

**Comment by zigapovhe** [comment]
> 
> 
> The web interface is correct.

Does web interface round numbers to 1 decimal? or just shows full integers?

I'm using pihole for about a year and half now, always similar stats, similar network traffic patterns and I've never seen load numbers that low before. I guess the optimizations are working too well. Good job! :D

**Comment by DL6ER** [comment]
Thanks. They are rounded to two decimals

https://github.com/pi-hole/AdminLTE/blob/50f43bde73d25211ac2c81e9092be67512611d2a/scripts/pi-hole/php/header.php#L71-L75

so I'd expect `0.02` to show up as number...

**Comment by zigapovhe** [comment]
Thank you. The issue is resolved.
