### ISSUE TITLE
Teleporter restore concatenates custom.list instead of replacing despite checking "clear data"

### ISSUE THREAD

**Issue by MaleNurse** [pi-hole/web#1926]
### Versions
- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform
- OS and version:  Ubuntu 20.10
- Platform:  RaspberryPi3B+ (arm64) and HP Desktop (amd64)

### Expected behavior

When performing a restore using Teleporter, the custom.list file/custom DNS entries, would be replaced by the backed up copy.

### Actual behavior / bug

The custom DNS entries from the backup are appended to the end of the current list. If there were matching entries, there are now duplicates.

### Steps to reproduce

Backup using Teleporter
Restore using Teleporter
Inspect Custom DNS entries and or /etc/pihole/custom.list

## Debug Token

- URL:  https://tricorder.pi-hole.net/kzc74vmeyr

**Comment by yubiuser** [comment]
Should be fixed with the lastest release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-11-web-v5-8-and-core-v5-6-released/50566/1
