### ISSUE TITLE
"Last 7 days" view is 1 day too short (also for "30 days view")

### ISSUE THREAD

**Issue by w0ng0** [pi-hole/web#1937]
### Versions

- Pi-hole:  Pi-hole version is v5.6 (Latest: v5.6)
- AdminLTE:  AdminLTE version is v5.8 (Latest: v5.8)
- FTL:  FTL version is v5.11 (Latest: v5.11)

### Platform

- OS and version:  Debian Stretch

- Platform:  Raspberry Pi model 2

### Expected behavior

When i select "last 7 days" i expect a graph spanning the last (7 x 24 = ) 168 hours, up to current time. 
Also for the "last 30 days" view , i expect a graph spanning the last (30 x 24 = ) 720 hours, ending at the current time.

### Actual behavior / bug

The resulting graphs are "1 day short". the selected time period starts 1 day too late, therefore only spanning 6 or 29 days.
For example: "October 19th 2021, 11:12 to October 25th 2021, 11:12", is only 144 hours long, The start date/time should be "October 18th 2021, 11:12".

### Steps to reproduce

1. Log on to Pi-hole
2. Click on 'Long-term data' 
3. Select 'Graphics'
4. In 'Select date and time range'
5. Click on 'Click to select date and time range'
6. Select 'Last 7 days'
7. Wait and examine the graph 'Queries over the selected time period'

## Debug Token

- URL:  https://tricorder.pi-hole.net/cYvplIw2/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

![pihole bug](https://user-images.githubusercontent.com/93125986/138683598-2921d836-6876-42dc-bbcb-6cd1928c9dd8.PNG)

**Comment by yubiuser** [comment]
I wonder why this was undiscovered for 4 years...

@w0ng0 

Please try if `pihole checkout web fix_date_range` fixes the issue for you. You can go back to master anytime by `pihole checkout web master`

**Comment by w0ng0** [comment]
Hello Yubiuser,

it does fix the issue. I discovered the issue quite some time ago, but i didn't take the effort to report it right away. 
I thought it couldn't be a big difficult bug, or really important. But now i have. Probably my aspergers has something to do with seeing the issue at all.

Thanx for your support, i use pihole in my home network and like it very much.

**Comment by w0ng0** [comment]
Again, thanx
