### ISSUE TITLE
Code litter or forgotten setting?

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#1941]
Once there was a privacy mode checkbox in Settings/API
https://github.com/pi-hole/AdminLTE/pull/258

It was removed by https://github.com/pi-hole/AdminLTE/pull/694/files, but part of the API settings were later restored, because they were accidentally removed.
https://github.com/pi-hole/AdminLTE/commit/7fde2f88d75c58ed1c502b36eebf49c0a357abb3

So: should the Privacy checkbox be re-introduced (does it have a effect at all after the switch to FTL?) or should the referencing code be remove?

https://github.com/pi-hole/AdminLTE/blob/ee50954be76fa53bdc4d95a3dd197030b96af5ab/settings.php#L188-L192

And 

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/advanced/Scripts/webpage.sh#L535

**Comment by DL6ER** [comment]
FTL currently reads the following keys from `setupVars.conf`:
```
~/FTL$ grep read_setupVarsconf\(\" src/* -R
src/api/api.c:  const char* filter = read_setupVarsconf("API_QUERY_LOG_SHOW");
src/api/api.c:          excludedomains = read_setupVarsconf("API_EXCLUDE_DOMAINS");
src/api/api.c:  const char* excludeclients = read_setupVarsconf("API_EXCLUDE_CLIENTS");
src/api/api.c:  char * filter = read_setupVarsconf("API_QUERY_LOG_SHOW");
src/api/api.c:  char * excludeclients = read_setupVarsconf("API_EXCLUDE_CLIENTS");
src/api/api.c:  char * excludeclients = read_setupVarsconf("API_EXCLUDE_CLIENTS");
src/setupVars.c:        char * iface = read_setupVarsconf("API_EXCLUDE_DOMAINS");
src/setupVars.c:        const char* blocking = read_setupVarsconf("BLOCKING_ENABLED");
```

`API_PRIVACY_MODE` is not among this so we can remove the obsolete code.
