### ISSUE TITLE
Error when saving settings on DNS card

### ISSUE THREAD

**Issue by ashr123** [pi-hole/web#1942]
### Versions

- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform

- OS and version:  Ubuntu Mate 21.10

- Platform:  Raspberry Pi 4B

### Expected behavior

I expect to see only the message that says that the settings were saved successfully without the error message

### Actual behavior / bug

> PHP error (2): Undefined array key "v6_2" in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:212

In addition to message that said that the settings were saved successfully

### Steps to reproduce

1. Go to `Settings`
2. Click on `DNS`
3. Click `Save`

## Debug Token

- URL:  [https://tricorder.pi-hole.net/8HkAmvWA/](https://tricorder.pi-hole.net/8HkAmvWA/)

### Screenshots

![image](https://user-images.githubusercontent.com/26481657/138930267-4966df1e-1713-4a9e-9e3f-9d3acbd79083.png)

**Comment by yubiuser** [comment]
Thanks for the report.
Duplicate of
https://github.com/pi-hole/AdminLTE/issues/1754
