### ISSUE TITLE
Dashboard pie chart for upstream server distribution shows wrong value

### ISSUE THREAD

**Issue by r2ixuz** [pi-hole/web#1947]
I am using two upstream DNS servers and the dnsmasq parameter "all-servers" for querying both server to get everytime the fastest answer.

With this setting, the upstream server distribution pie chart on the dashboard shows after 24h usage the exact same percentual usage for each of these two upstreams. This is actually not true, because one of them is way more ofter the first one to reply. I would guess it should be 6,8%/70% distribution not 38,4%/38,4% (rest of distribution goes to blocklist, cache, etc.).

Is this a bug or not possible to render correctly if one is using the "all-servers" setting?

**Comment by yubiuser** [comment]
It is correct. It shows where the query was sent to, not from where the reply came.

https://github.com/pi-hole/AdminLTE/commit/df9bf15e758c5caac9e339f58e4d59a8cb989b4d

**Comment by r2ixuz** [comment]
Oh I see. Seems to be that I did not properly recognized the wording change.

Still would be nice to see which one answered in that pie chart. But whatever, thanks for your work on this really good project! :-)
