### ISSUE TITLE
iOS icon has black background and no padding

### ISSUE THREAD

**Issue by jamieburchell** [pi-hole/web#1958]
### Versions

Pi-hole version is v5.6 (Latest: v5.6)
AdminLTE version is v5.8 (Latest: v5.8)
FTL version is v5.11 (Latest: v5.11)

### Platform

- OS and version:  Rasbian Buster

- Platform:  Pi

### Expected behavior

White background for iOS Home Screen icon with some padding around graphic

### Actual behavior / bug

Black logo background, graphic goes to the edges

### Steps to reproduce

Add to home screen from Safari

### Screenshots

![8BABCB6F-C185-413E-B63B-8368B8F7EC01](https://user-images.githubusercontent.com/3270426/140590789-76f43d46-eedd-422e-9ca6-a8239cafa0af.jpeg)

### Additional context

Would you be open to a PR with a revised set of favicons generated from your SVG using https://realfavicongenerator.net ?

**Comment by jamieburchell** [comment]
Maybe one for @XhmikosR looking at past issues. In realfavicongenerator there's the option to set a background and add padding for the Apple icon

**Comment by rdwebdesign** [comment]
The only way I know to do this is to use an image with solid background (`apple-touch-icon.png` with white background, for example). 
Transparent PNG background will turn into black.

**Comment by jamieburchell** [comment]
If you go to realfavicongenerator.net and upload the SVG icon, it will do all of this for you in an easy to use graphical interface. You can fine-tune how you want all of the icons to look and it shows you what it will look like in the various browsers/home screens/pinned tabs/Windows.

At the end of the process you can download a zip of the assets and you're provided with the code to insert in the HTML (links, manifest, theme colours etc)

**Comment by yubiuser** [comment]
Do you really think this looks better?

![IMG_0588](https://user-images.githubusercontent.com/26622301/140607107-6b016f0d-e33d-4c83-918c-e7bb8ed04ab4.PNG)

I think for this purpose we would need to design a new special icon

**Comment by jamieburchell** [comment]
I think it looks better, but of course that's subjective. At the very least I feel it needs some padding. It looks odd compared with other icons.

![298362E0-D7B5-49AE-BA7A-72D4D3558920](https://user-images.githubusercontent.com/3270426/140608363-42274867-3391-4279-947b-b785aea471fc.jpeg)

Could keep the black background or create a custom icon.

**Comment by jamieburchell** [comment]
I think it looks better, but of course that's subjective. At the very least I feel it needs some padding. It looks odd compared with other icons.

![4C0827D6-CD19-4DE5-A72D-128D17E0E26C](https://user-images.githubusercontent.com/3270426/140608504-e208bf26-273b-4b54-b9b1-dea30bc4aeb5.jpeg)

Could keep the black background or create a custom icon.

**Comment by yubiuser** [comment]
> Could keep the black background or create a custom icon.

We would be happy if you could create a modified icon with more padding :-)

**Comment by jamieburchell** [comment]
I'm no designer but I think you can select black as the background and add the padding in realfavicongenerator

**Comment by yubiuser** [comment]
![IMG_0589](https://user-images.githubusercontent.com/26622301/140621456-5d810ec7-6c5a-459d-a124-6b571d99f79b.PNG)

**Comment by jamieburchell** [comment]
LGTM
