### ISSUE TITLE
API reporting status: enabled while blocking is disabled

### ISSUE THREAD

**Issue by jojost1** [pi-hole/web#1965]
### Versions
- Pi-hole:  5.6
- AdminLTE:  5.11
- FTL:  5.8

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi Zero W

### Expected behavior

When disabling the Pi-hole (through the API) I would expect the API to return `"status": disabled`. The dashboard is showing the status correctly.

### Actual behavior / bug

When disabling the Pi-hole (through the API or through the web interface), the API is reporting `"status": enabled` while the dashboard is showing the status 'disabled' correctly.

### Steps to reproduce

1. Disable blocking
2. Look at the web interface and the response at http://[IP]/admin/api.php?summaryRaw

## Debug Token

- URL:  https://tricorder.pi-hole.net/Q1SX7zAi/

### Screenshots

<img width="663" alt="image" src="https://user-images.githubusercontent.com/8880568/141092084-bae2c8cd-b406-49d5-86d7-e7f80c6bb91f.png">

### Additional context

I notice this problem with users of my iOS app (Pi-hole Remote) and am now noticing it for the first time myself. It happens on my freshly installed Pi Zero W, but not on a freshly installed Pi 4.

**Comment by yubiuser** [comment]
For me it took a few `api.php` request before the new status was set correctly. Did you verify that the wrong status was included also after waiting a moments?

**Comment by jojost1** [comment]
Yes I did, after a minute it still reported the wrong status - while the web interface shows the correct status almost instantly.

**Comment by jojost1** [comment]
Still getting users who report this issue. The API is returning a different status state than the web interface. Anyone who could look into this?

**Comment by ucsbricks** [comment]
I am one of @jojost1 affected users. The issue started suddenly on both of my Pi-hole instances. Both systems are fully patched.

**Comment by jojost1** [comment]
Anyone who could look into this? Appreciate it!

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
