### ISSUE TITLE
Please add a "never-log" domains option

### ISSUE THREAD

**Issue by ckuethe** [pi-hole/web#1967]
Sorry for the bug, discourse isn't letting me add a new feature request.

### Versions

```
  Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)
```
### Platform

- OS and version: 
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Platform:  
NanoPi Neo

### Expected behavior

A way to exclude a few extra domains from ever being logged because I just don't care. I'm sure that just about everything on my network will, at some point, try talk to doubleclick. In fact, some badly behaved android apps will repeatedly spam the DNS with queries if they're rejected...

### Actual behavior / bug

Existing options to suppress domains from the dashboard summary don't suppress them from the query log

### Steps to reproduce

* add `doubleclick.net` to top domains exclusions
* make 10000 queries for `doubleclick.net` 
* observe that `doubleclick.net` is not shown in top advertisers
* observe that `doubleclick.net` is still visible in the query log

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
> Sorry for the bug, discourse isn't letting me add a new feature request.

No need to add a new one, there is already a FR
https://discourse.pi-hole.net/t/option-to-ignore-domains-from-appearing-in-the-query-log/6319
