### ISSUE TITLE
Group assignment shows &quot; HTML escaping when restoring from teleporter backup

### ISSUE THREAD

**Issue by jamieburchell** [pi-hole/web#2005]
### Versions
- Pi-hole version is v5.6 (Latest: v5.6)
- AdminLTE version is v5.8 (Latest: v5.8)
- FTL version is v5.11 (Latest: v5.11)

### Platform
- Raspbian GNU/Linux 11 (bullseye)
- Raspberry Pi

### Expected behavior

Group assignment drop down shows quotation marks instead of &quot ;

### Actual behavior / bug

I restored a teleporter backup which included a group name of "No blocking". When this was restored, the group assignment drop down showed &quot;No blocking&quot;.

After I resaved the group name as "No blocking", the drop down then showed this properly.

### Steps to reproduce

1. Create a group "No blocking"
2. Assign it to a client
3. Backup the configuration with teleporter
4. Restore the configuration
5. Look at the group assignment drop down for the client

## Debug Token

- URL:  https://tricorder.pi-hole.net/dDVdkaGA/

### Screenshots

![Capture](https://user-images.githubusercontent.com/3270426/146005850-4c405044-4165-452f-ac5f-b5835aaaa3ca.PNG)

### Additional context

N/A

**Comment by yubiuser** [comment]
Thanks for your report. This is bacially a duplicate of https://github.com/pi-hole/AdminLTE/issues/1928, even when it occurs at a different place. 
The whole XSS prevention and encoding/decoding needs a proper re-write.
