### ISSUE TITLE
IPv6 upstream DNS servers are not supported

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#203]
The address validation fails for IPv6 (only allows IPv4). Even using the preconfigured IPv6 upstreams does not pass the validation.

**Comment by Mcat12** [comment]
The backend also needs to support IPv6

**Comment by expressrussian** [comment]
Hello,
How to configure then pi-hole with dnscrypt-proxy?
Now 90% of blocked traffic goes via IPv6. 
Does this mean that pi-hole is not IPv6 compatible?
