### ISSUE TITLE
DHCP Lease want to set localhost as hostname to local network IP

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/web#2036]
### Versions
- Pi-hole:  5.6
- AdminLTE:  5.9
- FTL:  5.12.1

### Platform
- OS and version:  Raspberry OS 11
- Platform:  Raspberry Pi

### Expected behavior

A Button to remove all Pi-hole diagnosis at once.

### Actual behavior / bug

Not possible to clean up Pi-hole diagnosis at once in the Web Interface

**Comment by DL6ER** [comment]
Which warnings do you see? Isn't it better to fix their cause instead of just mass-ignoring them?

**Comment by pheiduck** [comment]
This one I get over 3400 of this warnings O.o:

Its from my Smart TV

```
not giving name localhost to the DHCP lease of <IP> because the name exists in /etc/hosts with address 127.0.0.1
not giving name localhost.lan to the DHCP lease of <IP> because the name exists in /etc/hosts with address 127.0.0.1
```

my /etc/hosts of the Pi-hole:
```
root:~/ # cat /etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

127.0.1.1		raspberrypi
```

**Comment by DL6ER** [comment]
This is a somewhat severe issue. Sometimes it is just a bug but most often this is actually intentional malicious. What kind of device is trying to get this hostname registered? Are you sure it is not compromised?

**Comment by pheiduck** [comment]
Its from my smart tv, will check for software updates.

**Comment by pheiduck** [comment]
I have noticed that the DHCP Lease for the IP hat localhost as hostname for whatever reason, I removed the entry and the Warning is no longer appears.

**Comment by pheiduck** [comment]
I have set a static dhcp lease for my TV so it never want to get localhost as hostname.
And I don't can update the TV OS.

**Comment by rdwebdesign** [comment]
What happens when the TV is not connected to the network?
Can you test this?

**Comment by pheiduck** [comment]
> What happens when the TV is not connected to the network?
> Can you test this?

I think that’s another good idea, I will try to gave a IP which is not in the DHCP Range [x]
