### ISSUE TITLE
CPU core count doesn't display anymore after v5.10 update

### ISSUE THREAD

**Issue by jojost1** [pi-hole/web#2047]
### Versions

- Pi-hole:  v5.8
- AdminLTE:  v5.10
- FTL:  v5.13

### Platform

- OS and version:  Raspberry Pi OS

- Platform:  Raspberry Pi 4

### Expected behavior

Number of cores (in my case: 4)

### Actual behavior / bug

Shows `$nproc cores`

### Screenshots

<img width="240" alt="image" src="https://user-images.githubusercontent.com/8880568/148291029-683c24a1-2cc1-455c-bc97-50329dde717f.png">

**Comment by rdwebdesign** [comment]
Confirmed.
I will look into it.

**Comment by jojost1** [comment]
Thanks for the quick fix!

**Comment by rdwebdesign** [comment]
> Thanks for the quick fix!

It was just a line of code and you reported the error exactly when I was working on pi-hole code.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
