### ISSUE TITLE
API: the 'summary' call now returns numbers instead of strings

### ISSUE THREAD

**Issue by jojost1** [pi-hole/web#2048]
### Versions

- Pi-hole:  v5.8
- AdminLTE:  v5.10
- FTL:  v5.13

### Platform

- OS and version:  Raspberry Pi OS

- Platform:  Raspberry Pi 4

### Expected behavior

Before, the `summary` API call returned data of type String for most values - whereas the `summaryRaw` call would return the raw numbers (Int/Double).

### Actual behavior / bug

Now, the `summary` call returns numbers, it seems identical to the `summaryRaw` API call.

### API Call

Replace IP with your IP, ofcourse.

http://192.168.1.68/admin/api.php?summary

http://192.168.1.68/admin/api.php?summaryRaw

### Additional Context

This makes life hard for my Pi-hole Remote companion app for iOS.

**Comment by DL6ER** [comment]
Why does it make your life hard? Because it changed without prior notice or because strings are really better than floats in your case?

**Comment by jojost1** [comment]
Good question, it's the first thing mostly. I expected `String` types and got something else which caused errors. Also I'm thinking this is not intentional, because the summaryRaw call already exists for numbers.

**Comment by C4Wiz** [comment]
how about an actual answer? is this the new behaviour of the summary call or is it a flaw?

if it is the new behaviour, why is it redundant with SummaryRaw? and since the behaviour was already present with summaryraw i see no point in this change

**Comment by DL6ER** [comment]
This is an unintended side-effect of fixing another issue with incorrect localization. A fix is already being prepared for those that depend on server-side stringification: https://github.com/pi-hole/AdminLTE/pull/2067

**Comment by dschaper** [comment]
> how about an actual answer?

Please tone down the attitude.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
