### ISSUE TITLE
Webpage "No temp sensor found" in Virtual Machine (VM)

### ISSUE THREAD

**Issue by Sysadminfromhell** [pi-hole/web#2058]
### Versions
- Pi-hole:  v5.8.1
- AdminLTE:  v5.10.1
- FTL:  v5.13

### Platform
- OS and version:  Debian 11.2
- Platform:  VM on Proxmox (PiMox)

### Expected behavior

Because I'm using Pihole in a VM the expected behavior would be that the line is hidden like before.

### Actual behavior / bug

Since the Update to 5.10.1 Webinterface i get an "ugly" No temp sensor found because im using PiHole in a VM.

### Steps to reproduce

go to the Web Page and Login.

## Debug Token

- URL:  https://tricorder.pi-hole.net/dM0p6MXe/

### Screenshots

![image](https://user-images.githubusercontent.com/78756354/148539491-67ab8644-aa89-4c5c-9ce6-bf48359b33fa.png)

**Comment by yubiuser** [comment]
We might remove it again: https://github.com/pi-hole/AdminLTE/pull/2054

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
