### ISSUE TITLE
UI: selected widget color matches or is too close to background color

### ISSUE THREAD

**Issue by xanoni** [pi-hole/web#2068]
### Versions

```bash
$ docker exec pihole pihole -v
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is release v5.10.2 (Latest: v5.10.2)
```

Stable Firefox and Chrome browsers.

### Platform

- OS and version:  Bullseye arm64

- Platform:  Docker on RPi

### Expected behavior

It's easy to see which UI widgets (e.g., tab buttons) are selected, e.g., that they have a color that's substantially different from the website background color.

### Actual behavior / bug

There are several places in the UI where the color of selected items matches the color of the background (or where there's insufficient contrast), which can be visually confusing. It can make it appear as if the unselected items were the selected ones and vice versa.

### Steps to reproduce

1. Install Pi-hole via Docker
2. Select "Pi-hole midnight theme (dark)" in the "API/Web Interface" settings (there are also challenges with the light theme, see screenshots)
3. Click "Blacklist" in navigation (example)
4. Toggle between the "Domain" and "RegEx filter" tabs

## Debug Token

- URL: n/a

### Screenshots

Background = selected color (with dark theme):
<img width="419" alt="image" src="https://user-images.githubusercontent.com/77220130/137842605-a2e0db8b-840a-4efc-95f9-715de7ffd650.png">

No contrast between selected color and background (with light theme):
<img width="564" alt="image" src="https://user-images.githubusercontent.com/77220130/137843254-8da27f70-8823-4e01-8ab4-0d764916a49b.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/77220130/137843280-ccf97b3a-f271-49d2-8aaf-162893e0dbdc.png">

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Please run 

`pihole checkout web navtabs_contrast` to try the fix @rdwebdesign prepared. You can go back on track with `pihole checkout master` anytime.

**Comment by xanoni** [comment]
Thank you. Due to "reasons" I currently don't have an environment to test this, but maybe someone else can.

**Comment by yubiuser** [comment]
We already did try this and it's part of the `development` branch already. It should be part of the next Pi-hole version.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
