### ISSUE TITLE
Settings "Colorful Query Log" is not remembered when restart Pi-hole

### ISSUE THREAD

**Issue by tntc4** [pi-hole/web#2089]
### Versions

- Pi-hole:  5.8.3
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform
- OS and version:  Windows 7
- Platform:  Raspberry Pi

### Expected behavior

Settings >> API/Web Interface >> Styling >> Colorful Query Log
this settings should be remembered when restart the Pi-hole

### Actual behavior / bug

Settings >> API/Web Interface >> Styling >> Colorful Query Log
this settings is not remembered when restart the Pi-hole

### Steps to reproduce

1. Go to 'Settings >> API/Web Interface >> Styling'
2. Click on 'Colorful Query Log'
3. Restart Pi-hole
4. Back to 'Settings >> API/Web Interface >> Styling'
5. the settings is not remembered

### Screenshot of the settings
![Screenshot_1](https://user-images.githubusercontent.com/3246834/149945679-b2ee79ff-b295-4d9c-9cfe-e5e5dfaaeefd.png)

**Comment by yubiuser** [comment]
It should be saved.

https://github.com/pi-hole/AdminLTE/blob/692d23edb034ce509aee146b895fab077805f19b/scripts/pi-hole/js/settings.js#L361-L377

Please check your browser settings reagarding deletion of the local storage. 
Which browser do you use?

**Comment by tntc4** [comment]
I'm using Firefox 50.1.0
Will check localstorage and cookie settings.
thanks

**Comment by tntc4** [comment]
I tested it again and now it's working like a charm.
Thank you and sorry for this bug report.
