### ISSUE TITLE
Undefined variable $temperaturelimit

### ISSUE THREAD

**Issue by Deshmir** [pi-hole/web#2092]
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform

- OS and version:  Ubuntu 21.10

- Platform:  Proxmox LXC

### Expected behavior

No error when a temperature sensor is not detected whilst going to the settings page of pihole.

### Actual behavior / bug
`There was a problem applying your settings.
Debugging information:
PHP error (2): Undefined variable $temperaturelimit in /var/www/html/admin/scripts/pi-hole/php/header.php:379`

It does seem that saving the settings work. e.g. I can change the theme correctly.

### Steps to reproduce

Go to "http://[ip]/admin/settings.php"
Check settings page
Notice error:

## Debug Token

- URL:   https://tricorder.pi-hole.net/2eVfkXyS/

### Screenshots

![image](https://user-images.githubusercontent.com/90623161/150352114-85a7971c-7c64-48c3-b28b-901e72b9da93.png)

### Additional context

I haven't added the config to actually have proxmox be able to check the system temperature, hence the LXC where pihole is running on can't find it too.

**Comment by Deshmir** [comment]
Reference #2058

**Comment by yubiuser** [comment]
We reworked the templimit logic. Fixed in the next release.
