### ISSUE TITLE
Deleting local DNS records failed but web interface displays success message

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2094]
Manually create an entry in `/etc/pihole/custom.list` containing an upper case letter. Try to delete it - web interface displays success message but the entry is not deleted. See https://discourse.pi-hole.net/t/unable-to-delete-local-dns-records-via-web-admin/52755

**Comment by yubiuser** [comment]
Reason why deletion failed is likely https://github.com/pi-hole/pi-hole/blob/3cd662eaeb36025a098cf336b1f8e7211d714f76/advanced/Scripts/webpage.sh#L651-L658

But this still leaves the wrongly reported status

**Comment by rdwebdesign** [comment]
I found the same problem on the Custom CNAME page. If the user enters CNAME records manually and the records contains uppercase letters, the deletion will fail.

The PR includes a fix for both cases.

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/pi-hole/pull/4598

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
