### ISSUE TITLE
API call to local DNS and CNAME records does not return valid JSON

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2123]
@yubiuser Thanks for this. Question: I'm getting a response like this:

`{"data":[["testje.testje","192.168.1.68"],["test.test2","192.168.1.42"]]}[]`

which is not valid JSON due to the `[]` at the end.

In theory, something like the response below would be ideal, though just having the [] removed would be enough for now. Is it possible to fix this?

```
{
    "data": [
        {
            "domain": "testje.testje",
            "ip": "192.168.1.68"
        },
        {
            "domain": "test.test2",
            "ip": "192.168.1.42"
        }
    ]
}
```

Thanks 😄

_Originally posted by @jojost1 in https://github.com/pi-hole/AdminLTE/issues/2091#issuecomment-1039012758_

**Comment by yubiuser** [comment]
@jojost1

I created a new issue from your report. This is an bug and should be fixed.

**Comment by subnut** [comment]
> In theory, something like the response below would be ideal

@jojost1 Instead of doing it in pi-hole itself, it is better to use a generic tool like [`jq`](https://github.com/stedolan/jq)

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/releases/tag/v5.12
