### ISSUE TITLE
API returning content type html/text

### ISSUE THREAD

**Issue by mapperist** [pi-hole/web#2178]
After upgrading to 5.10, when viewing the query log via API the http response sends a content type of HTML/text instead of application/json. Any application using the API isn't able to parse the log correctly and displays an error.

**Comment by rdwebdesign** [comment]
What URL are you accessing when you see this response?

**Comment by mapperist** [comment]
getAllQueries

Here's a screenshot of a tcpdump that shows the response:

![Screenshot_20220421-225617_JuiceSSH](https://user-images.githubusercontent.com/54448156/164606503-ae739f6a-f4c8-4022-add2-4de09c80b072.jpg)

**Comment by drupol** [comment]
Has this been already released?

**Comment by yubiuser** [comment]
Yes.
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-16-web-v5-13-and-core-v5-11-1-released/56384/1
