### ISSUE TITLE
Cannot upgrade to beta v5.6

### ISSUE THREAD

**Issue by 3DCoded** [pi-hole/web#2190]
### Versions

- Pi-hole:  v5.9
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform

- OS and version:  Raspberry Pi OS Bullseye ARM64

- Platform:  Raspberry Pi

### Expected behavior
Allow me to upgrade to AdminLTE v5.6.
_A clear and concise description of what you expected to happen._

### Actual behavior / bug
_A clear and concise description of what the bug is._
`Requested branch "release/v5.6" is not available`

### Steps to reproduce

1. Go to terminal
2. run `pihole checkout web release/v5.6`
3. press `y` and enter 
4. see error

URL: https://tricorder.pi-hole.net/YkJNK2f8/

**Comment by yubiuser** [comment]
There is no beta v5.6 (anymore). Why do you want to downgrade?

**Comment by rdwebdesign** [comment]
One more note:
an older web interface won't work with the current FTL and current pi-hole versions.

**Comment by rdwebdesign** [comment]
As I said on the other issue:

Your debug token shows **you are using `v5.12`** (the latest one).

Why do you want do **Downgrade** to `v5.6`?
