### ISSUE TITLE
Parse error: syntax error, unexpected '.' in /var/www/admin/scripts/pi-hole/php/auth.php on line 54

### ISSUE THREAD

**Issue by chekesote** [pi-hole/web#2191]
https://github.com/pi-hole/AdminLTE/blob/6c320a42574f9f0944ded71d84b7331557dbc6ea/scripts/pi-hole/php/auth.php#L54

Just needed remove 3 dots ... for explode function.

**Comment by rdwebdesign** [comment]
Can you please generate a debug token?

**Comment by rdwebdesign** [comment]
The 3 dots operator `...` is the PHP syntax for unpacking arrays and _Traversables_ into argument lists (also known as "splat operator", "scatter operator" or "spread operator"). 

It was introduced in PHP 5.6, in 2014.

Links:
 - [Function - Variable-length argument lists](https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list) - from PHP help.
 - [PHP RFC: Syntax for variadic functions](https://wiki.php.net/rfc/variadics) - from 2013.
 - [PHP RFC: Argument Unpacking](https://wiki.php.net/rfc/argument_unpacking) - from 2013.

**Comment by yubiuser** [comment]
Duplicate of https://github.com/pi-hole/AdminLTE/issues/2004
