### ISSUE TITLE
Release 5.12 is not on github

### ISSUE THREAD

**Issue by ulrichwisser** [pi-hole/web#2200]
There is a tag in the repo for version 5.12, but there is no release 5.12. 
This makes for some problems with pi-hole monitoring as 
```
#$pihole -v
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.11)
  FTL version is v5.15 (Latest: v5.15)
```
As you can see, pihole thinks I have a later version installed.
When trying to do an update pihole reports everything to be up-to-date.
```
# pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.31-1~deb10u1
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

```

**Comment by PromoFaux** [comment]
Thanks for the heads up - This has happened before and I'm not sure what the cause is.

Oddly, the release page is actually still there : https://github.com/pi-hole/AdminLTE/releases/tag/v5.12, but it's not showing on the list of releases.

I've gone in and hit "Update Release", and that should have sorted it. Please let us know if it has not!

Please let us know if it happens again - I would like to get to the bottom of what is causing it, though I suspect it is a bug on Github's end

**Comment by ulrichwisser** [comment]
I can see the release on github now.
But `pihole -v` uses versions from `/etc/pihole/GitHubVersions`.
How does the file get updated?
If I remove the file, `pihole -v` will check with github directly and the output is correct, but I do not get a new GitHubVersions file.

**Comment by PromoFaux** [comment]
I can never remember the exact process that updates that file, but it is on a `cron` job I think (I'm not near a system to be able to check right now!) Might just be that it takes a little time.

**Comment by C4Wiz** [comment]
Still not corrent here!

pi@pihole:~ $ pihole -v
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.11)
  FTL version is v5.15 (Latest: v5.15)
  
  UPDATE:
**Fixed After a Reboot**

**Comment by yubiuser** [comment]
The tag is back on github.
https://github.com/pi-hole/AdminLTE/releases/tag/v5.12

The `/etc/pihole/GitHubVersions` should be fine now as well. 
We check for the remote version every 24h

https://github.com/pi-hole/pi-hole/blob/2735481da8fac3cb521338b7af2259da7b621e88/advanced/Templates/pihole.cron#L34-L36
