### ISSUE TITLE
"Session expired!" caused by php output_buffering=Off

### ISSUE THREAD

**Issue by SR4ven** [pi-hole/web#2207]
### Versions
- Pi-hole:  5.10
- AdminLTE: 5.12 
- FTL:  5.15

### Platform
- OS and version:  Ubuntu 20.04
- Platform:  Raspberry Pi 4
- Apache/2.4.41
- PHP 8.0.19 (cli)

### Expected behavior

Deleting entries from Tools/Network overview table should work. (.../admin/network.php)

### Actual behavior / bug

When setting "output_buffering" to "Off" in the fpm php.ini and pressing delete on a table entry, it is not deleted and the error message 
>"Error, something went wrong! Session expired! Please re-login on the Pi-hole dashboard."

is shown in the top right corner.

PHP error log shows the following entry:
```
[Sat May 21 21:38:29.962866 2022] [proxy_fcgi:error] [pid 136763:tid 281472868729232] [client fe80::dd75:29a3:32b5:4cd8:52121] AH01071: 
Got error 'PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/admin/scripts/pi-hole/php/network.php:1) in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 93
PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 107
PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 109
PHP message: PHP Warning:  session_start(): Session cannot be started after headers have already been sent in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 110'
, referer: https://***/admin/network.php
```
To me this seems similar to what was discovered in https://github.com/pi-hole/AdminLTE/issues/2128

### Steps to reproduce

- Add output_buffering = Off to e.g. /etc/php/8.0/fpm/php.ini
- service php8.0-fpm restart
- Refresh pi-hole web admin (eventually log in)
- Open Tools -> Network
- Delete an entry
- See error message

### Additional context

- pi-hole itself works fine
- Everything works as expected if output_buffering = 4096

**Comment by rdwebdesign** [comment]
Please, generate a debug token.

**Comment by SR4ven** [comment]
https://tricorder.pi-hole.net/DswHa1G5/

**Comment by rdwebdesign** [comment]
I could not replicate the issue with `lighttpd`.

You are using Apache.
Apache is a non-supported web server.

**Comment by rdwebdesign** [comment]
Are you using a modified version of AdminLTE interface?

**Comment by SR4ven** [comment]
> Are you using a modified version of AdminLTE interface?

No, git status on /var/www/html/admin returns:
> On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

**Comment by rdwebdesign** [comment]
I just saw my PHP config.
The default config is `output_buffering=4096`.

**Comment by rdwebdesign** [comment]
As you are using Apache (and probably serving another site), and I imagine something might have changed this setting.

**Comment by SR4ven** [comment]
Correct, Nextcloud suggests turning output buffering off as described here: https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=output_buffering#configuring-php

I think I recall having problems with Nextcloud and output_buffering on 4096. Might have to test that again if you don't see this as an issue on your side.

**Comment by dschaper** [comment]
Can you set the `.htaccess` for the nextcloud's sever to no buffering and leave Pi-hole with it's set buffering?

**Comment by SR4ven** [comment]
Good idea @dschaper, I haven't thought about local configs yet.

However, as far as I understand this is only possible when using the php Apache module. I'm using php-fpm for performance reasons where php config over .htaccess seems impossible. https://www.php.net/manual/en/configuration.changes.php

Adding a separate php-fpm pool for pi-hole might be a possibility. However, that would surely be an inconvenience. I'll give it a try tomorrow.

Anyway, that's only a workaround for my specific case. Are you certain that this is no bug in AdminLTE? To my (very limited) understanding about php, a website should not depend on output buffering. The same could be said about Netxcloud I guess.

**Comment by rdwebdesign** [comment]
You can try `.user.ini` files:
https://stackoverflow.com/questions/38190279/can-i-override-php-setting-in-htaccess-when-using-php-fpm

**Comment by rdwebdesign** [comment]
Note:
I removed the empty line ([here](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/network.php#L1)).

This should fix the error, even with `output_buffering=Off`.

**Comment by SR4ven** [comment]
> You can try `.user.ini` files: https://stackoverflow.com/questions/38190279/can-i-override-php-setting-in-htaccess-when-using-php-fpm

Cool, good to know!

> Note: I removed the empty line ([here](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/network.php#L1)).
> 
> This should fix the error, even with `output_buffering=Off`.

Indeed, with your fix it works perfectly fine.
Thank you very much for looking into this and for all the suggestions. Great work, keep it up!
