### ISSUE TITLE
Update AdminLTE ended with 'Could not update local repository. Contact support.'

### ISSUE THREAD

**Issue by MrHappy** [pi-hole/web#2255]
### Versions

- Pi-hole:  5.11.1
- AdminLTE:  5.12
- FTL:  5.15

### Platform
- OS and version:  Ubuntu 18.04.6
- Platform:  VM on Proxmox

### Expected behavior
I expected every component to update.

### Actual behavior / bug
Only pi-hole got updated, AdminLTE stopped with the following message:
```
sudo pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.2.24-0ubuntu0.18.04.12
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	update available
  [i] FTL:		update available

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...

  : Could not update local repository. Contact support.
```

### Steps to reproduce
1. sudo pihole -up
2. See error

**Comment by rdwebdesign** [comment]
Please, generate a debug log and post the token here.

**Comment by MrHappy** [comment]
> Please, generate a debug log and post the token here.
Here you go.
https://tricorder.pi-hole.net/0Jzcg55c/

**Comment by rdwebdesign** [comment]
You have changes in your local AdminLTE:

```diff
Diff: diff --git a/api_FTL.php b/api_FTL.php
  index 98b2ee7b..5e9c4367 100644
  --- a/api_FTL.php
  +++ b/api_FTL.php
  @@ -6,6 +6,9 @@
*    This file is copyright under the latest version of the EUPL.
*    Please see LICENSE file for your rights under this license */

+/* Fix voor flutterhole */
+header('Content-type: application/json');
+
if (!isset($api)) {
   die("Direct call to api_FTL.php is not allowed!");
}
```

`git` is probably complaining about this change and you need to remove them.

Since you will update (and loose your changes), execute:

```sh
cd /var/www/html/admin/
git reset --hard
``` 

The changes will be gone and you can upgrade normally.

**Comment by MrHappy** [comment]
*smacks forehead* completely forgot about that one...
Thanks! 
Would it be an option to return git-errors like these directly?

**Comment by rdwebdesign** [comment]
Is it fixed?

**Comment by MrHappy** [comment]
It is 👍
