### ISSUE TITLE
Saving changes on DNS settings clears out all the upstream servers selected

### ISSUE THREAD

**Issue by ealap** [pi-hole/web#2256]
### Versions

- Pi-hole:  5.11.3
- AdminLTE:  5.13
- FTL:  5.16

### Platform

- OS and version:  Ubuntu 21.04

- Platform:  Raspberry Pi 4

### Expected behavior

Saving changes from the DNS settings page should be able to keep what was selected or manually configured in the configuration files

### Actual behavior / bug

After clicking the save button, there no more selected upstream servers.

### Steps to reproduce

![2022-07-08_20-41-30](https://user-images.githubusercontent.com/15620712/177994107-f648b129-8bb7-4339-9f8e-109bbe6ad23d.gif)

1. Set the DNS upstream server via Admin OR by manually editing `setupVars.conf`
2. On Admin > DNS settings page (/admin/settings.php?tab=dns), click the **Save** button

## Debug Token

- URL:  https://tricorder.pi-hole.net/mWlAPOVA/

### Additional context

Issue only started since update to:
- Pi-hole:  5.11.3
- AdminLTE:  5.13
- FTL:  5.16

**Comment by jfb-pihole** [comment]
Your debug log shows this recurrent error:
```
   2022-07-08 12:20:50: (mod_fastcgi.c.451) FastCGI-stderr:PHP Warning:  Executing sudo pihole -a setdns "127.0.0.1\#24153,127.0.0.1\#24053" domain-needed bogus-priv no-dnssec failed. in /var/www/html/admin/scripts/pi-hole/php/func.php on line 149
   2022-07-08 12:21:24: (mod_fastcgi.c.451) FastCGI-stderr:PHP Warning:  Executing sudo pihole -a setdns "127.0.0.1\#24153" domain-needed bogus-priv no-dnssec failed. in /var/www/html/admin/scripts/pi-hole/php/func.php on line 149
   2022-07-08 12:21:40: (mod_fastcgi.c.451) FastCGI-stderr:PHP Warning:  Executing sudo pihole -a setdns "1.1.1.1,1.0.0.1" domain-needed bogus-priv no-dnssec failed. in /var/www/html/admin/scripts/pi-hole/php/func.php on line 149
```

The applicable code is here:

https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/func.php#L149

What are the permissions on your setupVars.conf file?

Note - I am unable to duplicate this problem on the same versions of Pi-hole.

`ls -lha /etc/pihole/setupVars.conf`

**Comment by ealap** [comment]
Here's what I got
![image](https://user-images.githubusercontent.com/15620712/178005779-49c8b0be-c41b-4605-879c-f553ecd0821b.png)

**Comment by jfb-pihole** [comment]
Those are the correct permissions

**Comment by ealap** [comment]
I tried executing the command that is giving off that error.

```
$ sudo pihole -a setdns "1.1.1.1,1.0.0.1" domain-needed bogus-priv no-dnssec
Segmentation fault
```

**Comment by yubiuser** [comment]
> Segmentation fault

This usually indicates file system errors or corrupted SD card.

**Comment by ealap** [comment]
Alright, I could see how that might have happened on my side, the current OS install was a clone from my older SD card, and the corruption only manifested after the recent update. I'll close this issue for now and see if I could just do a simple reinstall.

One suggestion for improvement I can make out of this is maybe Pi-Hole Admin can recognize the error properly and show an error message instead of success message.
