### ISSUE TITLE
Can't delete entry with non-standard characters from lists using API

### ISSUE THREAD

**Issue by oleksiikutuzov** [pi-hole/web#2257]
### Versions

- Pi-hole:  v5.11.3
- AdminLTE:  v5.13
- FTL:  v5.16.1

### Platform

- Platform:  Docker

### Actual behavior / bug

When trying to delete the entry with non-standard characters (e.g. Cyrillic) from the whitelist/blacklist via API, it won't delete. However, can be deleted from web UI.

### Steps to reproduce

1. Create a whitelist/blacklist entry with non-standard characters 
2. Try to delete it using API

## Debug Token

- URL:  https://tricorder.pi-hole.net/BLP0eD0u/

### Screenshots

 Attaching video: https://share.icloud.com/photos/00cclKZfOgnzqeuKnRJfIFaJg

**Comment by yubiuser** [comment]
I know what's going on and prepare a fix.

**Comment by yubiuser** [comment]
@oleksiikutuzov 

Please checkout this branch and see if it solves your issue

`pihole checkout web idn`

You can go back on track (and before the next Pi-hole update` with `pihole checkout web master`

**Comment by oleksiikutuzov** [comment]
@yubiuser unfortunately still cannot be deleted from the app

**Comment by yubiuser** [comment]
Please contact the developer of the App then. Using the custom branch should support deleting non-standard characters via `pi.hole/api.php?list=black&sub=XXX` now (where `XXX` is the domain).

**Comment by oleksiikutuzov** [comment]
Sorry for the late reply. Can confirm it’s works good
