### ISSUE TITLE
Top Client Reports pihole

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/web#2271]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---

**Expected behavior:**
'http://pihole.local/admin/api.php?topClients should return top client'

**Actual behavior:**
http://pihole.local/admin/api.php?topClients returns {"top_sources":{"pi.hole|::":7564}}

<img width="783" alt="Screen Shot 2022-07-23 at 9 50 54 AM" src="https://user-images.githubusercontent.com/3883521/180607999-3aa7778b-50bd-4522-9c6f-99a554620b71.png">
<img width="376" alt="Screen Shot 2022-07-23 at 9 57 25 AM" src="https://user-images.githubusercontent.com/3883521/180608238-cd7188b8-aff4-4523-90f9-e805660fcc24.png">

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by yubiuser** [comment]
Very likely, this is not a bug but a configuration issue. Please visit our support forum at https://discourse.pi-hole.net/

**Comment by C4Wiz** [comment]
actually if you would take the time to ask, it has been the same config for over a year, worked fine till the latest update. so yes it is a bug!

**Comment by yubiuser** [comment]
If you would have take the time to read our issue template and provide more useful information we might have been able to help you

> Debug token provided by uploading pihole -d log:

> {Alphanumeric token}

P.S. Pi-hole is correctly returning the top client, in your case it is `pi.hole`

**Comment by C4Wiz** [comment]
pi.hole was never ever even on the client list till recent update

**Comment by PromoFaux** [comment]
The dashboard is only reporting based on the information it has. In this case it appears that something on the system you have Pi-hole installed on is making queries. How much time have you taken to investigate this?

Things to look at:
 - Query log, or just click `pi.hole` in the top clients list to give you an ideas as to the queries that are being made by that machine
 - A debug token for us, as requested, would help us to help you - that is why we ask for it in the issue template (as @yubiuser has already said)


"There is a bug" (which we cannot reproduce) isn't helpful :)

**Comment by jfb-pihole** [comment]
"worked fine till the latest update. so yes it is a bug!"

"pi.hole was never ever even on the client list till recent update"

https://docs.pi-hole.net/ftldns/configfile/#pihole_ptr

**Comment by C4Wiz** [comment]
> "worked fine till the latest update. so yes it is a bug!"
> 
> "pi.hole was never ever even on the client list till recent update"
> 
> https://docs.pi-hole.net/ftldns/configfile/#pihole_ptr

no clue what you are trying to point out here but, i solved pi.hole from being in the top client list by adding it here:
<img width="760" alt="Screen Shot 2022-07-23 at 1 43 49 PM" src="https://user-images.githubusercontent.com/3883521/180616775-9584a164-53bb-4bf2-9f6b-2946b5a00354.png">

**Comment by PromoFaux** [comment]
>no clue what you are trying to point out here

I think it a misunderstanding between Top Domains and Top Clients list.

Did you look into the queries that the Pi-hole device was making? Hiding it from your top clients is one thing, finding and solving the route cause is another. (Seen no evidence that suggests this is a bug in Pi-hole yet, though)

**Comment by jfb-pihole** [comment]
Why do you think this is a bug?  Is your Pi-hole not generating these queries?

From the Pi terminal, what is the output of the following:

`echo ">top-clients >quit" | nc localhost 4711`

**Comment by C4Wiz** [comment]
https://tricorder.pi-hole.net/mfgRXmIC/

**Comment by C4Wiz** [comment]
> 

pi@pihole:~ $ echo ">top-clients >quit" | nc localhost 4711
0 9017 10.172.69.49 
1 8009 10.172.69.79 
2 3400 10.172.69.12 
3 2996 10.172.69.8 
4 2882 10.172.69.36 
5 1786 10.172.69.19 
6 1255 10.172.69.57 
7 962 10.172.69.53 
8 825 127.0.0.1 localhost
9 722 10.172.69.77

**Comment by C4Wiz** [comment]
and with pi.hole removed from the hidden list:

pi@pihole:~ $ echo ">top-clients >quit" | nc localhost 4711
0 9036 10.172.69.49 
1 8286 :: pi.hole
2 8013 10.172.69.79 
3 3404 10.172.69.12 
4 3001 10.172.69.8 
5 2886 10.172.69.36 
6 1789 10.172.69.19 
7 1255 10.172.69.57 
8 967 10.172.69.53 
9 825 127.0.0.1 localhost

**Comment by yubiuser** [comment]
See
https://discourse.pi-hole.net/t/pi-hole-client-in-query-log/50285

Or

https://discourse.pi-hole.net/t/pi-hole-hostname-shows-as-top-client/52770/2

Suppress logging with
https://discourse.pi-hole.net/t/top-client-is/50385/4?u=yubiuser
