### ISSUE TITLE
Static lease hostnames aren't added to a custom hostname.list file

### ISSUE THREAD

**Issue by DroidFreak32** [pi-hole/web#2286]
### Versions

- Pi-hole:  v5.11.4
- AdminLTE:  v5.13
- FTL:  v5.16.1

### Platform

- OS and version:  Raspbian bullseye

- Platform:  Raspberry Pi

### Expected behavior

Upon adding static DHCP leases, it should be fair to expect the hostnames for these leases can be resolved.

### Actual behavior / bug

After adding a static DHCP lease, PiHole is unable to resolve the hostnames.
This was reported at https://discourse.pi-hole.net/t/can-i-use-dhcp-static-lease-name/49267
This issue is to check if PiHole could use existing code to add hostname <-> IP address to a list like /etc/pihole/custom.list 
https://github.com/pi-hole/AdminLTE/blob/1714b082c3a233ea3a0c344b50352c59818676fc/scripts/pi-hole/php/func.php#L197

### Steps to reproduce

1. Create a static DHCP lease
2. Query the hostname

### Additional context
I know this can be resolved when using custom.list file but that doesn't really solve the problem if "active" leases expire.
PiVPN actually creates a new hostname.list file which PiHole then reads and thus PiVPN hostnames are easily resolved.
PiHole could create its own "/etc/pihole/static_leases.list" file to manage static hostnames
This will also solve any stale hostnames that stay present on custom.list file incase one of the static leases are removed.

**Comment by yubiuser** [comment]
Thanks for your report.
Existing static leases should be able to be resolved as soon as the client acquires that lease. They won't resolve if the client has no active lease. Why do you want to be able to resolve the hostname when the client is offline?

I'm not sure if Pi-hole is the right place to "fix" this. Internally we use `dnsmasq` for DNS and DHCP. Hostnames from existing, but inactive static leases are not added to the DNS cache - if you want to get this fixed, this should be addressed at `dnsmasq` level.

**Comment by DroidFreak32** [comment]
Thanks for the quick response.

> Why do you want to be able to resolve the hostname when the client is offline?  

In my use case, I have clients that never really connect using DHCP (Access Point, VMs)
They are set to a static address internally and never performs DHCP requests.
However, I need to add them to the Static leases in order to not have duplicate addresses assigned to other devices.

> if you want to get this fixed, this should be addressed at dnsmasq level.  

I agree this is more of a `dnsmasq` issue. I chose to report here because the solution here in my eyes would be:
1) Add a new line in existing dnsmasq configs  `addn-hosts=/etc/pihole/static_hostnames.list`
2) Perform `addCustomDNSEntry()` and `deleteCustomDNSEntry()` as and when static leases are added/removed.

Since pihole is already doing this with `/etc/pihole/custom.list` it made sense for me to report here.


<sub>Currently achieving this manually:
 `awk -F ',' '{print $2" "$3}' /etc/dnsmasq.d/04-pihole-static-dhcp.conf | sudo tee /etc/pihole/static_hostnames.list
`
PS: OpenWrt also seems to be using dnsmasq and handles this very well
</sub>

**Comment by yubiuser** [comment]
Ok, I see from where you are coming.
My usual approach to 

> However, I need to add them to the Static leases in order to not have duplicate addresses assigned to other devices.

is:

If I have a `/24` subnet, I use the range `.2-20` for static addresses and only use DHCP within `.21-254`. So there will no be no overlap between static range and DHCP range. For each static address I create a Local DNS record. By default, Pi-hole has a DHCP range even smaller: `.201-254`. So you could define 199 static addresses Pi-hole would never conflict with.

Personally, I think this approach is better than to create DNS records for non-active leases.

**Comment by DroidFreak32** [comment]
@yubiuser I don't disagree with that approach, however, in my use case it adds an additional step from the user to maintain LocalDNS entries as well as DHCP lease entries. For example, VMs keep changing the hostnames which need to be updated in 2 places with this approach.
Maintaining one file (_at least in my opinion_) seems simpler. 
I see now this is more of a feature request than a bug report, so I did some little more digging and I think I can raise a PR to handle this use case inside [webpage.sh](https://github.com/pi-hole/pi-hole/blob/aefbe1f5b6225b7476fe08264c62da84aaa61fa0/advanced/Scripts/webpage.sh#L543)

Although, if there are any obvious downsides to my suggestion, please let me know.
