### ISSUE TITLE
"Use Bcrypt or Scrypt Instead of SHA* for Your Passwords, Please!"

### ISSUE THREAD

**Issue by MattAKAFred** [pi-hole/web#23]
I noticed that the login script hashes with SHA-256... If the web interface is going to go through the effort of hashing passwords (which, it's good that's what's happening), it's better to use a slow hashing algorithm like Bcrypt or Scrypt

https://rietta.com/blog/2016/02/05/bcrypt-not-sha-for-passwords/

https://github.com/dcodeIO/bcrypt.js

**Comment by Mcat12** [comment]
First, [Core](https://github.com/pi-hole/pi-hole/) will need to add support for this.

**Comment by walter-exit** [comment]
I would opt for either Scrypt or Argon2. Going forward, Bcrypt, even though it is battle-tested, is not as good nor future-proof as the others in my opinion. Argon2 is the latest and cryptographically very good, but rather new. So implementations have not had much time yet to prove themselves. Support is great though.
