### ISSUE TITLE
Use the new version file format for checks

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/web#2305]
After https://github.com/pi-hole/pi-hole/pull/4875 the versions and branches will be in a single file.

The PHP code needs to reflect this change.

**Comment by rdwebdesign** [comment]
This isn't really a bug.
It's an improvement, but will become a bug if not merged at the same time as the core PR.

**Comment by yubiuser** [comment]
I needed a label to keep it ignored from `stale` bot

**Comment by rdwebdesign** [comment]
> I needed a label to keep it ignored from stale bot

I hope the PR doesn't take that long to be finished.

**Comment by yubiuser** [comment]
Just in case 😜

**Comment by PromoFaux** [comment]
Might be worth adding a generic [never-stale](https://github.com/pi-hole/docker-pi-hole/labels/never-stale) label here, too.

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-17-web-v5-14-and-core-v5-12-released/57497
