### ISSUE TITLE
Docker Tag for link for Release 2022.09 is not clickable anymore

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/web#2323]
This is a: **Bug***

## Details
Starting with [Release 2022.09](https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.09) the link for "Docker Tag" for Pi-hole is not clickable anymore:
> Docker Tag 2022.09 Pi-hole [v5.12](https://github.com/pi-hole/pi-hole/releases/v5.12) FTL [v5.17](https://github.com/pi-hole/FTL/releases/v5.17) Web Interface [v5.14](https://github.com/pi-hole/AdminLTE/releases/v5.14)

Before:
> Docker Tag [2022.08.2](https://github.com/pi-hole/docker-pi-hole/releases/2022.08.2) Pi-hole [v5.11.4](https://github.com/pi-hole/pi-hole/releases/v5.11.4) FTL [v5.16.3](https://github.com/pi-hole/FTL/releases/v5.16.3) Web Interface [v5.13](https://github.com/pi-hole/AdminLTE/releases/v5.13)
> Docker Tag [2022.08.3](https://github.com/pi-hole/docker-pi-hole/releases/2022.08.3) Pi-hole [v5.11.4](https://github.com/pi-hole/pi-hole/releases/v5.11.4) FTL [v5.16.3](https://github.com/pi-hole/FTL/releases/v5.16.3) Web Interface [v5.13](https://github.com/pi-hole/AdminLTE/releases/v5.13)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
See your Docker Tag down below your web GUI.

**Comment by gh0sti** [comment]
for me docker tag is N/A and the other 3 also are N/A. I did not setup mine with docker. Clicking on the N/A hyperlinks lead to 404 github page which just needs to be correctly linked to the new links. I'm running mine off raspberry pi 4

**Comment by rdwebdesign** [comment]
@gh0sti 

Can you please show the output of `cat /etc/pihole/versions`?

**Comment by gh0sti** [comment]
@rdwebdesign just update the html page to include correct links.
Bottom of the view source page of pihole just needs links updated.

```html
<ul class="list-inline">
                                        <li>
                        <strong>Docker Tag</strong>
                        N/A                                            </li>
                                        <li>
                        <strong>Pi-hole</strong>
                        a href="https://github.com/pi-hole/pi-hole/releases/N/A" rel="noopener" target="_blank">N/A</a>                                            </li>
                    <li>
                        <strong>FTL</strong>
                        a href="https://github.com/pi-hole/FTL/releases/N/A" rel="noopener" target="_blank">N/A</a>                                            </li>
                    <li>
                        <strong>Web Interface</strong>
                        a href="https://github.com/pi-hole/AdminLTE/releases/N/A" rel="noopener" target="_blank">N/A</a>                                            </li>
                </ul>

                <p style="margin: 15px 0 0;">
```
Edit: to fix the pasted code.

**Comment by gh0sti** [comment]
They just need to be updated to point to the correct releases. 

https://github.com/pi-hole/pi-hole/releases/tag/v5.12

https://github.com/pi-hole/AdminLTE/releases/tag/v5.14
https://github.com/pi-hole/FTL/releases/tag/v5.17

**Comment by thomasmerz** [comment]
Ups, this issue should be transferred to https://github.com/pi-hole/docker-pi-hole/issues/ … It's not related to FTL in any way. Sorry… Can someone please transfer this issue or should I close this and reopen it in the correct repo?

**Comment by rdwebdesign** [comment]
The HTML is created by PHP code, using the content of `/etc/pihole/versions` file.

Can you please show the output of cat /etc/pihole/versions?

**Comment by gh0sti** [comment]
@rdwebdesign under my etc/pihole/ there is no versions folder/file 
![image](https://user-images.githubusercontent.com/4202657/188228356-12567ec0-51b4-4e5f-b094-2f7e969ff22e.png)

**Comment by rdwebdesign** [comment]
> Ups, this issue should be transferred to https://github.com/pi-hole/docker-pi-hole/issues/ … It's not related to FTL in any way. Sorry… Can someone please transfer this issue or should I close this and reopen it in the correct repo?

The links you are seeing are on the PHP files.
This code belongs to "AdminLTE" repo. It was already transferred.

**Comment by rdwebdesign** [comment]
@gh0sti 

How did you install pi-hole?

If you just updated, how did you do?

**Comment by thomasmerz** [comment]
> Can you please show the output of `cat /etc/pihole/versions`?

```
22:06 $ docker exec -it pihole bash
root@pihole-merz-nimbus:/# cat /etc/pihole/versions
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.12-0-gf998eee
WEB_VERSION=v5.14-0-g126b148
FTL_VERSION=v5.17
GITHUB_CORE_VERSION=v5.12
GITHUB_WEB_VERSION=v5.14
GITHUB_FTL_VERSION=v5.17
```

**Comment by gh0sti** [comment]
@rdwebdesign 

I used pihole imaging software to flash my sd card and did pihole -up to update recently.

**Comment by rdwebdesign** [comment]
@thomasmerz 
The link is really missing on the code. I'm already looking into it.

@gh0sti
~~Can you please run `pihole -v` and verify if the links on the web page are fixed?~~ Sorry. Wrong option. Should be `pihole updatechecker`

**Comment by rdwebdesign** [comment]
@gh0sti 
Sorry.
Can you please try **`pihole updatechecker`** and verify if the links on the web page are fixed?

**Comment by gh0sti** [comment]
@rdwebdesign 
still N/A
![image](https://user-images.githubusercontent.com/4202657/188231157-bb45ba26-24c3-4228-b9f7-d867c1665853.png)

**Comment by rdwebdesign** [comment]
Your command is showing an error message. Something is corrupted.

Please, try only `pihole updatechecker && cat /etc/pihole/versions` and post the output.

**Comment by PromoFaux** [comment]
There are two distinct issues here:

@gh0sti - there are corruptions in your `/etc/.pihole` directory (or maybe even `/var/www/html/admin`), go nuclear:
```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/adminlte /var/www/html/admin
pihole -r
```

If that does not fix the issue, please open a _new issue_ and we will look into it further. I'm going to minimise your comments in this thread now so as to keep things on topic with the originally reported issue

**Comment by gh0sti** [comment]
@rdwebdesign 
![image](https://user-images.githubusercontent.com/4202657/188232876-01f10b74-edce-4142-8a12-6486409306c2.png)

**Comment by PromoFaux** [comment]
Further locking this to org members, as we have all the information we need to investigate the _reported_ bug

**Comment by rdwebdesign** [comment]
As was said, you have something corrupted in your system.

That's the reason it's not working.
Try to fix this.

If you fix the corruption and still got this error, please open a new issue.
