### ISSUE TITLE
Fixing pihole

### ISSUE THREAD

**Issue by gh0sti** [pi-hole/web#2327]
### Versions

- Pi-hole:  5.12
- AdminLTE:  5.14
- FTL:  5.17

### Platform

- OS and version:  11 Bullseye

- Platform:  Raspberry Pi 4

### Expected behavior

"[PromoFaux](https://github.com/PromoFaux) commented [17 hours ago](https://github.com/pi-hole/AdminLTE/issues/2323#issuecomment-1235879519)
There are two distinct issues here:

@gh0sti - there are corruptions in your /etc/.pihole directory (or maybe even /var/www/html/admin), go nuclear:

sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/pi-hole /var/www/html/admin
pihole -r
If that does not fix the issue, please open a new issue and we will look into it further. I'm going to minimise your comments in this thread now so as to keep things on topic with the originally reported issue"

Following instructions given in the last bug report doing download of /var/www/html/admin is actually downloading the contents of /etc/.pihole from github. It should download the contents of /var/www/html/admin

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. sudo rm -rf /etc/.pihole
2. sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
3. sudo rm -rf /var/www/html/admin
4. sudo git clone https://github.com/pi-hole/pi-hole /var/www/html/admin

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Just following directions given from previous support member luckily I backedup my contents of /var/www/html/admin and /etc/.pihole to replace

**Comment by PromoFaux** [comment]
Whoops, sorry about that - the second one should be:

```
sudo git clone https://github.com/pi-hole/adminlte /var/www/html/admin

```

**Comment by gh0sti** [comment]
@PromoFaux ah man sometimes I can't read I should have noticed that lol. Anyways pihole is working again after restoring my /var/www/html/admin and I'm fully up to date.
