### ISSUE TITLE
Query Log is showing older logs than "Long-Term Logs"

### ISSUE THREAD

**Issue by gmbhneo** [pi-hole/web#2337]
### Versions

- Pi-hole: v5.12
- AdminLTE:  [v5.17](https://github.com/pi-hole/FTL/releases/v5.17)
- FTL:  [v5.14.2](https://github.com/pi-hole/AdminLTE/releases/v5.14.2)

### Platform

- OS and version:  Pi-OS

- Platform:  Raspberry Pi

### Expected behavior

The Query Log should show the latest logs.

### Actual behavior / bug
The Query Log is showing old entries when using a filter. The "Long-Term Log" is showing much more recent entries than the normal log, which does not make sense to me. 

### Steps to reproduce

Go to Query log and search for a client. The log I get is off by 1 day. Going to "Long-Term Log" will display the latest (today) logs that are not appearing in the normal logs.

## Debug Token

- URL:  https://tricorder.pi-hole.net/0UA9pjEp/

**Comment by yubiuser** [comment]
Please add a screenshot of what you are seeing.

**Comment by gmbhneo** [comment]
![pihole combined](https://user-images.githubusercontent.com/16648908/189111706-a1715401-fd80-4ae9-97ec-b347b2f20d12.jpg)
Hope this tells the story. Let me know if you need more info.

**Comment by yubiuser** [comment]
You used the table header in the Query log to order "by client". Now your latest queries are on a later page (you have 65 pages). Please have a look if the client made more recent queries.
In contrast, in the long-term data you ordered "by time" and the latest queries are on top.

**Comment by gmbhneo** [comment]
Oh you are right, I've expected the order to always be the same. The latest queries are at the end. What a bummer. This way it is so much harder to keep track of the latest queries of a certain client since there is no refresh button and refreshing the page will bring you back to page 1. Is there any way to kind of solve this? I am in need to keep track of all entries of a certain client in "real time" or at least every view seconds. I am using a "auto refresher" to do this atm.

**Comment by yubiuser** [comment]
You can use `pihole -t IP` to filter the live view of the `dnsmasq`log. Or you can order by time and use the "search field" of the Query log.

**Comment by rdwebdesign** [comment]
> Oh you are right, I've expected the order to always be the same. 

At first, all tables are always sorted by Time (most recent first).
If you select a different sort order for a table, the new order will be "remember" for that page.

Each page will remember the order. This is the same behavior for all tables that always keep the same data (Query log, Network, Local DNS, etc.).

On the other hand, the "Long-Term query log" table is completely reset every time you load this page.
The table is initially empty and you need to select a new time range.
The default behavior for this page is to reset the sort order.
