### ISSUE TITLE
FastCGI-stderr: PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/admin/scripts/pi-hole/php/database.php on line 285

### ISSUE THREAD

**Issue by emilioramirez** [pi-hole/web#2340]
### Versions

- Pi-hole:  v5.12 (Latest: v5.12)
- AdminLTE:  v5.14.2 (Latest: v5.14.2)
- FTL:  v5.16.3 (Latest: v5.17)

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi 2B

### Expected behavior

_The web interface loading the data (graphs, tables, etc) properly._

### Actual behavior / bug

_The web interface stop working properly, the sidebar works and render but the data does not load, for example, the dashboard or setting page does not load._

## Debug Token

- URL:  https://tricorder.pi-hole.net/A0aJpnun/

### Screenshots

_If applicable, add screenshots to help explain your problem._
![screenshot](https://user-images.githubusercontent.com/1151097/189232074-9f825e35-987d-4929-af2d-36f3ccb0ead3.png)

### Additional context

_This happend after i run `pihole -up` today.

**Comment by rdwebdesign** [comment]
Looks like this happens only if PHP version < 7.1.

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-18-web-v5-15-and-core-v5-12-1-released/57894
