### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by token0** [pi-hole/web#2348]
### Versions

- Pi-hole:  v5.12 (Latest: v5.12)
- AdminLTE:  v5.14.2 (Latest: v5.14.2)
- FTL:  v5.17 (Latest: v5.17)

### Platform

- OS and version:  Armbian 10 (Debian buster) with Linux 5.10.63-rockchip64
- Platform:  Rock64 single board computer

### Actual behavior / bug

1. Database error, message form "Groups" page:
JavaScript from "--pihole ip redacted--"
DataTables warning: table id=groupsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
2. No settings to manage lists available
3. "Restart dns resolver" and other Settings page buttons from web UI shows error "Wrong token! Please re-login on the Pi-hole dashboard." 
4. "Teleporter ­- Save backup" button does nothing.

### Steps to reproduce

1. pihole -up
2. open "Groups" page in web UI
3. try to restart dns resolver from web UI or other buttons on Settings tab

### Screenshots

Groups:
![image](https://user-images.githubusercontent.com/4627595/189826196-29a40548-9e04-4343-a5b9-c1c8c9b34923.png)

Restart dns:
![image](https://user-images.githubusercontent.com/4627595/189826533-7089bd17-243e-4e22-96eb-7e2aa95bab06.png)
![image](https://user-images.githubusercontent.com/4627595/189826709-2551d385-c631-4614-914f-33273ba96d72.png)
![image](https://user-images.githubusercontent.com/4627595/189826886-ce257757-5c37-49e9-baf3-6aa8b807070c.png)

### Additional context

Everything was working prior to `pihole -up`

**Comment by yubiuser** [comment]
Debug token please.

**Comment by token0** [comment]
@yubiuser 

https://tricorder.pi-hole.net/i3iJ7HIr/

**Comment by yubiuser** [comment]
You are running `apache` and `lighttpd` as webservers. Do the errors appear with both servers?

**Comment by token0** [comment]
Error appears even with apache2 down. My pihole set to alternate port, there's no conflict if you are asking. That could be something with database after update. Or pihole core component. I don't see any issues with FTL component.

**Comment by yubiuser** [comment]
The databases should be fine (at least from a technically point of view)

```
*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 17M Sep 13 10:32 /etc/pihole/pihole-FTL.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] Integrity of /etc/pihole/pihole-FTL.db intact
[i] Checking foreign key constraints of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] No foreign key errors in /etc/pihole/pihole-FTL.db

*** [ DIAGNOSING ]: Gravity Database
-rw-rw-r-- 1 pihole pihole 11M Sep 13 09:38 /etc/pihole/gravity.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] Integrity of /etc/pihole/pihole-FTL.db intact
[i] Checking foreign key constraints of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] No foreign key errors in /etc/pihole/pihole-FTL.db
```

**Comment by yubiuser** [comment]
Are you accessing the web interface via `pi.hole/admin` or `ip/admin`?

**Comment by token0** [comment]
ip:port/admin

**Comment by token0** [comment]
switched to development branches of core and web,
opened pi.hole:port/admin
tried to restart dns
```Error
There was a problem applying your settings.
Debugging information:
PHP error (2): Cannot modify header information - headers already sent by (output started at /var/www/html/admin/scripts/pi-hole/php/header_authenticated.php:159) in /var/www/html/admin/scripts/pi-hole/php/func.php:670
```
![image](https://user-images.githubusercontent.com/4627595/189872822-6f78c246-05e3-48b8-8a7d-69c6612d762d.png)

**Comment by token0** [comment]
Clients page working via pi.hole:port/admin/groups-clients.php

**Comment by yubiuser** [comment]
Please run `pihole -up` to update your installation (assuming you still use the development branches). We merged https://github.com/pi-hole/AdminLTE/pull/2351 which should address at least some of the issues you reported.

**Comment by token0** [comment]
@yubiuser, it's fixed now, thanks!
