### ISSUE TITLE
API does not return all command outputs.

### ISSUE THREAD

**Issue by FinlandApollo** [pi-hole/web#2359]
### Versions
- Pi-hole:  5.12.1
- AdminLTE:  5.15
- FTL:  5.18

- OS and version:  Ubuntu Server 20.04 (ARM64)
- Platform:  Raspberry Pi 4 (Docker)

### Expected behavior
API call with multiple options (summaryRaw, topItems, getQueryTypes) reports all the ones in the JSON with correct keys.

### Actual behavior / bug
API call returns the getAllQueries, ignoring all others commands.

### Steps to reproduce
http://**IP:PORT**/admin/api.php?from=1663399858&until=1663399917&auth=**YOURAUTHCODE**&rawSummary&getQueryTypes&getAllQueries
http://**IP:PORT**/admin/api.php?from=1663399858&until=1663399917&auth=**YOURAUTHCODE**&rawSummary&getQueryTypes&getAllQueries&topItems=25

## Debug Token

- URL:  https://tricorder.pi-hole.net/XQcRTG7l/

**Comment by rdwebdesign** [comment]
I only read your issue and didn't test it, but I spotted an error: 
There is no `rawSummary` response. It's `summaryRaw`.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/blob/4d12ee7f9a5a1353e4a1d6ea21bd4d535ff88715/api_FTL.php#L335

I guess it's because we create the `json` for `getAllQueries` "by hand" since https://github.com/pi-hole/AdminLTE/pull/2114

**Comment by FinlandApollo** [comment]
> I only read your issue and didn't test it, but I spotted an error: There is no `rawSummary` response. It's `summaryRaw`.

Good note, I accidentally wrote it wrong, but even replacing it correctly, doesn't work. Thanks for the note!

**Comment by rdwebdesign** [comment]
You can't request other values and `getAllQueries` together.
`getAllQueries` must be in a separate request.

**Comment by FinlandApollo** [comment]
> You can't request other values and `getAllQueries` together. `getAllQueries` must be in a separate request.

I would have preferred that this was notified clearly in the update logs when this was changed, because previously this has worked. But good to know, time to work out with my data collector to understand the new way.

**Comment by rdwebdesign** [comment]
This is not a recent change.

This was changed a in Feb/2022, by https://github.com/pi-hole/AdminLTE/pull/2114
