### ISSUE TITLE
[Tracking] `taillog.php` can't auto refresh during log rotation

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/web#2362]
### Actual behavior / bug

According to this post:
https://discourse.pi-hole.net/t/how-to-prevent-admin-taillog-php-from-stopping-auto-refresh-at-midnight/57979
`taillog.php` stops auto refreshing at midnight.

This happens when the pi-hole logs are rotated (cron job running at midnight).

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/releases/tag/v5.17
