### ISSUE TITLE
Update Available shows even for latest version

### ISSUE THREAD

**Issue by Riveloper** [pi-hole/web#2365]
### Versions

Pi-hole version is v5.12.2 (Latest: v5.12.2)
  AdminLTE version is v5.14.2-24-g4d5a37a8 (Latest: v5.15.1)
  FTL version is v5.18.1 (Latest: v5.18.1) 

### Platform

- OS and version:  

- Platform:  raspberry pi 3b

### Expected behavior

_A clear and concise description of what you expected to happen._

The update available alert is shown for the web interface even after reinstall.

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Visit admin web interface after install, cache clear, cookie clear and reboot

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
> AdminLTE version is **v5.14.2**-24-g4d5a37a8 (Latest: **v5.15.1**)

The information provided by you shows you don't have the latest web interface.

**Comment by TheNec** [comment]
> > AdminLTE version is **v5.14.2**-24-g4d5a37a8 (Latest: **v5.15.1**)
> 
> The information provided by you shows you don't have the latest web interface.

...and if you don't have a good reason for this 'pihole checkout master' should solve your problem :)

**Comment by PromoFaux** [comment]
Closing as this is not a reproducible issue, and OP has not provided a lot of information (namely a debug token) - so it is difficult for us to guess what is happening here.

**Comment by TheNec** [comment]
@PromoFaux Mistakenly answered the wrong issue? :)

**Comment by PromoFaux** [comment]
No, no. Correct issue. There isn't really a lot to go on here, but judging by the version output in the OP, they don't have another branch checked out. 

It's not a bug, else we would have had many many reports of it by now

**Comment by rdwebdesign** [comment]
Also, looking at your version number (v5.14.2-24-g4d5a37a8) it indicates you are using code from [`4d5a37a8` commit](https://github.com/arevindh/AdminLTE/commit/4d5a37a8).

Looks like your are using the Speedtest mod.
If that's the case, please ask for help on the correct repository: https://github.com/arevindh?tab=repositories

**Comment by PromoFaux** [comment]
Ah, good investigation - the debug token would have also told us this immediately!
