### ISSUE TITLE
PHPSESSID contains whitespace

### ISSUE THREAD

**Issue by tarumes** [pi-hole/web#2369]
### Versions

  Pi-hole version is v5.12.2 (Latest: v5.12.2)
  AdminLTE version is v5.15.1 (Latest: v5.15.1)
  FTL version is v5.18.1 (Latest: v5.18.1)

### Platform
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

### Expected behavior
PHPSESSID does not contain aditional whitespaces

### Actual behavior / bug
PHPSESSID contains whitespace

### Steps to reproduce
get PHPSESSID via code

```Go
res, err := http.Get("http://pi.hole")
if err != nil {
	log.Fatal()
}
for _, v2 := range res.Cookies() {
	if v2.Name == "PHPSESSID" {
		fmt.Printf("Site:%s\n%s '%s'\n", v, v2.Name, v2.Value)
	}
}
```
![Screenshot 2022-09-21 152853](https://user-images.githubusercontent.com/4124273/191517759-cd3c79fc-a1d6-4e46-b273-06ddb87c8e05.png)

**Comment by yubiuser** [comment]
Thanks for your report. Did you check you can reliably reproduce it? I just looked at my `PHPSESSID` and it does not contain spaces

**Comment by yubiuser** [comment]
Ok, I see it now. The cookie is correct, but the sent header contains the whitespace.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/pull/2370 Should fix the issue.

You can try it yourself with `pihole checkout web no_space`. To go back on track and before the next update run `pihole checkout web master`

**Comment by tarumes** [comment]
thx yes your PR fix it
