### ISSUE TITLE
Long-Term Data -> Graphics are fading in an disappear

### ISSUE THREAD

**Issue by qupfer** [pi-hole/web#2372]
### Versions
  Pi-hole version is v5.12.2 (Latest: v5.12.2)
  AdminLTE version is v5.15.1 (Latest: v5.15.1)
  FTL version is v5.18.1 (Latest: v5.18.1)

### Platform
- OS and version:  Ubuntu 22.04
- Platform:  LXC on Debian11 (Proxmox)

### Expected behavior

A beautiful graph is visible

### Actual behavior / bug

A beautiful graph is not visible

### Steps to reproduce

1. Go to 'Long-term Data'
2. Click on 'Graphics'
3. Select time range 'today'
4. See error (video added)

## Debug Token

- URL:  https://tricorder.pi-hole.net/G1Ri5hJ7/

### Screenshots

[Bildschirmaufzeichnung vom 23.09.2022, 09:49:03.webm](https://user-images.githubusercontent.com/2614431/191915271-2653092a-318c-41b6-a029-67b2a90e20c8.webm)

### Additional context
* the dashboard graphs are shown correctly
* installed and reinstall with the offical install.sh script on vanilla ubuntu lxc container
* tried firefox and google-chrome
* tried refreshing/deleting cache

Any ideas? 

Kind regards
Henning

**Comment by yubiuser** [comment]
Are there any browser plugins installed? Does the developer console show any errors?

**Comment by qupfer** [comment]
Only bitwarden addon on firefox, none on google-chrome. There are ano errors on the bebug console.
I will try a new reinstall.

**Comment by qupfer** [comment]
I make a full reinstall on ubuntu 22.04, use the install script
``` 
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
``` 
and use for everything the default config.  --> Same Error

I make the same on a debian11. Seems working now.
So it may be releated to a php7/8.1?

Edit: now its gone on my debian11 too.

**Comment by yubiuser** [comment]
I run debian 10 with `php7.3` and do not see this behavior. Still, it looks like a bug

**Comment by qupfer** [comment]
On my yesterday (original) ubuntu box, the "todays" box is now fine, only the yesterday-range disapears.
Maybe a bug in the data-aggregation or scaling....which solved with enough datapoints.

**Comment by yubiuser** [comment]
Interesting, I'll try later with a fresh database.

**Comment by qupfer** [comment]
> Interesting, I'll try later with a fresh database.

What would be great. I uploded pihole-ftl.db (is this the correct db?) there the error occurs for the "yesterday" timerange (22.09.22)
https://nc.caroschaf.de/s/9PdzDWiG8ko3NEY

An other thing, what could be related. As I use a container, there was no correct timezone and locale set (is now).

**Comment by yubiuser** [comment]
I can reproduce it using your database.

**Comment by yubiuser** [comment]
I know under which circumstances it occurs, I can reproduce it locally after modifying my database: It fades out, when there are no blocked queries for the selected time range. I'll see if I can fix this.

**Comment by yubiuser** [comment]
The data actually is still there - you can hover over the diagram and see the tooltip. It also just occurs only if "Use new Bar charts on dashboard" is ticked.

**Comment by rdwebdesign** [comment]
I didn't see the database yet, but looks like something in the data (maybe a corruption or something similar) is causing this behavior in javascript code.

**Comment by qupfer** [comment]
> The data actually is still there

Yes, this make sense as the data is shown during the "fade in" and looks like my expected data.
As you already found out, it seems correlated with "0 blocked queryies" i would assume some "div by zero" exceptions during some scaling/range/average calculations. But I have about 0 knowledge in JS.

**Comment by rdwebdesign** [comment]
I'm testing the graph using your database. I can only reproduce the issue selecting "Yesterday" as time range.

We will keep investigating, but this is just a presentation bug. 
Apparently there is nothing wrong with your data.
You can keep using your pi-hole installation.

**Comment by yubiuser** [comment]
> I can only reproduce the issue selecting "Yesterday" as time range.

Because there are 42 blocked queries "today".
_

> i would assume some "div by zero" exceptions during

I thought the same, however, I could not spot any such division. Additionally, it's strange that the behavior does not occur after switching to the line graphs. And that it's not occurring at the dashboard graph at all (assuming you remove the 42 blocked queries by hand from your database)

**Comment by rdwebdesign** [comment]
The graph is being drawn, but in a weird way.

Looks like there is something wrong with the width and opacity of each bar.
If I select a very small range (using "Custom Range"), I can see the bars are there, but they are very thin and using a very small opacity:

![image](https://user-images.githubusercontent.com/1385443/192040371-f14d3e23-1201-494f-8455-2b5bc97c21ac.png)

**Comment by rdwebdesign** [comment]
@qupfer 

I simplified how the data are prepared before it's sent to the graph.

This version never send zeros for "empty" time-slots and let the javascript plugin handle the "missing" data points.
It looks fixed here using your database.

Can you please try the test branch using **`pihole checkout web fix/db_graph`** to see if this is fixed?

**Note:**
after testing (and before update pi-hole) you can go back to the original code using `pihole checkout web master`.

**Comment by qupfer** [comment]
Seems working for me too. I will let run the pihole until Monday without blocking and verify these timeranges works well too.

Thanks a lot for your quick and professional help 👍

Kind regards 
Henning
