### ISSUE TITLE
Pi-hole admin pages will load in an iFrame, but table data will not (Invalid JSON response)

### ISSUE THREAD

**Issue by bnhf** [pi-hole/web#2377]
### Versions

- Pi-hole:  [v5.12.2]
- AdminLTE:  [v5.18.1]
- FTL:  [v5.15.1]

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi 4B

### Expected behavior

Normal functionality in an Organizr iFrame after commenting out  "X-Frame-Options" => "DENY" in lighttpd.conf on the Pi-hole host machine.

### Actual behavior / bug

Pi-hole AdminLTE pages will load, but table data will not. Also, if a password is enabled, one can never get past the login screen -- the login page just keeps reappearing. With the Pi-hole password disabled, any pages that contain table data generate an error of "DataTables warning: table id=groupsTable - Invalid JSON response.", or similar depending on which DataTable is applicable to a given AdminLTE page.

### Steps to reproduce

1. Go to /etc/lighttpd/lighttpd.conf and comment out "X-Frame-Options" => "DENY" (as shown below), remove Pi-hole password using pihole -a -p

```
# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
    # X-Pi-hole is a response header for debugging using curl -I
    # X-Frame-Options prevents clickjacking attacks and helps ensure your content is not embedded into other sites via < frame >, < iframe > or < object >.
    # X-XSS-Protection sets the configuration for the cross-site scripting filters built into most browsers. This is important because it tells the browser to block the response if a malicious script has been inserted from a user input.
    # X-Content-Type-Options stops a browser from trying to MIME-sniff the content type and forces it to stick with the declared content-type. This is important because the browser will only load external resources if their content-type matches what is expected, and not malicious hidden code.
    # Content-Security-Policy tells the browser where resources are allowed to be loaded and if itâ€™s allowed to parse/run inline styles or Javascript. This is important because it prevents content injection attacks, such as Cross Site Scripting (XSS).
    # X-Permitted-Cross-Domain-Policies is an XML document that grants a web client, such as Adobe Flash Player or Adobe Acrobat (though not necessarily limited to these), permission to handle data across domains.
    # Referrer-Policy allows control/restriction of the amount of information present in the referral header for links away from your pageâ€”the URL path or even if the header is sent at all.
    setenv.add-response-header = (
        "X-Pi-hole" => "The Pi-hole Web interface is working!",
#        "X-Frame-Options" => "DENY",
        "X-XSS-Protection" => "1; mode=block",
        "X-Content-Type-Options" => "nosniff",
        "Content-Security-Policy" => "default-src 'self' 'unsafe-inline';",
        "X-Permitted-Cross-Domain-Policies" => "none",
        "Referrer-Policy" => "same-origin"
```
2. Configure Pi-hole admin pages to load through an Organizr iFrame tab
3. Click on 'Groups'

## Debug Token

- URL:  

https://tricorder.pi-hole.net/1vunSGKM/

### Screenshots

![Screenshot 2022-09-27 082202](https://user-images.githubusercontent.com/41088895/192578214-7cecf826-9f1f-4e72-9250-db924d395646.png)

### Additional context

Organizr is such a great tool for organizing web-based setup pages for applications on one's LAN.  Pi-hole isn't the only application that requires minor tweaks to work in an iFrame, but it would be nice to know what those tweaks are for full Pi-hole admin page functionality. Any help would be greatly appreciated!

**Comment by bnhf** [comment]
This appears to only be an issue when Organizr and Pi-hole are installed on different hosts. When they're on the same host, and particularly if installed in Docker containers, the TableData JSON errors disappear and so does the problem with the perpetual login screen -- so there's no need to disable the password.

This leaves only the need to change the X-Frame-Options in a way that survives updates, which for Docker installations is addressed here:

https://github.com/pi-hole/docker-pi-hole/issues/327

**Comment by rdwebdesign** [comment]
This is a Feature Request.

We receive a high number of requests, but as a free open-source project run by volunteers we have very limited resources.
Please, we ask that you open your Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8).

Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8
