### ISSUE TITLE
Latest v5.15.1 and further 2022-10-10 updates not refreshed in webinterface (version information not in sync)

### ISSUE THREAD

**Issue by bcutter** [pi-hole/web#2396]
### Versions

- Pi-hole version is v5.13 (Latest: v5.13)
- AdminLTE version is v5.16 (Latest: v5.16)
- FTL version is v5.18.2 (Latest: v5.18.2)

### Platform

- OS and version:  Raspberry Pi OS Bullseye

- Platform:  Raspberry Pi

### Expected behavior

After updating with `pihole -up` the new version of all 3 components is updated on all places.

### Actual behavior / bug

The version information is updated correctly here:
- ✔cli (`pihole -v` and `pihole -up`)
- ✔PADD (see screenshot below)

But it isn't here:
- ❌webinterface (see screenshot below)
- ❌Home Assistant by using the official Pi-Hole integration

### Steps to reproduce

1. Update to latest version using `pihole -up`
2. Check version information at various places

### Screenshots

Webinterface
![grafik](https://user-images.githubusercontent.com/13799156/195186215-e5e9c7b0-9268-4bed-8048-d06c67d7407d.png)

PADD
![grafik](https://user-images.githubusercontent.com/13799156/195186470-fa4b8da6-e2ae-4d1d-9c4c-6c1164e54fee.png)

Home Assistant
![grafik](https://user-images.githubusercontent.com/13799156/195186652-9731deb3-ca55-4ee4-8c99-c21168d20e15.png)

### Additional context

- Probably an API issue?
- Did a `pihole restartdns` already.
- Refreshed browser cache, used another browser and machine - same output.

==> Update after looking at the PADD screenshot: various status information is not provided correctly. See the screen telling DNS server is off. At the same time `pihole status` gives

```
  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

Please feel free to move this issue to the right component (GitHub project), maybe it's a core or FTL issue.

**Comment by bcutter** [comment]
After searching the forums a bit deeper:

https://discourse.pi-hole.net/t/pihole-v-says-the-system-is-up-to-date-but-the-web-interface-indicates-updates-needed/58475

**Comment by bcutter** [comment]
After looking at https://discourse.pi-hole.net/t/padd-broken-after-latest-updates/58461 I am pretty sure this is the root cause for the underlying API issue:

https://github.com/pi-hole/FTL/pull/1445

**Comment by yubiuser** [comment]
Workaround is to run `pihole updatechecker`

**Comment by bcutter** [comment]
Fixed (for now) by https://discourse.pi-hole.net/t/pihole-v-says-the-system-is-up-to-date-but-the-web-interface-indicates-updates-needed/58475/5.

Leaving it open and up to devs to close it once the root cause has been fixed.

**Comment by yubiuser** [comment]
PADD issue fixed by https://github.com/pi-hole/PADD/pull/259

**Comment by dschaper** [comment]
A debug log before any changes would have been the best way to help us find if this is a bug or not.

**Comment by bcutter** [comment]
That's too late I guess. But for sure experts can downgrade and provoke the behavior again - or is it an edge case?

Off-topic: I don't like the debug logs as they contain really sensitive information (which takes a lot of time to manually identify and remove them), doesn't matter how few people for how short time have access to it. For example I doubt having my full domains list with all whitelisted and blacklisted domains is necessary for debugging such an issue.

**Comment by dschaper** [comment]
Unable to reproduce. I understand your concern about privacy. We don't have a lot of time to ask questions back and forth so we use the log to assist you. It states pretty clearly in the issue template that we will close issues tickets that omit information we need to debug so I'll close this out and you can use the community support forums to research further.

**Comment by rdwebdesign** [comment]
I understand your privacy concern. I also know users privacy is really respected by devs.

> For example I doubt having my full domains list with all whitelisted and blacklisted domains is necessary for debugging such an issue.

The debug log was designed to show information needed to fix A LOT of different issues.
Of course, not all information would be relevant to every issue, but it is the best way to avoid dozens of questions before we start to understand each user system.

Without it, we can't help as efficiently as we could if we had the log. 

We help users on our free time and we don't have a lot to spare. Feel free to seek help on Discourse Forum.
