### ISSUE TITLE
[Feature/Pre-PR] API - expose edit_group for groups.php?

### ISSUE THREAD

**Issue by NickJLange** [pi-hole/web#2404]
As a *Network  Administrator*, I'm looking to expose additional API Functions to enable more targeted domain blocking via scripts (for example, "Disable  DNS for Laptop from 20:00 - 06:00") for better peace of mind.

Based on the below code snippets, this seems rather straightforward to add. Are there any good reasons to not submit this a PR? Absent any other guidance, my only planned testing would be to manually overlay api.php into my container and then test out with an upstream automation:
https://github.com/5L-Labs/dns_admin

I appreciate any additional guidance.

Based on:

 https://github.com/pi-hole/AdminLTE/blob/c2afe4221ac275a1c082e1d8e14ccbb6113b0e7b/api.php#L112-L126

and

https://github.com/pi-hole/AdminLTE/blob/3f06dd87944b9930585a2c227631f898332e1a68/scripts/pi-hole/php/groups.php#L705-L706

**Comment by rdwebdesign** [comment]
We receive a high number of requests, but as a free open-source project run by volunteers we have very limited resources.
Please, we ask that you open your Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8).

Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8

**Comment by yubiuser** [comment]
As @rdwebdesign pointed out, general ideas and talking about features not implemented yet should happen at our discourse forum. If you want to talk about code, it's best to open a pull request where we and other users can directly see how you want to implement things. It's also enables us to make code suggestions directly where they belong.

**Comment by rdwebdesign** [comment]
If you already have code ready to show, you can open a PR. We will discuss the code here, on Github.

On the other hand, if you like to discuss your ideas before open a PR, create a discussion on our Discourse Forum. We can talk there.
