### ISSUE TITLE
Pi-hole looking for non-existent PHP session directory?

### ISSUE THREAD

**Issue by inflatador** [pi-hole/web#2416]
### Versions
# pihole -v
  Pi-hole version is v5.13 (Latest: v5.13)
  AdminLTE version is -1 (Latest: v5.16)
  FTL version is v5.18.2 (Latest: v5.18.2)

^^ You can ignore the version for AdminLTE above as I've installed AdminLTE-v5.16 manually from its Github release.

### Platform

- OS and version:  Debian 11.5
- Platform:  Raspberry Pi 3 Model B Rev 1.2

### Expected behavior

Web UI works without errors

### Actual behavior / bug

When I click on Local DNS > DNS Records from the Web UI, I get a popup error from Firefox, which says:

`DataTables warning: table id=customDNSTable - Invalid JSON response`

Looking in [the nginx error logs](https://gist.github.com/inflatador/795ab06e38445d87c65744ebdcbbe363), it appears that AdminLTE is trying to use `/var/lib/php/session`, which doesn't exist on my host. After creating this directory, the above error no longer appears.

### Steps to reproduce

When I click on Local DNS > DNS Records from the Web UI, I get a popup error from Firefox, which says:

`DataTables warning: table id=customDNSTable - Invalid JSON response`

## Debug Token

- URL:  https://tricorder.pi-hole.net/TxUFx4Mj/

### Additional context
Using nginx package 1.18.0-6.1+deb11u2

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by inflatador** [comment]
Thanks @dschaper , I created a forum topic [here](https://discourse.pi-hole.net/t/nginx-users-are-you-getting-php-session-errors-with-adminlte-v5-16/58902)
