### ISSUE TITLE
Local DNS Records Domain Names Input Verification Improvement

### ISSUE THREAD

**Issue by x-Felix** [pi-hole/web#2422]
### Versions

- Pi-hole: v5.13
- AdminLTE: v5.16
- FTL: v5.18.2

### Platform

- OS and version: Debian 11
- Platform: Docker

### Expected behavior
On Admin web interface, Local DNS - DNS Records, when entering invalid domain names such as special characters, it should not accept the entry but prompt error message like.

x Error, something went wrong!
Domain must be valid

### Actual behavior / bug
However, when entering underscore in domain name field, the Admin web interface does not prompt error message, but accept the input.
While underscore characters are not permitted in domain names in accordance with RFC 1035. By accepting underscore in domain name field, it will cause http 400 bad request when accessing that domain URL.

### Steps to reproduce

- Go to Local DNS - DNS Records
- Enter a Domain name, like test_123.example.com, IP address: 192.168.1.3
- Click Add.
- The invalid domain name is added to local DNS.
- Use browser to access http://test_123.example.com/admin will return http 400 bad request.

### Additional context
Suggest to add additional input check to ensure only letters, digits and hyphens are allowed in domain name field. Thanks.

**Comment by rdwebdesign** [comment]
All checks are made on this function (pihole core code):

https://github.com/pi-hole/pi-hole/blob/e773e3302ca66a6d918a40c8a8c6282f223d4906/advanced/Scripts/webpage.sh#L620-L628

We probably need to split the function in 2, to check domains and hostnames:
https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it#2183140

**Comment by TheNec** [comment]
The given rules are only valid for hostnames. DNS can and every DNS server should be able to handle any character.

Read: https://www.rfc-editor.org/rfc/rfc2181#section-11
