### ISSUE TITLE
Docker Tag nightly points to a non-existent URL

### ISSUE THREAD

**Issue by pluim003** [pi-hole/web#2426]
### Versions

- Pi-hole:   v5.13-50-ga8b6eb9 (Latest: v5.13
- AdminLTE:   v5.16-32-g8e22142 (Latest: v5.16)
- FTL:  vDev-aa57cee (Latest: v5.18.2)

### Platform

- OS and version: Debian 11  

- Platform:   Raspberry Pi

### Expected behavior

When clicking the link behind Docker Tag I would expect to get to an existent URL.

### Actual behavior / bug

![afbeelding](https://user-images.githubusercontent.com/67138922/201063799-8b164b3b-6ec5-4c86-ae40-43030a1d85bb.png)

But clicking 'nightly' this leads to : https://github.com/pi-hole/docker-pi-hole/releases/nightly which doesn't exist. I can imagine you won't put a nightly release on github. So maybe removing the link in case it's a Nightly?

### Steps to reproduce

1. Go to 'pihole-admin'
2. Click on 'nightly'
3. See error

**Comment by PromoFaux** [comment]
That's not a bad idea. I think probably the same for the `dev` tag, too.

**Comment by pluim003** [comment]
That's fast. I was already looking through the code to see if I could make the changes, but went just out for lunch. :-)

And copied the new update_checker.php in my docker-container and tested it. Can confirm that it works:

![afbeelding](https://user-images.githubusercontent.com/67138922/201078411-86c03617-36f6-48f3-8526-60f8ea513d0e.png)

Thanx Adam.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/releases/tag/v5.17

**Comment by urtabajev** [comment]
As of today nightly dashboard still points to non-existing releases.

<img width="1472" height="472" alt="Image" src="https://github.com/user-attachments/assets/c6f199e5-9d48-4b2f-b49e-d7bb1070a75c" />

**Comment by rdwebdesign** [comment]
The issue was actually fixed only on Pi-hole v5.

At that time, Pi-hole v6 was already in development, but the fix was not ported to `development-v6` branch and no one noticed until now.

I will check this soon.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/web/pull/3718
