### ISSUE TITLE
Wonky Upstream servers donut

### ISSUE THREAD

**Issue by saint-lascivious** [pi-hole/web#2433]
### Versions

- Pi-hole:  5.14.1
- AdminLTE:  5.19.1
- FTL:  5.17

### Platform

- OS and version:  Ubuntu 22.10

- Platform:  Raspberry Pi 3

### Expected behavior

Accurate Upstream servers donut graph representation and tooltip values.

### Actual behavior / bug

Inaccurate Upstream servers donut graph representation or tooltip values.

### Steps to reproduce

In this instance the selected metrics for display in Upstream servers were whittled down to cached and other.

Both values report as 0.1% of total queries, and 45% of queries shown. This should be 50% (Yes?, 0.1 and 0.1 are equal).

The donut displays a (correct?) division of 50%/50%.

## Debug Token

N/A

### Screenshots

![Upstream servers cache tooltip](https://user-images.githubusercontent.com/1484933/202330103-28be63f3-372d-4392-b786-652e167231ab.jpg)

![Upstream servers other tooltip](https://user-images.githubusercontent.com/1484933/202330196-ac63d1c9-0bcc-43d7-ac71-8deb9622b026.jpg)

### Additional context

As seen on [Reddit](https://www.reddit.com/r/pihole/comments/ywdzz9/wonky_upstream_servers_donut/).

**Comment by yubiuser** [comment]
Please try if 

`pihole checkout web doughnut` sovles the issue for you.

You can go back anytime and before the next Pi-hole update with `pihole checkout web master`

**Comment by saint-lascivious** [comment]
Hey sorry about the delay in reply. I didn't get a notification for this for whatever reason, professional/life obligations, time zones, etc.

Looks like I missed the window on the branch, so I switched to devel and we'll see how things go there.

I can't help but wonder if a simpler approach might just be adding another degree of precision after the decimal place, rather than the rounding everywhere.

In a prior incantation of this bug (and the reason I re-checked this behavior in the newest release), was that slices like this with very low values would erroneously show as "0.0" of all queries, N% shown.

![Example Image](https://user-images.githubusercontent.com/1484933/202675939-5c78450a-4938-406e-81d6-cb65f0cd61f5.jpg)

**Comment by yubiuser** [comment]
Thanks for getting back to use. 

> that slices like this with very low values would erroneously show as "0.0" of all queries

This should be fixed in `devel` as well now.

___

> just be adding another degree of precision after the decimal place

This wouldn't solve the problem, it would only shift the issue one position to the right. I also think 0.1% precision is enough for such an application.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/AdminLTE/releases/tag/v5.18
