### ISSUE TITLE
http://xxx/admin/api.php?gravity_last_updated shows empty response

### ISSUE THREAD

**Issue by miloit** [pi-hole/web#2441]
### Versions

- Pi-hole:  vDev (development, v5.14.1-7-g82dfcbcd)
- AdminLTE:  vDev (development, vDev-bfd2c98)
- FTL:  vDev (devel, v5.17-6-gc00d127b)

### Platform

- OS and version:  

- Platform:  raspberry

### Expected behavior

Shows same information like http://pihole.fritz.box/admin/api.php
`
{"domains_being_blocked":14837184,"dns_queries_today":19772,"ads_blocked_today":506,"ads_percentage_today":2.559175,"unique_domains":4883,"queries_forwarded":16956,"queries_cached":16,"clients_ever_seen":3,"unique_clients":3,"dns_queries_all_types":19772,"reply_UNKNOWN":6738,"reply_NODATA":2010,"reply_NXDOMAIN":532,"reply_CNAME":3681,"reply_IP":6303,"reply_DOMAIN":50,"reply_RRNAME":0,"reply_SERVFAIL":275,"reply_REFUSED":40,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":143,"dns_queries_all_replies":19772,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1669264344,"relative":{"days":2,"hours":19,"minutes":19}}}`
### Actual behavior / bug
empty response
_A clear and concise description of what the bug is._

### Steps to reproduce

Just open the api

**Comment by rdwebdesign** [comment]
This is the correct behavior.

There is no `/admin/api.php?gravity_last_updated` endpoint.

The correct is `/admin/api.php?summary` or `/admin/api.php?summaryRaw` (or even `/admin/api.php`).
