### ISSUE TITLE
pihole api.php response is empty

### ISSUE THREAD

**Issue by miloit** [pi-hole/web#2442]
### Versions

- Pi-hole vDev (development, v5.14.1-7-g82dfcbcd)
- FTL vDev (development, vDev-bfd2c98)
- Web Interface vDev (devel, v5.17-6-gc00d127b)

### Platform

- OS and version: raspbian  

- Platform:  Raspberry Pi

### Expected behavior

API response should not be empty with curl -ks "https://your.pihole.address/admin/api.php"

### Actual behavior / bug

API response is empty with curl -ks "https://your.pihole.address/admin/api.php" []

**Comment by yubiuser** [comment]
What did you expect to see? You did not include an API endpoint.

**Comment by miloit** [comment]
> https://your.pihole.address/admin/api.php

Endpoint `?summary` is also empty

in the browser I see a json summary

**Comment by yubiuser** [comment]
Is your web interface password protected?

**Comment by miloit** [comment]
> Is your web interface password protected?

Yes it is

**Comment by yubiuser** [comment]
You need to include the authentication token 

https://discourse.pi-hole.net/t/upcoming-changes-authentication-for-more-api-endpoints-required/59315

**Comment by miloit** [comment]
Thanks :)

**Comment by miloit** [comment]
Solved
