### ISSUE TITLE
Dashboard very slow to load with excessive CPU load

### ISSUE THREAD

**Issue by ozskywalker** [pi-hole/web#2443]
### Versions
- Pi-hole:  5.14.2
- AdminLTE:  5.17
- FTL:  5.19.2

### Platform
- OS and version:  Docker
- Platform:  Ubuntu 20 LTS

### Expected behavior

Dashboard should load in under half a second

### Actual behavior / bug

Dashboard takes a long time to load and sends browser process CPU to 100% trying to render the _Client Activity over last 24 hours_ graph.  Occurs with new & old style.  Resizing the window (dev tools enabled) also triggers the high CPU usage when switching resolution.  Forcing a flush (-f) provides temporary relief.

### Steps to reproduce

1. Configure Pi-Hole for IPv6 resolution
2. Generate 500-1000 queries per hour - 3hrs worth seems to be enough to trigger the problem
3. Load landing page for pi.hole
4. Page rendering should halt when attempting to process Client Activity over last 24 hours
5. Check Dev Tools / Task Manager in Browser to confirm 100% CPU

### Debug Token

- URL:  https://tricorder.pi-hole.net/aX8Ia6Cl/

### Screenshots

![204352789-17ede4da-ea44-4a91-acb2-4984d34a8af1](https://user-images.githubusercontent.com/5518808/204424739-8053103c-d7cc-4d3e-a24e-d61963348544.png)
![204352809-420025b3-bff2-446b-b160-259164e0e859](https://user-images.githubusercontent.com/5518808/204424795-d9331be0-9353-4d5b-9896-75aecdbcbb49.png)
![204352829-5aab7ba1-eabe-4479-b86c-5a723c1bdb82](https://user-images.githubusercontent.com/5518808/204424800-97ae5f05-e6f4-4f79-a121-1ed9318c7902.png)
![204352863-12da16f0-208e-4f2e-bf22-bb3efbcd9273](https://user-images.githubusercontent.com/5518808/204424804-80cd8479-47e8-45ed-bf28-38a386f3fff5.png)

### Additional context

Reason for including IPv6 is it appears Apple devices are aggressive in swapping out their temporary addresses, often, and so memory consumption considerably increases when looking across the Client activity dataset and seeing the # of temp addresses from iOS/iPadOS devices on this home network - so I suspect that the nature of the bug in the front-end is related not just to the # of queries on the network but the # of (perceived) clients as well. (2 dimensions)

**Comment by DL6ER** [comment]
So it appears you have to add a zeroth requirement for reproduction: Have Apple devices (or possibly any other behaving the same). We'll look into improving the situation but I don't think there is much we could do as the performance issues seem to be solely in the chart libraries which are "standard" software we are just using. The only adjustments we can make is the data we get plotted. And here the only thing we can do seems to be artificially limiting the data. Let us think about it. The backend of Pi-hole has absolutely no problem with this.

You should be able to remedy this yourself by disabling using temporary addresses for your local WiFi (I'm just assuming Applie offers this possibility here).

**Comment by ozskywalker** [comment]
Fair statement & can confirm that yes, not only is the backend just fine, but any other page on AdminLTE operates without issue.  For now, I'm bypassing the problem by directly accessing the `/admin/settings.php` page then navigating to where I need to be.  

[FWIW.. believe only way I can disable temporary addresses is to build a DHCPv6 server.. Android & iOS aim for SLAAC as that's the preferred mode]

Happy to assist if there's something I can do or profile from my end, but suspect I won't get free time myself until the holidays.

**Comment by rdwebdesign** [comment]
I never saw this behavior before and currently I'm not using IPv6, so this makes it even harder to replicate.
I have 2 questions, but I'm not sure if this will help us to understand what is happening on your system:

1. If you access the dashboard using the IP (not pi.hole hostname), does this change something?

2. What is the output of `http://pi.hole/admin/api.php?summaryRaw`?

**Comment by ozskywalker** [comment]
1. No change
2. See below.

`{"domains_being_blocked":872362,"dns_queries_today":195076,"ads_blocked_today":9145,"ads_percentage_today":4.687916,"unique_domains":12942,"queries_forwarded":140025,"queries_cached":43933,"clients_ever_seen":5340,"unique_clients":2274,"dns_queries_all_types":195076,"reply_UNKNOWN":9941,"reply_NODATA":55423,"reply_NXDOMAIN":4088,"reply_CNAME":75314,"reply_IP":41246,"reply_DOMAIN":134,"reply_RRNAME":0,"reply_SERVFAIL":8,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":1627,"reply_NONE":0,"reply_BLOB":7295,"dns_queries_all_replies":195076,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1669750547,"relative":{"days":1,"hours":9,"minutes":48}}}`

**Comment by k3it** [comment]
I ran into the slowness as described within 24 hours after enabling ipv6 and with a dozen or so ipv6 clients on the network (some of them are Apple).  the rotating temp ipv6 address is an inherent protocol privacy feature so it may be be counter productive to try to disable it, and I don't necessarily have access to all of these IPv6 devices.   Perhaps add an option to turn off the 24 hour graph?

**Comment by TSTarke** [comment]
Same here!
The interesting twist: This behavior started just 2 or 3 updates ago. Sorry I did not take notes regarding the version it appeared first on my install.)
I had > 1200 "active" clients and dashboard took > 1 Minute to load. After flushing the log I am down to 20 clients (tendency: inclining) and dashboard is displayed in a split second again. After writing this, # of clients is 37.
