### ISSUE TITLE
DNS server is printed using words instead of numbers in dashboard

### ISSUE THREAD

**Issue by adeelurehman** [pi-hole/web#2462]
Just open the admin panel. 

## Debug Token

- URL:  

### Screenshots

![image](https://user-images.githubusercontent.com/22510045/208891512-1a5270e7-584e-4bab-9968-df8660e51864.png)

![image](https://user-images.githubusercontent.com/22510045/208891582-c018e859-c941-4e7f-9bd6-7355dad559a2.png)

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
This is normal. Pi-hole does a PTR query on the upstream DNS server IP to determine the name of the DNS server, and displays that. 

```
root@nanopi:~# dig -x 1.1.1.1

; <<>> DiG 9.11.5-P4-5.1+deb10u8-Debian <<>> -x 1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38556
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;1.1.1.1.in-addr.arpa.          IN      PTR

;; ANSWER SECTION:
1.1.1.1.in-addr.arpa.   1800    IN      PTR     one.one.one.one.
```

Cloudflare responds with the same name for their alternate DNS server:

```
;; ANSWER SECTION:
1.0.0.1.in-addr.arpa.   1800    IN      PTR     one.one.one.one.
```

Edit - if you prefer to see something other than the names provided by Cloudflare, you can map those IP's to your preferred names in a local hosts file on the Pi (/etc/hosts or using Local DNS records in Pi-hole).

```
1.1.1.1  Cloudflare-1
1.0.0.1  Cloudflare-2
```
