### ISSUE TITLE
api.php?summary with , in numbers

### ISSUE THREAD

**Issue by somera** [pi-hole/web#2468]
### Versions

- Pi-hole:  v5.14.2
- AdminLTE:  v5.18
- FTL:  v5.20

### Platform

- OS and version:  Ubuntu 20.04

### Actual behavior / bug

Im using tepegraf and grafana to monitor my Pi-Hole instances.

```
$ curl -s "http://localhost:8093/admin/api.php?summary&auth=xxxx" | jq '.'
{
  "domains_being_blocked": "906,400",
  "dns_queries_today": "76,688",
  "ads_blocked_today": "33,844",
  "ads_percentage_today": "44.1",
  "unique_domains": "4,323",
  "queries_forwarded": "30,667",
  "queries_cached": "11,372",
  "clients_ever_seen": "36",
  "unique_clients": "33",
  "dns_queries_all_types": "76,688",
  "reply_UNKNOWN": "821",
  "reply_NODATA": "16,730",
  "reply_NXDOMAIN": "903",
  "reply_CNAME": "14,352",
  "reply_IP": "42,904",
  "reply_DOMAIN": "437",
  "reply_RRNAME": "0",
  "reply_SERVFAIL": "0",
  "reply_REFUSED": "0",
  "reply_NOTIMP": "0",
  "reply_OTHER": "0",
  "reply_DNSSEC": "0",
  "reply_NONE": "0",
  "reply_BLOB": "541",
  "dns_queries_all_replies": "76,688",
  "privacy_level": "0",
  "status": "enabled",
  "gravity_last_updated": {
    "file_exists": true,
    "absolute": 1671708417,
    "relative": {
      "days": 0,
      "hours": 7,
      "minutes": 38
    }
  }
}
```

But after the update yesterday it's not working. I thing the problem is the , in the numbers:

"906,400"
"76,688"

I'm right?

**Comment by leafonthewind** [comment]
Same pi-hole, AdminLTE, and FTL versions.  

Found a decoding error while debugging the [PiStats app](https://github.com/Bunn/PiStats) for macOS (Bunn/PiStats which relies on Bunn/SwiftHole).

```
▿ DecodingError
  ▿ typeMismatch : 2 elements
    - .0 : Swift.Int
    ▿ .1 : Context
      ▿ codingPath : 1 element
        - 0 : CodingKeys(stringValue: "domains_being_blocked", intValue: nil)
      - debugDescription : "Expected to decode Int but found a string/data instead."
      - underlyingError : nil
```

I have similar API output.  `curl "http://pihole.lan/admin/api.php?summary=&auth=<TOKEN>`

```json
{
  "domains_being_blocked": "182,810",
  "dns_queries_today": "103,651",
  "ads_blocked_today": "7,370",
  "ads_percentage_today": "7.1",
  "unique_domains": "6,262",
  "queries_forwarded": "64,275",
  "queries_cached": "31,583",
  "clients_ever_seen": "44",
  "unique_clients": "42",
  "dns_queries_all_types": "103,651",
  "reply_UNKNOWN": "2,288",
  "reply_NODATA": "21,901",
  "reply_NXDOMAIN": "13,097",
  "reply_CNAME": "27,618",
  "reply_IP": "35,564",
  "reply_DOMAIN": "1,712",
  "reply_RRNAME": "24",
  "reply_SERVFAIL": "8",
  "reply_REFUSED": "0",
  "reply_NOTIMP": "0",
  "reply_OTHER": "0",
  "reply_DNSSEC": "0",
  "reply_NONE": "0",
  "reply_BLOB": "1,439",
  "dns_queries_all_replies": "103,651",
  "privacy_level": "0",
  "status": "enabled",
  "gravity_last_updated": {
    "file_exists": true,
    "absolute": 1671723990,
    "relative": {
      "days": 0,
      "hours": 3,
      "minutes": 36
    }
  }
}
```

Would agree it looks like a change in the API response from `Int`'s to `String`'s is causing some problems.

**Comment by DL6ER** [comment]
It will depend on whatever `telegraf` is able to interpret but I'd suggest using `summaryRaw` instead of `summary` when you want to post-process the data.

**Comment by DL6ER** [comment]
I just checked the API code and there was definitely nothing in the last release (https://github.com/pi-hole/AdminLTE/pull/2463). Furthermore, the last relevant change in the API code is > 10 months in the past. 

e rely on PHP's [`number_format()`](https://www.w3schools.com/php/func_string_number_format.asp) to do the formatting of the numbers, maybe a PHP update changed something. Pinging @rdwebdesign and @yubiuser if they know whether something relevant has been changed.

**Comment by somera** [comment]
This is my config which wasn't changes for ~2 years.

telegraf:

```
# pihile monitoring
[[inputs.exec]]
  commands = ["/usr/local/bin/piholestats.sh"]
  timeout = "5s"
  data_format = "json"
  name_suffix = "_pihole"
```

/usr/local/bin/piholestats.sh:
```
#!/usr/bin/env sh

if [ ! -n "$(which sed)" ]; then echo "sed not installed/does not appear in $PATH"; exit 1; fi
if [ ! -n "$(which curl)" ]; then echo "curl not installed/does not appear in $PATH"; exit 1; fi
if [ ! -n "$(which jq)" ]; then echo "jq not installed/does not appear in $PATH"; exit 1; fi

curl -s "http://localhost:8093/admin/api.php?summary&auth=873bbc145a3d0b9596f06bc7022f80b47e9942f3a24aa8ffca72d66b152d434c" | jq '.' |
        sed 's|"enabled"|1|g' | # changes enabled to 1 and removes quote ["status": "enabled" -> "status": 1]
        sed 's|"disabled"|0|g' |  # changes disabled to zero and removes quote ["status": "disabled" -> "status": 0]
        sed 's|status|enabled|g' | # changes status to enabled to better fit boolean value ["status": "enabled" -> "enabled": 1]
        sed 's|true|1|g' | # changes true to 1 [ "file_exists": true -> "file_exists": 1]
        sed 's|false|0|g' | # changes false to 0 [ "file_exists": false -> "file_exists": 0]
        sed 's|"\([[:digit:]]\+\)"|\1|g' | # removes the quotes around any digits ["hours": "03" -> "hours": 03]
        sed -r 's/[[:space:]]0+([0-9]+)/\1/g'; # removes any leading zeros but only if there's a digit after it ["hours": 03 -> "hours": 3]
```

When I now remove , in numbers with

`sed 's|\([[:digit:]]\+\),\([[:digit:]]\+\)|\1\2|g' | # remove , in numbers`

than it works.

Only the "Ads Percentage" want.

**Comment by rdwebdesign** [comment]
Nothing related to format has change recently, only the authorization.

To make it clear:

`summary` formats the number as a string with grouped thousands.
`summaryRaw` outputs numbers (floats).

**Comment by rdwebdesign** [comment]
Use `summaryRaw`. No need to remove the comma (there is no comma).

**Comment by somera** [comment]
Thx. You added the auth token to the api. And before the update yesterday I used only

`http://localhost:8093/admin/api.php`

Not I added the wrong parameter. With summaryRaw it woks again. Thx.

**Comment by rdwebdesign** [comment]
Because the default API output is `summaryRaw`:

`/api.php` = `/api.php?summaryRaw` = `summaryRaw` (numbers)
 `/api.php?summary` = `summary` (formated strings)

**Comment by somera** [comment]
@rdwebdesign when I call only

```
$ curl -s "http://localhost:8093/admin/api.php?auth=xxxxxxxxxxxxxxxx" | jq '.'
[]
```

than I get nothing back. This was my problem after the update.

**Comment by DL6ER** [comment]
Yes, the `summaryRaw` behavior is only triggered when there are NO arguments. However, `auth=...` is an argument. This may be an unintended regression.

**Comment by rdwebdesign** [comment]
Yes.

the current code has no "default" response.
