### ISSUE TITLE
Pihole API summaryRaw returns nothing

### ISSUE THREAD

**Issue by mxmartins** [pi-hole/web#2470]
### Versions
- Pi-hole:  5.14.2
- AdminLTE:  5.18
- FTL:  5.20

### Platform
- OS and version:  Ubuntu 22.04.1
- Platform:  Synology VM

### Expected behavior

http://localhost/admin/api.php?summaryRaw should return statistical data

### Actual behavior / bug

http://localhost/admin/api.php?summaryRaw returns no data

## Debug Token

- URL:  https://tricorder.pi-hole.net/2LrT2roo/

**Comment by yubiuser** [comment]
Is your web interface password protected?

**Comment by mxmartins** [comment]
> Is your web interface password protected?

Yes, my pihole requires a logon/password to be able to access the localhost/admin page.  Is that what you were looking for?

**Comment by DL6ER** [comment]
See https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/ and the latest release notes https://pi-hole.net/blog/2022/12/21/pi-hole-ftl-v5-20-and-web-v5-18-released/
