### ISSUE TITLE
Diagnosis page - table does not load

### ISSUE THREAD

**Issue by Skinner927** [pi-hole/web#2476]
### Versions
```
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.18 (Latest: v5.18)
  FTL version is v5.20 (Latest: v5.20)
```

### Platform
- OS and version: Ubuntu 22.04
- Platform: Bare-metal x64 machine
- Firefox 108.0.1 Windows

### Expected behavior

Diagnosis shows 2 notifications. I would expect two rows of information.

### Actual behavior / bug

Nothing is shown. Browser console has error: `Uncaught TypeError: data.columns[hiddenCols[key]] is undefined`

![image](https://user-images.githubusercontent.com/1518323/210151935-23b55cea-5be9-462d-93b5-1f93a2b0445b.png)

### Steps to reproduce

1. Click Pi-Hole diagnosis when there are alerts

## Debug Token

- URL:  https://tricorder.pi-hole.net/RRfnjwgk/

### Screenshots
![image](https://user-images.githubusercontent.com/1518323/210151973-f038f2fc-c27c-4274-b5cc-6320f7150cab.png)

**Comment by rdwebdesign** [comment]
Can you try to access the page using a different browser or from a different device (another computer or a phone)? 
Do you see the same problem?

**Comment by PromoFaux** [comment]
From Debug log:

```
*** [ DIAGNOSING ]: Pi-hole diagnosis messages
   count   last timestamp       type                  message                                                       blob1                 blob2                 blob3                 blob4                 blob5               
   ------  -------------------  --------------------  ------------------------------------------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
   1       2022-12-31 17:52:33  ADLIST                https://hosts-file.net/ad_servers.txt                         6                                                                                                           
   1       2022-12-31 17:53:46  ADLIST                https://mirror1.malwaredomains.com/files/justdomains          2                                                                                                           
   1       2022-12-31 17:58:21  DNSMASQ_WARN          no address range available for DHCP request via lo                                                                                                                        
```

@DL6ER , should that `DNSMASQ_WARN` one have something in `blob1`?

**Comment by rdwebdesign** [comment]
No.

`DNSMASQ_WARN` only use the `message` field.
Other items are `NULL`:

https://github.com/pi-hole/FTL/blob/cba74934b439385da354f2319e09ec13eed613bb/src/database/message-table.c#L69-L75

**Comment by futuro** [comment]
I've also experienced this, and opened up the dev console to see what was going on. It looks like [hiddenCols](https://github.com/pi-hole/AdminLTE/blob/126b1484903fc74dfbf26f8988d37725fe49c6ed/scripts/pi-hole/js/messages.js#L265) wants to hide column 10 (index 9), but the `data` array only has up to index 8.

See the attached screenshot for both values.
<img width="191" alt="Screen Shot 2023-01-03 at 11 07 04 AM" src="https://user-images.githubusercontent.com/916769/210406426-ec3e5680-41d0-40a5-b32b-b2f231c4c1b6.png">

Let me know if I can provide any other debugging details!

**Comment by rdwebdesign** [comment]
@futuro 
Can you try to access the page using a different browser or from a different device (another computer or a phone)?

**Comment by rdwebdesign** [comment]
Also, what is the output of `http://pi.hole/admin/api_db.php?messages` _(you need to be logged in)_?

**Comment by Skinner927** [comment]
Seems to work in Chrome. The bug happens in Firefox. Updated original issue with Firefox version.

**Comment by rdwebdesign** [comment]
If this is working on a browser and failing on another, is probably a local (browser) issue.

Please, try to clear the pi-hole `local storage` on your browser (this might be different on other browsers):
- with the Diagnosis page opened, open the browser Web Developers tools (<kbd>CTRL</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) or (<kbd>F12</kbd>);
- select the **"Storage"** tab (called "Application" on some browsers);
- on the left, expand the **"Local storage"** item and select the pi-hole domain or IP;
- right-click the item and select "Delete" or "Clear".

Now try again.

**Comment by Skinner927** [comment]
Oh how embarrassing. I didn't think of local storage. That was the issue. Thank you very much. So sorry to even open this.
