### ISSUE TITLE
Undefined Variable in func.php

### ISSUE THREAD

**Issue by ElectronicsTinkerer** [pi-hole/web#2496]
### Versions

- Pi-hole:  v5.15
- AdminLTE:  v5.18.1
- FTL:  v5.20.1

### Platform

- OS and version:  Debian 11 (Raspberry Pi OS)

- Platform:  Raspberry Pi 4B

### Expected behavior

_The user should be able to open the settings pages in the web admin interface without an error message._

### Actual behavior / bug

_Opening the Web UI and navigating to the settings tab displays a red Error banner at the top of the page._

### Steps to reproduce

1. Log in to the Web UI
2. Click on "Settings" on the right side
3. The error appears on the following page

## Debug Token

- URL:  https://tricorder.pi-hole.net/PBNyhdFq/

### Screenshots

Error message:

![image](https://user-images.githubusercontent.com/44784879/212738419-ffdc68e8-c783-4e7a-8cfc-0832c491e3a9.png)

### Additional context

Webserver: `nginv -v`
`nginx version: nginx/1.18.0`

PHP: `php -v`
```
PHP 8.2.1 (cli) (built: Jan  7 2023 08:34:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies
```

### Proposed Solution

The file `admin/scripts/pi-hole/php/func.php` contains a function to get the current file date:

```php
// Avoid browser caching old versions of a file, using the last modification time
//   Receive the file URL (without "/admin/");
//   Return the string containin URL + "?v=xxx", where xxx is the last modified time of the file.
function fileversion($url)
{
    $filename = $_SERVER['DOCUMENT_ROOT'].'/admin/'.$url;
    if (file_exists($filename)) {
        $ver = filemtime($filename);
    }

    return $url.'?v='.$ver;
}
```

Proposed change: set a default value for the variable `$ver`:

```php
// Avoid browser caching old versions of a file, using the last modification time
//   Receive the file URL (without "/admin/");
//   Return the string containin URL + "?v=xxx", where xxx is the last modified time of the file.
function fileversion($url)
{
    $filename = $_SERVER['DOCUMENT_ROOT'].'/admin/'.$url;
    $ver = 0;  // Default
    if (file_exists($filename)) {
        $ver = filemtime($filename);
    }

    return $url.'?v='.$ver;
}
```

Adding this default value removes the error message.

**Comment by yubiuser** [comment]
`nginx` is not a supported web server. However, this fix is trivial and I created the linked PR.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/AdminLTE/releases/tag/v5.18.2
