### ISSUE TITLE
Redirect/Symbolic Link removed.

### ISSUE THREAD

**Issue by justinmstark** [pi-hole/web#2499]
### Versions

  Pi-hole version is v5.15 (Latest: v5.15)
  AdminLTE version is v5.18.1 (Latest: v5.18.1)
  FTL version is v5.20.1 (Latest: v5.20.1)

### Platform

- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

The index.php page that used to be on the /www root directory has moved to the pihole directory and the symbolic link is not maintained.

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

Basic error - the redirect page is no longer in the root directory.

Cheers,

Justin.

**Comment by yubiuser** [comment]
https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

**Comment by justinmstark** [comment]
Thanks (:
