### ISSUE TITLE
Table border color on the Query log page is excessively white

### ISSUE THREAD

**Issue by Marcoevich** [pi-hole/web#2501]
### Versions
  Pi-hole version is v5.15 (Latest: N/A)
  AdminLTE version is v5.18.1 (Latest: N/A)
  FTL version is v5.20.1 (Latest: N/A)

### Platform
- OS and version:  Raspbian 11 Bullseye
- Platform:  Raspberry Pi 3B

### Expected behavior

I would expect the table border colors to be trimmed down a bit.

### Actual behavior / bug

The table border colors on the query log page seem to be a bit excessive compared to the rest of the pi-hole interface. I think this may be a bug.

![image](https://user-images.githubusercontent.com/1243033/213284701-e33c3a10-5dcb-43c1-a1b9-34eb6da21894.png)

### Steps to reproduce

Upgrade to Pi-hole version v5.15 and AdminLTE version v5.18.1

**Comment by rdwebdesign** [comment]
To tell the truth, the logo colors are strange on your screenshot.

I can't replicate it here:

![image](https://user-images.githubusercontent.com/1385443/213285831-ef6d6a57-2581-4eb3-8c68-ec64854352fa.png)

Did you try another browser?
Also try again after disabling any browser extensions to see if there is something messing with the colors.

**Comment by jfb-pihole** [comment]
I also cannot replicate this - this screenshot is on MacOS Ventura running Safari latest, with the auto theme (light/dark) selected.

<img width="2529" alt="image" src="https://user-images.githubusercontent.com/41806245/213287742-a2980ac0-f0f1-4d71-8a8d-4415d5375c79.png">

**Comment by Marcoevich** [comment]
Edit: Never mind, it was caused by a flag in Chrome called "Auto dark-mode".

Sorry for the noise :) You may close this one

**Comment by SodaWithoutSparkles** [comment]
This could be fixed by #2555.
