### ISSUE TITLE
fileversion function requires default $ver value

### ISSUE THREAD

**Issue by dpopham** [pi-hole/web#2504]
admin/scripts/pi-hole/php/func.php function fileversion($url) requires default value of $ver for when file_exists test fails, otherwise throws exception of undefined parameter.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/pull/2497

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/AdminLTE/releases/tag/v5.18.2
