### ISSUE TITLE
UX: Keep sidebar closed

### ISSUE THREAD

**Issue by webysther** [pi-hole/web#2515]
### Versions

- Pi-hole:  [v5.15.3](https://github.com/pi-hole/pi-hole/releases/v5.15.3)
- AdminLTE:  [v5.18.3](https://github.com/pi-hole/AdminLTE/releases/v5.18.3)
- FTL:  [v5.20.1](https://github.com/pi-hole/FTL/releases/v5.20.1)

### Platform

- OS and version:  [Synology DSM 7.1.1-42962 Update 1](https://www.synology.com/en-global/releaseNote/DSM)

- Platform:  Docker

### Expected behavior

Keep the sidebar closed when navigating between pages.

### Actual behavior / bug

Sidebar opens between pages.

### Steps to reproduce

1. Open any page
2. Close sidebar
3. Click any page
4. Sidebar opens

**Comment by yubiuser** [comment]
I'm not sure if this can be implemented with AdminLTE 2.X. AdminLTE v3 has a nice `enableRemember` option (https://adminlte.io/docs/3.0/javascript/push-menu.html), but v2.x doesn't. I just tried to implement solutions provided here: https://github.com/ColorlibHQ/AdminLTE/issues/1240 but it always opend the sidebar first and collapsed afterwards.

**Comment by rdwebdesign** [comment]
This is possible, but not via Javascript.

Javascript runs AFTER the page was loaded with the sidebar opened.

It will be possible if PHP reads an option and add `sidebar-collapse` class to the `<body>` tag before the page is sent to the browser.

**Comment by yubiuser** [comment]
We discussed internally how this could be implemented and there was no (feasible) way. We could change it to **always** being closed while switching between pages, but this would also include visiting the page for the first time. Also, we think a lot of users won't want their sidebar always closed on page switch so we would need to implement a option for this. As this would be a feature request, we would like to ask you to open a request on https://discourse.pi-hole.net/c/feature-requests/8
If it gathers enough votes, we'll consider implementation.
