### ISSUE TITLE
[WebUI] Wrong CPU temperature on Elkhart Lake devices

### ISSUE THREAD

**Issue by GvY85** [pi-hole/web#2520]
### Versions
- Pi-hole:  5.15.3
- AdminLTE:  5.18.3
- FTL:  5.20.1

### Platform
- OS and version:  Debian 11 with DietPi 
- Platform:  x86_64 Intel Elkhart Lake, J6426 CPU

### Expected behaviour

Correct CPU temp in web interface

### Actual behaviour / bug

Currently the `Temp:` field shows `26.8*C` while running the DietPi command `cpu` shows `33*C`.
It seems reasonable to assume the highest of these is the actual CPU die temperature and the web interface is showing a different temperature sensors value.

## Debug Token

- URL:  https://tricorder.pi-hole.net/isfMrOyE/

### Screenshots

![image](https://user-images.githubusercontent.com/38404393/216763950-7f0fa56c-9f3a-477b-9877-59a9b1425b3e.png)

![image](https://user-images.githubusercontent.com/38404393/216763966-24324121-d88e-4b0d-8c78-4263452d9a4e.png)

Thank you.

**Comment by DL6ER** [comment]
> It seems reasonable to assume the highest of these is the actual CPU die temperature 

No. We have already seen several devices with unconnected chassis sensors reporting almost random temperatures, often in the 80-100°C area where you could also expect a very hot CPU.

My vote is still removing the temperature display and make a high load value (high CPU %) more prominent. This is the cause of issues, the temperature is almost always just an indirect measure of this.

**Comment by jfb-pihole** [comment]
I am in favor of removing the CPU temperature.  I am ambivalent on the load display.  In many cases, the underlying host has recently completed a CPU intensive task such as rebuilding gravity, and it is not abnormal to see higher CPU load during that time.  But, when the dashboard warns the user of this, we frequently get help requests.

Rarely have we seen a performance issue with small and temporary CPU load spikes.

My preference would be not to make the CPU load value more prominent, unless it is clearly excessive and unusually high.

**Comment by DL6ER** [comment]
The load values are 1, 5, and 15 minute averages, respectively. One can say that the system is not able to handle things when the load is larger than the number of cores (rule of thumb). I'd say it's justified to assume Pi-hole operation is degraded when the 15 minutes average exceeds this level as it ultimately means there is too much to be done on this device and every process (including `pihole-FTL`) will be queued for CPU time.

**Comment by yubiuser** [comment]
The temperature info on the dashboard is not updated when the page stays open. Therefore, any comparison needs to be done right after the page loaded initially.

**Comment by GvY85** [comment]
Hi, thanks for the feedback. 

A bit of context: the measurements have been done within a few seconds of each other (ie loading the webpage and using the console at the aproxx same time) and have been done multiple times so I believe different sensor data is being used.

Perhaps @MichaIng can shed some light on the sensor he uses (or give me the command to check myself) and we can compare with Pihole?

Else this becomes a discussion about me not measuring correctly (time between measurements), if you want this in future code anyway, etc etc.

A comparison of code seems the quickest solution to find out who is "right"?

**Comment by MichaIng** [comment]
If available, we read temperatures from the coretemp sysfs API:
```sh
for i in /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input; do echo "$i:"; cat "$i"; done
```
Especially on Intel systems, this is often the only correct source when `/sys/class/{thermal,hwmon}` shows garbage (at least not the CPU cores temperature). I've seen at least quite some libraries, e.g. for Rust, where the coretemp API is not used, an hence wrong results shown. Not sure what the Pi-hole admin interface is using?

I think the CPU temperature can be quite an important stat on systems in unsteady ambient temperature environments or if cooling systems depend on some unsteady temperature sink. And of course it is interesting for new devices where one simply has not tested which temperature is reached in which load scenarios. But it is indeed a pain to reliably determine it. We use some SBC/hardware-depending readout of those sysfs APIs which is more based in empirical results. Quite ugly, but I just looped through some SBCs here and it seems still correct 😄.

**Comment by GvY85** [comment]
In as quick as possible/parallel I get these outputs:

`for i in /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input; do echo "$i:"; cat "$i"; done`
`/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input:`
`29000`
`/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input:`
`26000`
`/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input:`
`26000`
`/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp4_input:`
`27000`
`/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp5_input:`
`27000`

![image](https://user-images.githubusercontent.com/38404393/216820958-48494b58-4938-4224-bf32-de0574a5d7b0.png)

![image](https://user-images.githubusercontent.com/38404393/216820977-86d73088-8bc5-4562-91d8-19ad75aeab26.png)

**Comment by yubiuser** [comment]
Pihole uses

```
    if (file_exists('/sys/class/thermal/thermal_zone0/temp')) {
        $output = rtrim(file_get_contents('/sys/class/thermal/thermal_zone0/temp'));
    } elseif (file_exists('/sys/class/hwmon/hwmon0/temp1_input')) {
        $output = rtrim(file_get_contents('/sys/class/hwmon/hwmon0/temp1_input'));
    } else {
        $output = '';
```

**Comment by MichaIng** [comment]
Adding this coretemp API should be safe and fix the temperature readout on all Intel systems, without breaking it on other systems.

The kernel docs are not sooo helpful: https://www.kernel.org/doc/html/latest/hwmon/coretemp.html

But the source code is: https://github.com/torvalds/linux/blob/fae30e3/drivers/hwmon/coretemp.c#L505-L510
- `/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input` is the package temperatures of all core on that CPU.
- `/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input` is the temperature of core `0` etc.

I guess `hwmon2` would be used when different types of CPU cores are used (although isn't this in a single pack an ARM thing only with big.LITTLE etc?), and probably `coretemp.1` when really multiple CPUs are used? However should be a very rare case, and the first match to the `/sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input` should be fine as package temperature of the first CPU.

Don't ask me why the individual cores have a lower temperature than the pack. Cooling down that much while the command is executing doesn't sound realistic 🤔.

**Comment by DL6ER** [comment]
The currently under-development (v6.0) API of Pi-hole has the endpoint `/api/info/sensors` using the `hwmon` data offered by the Linux kernel. The consumer can then pick the most suitable value for what it wants to display.

For instance, the result on my Pi-hole (running on a very basic barebone with a AMD Ryzen 5 4500 CPU) is:
`curl 127.0.0.1:8080/api/info/sensors | jq`
``` json
{                                                   
  "sensors": [          
    {                    
      "name": "amdgpu",
      "path": "hwmon1",
      "temps": [
        {
          "name": "edge",
          "value": 44, 
          "path": "temp1"
        }
      ]                  
    },                   
    {                    
      "name": "nct6793",
      "path": "hwmon2",
      "temps": [
        {
          "name": "SYSTIN",
          "value": 115,
          "path": "temp1"
        },
        {
          "name": "CPUTIN",
          "value": 49,
          "path": "temp2"
        },
        {
          "name": "AUXTIN0",
          "value": 44,
          "path": "temp3"
        },
        {
          "name": "AUXTIN1",
          "value": 109,
          "path": "temp4"
        },
        {
          "name": "AUXTIN2",
          "value": 107,
          "path": "temp5"
        },
        {
          "name": "AUXTIN3",
          "value": 105,
          "path": "temp6"
        },
        {
          "name": "SMBUSMASTER 0",
          "value": 71.5,
          "path": "temp7"
        }
      ]
    },
    {
      "name": "k10temp",
      "path": "hwmon3",
      "temps": [
        {
          "name": "Tctl",
          "value": 71.25,
          "path": "temp1"
        }
      ]
    }
  ],
  "hot_limit": 60,
  "unit": "C"
}
```

For this device, the `sensors[2]["temps"][0]` is the best CPU temp fit (`name == k10temp`). Running this on an older Intel machine I have here, the best fit was `sensors[0]["temps"][0]` (`name == pch_skylake`). These two are simple and should work on any modern AMD and Intel powered machines. However, things are vastly different on the various flavors for ARM devices out there.

There is no one rule to identify what the correct processor "sum temperature" is - or, at the very least - I don't know such a rule (but I'd like to be told if you know).

**Comment by MichaIng** [comment]
Does `hwmon` data mean those provided in `/sys/class/hwmon`? Because that can be all incorrect on Intel hardware.

As said, if the coretemp API is available, then it is assured (as much as possible 😄) to be correct, and the `temp1_input` is the "package" temperature according to kernel docs, i.e. the best fitting one if you want to show a single value only (instead of one each core). All other APIs can be used by any device, ordered based on whichever device registers its sensor first.

But a selection is nice as well, in case with coretemp values added. One might even want to see some HDD temperature instead of CPU, or something else 😉.

**Comment by DL6ER** [comment]
> Does `hwmon` data mean those provided in `/sys/class/hwmon`?

Yes

> Because that can be all incorrect on Intel hardware.

How so? Following [the `hwmon` documentation](http://blog.foool.net/wp-content/uploads/linuxdocs/hwmon.pdf) it looks to me that each driver should simply register their respective sensors with `hwmon` without any other magic happening. 

When I check this, it does seem to make sense, below are some examples I compiled just now:

AMD Laptop (`AMD Ryzen 7 4800H`)
```
$ ls -l /sys/class/hwmon/
total 0
lrwxrwxrwx 1 root root 0 Jan 21 11:59 hwmon0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ADP0/hwmon0
lrwxrwxrwx 1 root root 0 Jan 21 11:59 hwmon1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:3d/PNP0C09:00/PNP0C0A:00/power_supply/BAT0/hwmon1
lrwxrwxrwx 1 root root 0 Jan 21 12:00 hwmon2 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/nvme/nvme0/hwmon2
lrwxrwxrwx 1 root root 0 Jan 21 12:00 hwmon3 -> ../../devices/pci0000:00/0000:00:18.3/hwmon/hwmon3
```

AMD Pi-hole barebone (`AMD Ryzen 5 4500U`)
```
$ ls -l /sys/class/hwmon/
total 0
lrwxrwxrwx 1 root root 0 Nov 11 16:03 hwmon0 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/hwmon0
lrwxrwxrwx 1 root root 0 Nov 11 16:03 hwmon1 -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.0/hwmon/hwmon1
lrwxrwxrwx 1 root root 0 Nov 11 16:03 hwmon2 -> ../../devices/platform/nct6775.656/hwmon/hwmon2
lrwxrwxrwx 1 root root 0 Nov 11 16:03 hwmon3 -> ../../devices/pci0000:00/0000:00:18.3/hwmon/hwmon3
```

AMD server (`AMD EPYC 7502P 32-Core Processor`)
```
$ ls -l /sys/class/hwmon/
total 0
lrwxrwxrwx 1 root root 0 Okt 14 07:57 hwmon0 -> ../../devices/pci0000:c0/0000:c0:03.4/0000:c5:00.0/hwmon/hwmon0
lrwxrwxrwx 1 root root 0 Okt 16 13:05 hwmon1 -> ../../devices/pci0000:00/0000:00:18.3/hwmon/hwmon1
```

Intel desktop (`Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`)
```
$ ls -l /sys/class/hwmon/
total 0
lrwxrwxrwx 1 root root 0 Okt 21 21:52 hwmon0 -> ../../devices/virtual/thermal/thermal_zone0/hwmon0
lrwxrwxrwx 1 root root 0 Okt 21 21:52 hwmon1 -> ../../devices/platform/coretemp.0/hwmon/hwmon1
```

Intel server (`Intel(R) Xeon(R) W-2245 CPU @ 3.90 GHz`)
```
$ ls -lh /sys/class/hwmon/
total 0
lrwxrwxrwx 1 root root 0 Feb  7 19:24 hwmon0 -> ../../devices/platform/eeepc-wmi/hwmon/hwmon0
lrwxrwxrwx 1 root root 0 Feb  7 19:24 hwmon1 -> ../../devices/platform/coretemp.0/hwmon/hwmon1
```

You see my variety in Intel devices is severely limited but the two I have access to do include the `coretemp.0` sensors in `/sys/class/hwmon`. That is the reason why I chose to not add `coretemp.X` separately. The information would simply be duplicated.

Do you have output from a system where this is not the case?

**Comment by MichaIng** [comment]
Probably you are right that all coretemp sensors are below `/sys/class/hwmon` as well. The only benefit of using coretemp then would be that you know that it is CPU core/package temperatures, if wanted even which core's temperature exactly.

But with a manual selection it doesn't make sense then to add it.

**Comment by DL6ER** [comment]
We always try to be as good as possible so I just pushed a small addition that also adds the symlink targets to ease picking the "correct" (read as: most appropriate) device/sensor. The new output looks like this:

``` json
{                                                   
  "sensors": [                                      
    {                                               
      "name": "amdgpu",                             
      "path": "hwmon1",                             
      "source": "devices/pci0000:00/0000:00:08.1/0000:05:00.0",                                          
      "temps": [                                    
        {                                           
          "name": "edge",                           
          "value": 39,                              
          "max": null,                              
          "crit": null,                             
          "sensor": "temp1"                         
        }                                           
      ]                                             
    },                                              
    {                                               
      "name": "nct6793",                            
      "path": "hwmon2",                             
      "source": "devices/platform/nct6775.656",                                                          
      "temps": [                                    
        {                                           
          "name": "SYSTIN",                         
          "value": 115.5,                                                                                
          "max": null,                              
          "crit": null,                             
          "sensor": "temp1"                         
        },                                          
        {                                           
          "name": "CPUTIN",                         
          "value": 42.5,                            
          "max": 80,                                
          "crit": null,                             
          "sensor": "temp2"                         
        },                                          
        {                                           
          "name": "AUXTIN0", 
          "value": 42,
          "max": 0,
          "crit": null,
          "sensor": "temp3"
        },
        {
          "name": "AUXTIN1",
          "value": 109,
          "max": null,
          "crit": null,
          "sensor": "temp4"
        },
        {
          "name": "AUXTIN2",
          "value": 108,
          "max": null,
          "crit": null,
          "sensor": "temp5"
        },
        {
          "name": "AUXTIN3",
          "value": 106,
          "max": null,
          "crit": null,
          "sensor": "temp6"
        },
        {
          "name": "SMBUSMASTER 0",
          "value": 45,
          "max": null,
          "crit": null,
          "sensor": "temp7"
        }
      ]
    },
    {
      "name": "k10temp",
      "path": "hwmon3",
      "source": "devices/pci0000:00/0000:00:18.3",
      "temps": [
        {
          "name": "Tctl",
          "value": 45.5,
          "max": null,
          "crit": null,
          "sensor": "temp1"
        }
      ]
    }
  ],
  "hot_limit": 60,
  "unit": "C"
}
```

or on one of the Intel machines (showing only an excerpt here):

``` json
    {
      "name": "coretemp",
      "path": "hwmon3",
      "source": "devices/platform/coretemp.0",
      "temps": [
        {
          "name": "Package id 0",
          "value": 48.0,
          "max": 100.0,
          "crit": 100.0,
          "sensor": "temp1"
        },
        {
          "name": "Core 0",
          "value": 48.0,
          "max": 100.0,
          "crit": 100.0,
          "sensor": "temp2"
        },
        {
          "name": "Core 1",
          "value": 47.0,
          "max": 100.0,
          "crit": 100.0,
          "sensor": "temp3"
        },
      ]
    }
```

**Comment by MichaIng** [comment]
Nice, with the names `Package id 0`, `Core 0` etc all needed info is there (on Intel platforms) 👍.

**Comment by MichaIng** [comment]
I think this is solved for Pi-hole v6 and nofix for Pi-hole v5, and can hence be closed?
