### ISSUE TITLE
admin/api.php?messages - doens't return RATE_LIMIT ?

### ISSUE THREAD

**Issue by BornToBeRoot** [pi-hole/web#2530]
### Versions
- Pi-hole:  5.14.2
- AdminLTE: 5.17 
- FTL:  5.19.2

### Platform
- Platform:  Docker

### Expected behavior

Get the messages from the pihole diagnostics? Or is this the wrong api?

![image](https://user-images.githubusercontent.com/16019165/218473539-49c8a67d-4cbc-4460-a559-9d4000df91fd.png)

### Actual behavior / bug

I get an empty array: `[]` 

### Steps to reproduce

Query: https://pihole/admin/api.php?messages

if there is a RATE_LIMIT in the diagnostics.

### Additional context

Would be great to troubleshoot problems with Icinga...

**Comment by rdwebdesign** [comment]
There is no `messages` endpoint on `api.php`.

The correct path to retrieve what you want is `/admin/api_db.php?messages`.

**Comment by BornToBeRoot** [comment]
Thanks!
