### ISSUE TITLE
Persistent login not working

### ISSUE THREAD

**Issue by Sonofapo** [pi-hole/web#2539]
### Versions
- Pi-hole:  5.15.5
- AdminLTE:  5.18.4
- FTL:  5.21

### Platform
- OS and version:  Debian 11 64 bit (RaspberryPI OS)
- Platform:  RaspberryPi 400

### Expected behavior
Keep user logged when "Remember me for 7 days" is selected

### Actual behavior / bug
Persistent login not working due to session_save_path() returning empty string

### Steps to reproduce
- Login with your password and persistent login selected
- Close you browser
- Web page asks for login again

## Debug Token

- URL: https://tricorder.pi-hole.net/paGwmi0H/

### Additional context
I run my Pi-hole setup with slight modification:
- I run PHP 8.2.3 and I have modified some funtions (as seen in the debug log) to overcome deprecation errors as well as replacing nulls with false as php doesn't accept nullable values anymore
- I run a custom nginx configuration with the current root directory pointing to  /var/www/html/admin
- Web page is served via HTTPS on port 5380 as I already use port 80 (i access web admin through https://pi.hole:5380)
- lighttpd is not installed (of course)

I found out the issue is cause by session_save_path() returning empty string and thus not passing the check in getPathPersistentLoginToken in persistentlogin_token.php. I temporarily solved this writing the file in /tmp

**Comment by yubiuser** [comment]
We do not modify the `session_save_path() `. What is the corresponding setting in your `php.ini` on my stock `php7.4` it is not set so it defaults to 

```
pi@s740:~$ bat /etc/php/7.4/cgi/php.ini | grep session.save
; http://php.net/session.save-handler
session.save_handler = files
;     session.save_path = "N;/path"
;     session.save_path = "N;MODE;/path"
; http://php.net/session.save-path
;session.save_path = "/var/lib/php/sessions"
;       (see session.save_path above), then garbage collection does *not*
```

Which is what I also see running `phpinfo()`
![Screenshot at 2023-03-03 10-21-26](https://user-images.githubusercontent.com/26622301/222683137-c4cd9e63-824c-4a77-aa86-41b66b106d8f.png)

**Comment by Sonofapo** [comment]
I've compiled myself php from source with a custom configuration without specifying additional ini setting. As my `php.ini` says, `session.save_path` is commented out.

```
sonofapo@HomeServer:~ $ cat /etc/php/lib/php.ini | grep session.save
; https://php.net/session.save-handler
session.save_handler = files
;     session.save_path = "N;/path"
;     session.save_path = "N;MODE;/path"
; https://php.net/session.save-path
;session.save_path = "/tmp"
;       (see session.save_path above), then garbage collection does *not*
```

Indeed my `phpinfo()` defaults to nothing.

![immagine](https://user-images.githubusercontent.com/73821463/222719469-58227ba7-dc3e-43b4-85f2-5c615c8fcfd7.png)

I'm guessing stock php is compiled differently.

<details> 
  <summary>configure script parameters</summary>
--prefix=$DIR
--enable-fpm
--enable-sockets
--enable-mbstring
--with-bz2
--with-zip
--with-zlib
--with-curl
--with-mysqli
--with-openssl
--with-readline
--with-fpm-systemd
--with-fpm-user=www-data
--with-fpm-group=www-data
</details>

**Comment by yubiuser** [comment]
Try to uncomment 

> ;session.save_path = "/tmp"

**Comment by Sonofapo** [comment]
Yes, already uncomment and fixed my issue. Thanks for your help and your time
