### ISSUE TITLE
query log / links for some status entries / cosmetic

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/web#2571]
### Versions
  Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is new/ede-dnssec vDev-8a4488c (Latest: v5.22)

### Platform
raspberry pi 3B, latest raspbian
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

### Expected behavior

Some entries in the status column of the query log have a link that isn't expected.
- status "OK(cache)"
- status "OK(answered ...) where pihole-FTL has been configured to use a different resolver then the default. the default (configured) upstream is unbound.

### Steps to reproduce

cname entry in a dnsmasq config file:
```
cname=dns.msftncsi.com,ncsi.localdomain
```

alternate upstream configuration in a dnsmasq config file
```
server=/raw.githubusercontent.com/127.10.10.5#5555
```

## Debug Token

https://tricorder.pi-hole.net/cgxvkCuN/

### Screenshots

![image](https://user-images.githubusercontent.com/24669386/230709964-48c61aaa-4d1e-4016-b25c-de9af1e07fc7.png)

![image](https://user-images.githubusercontent.com/24669386/230709992-7596ee1d-c637-48b0-b422-3872386d2924.png)

### Additional context

cosmetic, clicking on the link opens domain management page, which might be confusing

**Comment by yubiuser** [comment]
Isn't that expected: https://github.com/pi-hole/AdminLTE/pull/2346

There are entries for both domains in your domainlist.

**Comment by jpgpi250** [comment]
apologies, totally overlooked that, is indeed expected.
