### ISSUE TITLE
[Tracking] Dashboard graphics don't respect MAXLOGAGE limitation.

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/web#2584]
### Actual behavior / bug

There is a small bug in FTL causing the API to return 24h of data even when MAXLOGAGE option is set to a smaller value.
The return has a lot of empty time slots (filled with zeros).

As a side effect, the graphics looks like this:
![image (2)](https://user-images.githubusercontent.com/1385443/234405984-788e8c37-d3d7-447f-bbe4-09856f3d3ff5.png)

### Expected behavior

The graphics should show only time slots between `Now` and  `Now - MAXLOGAGE`.

Expected output:
![image (4)](https://user-images.githubusercontent.com/1385443/234406664-6d26a9f4-f31c-4d11-a810-786c6d9991c5.png)

### Additional Information:

Related Discourse topic:
https://discourse.pi-hole.net/t/option-for-change-time-range-on-the-dashboard/62634/2?u=rdwebdesign

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/releases/tag/v5.20
