### ISSUE TITLE
Output the last lines of the pihole.log file (live) empty

### ISSUE THREAD

**Issue by miloit** [pi-hole/web#2586]
### Versions

- Pi-hole:  v5.16.2
- AdminLTE:  v5.19
- FTL:  v5.22
- 
### Platform

- OS and version:  

- Platform:  raspbian latest

### Expected behavior

Show the tail of pihole.log

### Actual behavior / bug

Don't Show the tail of pihole.log

### Steps to reproduce

1. Go to '[...]admin/taillog.php'
2. See no output

## Debug Token

- URL:  
https://tricorder.pi-hole.net/eBVKnFFF/

**Comment by yubiuser** [comment]
Did you disable logging?

```
* [ DIAGNOSING ]: Pi-hole log
[i] Query logging is disabled
```
