### ISSUE TITLE
Formatting of numbers should be done in the UI, not in the API

### ISSUE THREAD

**Issue by intomotion** [pi-hole/web#2590]
https://github.com/pi-hole/AdminLTE/blob/d7f1842825e33abe098a9383672b63d6d56dfd0f/api_FTL.php#L52

This line  should be altered to:

`$stats[$tmp[0]] = number_format($tmp[1], 0, '', '');`

so that there are no "thousand" separators, formatting of the numbers should be done in the UI instead of the API

**Comment by DL6ER** [comment]
We are close to starting a Pi-hole v6.0 public beta round with an altogether new, fully redesigned and non-PHP REST API. Not doing any formatting on the server is part of the new API.

**Comment by rdwebdesign** [comment]
@intomotion 

There is already an endpoint without format, specially for cases like this.

- If you want an output WITH format, you should use `summary`.
  https://github.com/pi-hole/AdminLTE/blob/d7f1842825e33abe098a9383672b63d6d56dfd0f/api_FTL.php#L49-L55

- If you want an output WITHOUT format, you should use **`summaryRaw`** endpoint:
  https://github.com/pi-hole/AdminLTE/blob/d7f1842825e33abe098a9383672b63d6d56dfd0f/api_FTL.php#L56-L59

**Comment by intomotion** [comment]
> @intomotion
> 
> There is already an endpoint without format, specially for cases like this.
> 
> * If you want an output WITH format, you should use `summary`.
>   https://github.com/pi-hole/AdminLTE/blob/d7f1842825e33abe098a9383672b63d6d56dfd0f/api_FTL.php#L49-L55
> * If you want an output WITHOUT format, you should use **`summaryRaw`** endpoint:
>   https://github.com/pi-hole/AdminLTE/blob/d7f1842825e33abe098a9383672b63d6d56dfd0f/api_FTL.php#L56-L59

Thank you for this information, apparently i have missed this somewhere in the code.

Keep up the good work!
