### ISSUE TITLE
Top Clients (blocked only) shows empty page

### ISSUE THREAD

**Issue by JF62** [pi-hole/web#2596]
### Versions

- Pi-hole:  5.17
- AdminLTE:  5.20
- FTL:  5.23

### Platform

- OS and version:  Debian 11

- Platform:  x86

After Update to actual version, In Dashbord the Top clients (blocked only) shows in overview the numbers, but after clicking on a client for detailed infomation, the list is empty

**Comment by yubiuser** [comment]
Should be fixed by https://github.com/pi-hole/AdminLTE/pull/2597

**Comment by yubiuser** [comment]
Fixed with v5.20.1.
