### ISSUE TITLE
Query Log to analyze between two date times

### ISSUE THREAD

**Issue by renoirb** [pi-hole/web#2602]
### Versions

- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A 

I've noticed the same in every versions since 2021. 

### Platform

- OS and version:  DietPi

- Platform:  Pine64 arm64

### Expected behavior

Question: what is the purpose of the query log? Looking at DNS queries made between two specific date time a use case?  Wanting to see for one specific client, vs rest of network, and flip through many pages, not losing where we are as part of Query Log? (Edit: OR in Long-Term data)

I'm trying to use the query log, and I can't "freeze" the time range I'm interested in.  When I reload or click to copy a domain name, or by accident, I lose the page I was at.  It can quickly be at page 200, and I can't get there directly, and over the minutes the starting time will slide at page 203, and so on.
 
There's also the repetitions. They're valid entries, made at precise moments.  But they contribute to visual noise.

What I would expect:
- Ability to freeze time range. It could be UNIX epoch seconds.
- Ability to keep the URL for this search to get back to it, or tweak it.
- Ability to include/exclude items from domains (ones we're Ok)
- Ability to include/exclude client(s)
- Not lose the page, search criteria
- Ability to refer a few days later on the same search criteria

I'm curious why it isn't like that.  URL Query strings does this since the earliest days.  Date time can be in UNIX epoch, already in UTC, already in memory and in use in computers. <add>Besides, the [data API looks like it is using URL Query parameters](https://github.com/pi-hole/AdminLTE/blob/34e45edb/scripts/pi-hole/js/queries.js#L55-L75) the frontend could mirror this.</add>

Maybe it wasn't though to be done like that for a valid reason, if someone knows why, tell me (please😄)

### Actual behavior / bug

Losing which page in a time range on any click or page refresh (IMHO, that's a bug in my own projects)

Inability to get "frozen" list between two date times.

### Steps to reproduce

1. I've just clicked by mistake on a malicious URL at a specific time (e.g. 2023-05-30 at 20:30:00 In America/New_York).  Many clients on the network using the pi-hole as their DNS
2. It's now few minutes later, I can now open Pi-Hole from a computer, Login;
3. Go to Query Log;
4. Click on All; (wait, yes, using database would be faster than SQLite)
5. Use filter field, enter client DNS name
6. Click "next" until I get to see the date time 20:30:00.  I'm at page 70.
7. see an item, click to copy a suspicious domain name
8. Click again (to remove)
9. I have to repeat

## Debug Token

N/A (at the moment)

### Screenshots

N/A (at the moment)

**Comment by yubiuser** [comment]
Use Long-Term Data > Query Log.

**Comment by renoirb** [comment]
(After looking at the code).  

OK! [Been there done that](https://github.com/pi-hole/AdminLTE/blob/34e45edb/scripts/pi-hole/js/queries.js#L48-L76), this isn't a new code base. I have done this too, more than 16y ago.  I wonder how hard it would be to have the API be mirrored on the UI.  I've used jQuery when it got out up to 2014. I don't miss it. 

I can try to help there.

I guess the js/queries.js is onlh loaded once, and the document.querySelector("all-queries") (writing this from iOS GitHub on top of my head) already is in the DOM. We don't need jQuery on load anymore.  addEventListener on form events and click, history push new location with URL object natively should work well.

Are we still stuck with supporting IE? (What was before MS Edge?)  I'm a recovering veteran of that Epoch.  Please tell me we don't have to.

Or that's the reason it hasn't changed 🫠

**Comment by renoirb** [comment]
Long-Term Data.

Oh.  Yay!  I knew it didn't make sense.

Thanks.

Let's add a link to it?

**Comment by renoirb** [comment]
Oh. Well.  Refreshing we lose where we were.  Search criteria and all are awesome.  But paginating and losing so easily.   I'll try from a desktop computer later and try some more.

That's so strange.  In all my employment, I would make sure this kind of thing never to happen. But I see so many webapps live not caring about that. 

(Ok, there's the "reload data" warning, oof 😅)

**Comment by DL6ER** [comment]
I should mention here that we are getting close to a public Pi-hole v6.0 beta testing phase. For v6.0, the API has been rewritten from scratch in a RESTful way. The (still moving!) API documentation can be found here: https://ftl.pi-hole.net/new/http/docs/#overview

And this is how the new Query Log looks like (with expanded advanced filtering box):

![Screenshot from 2023-05-31 19-31-43](https://github.com/pi-hole/AdminLTE/assets/16748619/e52a0e17-cfd9-4d1c-9974-771c3b04da64)

Also here work-in-progress concerning UI design but it gives an impression of the direction we are currently going.

**Comment by renoirb** [comment]
Oh! I'm going to have a look, I guess it's in this repo, in another branch.

I'll have a look!  KUTGW!

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/tree/devel-v6

**Comment by amec0e** [comment]
Does the new API include a way to exclude showing a particular domain when querying the log? I don't mind that the domain is logged at all but it's frustrating when it's dominating the logs things can slip through the cracks, I was just hoping that this is doable so I can put the noisy devices back on the pihole.

For example events.cid.samba domain with 60k hits in less than 24 hours. When accessing all the logs from time to time the web UI just reloads and takes you back to the login portal, I'm guessing because of the amount of logs it's trying to show?

**Comment by renoirb** [comment]
The main points for such a view is still valid though. Hopefully part in the rework.

- Keep in URL Query the pageSize, pageNumber, search criteria, filtering, date range

Also, just use browser native Location, URL (...) objects. That's what window.location is a Location object, we can mutate history with window.history.  It wasn't possible back in 2014 without hacks.  There's ways to detect form events, push on events  to API.

Date range be as UNIX Epoch, not because of taste, but as it's simplest way to take any date and encode all date and time.  Besides in collaborative apps reporting, team members in different time zones typically wants to see the same events, regardless of the TimeZone it happened.


Which makes me wonder, how do you handle pagination? Both data collection and drawing the UI, client and server side?  I've written this back in 2019, it's in use on all of what I'm describing.  See [paginator on GitLab here](https://gitlab.com/renoirb/renoirb-particles/-/tree/@renoirb/paginator_v0.1.2/packages/paginator?ref_type=tags)  it's all with tests. And [on **NPM**](https://www.npmjs.com/package/@renoirb/paginator)

For handling collection of objects in memory, I've written this helper. It was meant as a Vuex plugin, but you'll notice it isn't using it. You can just use it as it and replace vuex's.  It handles  selecting one item, ~~slicing for a range~~, etc. [see **create-store-view**](https://gitlab.com/renoirb/renoirb-particles/-/blob/@renoirb/state-utils-vue_v0.3.3/packages/state-utils-vue/src/vuex/create-store-view.ts?ref_type=tags)

**Comment by renoirb** [comment]
I'm unsure if any of the listing views will have the essential (i.e. filtering off my chatter) of the reason I've opened an issue:

Ability to have in the URL:

- listing within a time range
- with page size
- which page we are in


So we can:
- Refresh the view and get exactly where we were
- use back and next buttons

For example:
- 2023-06-22T16:51:38 and 2023-06-22T18:12:11 from New-York (expressed as 1687467098  and 1687471931)
- size 200
- page 12

As URL: ‘?begin=1687467098&end=1687471931&size=200&p=12‘


Respectfully, if possible(?) 😊

PS: I can contribute some modules I've published for this kind of need. All as ESM. I'll just have to figure out which repo, branch to look at.

**Comment by Bucking-Horn** [comment]
> As URL: ‘?begin=1687467098&end=1687471931&size=200&p=12‘

While this discussion should target v6, I just add that similar requests (for in-memory data(!)) are already possible in v5, e.g.
http://pi.hole/admin/queries.php?from=1688551200&until=1688551800

(AFAIAAO, requesting pagination and combination of results (e.g. with `&client=192.168.127.20`) via URL is lacking in v5.)

**Comment by renoirb** [comment]
Oh. Neat.  We can add a time range. TIL

Now is "just" the page number and size mirrored from API call and UI.  (They're separated, great, but we're losing this)
