### ISSUE TITLE
"Failed CORS:" even though the VIRTUAL_HOST environment variable is set correctly

### ISSUE THREAD

**Issue by binary-person** [pi-hole/web#2609]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  Ubuntu 20.04.4 LTS

- Platform:  DigitalOcean VPS

### Expected behavior

My current setup is Nginx on port 443, reverse proxy to lighttpd running on 2001.

/etc/lighttpd/external.conf is

```
server.bind = "127.0.0.1"
server.port := 2001
setenv.add-environment = ( "VIRTUAL_HOST" => "mydomain.com" )

$HTTP["host"] == "mydomain.com" {
  # Ensure the Pi-hole Block Page knows that this is not a blocked domain
  setenv.add-environment = ("fqdn" => "true")
}
```

The expected behavior is I should be able to save pihole settings without throwing a CORS error, when accessing it on mydomain.com through nginx.

### Actual behavior / bug

When I try to save any settings, I am greeted with

```
Failed CORS: mydomain.com vs 127.0.0.1, 127.0.0.1, pi.hole, localhost, mydomain.com, mydomain.com
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/T4hBEtPf/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I found that the problem happens right in `/var/www/html/admin/scripts/pi-hole/php/auth.php` under `// Allow user set virtual hostnames`.

The issue is even though I set `setenv.add-environment = ( "VIRTUAL_HOST" => "mydomain.com" )` in `/etc/lighttpd/external.conf`, `getenv('VIRTUAL_HOST')` is somehow `mydomain.com, mydomain.com`.

To see this in action, if I edit the file to print the virtual_host variable,
```
    // Allow user set virtual hostnames
    $virtual_host = getenv('VIRTUAL_HOST');
    if (!empty($virtual_host)) {
        array_push($AUTHORIZED_HOSTNAMES, $virtual_host);

pi_log(join('|',$AUTHORIZED_HOSTNAMES));
pi_log(getenv('VIRTUAL_HOST'));
pi_log($_SERVER['VIRTUAL_HOST']);

    }
```

`/var/log/error-pihole.log` reads
```
2023-06-11 19:55:01: 127.0.0.1|127.0.0.1|pi.hole|localhost|mydomain.com, mydomain.com
2023-06-11 19:55:01: mydomain.com, mydomain.com
2023-06-11 19:55:01: mydomain.com, mydomain.com
2023-06-11 19:55:01: Failed CORS: mydomain.com vs 127.0.0.1, 127.0.0.1, pi.hole, localhost, mydomain.com, mydomain.com
```

**Comment by rdwebdesign** [comment]
I don't think the problem is in `auth.php`.

I think the value is already set when the Pi-hole web interface reads the variable.

To make sure, please create a new file with this command:
```console
echo '<?php phpinfo(); ?>' > /var/www/html/admin/info.php
```
And access the file on the browser: http://pi.hole/admin/info.php

Search for the **Environment** section.
It should look like this:
![image](https://github.com/pi-hole/AdminLTE/assets/1385443/cecfd190-ec83-47d9-8e9f-4f27720e6595)

What are the values for `CORS_HOSTS` and `VIRTUAL_HOST`?

Also, right below you will find the **PHP Variables** section. Do you see `$_SERVER['CORS_HOSTS']` or `$_SERVER['VIRTUAL_HOST']`?

**Comment by binary-person** [comment]
`CORS_HOST` doesn't exist. Value of `VIRTUAL_HOST` is still `mydomain.com, mydomain.com`
![image](https://github.com/pi-hole/AdminLTE/assets/16139772/6e984405-fa06-4db4-b789-f3b44730ea7b)

To make sure I didn't have any duplicate VIRTUAL_HOST set somewhere, I tried changing

```
setenv.add-environment = ( "VIRTUAL_HOST" => "mydomain.co" )
```

and consequently, the value changed to `mydomain.co, mydomain.co`

**Comment by rdwebdesign** [comment]
OK.
This confirms the PHP page is not changing the value.
This is being set by the web server, but I don't know why it's set twice.

I'm trying to replicate the issue, but I wasn't able so far:
Some attempts setting the value twice with 2 `setenv.add-environment = ( "VIRTUAL_HOST" => "mydomain.co" )` resulted in invalid config and `lighttpd` doesn't even start.
Using the `:=` operator (`setenv.add-environment := ( "VIRTUAL_HOST" => "mydomain2.co" )`) overwrites the first value. No duplication.

I'm starting to think there is something else setting this value.

What happens when you remove the line from `external.conf`? Only one value? no values?

**Comment by binary-person** [comment]
If I don't set it, it doesn't show up.

For some background, I followed the steps from

https://github.com/pi-hole/pi-hole/issues/2799
https://discourse.pi-hole.net/t/white-listed-site-does-not-open/11517/7?u=mcat12

This is the copy-paste from `external.conf`
```
server.bind = "127.0.0.1"
server.port := 2001
setenv.add-environment = ( "VIRTUAL_HOST" => "mydomain.co" )
```

If it helps, here are also the lighttpd and php versions

```
$ lighttpd -v
lighttpd/1.4.55 (ssl) - a light and fast webserver

$ php --version
PHP 7.4.3-4ubuntu2.18 (cli) (built: Feb 23 2023 12:43:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.18, Copyright (c), by Zend Technologies
```

I've also tried accessing it directly through port 2001 bypassing nginx, and it's still the same issue

**Comment by rdwebdesign** [comment]
Hmmm... that Discourse post is from 2018. Last year, there was a lot of changes in `lighttpd` config.

New fresh installs doesn't use `external.conf` and use a different `lighttpd.conf` file. Older installs will keep the original config. 

Maybe you ended up with a mix of new/old `lighttpd` config files.

What are the contents of your `/etc/lighttpd/conf-enabled/10-fastcgi.conf` and `/etc/lighttpd/conf-enabled/15-fastcgi-php.conf`?

**Comment by binary-person** [comment]
```
$ cat /etc/lighttpd/conf-enabled/10-fastcgi.conf
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules += ( "mod_fastcgi" )
```

```
$ cat /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
# -*- depends: fastcgi -*-
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

## Start an FastCGI server for php (needs the php5-cgi package)
fastcgi.server += ( ".php" => 
        ((
                "bin-path" => "/usr/bin/php-cgi",
                "socket" => "/var/run/lighttpd/php.socket",
                "max-procs" => 1,
                "bin-environment" => ( 
                        "PHP_FCGI_CHILDREN" => "4",
                        "PHP_FCGI_MAX_REQUESTS" => "10000"
                ),
                "bin-copy-environment" => (
                        "PATH", "SHELL", "USER"
                ),
                "broken-scriptfilename" => "enable"
        ))
)
```

thank you for helping me troubleshoot by the way, I really appreciate it 😄

**Comment by rdwebdesign** [comment]
This config is already set in `15-pihole-admin.conf`.

Remove the file `/etc/lighttpd/conf-enabled/15-fastcgi-php.conf` and restart `lighttpd`.

**Comment by binary-person** [comment]
the behavior is still the same. Also, changing it to `setenv.add-environment = ( "testenv" => "foobar134" )` also results in `$_SERVER['TESTENV'] = foobar134, foobar134`

**Comment by binary-person** [comment]
Ah, I found the culprit. Under the file `/etc/lighttpd/conf-available/05-setenv.conf`, if I comment out `server.modules                += ( "mod_setenv" )` so it looks like

```
# /usr/share/doc/lighttpd/setenv.txt.gz

#server.modules                += ( "mod_setenv" )


#setenv.set-request-header = (
#  "My-Custom-Request-Header" => "set/overwrite request header"
#)
```

no more duplicates

**Comment by binary-person** [comment]
Okay, I found the problem. The last time I updated pihole was on April 2021. The problem only occurred after I updated to the newest version. The problem was `lighttpd.conf` was updated to the newest version, but there was still `conf-available/05-setenv.conf` left as a remanent.

```
$ grep -r mod_setenv /etc/lighttpd
/etc/lighttpd/lighttpd.conf:    "mod_setenv",
/etc/lighttpd/conf-available/05-setenv.conf:#server.modules                += ( "mod_setenv" )
```

that was what caused the duplication

**Comment by binary-person** [comment]
Thank you for your help! I'm not sure if anything needs to be done on your end, (maybe update scripts?) so I'm leaving this issue open to you if you think something needs to be done
