### ISSUE TITLE
Web config doesn't accept standard `:` delimiter for port

### ISSUE THREAD

**Issue by poshul** [pi-hole/web#2636]
https://github.com/pi-hole/AdminLTE/blob/c9e170ef5d73d85b3c7efc34634513a5d9d5cca4/settings.php#L748
Use of `#` instead of `:` is documented in the docker instructions but not on the web interface.

**Comment by poshul** [comment]
bumping.

**Comment by yubiuser** [comment]
This is fixed in the v6 web interface already
![Screenshot at 2023-08-15 14-30-54](https://github.com/pi-hole/AdminLTE/assets/26622301/1239b633-4533-42f4-9644-96c4508c2016)

**Comment by yubiuser** [comment]
P.s. The underlying reason for `#` instead of `:` is that the embedded `dnsmasq` uses this syntax for the `server` setting.
https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
