### ISSUE TITLE
V6 - Confusing Settings Level dropdown

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/web#2642]
### Versions

- Pi-hole:  v6
- AdminLTE:  v6 
- FTL:   v6

Duplication of options in settings drop down

![image](https://github.com/pi-hole/AdminLTE/assets/1998970/e52d3526-93a6-4741-9c1a-57dfe373bbff)

Note that there is also an empty option - in my mind it should just be basic, advanced, expert?

One other thing to note is that the save and apply button does not appear until one selects the latter advanced option.

**Comment by rdwebdesign** [comment]
I remember to talk about this with DL6ER, but I think he forgot.
The first 2 items (Blank and first Advanced) shouldn't be there.

**Note:**
I'm thinking about moving this selector to a different place (maybe only display it within the settings pages) but haven't had time to play around with it yet.

**Comment by DL6ER** [comment]
See branch `fix/settings-levels` that fixes the first two extra options in the dropdown. @rdwebdesign feel free to push further commits to optimize things. There is no PR yet.

**Comment by rdwebdesign** [comment]
I added 2 commits to `fix/settings-levels` branch.

The settings dropdown selector was moved from the top bar and page titles were added:

![desktop](https://github.com/pi-hole/AdminLTE/assets/1385443/33660142-8580-4b16-90c8-62cd41d48d43)
*Desktop screen*

![mobile](https://github.com/pi-hole/AdminLTE/assets/1385443/80353e4a-5e60-4f80-9a22-95a51c9b670c)
*Mobile screen*

**Comment by rdwebdesign** [comment]
Fixed by:
https://github.com/pi-hole/web/pull/2720 and https://github.com/pi-hole/web/pull/2740
