### ISSUE TITLE
Development-v6: empty last four blocks of admin page (top client, top domain, ....)

### ISSUE THREAD

**Issue by edgd1er** [pi-hole/web#2650]
https://github.com/pi-hole/AdminLTE/blob/75e9a5921e681fc71dd505ac7606489a035160a8/scripts/pi-hole/js/utils.js#L33

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll , the regex require a global switch.

`return text.replaceAll(/[&<>"']/, function (m) {` should be `return text.replaceAll(/[&<>"']/g, function (m) {`

I'm not a js expert but other "replaceAll" with regex may need the global switch:
```
/var/www/html/admin/scripts/pi-hole/js/settings.js:  var escapedKey = key.replaceAll(/\./, "\\.");
--
/var/www/html/admin/scripts/pi-hole/js/utils.js:  return text.replaceAll(/[&<>"']/g, function (m) {
--
/var/www/html/admin/scripts/pi-hole/js/utils.js:  return text.replaceAll(
/var/www/html/admin/scripts/pi-hole/js/utils.js-    /&(?:amp|lt|gt|quot|#039|Uuml|uuml|Auml|auml|Ouml|ouml|szlig);/,
1
```

**Comment by rdwebdesign** [comment]
Thanks.

We already saw that and we will fix it.

**Comment by rdwebdesign** [comment]
Fixed.
