### ISSUE TITLE
Query Log List eats selections

### ISSUE THREAD

**Issue by Andersama** [pi-hole/web#2662]
### Versions
Presumably any, this has been how the web interface has behaved as long as I remember playing around with pi-hole.

### Platform
Presumably any, I've just swapped between firefox and chrome browsers, the behavior is the same.

### Expected behavior

When click-drag selecting the selected area should remain.

### Actual behavior / bug

After letting go to finalize the selection the query list is updated, discarding the selection.

### Steps to reproduce

1. Go to Query Log
2. Attempt to select anything in the query log, for example a client or status entry

### Additional context

The "bug" is clearly due to processing events to update the query log for filtering. The issue stems from when an entry in the query log is normally clicked the query log gets filtered to show matching entries. This update / filter step is performed even if the filter would not have changed between clicks. The result is that the selection is discarded no matter what.

I suspect (without going into the code), that selection events are not being processed. A simple fix would be to not filter results when a click-drag selection event is in process.

Edit: The relevant area in javascript appears to be here: https://github.com/pi-hole/AdminLTE/blob/41682f17b72d3fb83837a7a08fa68b3e37cd35b7/scripts/pi-hole/js/queries.js#L375

If my guess is correct that the code in this section is jquery, then presumably adding a `.select()` handler will solve the issue.

**Comment by rdwebdesign** [comment]
Did you try to hold the <kbd>CTRL</kbd> key while you click on a table cell?
This will select the content, then you can use <kbd>CTRL</kbd>+<kbd>C</kbd> to copy the selected text.

This is explained below the table.

![image](https://github.com/pi-hole/AdminLTE/assets/1385443/32d8fd6c-b5e0-4116-8773-3efac05fd4d7)

**Comment by Andersama** [comment]
Interesting, well I can assume that's also been there forever. Just going to say, completely unintuitive.

I guess I should add, if you select across columns the selection remains, so there's bizarre inconsistent behavior with selecting in any case.

**Comment by Andersama** [comment]
@rdwebdesign oh, I see you're working on making a new UI, any chance your new UI behaves like this? I'd avoid requiring any additional keys for selecting any text if possible. It's not what anyone would expect. Take me as a perfect example never read the little helper at the bottom, why would I have needed to? Its fairly obvious what happens when you click on a column...it's not so obvious why selections disappear.

**Comment by rdwebdesign** [comment]
> well I can assume that's also been there forever.

This is like that since the filters were simplified (more than 3 years ago). I think it was more complex before that.

> unintuitive

I agree this is not the simpler way to copy text on the table.

> Take me as a perfect example never read the little helper at the bottom, why would I have needed to?

We can try to change some features if you promise you will also change and start to read what we write on the pages (and release notes and docs). :wink:

---

> I see you're working on making a new UI

We are still developing the new version.
The `v6` query log will have some changes on the filtering and probably (I can't promise) it will be easier to select text.

**Comment by Andersama** [comment]
Regardless of whether there was a note, it's not standard behavior for selections to disappear or to need an additional key to avoid what I'm assuming is the click event. Also, in terms of design, that helper section on my screen, well below the first page view. I wouldn't see it unless I scrolled down anyway, at which point I'm already focused on what I'm doing...literally did not notice that piece of text was there for to your point, 3+ years. I'm not going to do much more than the regular user would, and if I a developer myself gets the sense the UI feels buggy...then it probably does for other people too. It sounds like you agree so if you're the one responsible for the new UI I suppose this is a heads up, make sure to handle the select event separate from click events, I'm 99% confident that would take care of it. I haven't touched jQuery I feel like in ages, but I'm pretty confident if a select handler is added, and the event is not allowed to bubble up, this would not happen.

**Comment by Andersama** [comment]
Slowly remembering why I left web development,, .select() I don't believe has anything to do with selecting text. Took me a few minutes, it's definitely doable manually, I'm sure there's something simpler.

Edit: my awful hack solution to this
```html
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
</head>
<body>
<div id="target">Something</div>
<script>
	var test = $( "#target" );
	
	function getSelectedText() {
		if (window.getSelection) {
			return window.getSelection().toString();
		} else if (document.selection) {
			return document.selection.createRange().text;
		}
		return '';
	}
	// just checking between mouse down and up whether the selection text has changed
	let tmp_selection;
	test
	.on( "mousedown", function (event){
		tmp_selection = getSelectedText();
	})
	.on( "click", function( event ) {
		let selected = getSelectedText();
		if (selected != tmp_selection) {
			console.log(selected);
			alert("selected");
		} else {
			alert("clicked");
		}
	});
</script>
</body>
</html>
```

**Comment by yubiuser** [comment]
The reason for introducing a single click for selecting and de-selecting was that it should work on touch devices as well. Selecting should be easy and the default behaviour for a click. We assumed they use filter way more often than they selecting text.

**Comment by Andersama** [comment]
I can understand the ease of use of the filtering being real handy, I'm just trying to work out being able to select from the UI without having the filter handler remove the selection. I didn't provide a video of this, but its clear when you do this the selection's there for a fraction of a second before it gets cleared, so...there's reason in my mind to believe the experience could be completely normal...so long as you can tell whether the user's trying to select text or not.

The give away actually is what @rdwebdesign pointed out to me which was the text at the bottom explaining you could hold a key. I'm vaguely remembering that alt or ctrl specifically change what the operating system sends to the browser, so it's not a click event anymore. There's no code being executed to process a filter and in turn deleting dom elements that are being selected.

And then from reading the code, it just only cares that a click occurred. I suspect that's why dragging across a column works, because a click event has to do with mouse downing and upping on the same dom element.

**Comment by Andersama** [comment]
@rdwebdesign  it really shouldn't require reading a footnote, or anything really to be able to do something extremely common like selecting text. And why would I want to change? If this didn't bother me at least the tiny bit it does, I wouldn't have bothered to point it out, or motivated to figure out if it could be changed. Obviously, had I read the note, I'd have made a PR first and been on my way. It's weird to me that there's a note at all left behind specifically to address exactly this, which is clearly a hack in and of itself to avoid sending a click event.

**Comment by Andersama** [comment]
Here's the thing, this isn't important, this is just weird. It was weird to me 3+ years ago I guess, it was weird to me today. Maybe its less so in native development than in web development, but normally there's a lot more code to sift through to spot weird behavior or a solution to a problem. Sometimes you dig through documentation, sometimes there's actual paper manual. It's strange to have someone point out a note which to me might as well read FIX ME. And then to boot tells me to read more when its buried underneath 1000's of log messages, that's just funny. Obviously, there's no way anyone else would've known that, so fair enough. At least now I understand why it's been this way this entire time, here I thought this is must be insanely frustrating for everyone, if you've gotten used to it or just know, or are using the default UI settings of 10 logs per page, it's probably a bit more obvious. Here I am having 1st time use experiences years after I've installed pihole because of how infrequently I ever would look at the query log.

**Comment by yubiuser** [comment]
Just a note: the upcoming v6 Pi-hole will have a completely resigned query log. The filtering happens via drop-down boxes and text selection is possible as usual by simple click.

![Screenshot at 2023-07-28 10-56-38](https://github.com/pi-hole/AdminLTE/assets/26622301/e4a46ad8-5358-4a44-960a-792dd87d5092)

**Comment by Andersama** [comment]
Yeah I saw the preview image from the other issue so I got the idea. Any clue as to how far off that would be? Because in the meantime this could be a very small edit. I didn't have my phone to test, but I think my hack works on mobile/touch devices.

**Comment by PromoFaux** [comment]
No ETA, but soon, but also not soon.

Certainly before the heat death of the universe. And probably closer to now than that.

We're more or less in a feature freeze on the v5 stuff now, only fixing critical bugs if needed. There is unlikely to be another v5 release with anything new in it - and IMO this probably doesn't count as a critical bug :)

**Comment by Andersama** [comment]
Well, I'd hope there aren't critical bugs in the admin panel, that'd be concerning.

**Comment by PromoFaux** [comment]
We'd hope so too, but security researchers like to try and prove us wrong from time to time

**Comment by Andersama** [comment]
Yeah, and this whole thing isn't nearly as bad as I thought it might be. I did have a sense phones / mobile would be weird because it always is, long presses to get to the copy prompt doesn't end up clearing selections, probably because its an entirely different event from a click, so this strictly is desktop based.
