### ISSUE TITLE
Selecting `Permit all origins` option fails to set configuration properly

### ISSUE THREAD

**Issue by isikkema** [pi-hole/web#2678]
### Versions

- Pi-hole:  v5.17.1
- AdminLTE:  v5.20.1
- FTL:  v5.23

### Platform

- OS and version:  Fedora Server 36

- Platform:  Bare Metal

### Expected behavior

Once the `Permit all origins` option was selected in DNS Interface settings, the proper configurations would be set in both `/etc/pihole/setupVars.conf` and `/etc/dnsmasq.d/01-pihole.conf`

### Actual behavior / bug

The configurations in `/etc/pihole/setupVars.conf` were set correctly.
The configurations in `/etc/dnsmasq.d/01-pihole.conf` were NOT set correctly. Instead, the new configurations were appended to the bottom of the file. This seems to have caused the new configurations to be ignored in favor of the original configurations.

### Steps to reproduce

1. Go to 'Settings'
2. Click on 'DNS'
3. Scroll down to 'Interface settings'
4. Click on 'Permit all origins'
5. Note that the new configuration does not take effect.

## Debug Token

- URL:  https://tricorder.pi-hole.net/6scqzEsG/

### Additional context

I'm running OpenVPN and Pi-hole on the same home server. I ran into this because OpenVPN wasn't able to use Pi-hole, and changing the above setting was having no effect.

Despite the warnings, I manually edited `/etc/dnsmasq.d/01-pihole.conf` to remove the earlier configurations, and that made it work. Note that I generated the debug log after the manual editing.

`/etc/dnsmasq.d/01-pihole.conf` before:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv

log-queries
log-facility=/var/log/pihole/pihole.log

log-async
cache-size=10000
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
local-service
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
interface=eno1
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
local-service
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
except-interface=nonexisting
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
except-interface=nonexisting

```

`/etc/dnsmasq.d/01-pihole.conf` after:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv

log-queries
log-facility=/var/log/pihole/pihole.log

log-async
cache-size=10000
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
except-interface=nonexisting

```

**Comment by yubiuser** [comment]
I tried to replicate your issue, but can't.
Adding duplicated config entries should not happen. We use the functions `removeKey` and  `addOrEditKeyValPair` from `utils.sh` to add or edit settings to config files. 

https://github.com/pi-hole/pi-hole/blob/8495565a6f065f372a8b0c64265ff3cdabe26d4b/advanced/Scripts/webpage.sh#L241-L267

https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/utils.sh

Can you still replicate the issue?

**Comment by isikkema** [comment]
Yes. But after reading the scripts you linked, I realized it's my fault.
I had aliased grep to ripgrep, an alternative I find more usable, but it's not a drop-in replacement so the command running in the script didn't work as expected.

Perhaps you could use an absolute path to the grep binary, but I'd understand if you choose not to support that.

Thanks for your help.

**Comment by yubiuser** [comment]
> Perhaps you could use an absolute path to the grep binary

I don't think we will do that. We support quite a few different OS which my have their binaries in different locations. Adding a check where to find each used binary for all systems seems a bit to much. 

With the upcoming Pi-hole v6 `webpage.sh` will be gone and settings will be set via our new REST API. Hopefully, such issues won't occur again.
