### ISSUE TITLE
ABP-style entry count value incorrect on adlists status dropdown.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/web#2690]
### Versions

- Pi-hole:  v5.17.1
- AdminLTE:  v5.20.1
- FTL:  v5.23

### Platform

- OS and version:  Docker

- Platform:  Docker

### Expected behavior

Status display should accurately reflect the list counts.

### Actual behavior / bug

```plain
  [i] Target: big.oisd.nl
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 249428 ABP-style domains (ignored 0 non-domain entries)
```

![image](https://github.com/pi-hole/AdminLTE/assets/2782850/9bad2878-1234-4a33-a671-7abf6de7aba1)

Number of non-domains is incorrect.

## Debug Token

- URL:  N/A

### Screenshots

See above.

### Additional context

Originally reported at https://www.reddit.com/r/pihole/comments/15wjqmt/comment/jx66xo8/

**Comment by yubiuser** [comment]
This is fixed in v6 

https://github.com/pi-hole/FTL/issues/1573
