### ISSUE TITLE
Tools > Search adlists has not obvious default behaviour when pressing Enter inside textbox

### ISSUE THREAD

**Issue by tobbi** [pi-hole/web#2701]
### Versions

- Pi-hole:  [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1) 
- AdminLTE:  [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1)
- FTL:  [v5.23](https://github.com/pi-hole/FTL/releases/v5.23)

### Platform

- OS and version:  Debian 11

- Platform:  Raspberry Pi

### Expected behavior

The button for the action that gets executed when pressing Enter in the Search Adlists text field is highlighted.

### Actual behavior / bug

When pressing Enter inside the "Domain to look for (example.com or sub.example.com)", it is not clear whether "Search partial match" or "Search exact match" is triggered. From the behaviour, it looks like it's "Search partial match", but this is not clear to the user.

### Steps to reproduce

1. Go to Tools > Search adlists.
2. Click inside the "Domain to look for (example.com or sub.example.com)" textbox and enter a search term.
3. Press Enter

**Comment by tobbi** [comment]
Yo momma is stale!

**Comment by yubiuser** [comment]
You're correct this is a UI bug.

**Comment by tobbi** [comment]
Can this please be reopened?

**Comment by tobbi** [comment]
Is there a way to prevent the bot from marking this as "stale"?

**Comment by DL6ER** [comment]
We could either put the `never-stale` label on it or fix the underlying issue itself :-)

I propose the latter: https://github.com/pi-hole/web/pull/2957
