### ISSUE TITLE
FTL shows offline, although working

### ISSUE THREAD

**Issue by rguca** [pi-hole/web#2719]
### Versions

- Pi-hole:  5.17.1
- AdminLTE:  5.20.1
- FTL:  5.23

### Platform

- OS and version:  Ubuntu 22.04.3 LTS

- Platform:  arm64

### Expected behavior

"FTL Information" is shown in "Settings".

### Actual behavior / bug

"The FTL service is offline!" is shown, although everything is working.

### Explanation

The user `www-data` of the webserver can't see the process of user `pihole`.

### Possible fix

Add `sudo` in https://github.com/pi-hole/AdminLTE/blob/41682f17b72d3fb83837a7a08fa68b3e37cd35b7/scripts/pi-hole/php/func.php#L716
```
function pidofFTL()
{
    return shell_exec('sudo pidof pihole-FTL');
}
```

**Comment by rdwebdesign** [comment]
Can you please provide a Debug Token: 

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Comment by rguca** [comment]
https://tricorder.pi-hole.net/pu53rQNG/
