### ISSUE TITLE
AdminLTE Lastest Version showing Null from pihole -v command

### ISSUE THREAD

**Issue by gelsbern** [pi-hole/web#2732]
### Versions
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: null)
  FTL version is v5.23 (Latest: v5.23)

OS: Debian 11

Platform:  Desktop PCs.

### Expected behavior

When you run pihole -v it should show current version and latest version.   AdminLTE is showing Latest Version Null even after running pihole updatechecker manually

**Comment by PromoFaux** [comment]
This will be fixed by https://github.com/pi-hole/pi-hole/pull/5421 and is an unintended side-effect of https://pi-hole.net/blog/2023/10/06/psa-renaming-the-web-repo/

**Comment by gelsbern** [comment]
Thank you.
