### ISSUE TITLE
Cannot get latest version of AdminLTE

### ISSUE THREAD

**Issue by OPTips** [pi-hole/web#2733]
### Versions
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: null)
  FTL version is v5.23 (Latest: v5.23)

### Platform
- OS and version:  Debian 11/12
- Platform:  Raspberry Pi & Proxmox VM

### Expected behavior

When doing `pihole -v`, I expect to get latest version

### Actual behavior / bug

For AdminLTE, I get a Latest: null

I tried to modify /etc/pihole/versions, but it is back to null when server is restarted

## Debug Token

- URL:  https://tricorder.pi-hole.net/vmoba6VD/

### Screenshots

![image](https://github.com/pi-hole/web/assets/12797666/8b7a6dbb-9038-4290-8e7e-0da518923b91)

**Comment by PromoFaux** [comment]
Can you run `pihole -up` and see if that pulls in the latest code to check this? Should change the `AdminLTE` string in the version output to `web`, too.

**Comment by OPTips** [comment]
I should have been more patient ^^

It works now. When I created the issue, I tried `pihole -up`, but it did nothing. And now I see a new release 3h ago.

Thanks

![image](https://github.com/pi-hole/web/assets/12797666/f29e0592-5cdf-4bf3-b270-66d91bd79641)
