### ISSUE TITLE
Multiple lists separated by a space cannot be added correctly

### ISSUE THREAD

**Issue by LizenzFass78851** [pi-hole/web#2755]
### Versions

  Pi-hole: development-v6 2841a33
  web: development-v6 e3a547d
  FTL: development-v6 vDev-c5067b3

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Docker

### Expected behavior

I wanted to add several blocklists separated by a space.

### Actual behavior / bug

When inserting the data separated by a space, all links are written in one block

And you can't delete it either

### Steps to reproduce

1. I call the pihole via `[ip]:80/admin`
2. I go to the `lists` menu item
3. I remove the default list from stevenblock
4. I insert the block lists all at once in a line separated by spaces (e.g. `myblocks.org/adlist.txt myblocks.org/malware.txt`) instead of inserting each link individually, which is cumbersome with multiple lists.
5. And there comes the error that the pihole doesn't split the links again at the end and then inserts the corresponding ones, but instead inserts them into a data record.
6. and when deleting there is an error message (see second screenshot)

## Debug Token

- URL:  https://tricorder.pi-hole.net/u7YeTCwJ

### Screenshots

when adding: ![Screenshot (96)](https://github.com/pi-hole/web/assets/82592556/a4c50395-7c71-48ef-9d27-eed46cf98e01)
when deleting: ![Screenshot (98)](https://github.com/pi-hole/web/assets/82592556/5a89fb3c-c76d-4de4-8181-ee96fd63568e)

### Additional context

I suspect that the pihole has the links separated by spaces that can actually be inserted all together. While the pihole does not take the links apart again in order to create a data record for each link instead of not taking this into account.
For testing I used the block lists from @RPiList

**Comment by DL6ER** [comment]
This is already known and will be fixed by https://github.com/pi-hole/web/pull/2707 once someone can find the time to review it.
