### ISSUE TITLE
Gravity update from web interface does not show success message

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2758]
This part of the code does not trigger anymore on v6

https://github.com/pi-hole/web/blob/191f89d58e102610fb7e9e5135b3c3d63c0a87ec/scripts/pi-hole/js/gravity.js#L53-L55

**Comment by rdwebdesign** [comment]
We can simply move the `alSuccess.show();` command to the `if (done) {` command:

```diff
              if (done) {
+               alSuccess.show();
-               ta.append("Done.");
                controller.close();
                alInfo.hide();
                $("#gravityBtn").prop("disabled", false);
                return;
              }
```

**Comment by yubiuser** [comment]
However, we are 'done' when no new data is received - but before we had a check if gravity really succeeded (and not just finished).

**Comment by rdwebdesign** [comment]
Then, we need gravity process to send a success message when it's done, in case of success.
Any finish without the success message will be a failure.

**Comment by rdwebdesign** [comment]
Fixed.
