### ISSUE TITLE
Multi delete only deletes first item 

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2760]
Tested on Adlists, but probably also in other places, multi-selecting and deleting only deletes the first item. It also does not reload the table afterwards

**Comment by DL6ER** [comment]
Wasn't this already fixed by https://github.com/pi-hole/web/pull/2751 ?

**Comment by yubiuser** [comment]
Mhh.. let me check

**Comment by yubiuser** [comment]
Ah true. Switching all those branches all the time got me confused

```
nanopi@nanopi:~$ pihole -v
  Pi-hole version is gravity_success_msg v5.17.1-169-g27522fb (Latest: v5.17.2)
  web version is gravity_success_msg v5.19-339-g7c5908fc (Latest: v5.20.2)
  FTL version is tweak/domain_array vDev-bc72fe6 (Latest: v5.23)
  
  ```
  
  It happend when reviewing https://github.com/pi-hole/web/pull/2707 which let me add numerous adlists but is not yet based on latest devleopment and I had to delete them one by one.
