### ISSUE TITLE
Web interface should inform users when settings require FTL restart

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2773]
Various settings require a FTL restart after changes were applied. FTL will immediately restart without prior notification. Currently active sessions will be cleared.

I think there should be a notification (modal?) that a restart will happen after applying changes.

**Comment by DL6ER** [comment]
This does not happen any longer when https://github.com/pi-hole/FTL/pull/1689 is merged and the session restore feature is not intentionally disabled. Do you think this suffices or should we still add some indication anywhere?

**Comment by yubiuser** [comment]
Additionally, mitigated by https://github.com/pi-hole/web/pull/2774

**Comment by yubiuser** [comment]
Various PRs added/read FTL_Restart_Flags fixing this issue.
