### ISSUE TITLE
Settings subitems change depending on setting level

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2775]
The (number of) items of the settings menu change depending on the setting level chosen from within one of the settings subitems. 
I think it's confusing that the items change at all and in particular that to change them one has first go into one of the setting subitems to change the setting level.
Basic
![Screenshot at 2023-10-23 21-42-24](https://github.com/pi-hole/web/assets/26622301/7d50f02b-770d-4504-be21-ede0aa3ec18f)

Advanced
![Screenshot at 2023-10-23 21-42-39](https://github.com/pi-hole/web/assets/26622301/230119f9-52d6-4e46-ad2a-94152f070b1f)

Expert
![Screenshot at 2023-10-23 21-42-56](https://github.com/pi-hole/web/assets/26622301/ef071ec2-024f-428e-ba27-4bc88ac8fabd)

**Comment by DL6ER** [comment]
I disagree with the idea of having all menu items all the time at the cost of empty pages being hidden being them.

Yes, it may be unfortunate that you first have to go into some setting to be able to "unlock" a higher level, however, this was recently changed and maybe the control should be put somewhere else.

Empty menu items seem much less useful than not having them visible to even begin with. In the end we all have to be aware that the settings level is something users will not change on a daily basis (not even monthly).

**Comment by DL6ER** [comment]
My alternative proposal would be to remove the settings level selector from *every* settings page and put it once on one that is visible on every level.

**Comment by rdwebdesign** [comment]
_"Settings subitems change depending on setting level"_ is common in some other systems with multiple access levels (Ex: Wordpress).

I don't like the idea of empty (or almost empty) pages just to always show the same menu items and I don't think we should move some settings to different pages just to adjust the number of menu items.
This will be a nightmare if in the future we decide to add new items and new settings pages.

On the other hand, I don't think we should put the "Settings Level Selector" outside Settings page. 

I have 2 possible solutions:
- we leave the menu as it is. From a user experience point of view, I don't think changing the number of menu items is a real issue. 
- We use the v5 pattern: 
  Only one "Settings" button on the menu and we add tabs or a sub-menu inside Settings page _(I don't think anyone will like this option)_.
  Something like this:
  ![image](https://github.com/pi-hole/web/assets/1385443/3bdd9fc2-11e6-4e44-b8bd-1f65a7b6bc4d)

**Comment by yubiuser** [comment]
> Only one "Settings" button on the menu and we add tabs or a sub-menu inside Settings page (I don't think anyone will like this option).

Actually, I like your mockup.
