### ISSUE TITLE
[6.0] Unable to change "Status" of domain entry

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/web#2814]
### Versions
  Pi-hole version is development-v6 v5.17.1-214-g834e52f (Latest: N/A)
  web version is development-v6 v5.19-445-g1b7666b9 (Latest: v5.20.2)
  FTL version is development-v6 vDev-b192c2b (Latest: v5.23)

### Platform
Raspberry Pi

### Expected behavior
Unable to change "Status" of domain entry. When item is "Enabled" and I click on the toggle, I get a notification that the domain was successfully enabled. I would expect that it is disabled first...

**Comment by DL6ER** [comment]
This is already known and will be fixed once https://github.com/pi-hole/FTL/pull/1735 and https://github.com/pi-hole/web/pull/2808 are reviewed and merged

**Comment by yubiuser** [comment]
Should be fixed as both linked PRs are merged
