### ISSUE TITLE
Layout of privacy options is broken on smaller screens

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2822]
![Screenshot at 2023-11-12 23-02-58](https://github.com/pi-hole/web/assets/26622301/d6b32713-b855-4cd5-8f4b-1cae995cdfff)

The text should be on the same line as the input field.

**Comment by rdwebdesign** [comment]
Not only small screens. It is also broken when using boxed layout:

![image](https://github.com/pi-hole/web/assets/1385443/fa6dc785-6957-4096-935d-43348423c6f2)
