### ISSUE TITLE
Saving settings in `DHCP` removed flag indicators

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2824]
A refresh will re-add them.

![Peek 2023-11-12 23-08](https://github.com/pi-hole/web/assets/26622301/b225649e-c4e7-4d73-abb8-4c409bda47b7)

**Comment by rdwebdesign** [comment]
I see a delay, but the icons are shown after a while.

![save_delay](https://github.com/pi-hole/web/assets/1385443/b4a79868-7678-4a58-a79d-7ffdc3744f1f)

**Comment by yubiuser** [comment]
I can still reproduce it - just no every time. It must be a timing issue  - I'm using a rather slow hardware. I see the page refresh while FTL is still shutting down. When the page refresh triggers API queries while it's already closed the API the info is lost.

**Comment by rdwebdesign** [comment]
Apparently is similar to the delay we have in v5 when FTL is restarted.

In v5 the issue happens in PHP (details [here](https://github.com/pi-hole/web/pull/2511)). 
Maybe we can try to add a delay before the request or resend the API request in case of failure.
