### ISSUE TITLE
Clicking on an upstream server in the 'upstream servers' view on the Dashboard view shows an empty log list

### ISSUE THREAD

**Issue by churchofnoise** [pi-hole/web#2833]
### Versions
PI-Hole Docker development v6, last updated on Nov 14
- Pi-hole:   vDev (development-v6, af9b8df1)
- AdminLTE: vDev (development-v6, e0ca2b2b)  
- FTL:  vDev (development-v6, 6e25f5ce)

### Platform

- OS and version:  Ubuntu LTS 20.04 (modified by Firewalla)

- Platform:  Firewalla Purple

### Expected behavior

When clicking on one of the servers next to the 'Upstream servers' donut graph, I expect to see the queries that were handled by that upstream server

### Actual behavior / bug

No queries are displayed in the query log

However, replacing the 'name' of the upstream server with its IP address fixes it, so I assume it's linked to the recent change that shows the upstream server's name iso its IP address

### Steps to reproduce

1. Go to main dashboard view
2. Click on one of the upstream servers
3. Look at the queries that are displayed
4. See empty list while the donut chart indicates in my case >20% of > 30k queries that passed through that one

## Debug Token

- URL:  don't seem to find the button in the web interface to generate a debug log (not listed under 'tools' it seems), I generated a log using CLI but it doesn't upload and doesn't ask me to upload either

### Screenshots

![image](https://github.com/pi-hole/web/assets/65717719/e5d11053-e838-45ef-836a-ba8d0ec4a242)
![image](https://github.com/pi-hole/web/assets/65717719/abc668a9-eab7-4a79-b2ac-b56c2ce46942)
![image](https://github.com/pi-hole/web/assets/65717719/0be4bd24-00cc-4495-862a-74b91f86429c)

**Comment by yubiuser** [comment]
Bug confirmed. This is likely a regression of https://github.com/pi-hole/web/pull/2827.

**Comment by DL6ER** [comment]
Indeed. I checked the database if we could accept hostnames here as well but we do only store upstream IP addresses so this is not really possible. This issue will instead be fixed by https://github.com/pi-hole/web/pull/2843
