### ISSUE TITLE
Click on query log details causes Uncaught TypeError

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2841]
Steps to reproduce:

- open the Query Log page with the Developer Tools opened (console tab);
- click on any table row (this will open the details row, below the original row).
- now, click on the details row.
- An error will be shown (data is undefined)

**Comment by rdwebdesign** [comment]
As I suspected in the initial report, the issue is happening because the function is trying to show details for every clicked row, including detail rows.

I have a fix.
