### ISSUE TITLE
Group assignment dropdown not always populated

### ISSUE THREAD

**Issue by patrickli** [pi-hole/web#2845]
### Versions

- Pi-hole:  development-v6 af9b8df
- AdminLTE:  development-v6 e0ca2b2
- FTL:  development-v6 vDev-6e25f5c

### Platform

- OS and version:  VyOS

- Platform:  Docker

### Bug

For group management pages with group assignment fields (that's Clients, Domains and Lists pages), sometimes the group assignment dropdown will show no groups, not even the Default group. But refresh it a few times it will be populated with the correct information. Refresh it a few some will cause this to happen again. There is no errors in the browser console.

### Screenshots

https://github.com/pi-hole/web/assets/502326/bb67924d-36f6-449d-ade4-33aed7d7c5db

**Comment by rdwebdesign** [comment]
Do you see the same behavior in other browsers?

Also, which device are you using to host Pi-hole?

**Comment by patrickli** [comment]
Sorry forgot to mention it is on Chrome 118.0.5993.117 in MacOS arm 14.1. I don't use other browsers so can't test.

Pi-hole is running in amd64 container.

**Comment by DL6ER** [comment]
@patrickli The issue should be fixed since yesterday evening (European time).

**Comment by patrickli** [comment]
Seems to be fixed.
