### ISSUE TITLE
Local DNS records and CNAME don't show pagination buttons

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/web#2854]
As per title.

**Comment by rdwebdesign** [comment]
NOTE:

It also doesn't show buttons for bulk deletion:

![image](https://github.com/pi-hole/web/assets/1385443/5b4709a5-1614-4d70-ac1a-bf97568b2ba3)

**Comment by rdwebdesign** [comment]
I also think the columns are too narrow and the side-by-side tables doesn't look good in boxed layout:

![image](https://github.com/pi-hole/web/assets/1385443/490a4728-11bd-4523-abbe-4c07dd641e03)

**Comment by rdwebdesign** [comment]
@yubiuser 

I think most fields are mandatory, but the page is accepting incomplete entries (without domain, IP, target, etc).
![image](https://github.com/pi-hole/web/assets/1385443/7260a06a-16b2-4ca2-8358-a48821c3824e)

**Comment by yubiuser** [comment]
Good catch.
This should be fixed on the FTL side of things (@DL6ER)

**Comment by DL6ER** [comment]
This will be tricky, so far we have relied on `dnsmasq` validating this input. But it seems it gracefully ignores local DNS records which are only partial and also accepts useless combinations like in your screenshot (right side) leading to config options
```
cname=x,
cname=,ffff
```

I think we will have to add some method to attach individual "validators".

**Comment by yubiuser** [comment]
The pagination and the search box don't align well (pagination a bit shorter)

![Screenshot at 2023-11-21 20-51-34](https://github.com/pi-hole/web/assets/26622301/a5aac7fa-8752-4472-86b2-9a76492e1670)

On mobile it looks even worse I think
![Screenshot at 2023-11-21 20-51-18](https://github.com/pi-hole/web/assets/26622301/514d2ac2-d44d-41ed-8111-261399b5cff8)

**Comment by rdwebdesign** [comment]
I will take a look.

Note:
On mobile, this is center aligned and there is nothing we can do because each line has a different width (this is the same in v5).

**Comment by yubiuser** [comment]
Ok.

**Comment by rdwebdesign** [comment]
As I said a few comments above, the columns are too narrow to show the tables.

There is not enough space for both tables, side-by-side:

![no_space](https://github.com/pi-hole/web/assets/1385443/ca0d84ac-e628-4aa8-aff5-87179db5922f)

Even if I change the column grid sizes from (6 - 6) to (5 - 7) there is an overlap:

![no_space2](https://github.com/pi-hole/web/assets/1385443/baa1b610-bee6-48c5-8c06-9f140fa3752e)

I think we need a layout with one table above the other, at least for `layout-boxed` and mid/small screens.

**Comment by DL6ER** [comment]
> I think we will have to add some method to attach individual "validators".

https://github.com/pi-hole/FTL/pull/1773

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/web/pull/2859 and https://github.com/pi-hole/web/pull/2864. Improved by https://github.com/pi-hole/FTL/pull/1773
