### ISSUE TITLE
Swap Forgot password and Login buttons.

### ISSUE THREAD

**Issue by Toontje** [pi-hole/web#289]
![pWfCl7L](https://user-images.githubusercontent.com/4884243/59780879-02801980-92bb-11e9-8dec-b858bb47bb19.jpg)

I think the Login button should be large and the Forgot Password button should be small. After all, you should use the Login button much more than the Forget password button. Hopefully.

**Comment by Mcat12** [comment]
Original report: https://www.reddit.com/r/pihole/comments/c2fmgi

**Comment by Yemono** [comment]
I suggest using this layout (taken from the reddit thread): https://i.imgur.com/TZM6Tpl.jpg

**Comment by rajannpatel** [comment]
i am happy to make the update tonight and submit a pull request for review.

**Comment by Mcat12** [comment]
@rajannpatel Note that this web interface (in this repo) is the upcoming web interface, while the screenshots shown are from the old web interface (https://github.com/pi-hole/AdminLTE).

The old web interface is in maintenance mode, although this change would likely be accepted. Either way, it should be done for the new web interface as well.

**Comment by rajannpatel** [comment]
@Mcat12 no worries; I do see the differences in my local build of the development branch on my up to date fork. I can make the proposed changes on the latest development codebase and submit a PR.

**Comment by rajannpatel** [comment]
I have an open Pull Request here:
https://github.com/pi-hole/web/pull/290

Happy to make modifications based on a Peer Review.
