### ISSUE TITLE
SQL-Error on fresh installation on Raspberry 

### ISSUE THREAD

**Issue by toteph42** [pi-hole/web#2913]
### Versions

- Pi-hole:  v5.17.2
- AdminLTE:  v5.21 
- FTL:  v5.23 

### Platform

- OS and version:  Raspbian GNU/Linux 11 (bullseye)

- Platform:  Pi 4 Model B (8GB RAM)

### Expected behavior

pi-hole is working, dashboard should show graphs

### Actual behavior / bug

dashboard is empty

### Steps to reproduce

1. sudo su
2. curl -sSL https://install.pi-hole.net | bash
3. Open http://raspberry/admin and log in

## Debug Token

- URL:   https://tricorder.pi-hole.net/ys36FICI/

### Screenshots

![grafik](https://github.com/pi-hole/web/assets/2334583/9f7f774e-f1a5-4fad-9103-786c513c6c7b)

### Additional context

Started diagnostics:
![grafik](https://github.com/pi-hole/web/assets/2334583/da150a75-74b6-4ec6-8dea-e9c99a47d11d)

Checked /var/log/apache2/error.log

[Mon Dec 18 00:00:02.540006 2023] [mpm_prefork:notice] [pid 561] AH00163: Apache/2.4.56 (Raspbian) configured -- resuming normal operations
[Mon Dec 18 00:00:02.540159 2023] [core:notice] [pid 561] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 18 10:12:19.475757 2023] [php7:warn] [pid 26535] [client 192.168.10.100:54780] PHP Warning:  Use of undefined constant SQLITE3_OPEN_READONLY - assumed 'SQLITE3_OPEN_READONLY' (this will throw an Error in a future version of PHP) in /var/www/html/admin/scripts/pi-hole/php/database.php on line 57, referer: http://raspberry/admin/login.php
[Mon Dec 18 10:12:19.475933 2023] [php7:error] [pid 26535] [client 192.168.10.100:54780] PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /var/www/html/admin/scripts/pi-hole/php/database.php:42\nStack trace:\n#0 /var/www/html/admin/scripts/pi-hole/php/database.php(60): SQLite3_connect_try()\n#1 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#2 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 42, referer: http://raspberry/admin/login.php

**Comment by toteph42** [comment]
`sudo su`
`apt install sqlite3`
`/etc/init.d/apache2 restart`

solved the problem. May you should add a check for module in your installation script

**Comment by yubiuser** [comment]
Apache is not a supported Webserver.
