### ISSUE TITLE
Web GUI add domain to whitelist / blacklist is added only in default group

### ISSUE THREAD

**Issue by EasyNetDev** [pi-hole/web#2933]
### Versions

- Pi-hole:  v5.17.3
- AdminLTE:  v5.21
- FTL:  v5.24

### Platform

- OS and version:  Debian GNU/Linux 12 (bookworm)

- Platform:  Proxmox VPE Docker

### Expected behavior

When adding a domain in whitelist / blacklist it is automatically added only Default group.

### Actual behavior / bug

I expected to have an option to add automatically or to specify in which group / groups should be added.

### Steps to reproduce

1. Go to 'Queries Log'
2. Select one of the domains.
3. Click on 'Whitelist' or 'Blacklist'
4. Go to 'Domains'
5. Check 'Group assignment'

## Debug Token

- URL:  N/A

### Screenshots

_N/A._

### Additional context

_N/A._

**Comment by yubiuser** [comment]
Only adding to the default group is the expected behaviour. Feature requests should be voted/opened at https://discourse.pi-hole.net/c/feature-requests/8
