### ISSUE TITLE
No log in for a week

### ISSUE THREAD

**Issue by Mister-XY** [pi-hole/web#2940]
### Versions

- Pi-hole:  Version is v5.17.1-269-ge1c41fe4
- AdminLTE:  Version is v5.19-651-g32a1954b
- FTL:  Version is vDev-1218151

### Platform

- OS and version:  DietPi

- Platform:  Raspberry Pi

### Expected behavior
Why is it not possible to log in for a week in Pihole V6 like in V5?
If I close the browser or have been inactive on the dashboard for a while, I have to log in again.
It would be nice if this could work again for a week like in V5.

**Comment by yubiuser** [comment]
You can set the timeout in the config file in `webserver.session.timeout`

**Comment by Mister-XY** [comment]
Thanks, I was able to change it.
Maybe it will be installed correctly and will therefore be easier for others to find.

**Comment by DL6ER** [comment]
Should we somehow highlight how long a session will last? Possibly with a tooltip showing you how to configure the timeout on hover?

Like
![Screenshot from 2024-01-25 20-06-46](https://github.com/pi-hole/web/assets/16748619/30994e90-01cd-4f9f-af29-fcafafc24a23)
but maybe prettier if anyone has a decent idea.

**Comment by yubiuser** [comment]
We once had a count-down timer.

**Comment by DL6ER** [comment]
Removed by @rdwebdesign in https://github.com/pi-hole/web/pull/2298 but this was also in a hidden place

**Comment by rdwebdesign** [comment]
> this was also in a hidden place

That's what I was about to say.

The timer was hidden in the top menu and it was never accurate. The timer never really worked in `index.php` because the page was constantly sending requests to PHP and the timer was constantly reset.
