### ISSUE TITLE
admin/scripts/pi-hole/php/customdns.php and admin/dns_records.php: CORS is something the browser handles, not the server

### ISSUE THREAD

**Issue by voltagex** [pi-hole/web#2944]
The UI does a POST to `admin/scripts/pi-hole/php/customdns.php` and gets back HTML that says `Failed CORS: pihole.my.domain vs my.ip, pi.hole, pi.hole, localhost`

https://github.com/pi-hole/web/blob/be05b0f61d3fcf796dae4cc3f89f8540b2359325/scripts/pi-hole/php/auth.php#L94 caused a tricky to debug error once Pi-Hole was behind a reverse proxy

![image](https://github.com/pi-hole/web/assets/83080728/aecc97aa-786b-492d-b6db-0d1b7459ca0b)

Note that the rest of Pi-Hole worked without any reconfiguration, so if it is a security check

a) It shouldn't say CORS in the message (CORS is a *browser* side check, in conjunction with headers sent by the server)

b) it shouldn't be a single request from a page expecting JSON that suddenly gets HTML

c) The Javascript should have an error handler instead of throwing an alert like that

**Comment by voltagex** [comment]
Setting `Environment="CORS_HOSTS=pihole.my.domain"` in the `[Service]` section of the Pi-Hole unit didn't seem to work.

**Comment by yubiuser** [comment]
Thanks for the report. Please note that this error might be fixed in the upcoming Pi-hole v6 which got rid of php, uses a completely new API and many changes to the web interface.
