### ISSUE TITLE
Clients (over time) Graph Info Box Isn't Visible

### ISSUE THREAD

**Issue by IronWalnut** [pi-hole/web#3]
When mousing over the "Clients (over time)"chart the box that is displayed goes downward rather than up so the box isn't visible. I was able to reproduce this on multiple browsers:

* Google Chrome - Version 63.0.3239.132
* Firefox 52.5.3 (64-bit)
* Microsoft Edge 41.16299.15.0

The "Queries over last 24 hours" chart seems to handle this correctly.

![untitled](https://user-images.githubusercontent.com/12644611/35313245-4a2e6244-008d-11e8-98e1-eada1ccc1ebf.png)

**Comment by Mcat12** [comment]
Issue moved to [pi-hole/AdminLTE #675](https://github.com/pi-hole/AdminLTE/issues/675) via [**ZenHub**](https://www.zenhub.com/)
