### ISSUE TITLE
Mapping 2 MAC addresses to the same IP address not displayed correctly on web

### ISSUE THREAD

**Issue by toffee** [pi-hole/web#3003]
### Versions

- Pi-hole:  [v5.18.2](https://github.com/pi-hole/pi-hole/releases/v5.18.2)
- AdminLTE:  [v5.21](https://github.com/pi-hole/AdminLTE/releases/v5.21)
- FTL:  [v5.25.1](https://github.com/pi-hole/FTL/releases/v5.25.1)

### Platform

- Pi-hole running on Docker [2024.03.2](https://github.com/pi-hole/docker-pi-hole/releases/2024.03.2)

### Expected behavior

MAC addresses (may be at least two) to be displayed correctly in Settings > DHCP > Static DHCP leases configuration table.

### Actual behavior / bug

If you configure a dhcp host for two MAC addresses in 04-pihole-static-dhcp.conf file then the line is not parsed correctly.

### Steps to reproduce

1. Edit 04-pihole-static-dhcp.conf file and in one line configure 2 MAC addressed for the same host like:
```dhcp-host=D4:8X:XX:XX:XX:14,D4:8X:XX:XX:XX:17,192.168.120.60,zigbee-adapter```
2. Restart pi-hole
3. View the changes displayed wrongly into Settings > DHCP > Static DHCP leases configuration table. The second MAC is displayed on IP address column, the IP address is displayed in Hostname column. 

### Screenshots
![image](https://github.com/pi-hole/web/assets/1410861/f029cedc-be7f-4c51-96e2-c44078d197e1)

### Additional info
This feature is supported by [dnsmasq](https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2009q3/003081.html) long time ago

**Comment by DL6ER** [comment]
Thanks for your report, this is already fixed in the v6 beta. There probably won't be another full v5 release.
