### ISSUE TITLE
"Total queries over last 24 hours" empty

### ISSUE THREAD

**Issue by tobbi** [pi-hole/web#3004]
### Versions

- Pi-hole: v5.18.2 
- AdminLTE:  v5.21
- FTL:  v5.25.1

### Platform

- OS and version: Debian 10  

- Platform:  Raspberry Pi 

### Expected behavior

"Total queries over last 24 hours"  is showing live data and updating

### Actual behavior / bug

"Total queries over last 24 hours" is empty and not updating

### Steps to reproduce

1. Go to the pihole admin interface and log in.
2. Select "Dashboard" from the top left.
4. See the total queries bar chart and how it's not updating.

## Debug Token

- URL:  https://tricorder.pi-hole.net/heqBF4C4/

### Screenshots

![Screenshot at Apr 16 17-24-49](https://github.com/pi-hole/web/assets/583169/cddec9f8-5e9c-41d9-b0b7-19836192d6e3)

### Additional context

I posted about this problem here https://discourse.pi-hole.net/t/potential-bug-total-queries-over-last-24-hours-empty/69602 already. I just want to make sure to cross-reference this.

What API is responsible for updating the live data? I can check what the API returns for me then.

**Comment by rdwebdesign** [comment]
> What API is responsible for updating the live data?

More than one:

- Total queries 24h graph: `admin/api.php?overTimeData10mins`;
- Clients over 24h graph: `api.php?overTimeDataClients&getClientNames`;
- Query Types graph (this is working in your screenshot): `api.php?getQueryTypes`;
- Upstream servers graph (also working): `api.php?getForwardDestinations`.

**Comment by tobbi** [comment]
Okay, so I noticed that `admin/api.php?overTimeData10mins` (apparently only executed once when loading) returns 
```json
{"domains_over_time":[],"ads_over_time":[]}
```

Not sure if that is correct.

`api.php?overTimeDataClients&getClientNames` returns
```json
{"clients":[{"name":"fritz.box","ip":"192.168.178.1"},{"name":"localhost","ip":"127.0.0.1"},{"name":"raspberrypi.fritz.box","ip":"192.168.178.23"},{"name":"localhost","ip":"::1"},{"name":"raspberrypi.fritz.box","ip":"<my public v6 IP>"}],"over_time":[]}
```

**Comment by rdwebdesign** [comment]
Please post your answers (including the last one above) in Discourse topic to keep all information in one place.

**Comment by tobbi** [comment]
This issue was resolved after I restarted my Raspberry Pi.
