### ISSUE TITLE
Glow effect in "Total Queries" box result in blurry text.

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/web#3011]
The glow effect (used when the Total Queries value is updated) creates a blurry effect, specially in dark themes.

![glow](https://github.com/pi-hole/web/assets/1385443/f20221a3-9dec-47a1-9947-c9c59bd9e3eb)

This is not very user friendly for users with some kind of visual impairment or anything different than a perfect vision (and almost nobody has perfect vision).

Suggestions:

1. Remove the effect from "High Contrast" and "High Contrast Dark" themes;
2. Change the color effect to some dark color;
3. Replace this effect by some other effect;
4. Remove the effect from every theme;
5. other options?

The issue affects all themes (v5 and v6).

This was reported by an user, on Discourse:
https://discourse.pi-hole.net/t/fuzzy-changes-to-total-queries/69695

**Comment by PromoFaux** [comment]
Following the KISS principle... 

> Remove the effect from every theme;

I would vote this one. It doesn't really add an awful lot

**Comment by rdwebdesign** [comment]
Just to make sure that removing the effect is our best option, I tested using a different effect (changing the color of the text), but it doesn't look good if I use a color that is too contrasting to the original.

This is the result using "White to Black to White":
![white to black](https://github.com/pi-hole/web/assets/1385443/307b61f3-361a-474a-8272-1acc604702c1)

It looks very disturbing, specially considering accessibility.

I will completely remove the glow effect.

**Comment by rdwebdesign** [comment]
Fixed in v6
