### ISSUE TITLE
Universal Time Displayed in Firefox Instead of Local Time

### ISSUE THREAD

**Issue by akumar48** [pi-hole/web#3012]
### Versions

- Pi-hole:  v5.18.2 (Latest: v5.18.2)
- AdminLTE:  v5.21 (Latest: v5.21)
- FTL:  v5.25.1 (Latest: v5.25.1)

### Platform

- OS and version:  Raspbian Bullseye

- Platform:  Raspberry Pi
OS: Raspbian GNU/Linux 11 (bullseye) armv6l
Host: Raspberry Pi Zero W Rev 1.1
Kernel: 6.1.21+
Uptime: 6 days, 11 hours, 40 mins
Packages: 1450 (dpkg)
Shell: bash 5.1.4
Terminal: /dev/pts/0
PU: BCM2835 (1) @ 1.000GHz
Memory: 57MiB / 429MiB

### Expected behavior
I expect when I login to the web portal to see the correct time listed on the graphs and in logs. This means my local time, which is UTC-8. This experience is consistent on Chrome.

### Actual behavior / bug
When I use Firefox, my preferred browser, all logs and graphs are shown using the system universal time, not local time, which leads all times to be 8 hours off.

### Steps to reproduce

1. Open Firefox.
2. Go to 10.0.0.150/admin/login.php (my static ip for the pihole, ymmv)
3. Login using password
4. View Graphs (Wrong Time)
5. Click on Queries Blocked
6. View Logs (Wrong Time)

## Debug Token

- URL:  https://tricorder.pi-hole.net/7ThCEbKO/

### Screenshots
##Firefox:
graphs: ![image](https://github.com/pi-hole/web/assets/10107591/aceffd8a-0645-44f5-a98a-3d200e36b798)
logs: ![image](https://github.com/pi-hole/web/assets/10107591/85be9864-483b-4792-9d1e-c8cae62838fa)

##Chrome:
graphs: ![image](https://github.com/pi-hole/web/assets/10107591/ff417619-797e-47c7-9538-226e13a16070)
logs: ![image](https://github.com/pi-hole/web/assets/10107591/25127487-f148-4a61-88d6-40def317d34f)

**Comment by rdwebdesign** [comment]
Does the issue happens if you disable all Firefox browser extensions/add-ons?

**Comment by DL6ER** [comment]
Also check whether you have some "advanced" tracking protection enabled. This may intentionally conceal the time zone from the website to reduce the potential of "fingerprinting" you.
