### ISSUE TITLE
Disabled Blocking doesn't get resumed after timer expiry.

### ISSUE THREAD

**Issue by ghpk** [pi-hole/web#3026]
### Versions

  -Pi-hole version is v5.18.2 (Latest: v5.18.2)
 -web version is v5.21 (Latest: v5.21)
  -FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- OS and version:  

- Platform:  Raspberry Pi Zero W

### Expected behavior

_A clear and concise description of what you expected to happen._
After disabling blocking for say 60 minutes, although the web interface shows its active, ads keep coming on all connected devices
until I go again and disable blocking and then enable it manually from web interface.

### Actual behavior / bug
Blocking should resume back after timer expiry as its always been in past years.

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to 'web admin page'
2. Click on 'disable blocking'
3. Scroll down to 'for custom time.'
4. after time expires, blocking doesn't gets resumed

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
I tested in my browser and I didn't see the same issue.

I also tested using the command line. I executed the command `watch -d dig flurry.com @<pihole_IP>` in a terminal window and disabled Pi-hole for 15 seconds using the web interface. 

![watch_dig](https://github.com/pi-hole/web/assets/1385443/dc014751-5a11-4eba-aac5-d5b4b1ac9f5d)

The output showed `flurry.com` was allowed during the 15 seconds. 
After the time expired the answer was `0.0.0.0`, meaning the domains was immediately blocked.


Can you please generate a debug log as requested on the template?

**Comment by ghpk** [comment]
Thanks for looking into this,  Can you please also try setting a custom time disable blocking.
It may be possible only custom time may have an issue.


I tried generating debug log,
But after long wait and confirmation to upload it fails to generate.
On my original post, I included that error message.
Will post again in a few hours.

**Comment by ghpk** [comment]
Accidentally closed

**Comment by rdwebdesign** [comment]
> Can you please also try setting a custom time disable blocking.

My test above was made using the **Custom Time** option. I set the timer for 15 seconds.
