### ISSUE TITLE
[development-v6] Top Domains and Top Clients are not hidden when they contain no data

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/web#3068]
was originally opened as pi-hole/pi-hole/issues/5699 in error

### Versions

Core
    Version is v5.18.2-400-g8b324741 (Latest: null)
    Branch is development-v6
    Hash is 8b324741 (Latest: 8b324741)

Web
    Version is v5.19-818-ge852fbb2 (Latest: null)
    Branch is development-v6
    Hash is  e852fbb2  (Latest: e852fbb2 )

FTL
    Version is vDev-5c97d29 (Latest: null)
    Branch is development-v6
    Hash is 5c97d290  (Latest: 5c97d290 )

### Platform

- OS and version:  Ubuntu 24.04 LTS

- Platform:  Raspberry Pi 4 Model B Rev 1.1

### Expected behavior

when privacy mode is set to anything other than `Show Everything`  the last 4 boxes should be hidden when they contain no data.

### Actual behavior / bug

when privacy mode is set to anything other than `Show Everything`  the last 4 boxes show a loading wheel endlessly when they contain no data.

### Steps to reproduce

1. set privacy mode to anything other than `Show Everything`
2. go to the dashboard 
3. Scroll down to the bottom of the dashboard (http://pi.hole/admin/)
4. See boxes with loading wheels, how many depends on privacy mode selection ( as seen in screenshots )

## Debug Token

- URL:  https://tricorder.pi-hole.net/tog4t1Nu/

#### This is when `Anonymous mode` & `Hide domains and clients` is selected 
![Screenshot from 2024-07-07 21-09-56](https://github.com/pi-hole/pi-hole/assets/5729320/3dc965fc-20fb-440c-a97f-924497e5e859) 

#### This is when `Hide domains` is selected 
![Screenshot from 2024-07-07 21-45-52](https://github.com/pi-hole/web/assets/5729320/f45cb8c6-ed22-415b-a129-d0f7298e79fc)

### Additional context

Worth noting is an old issue that's very similar #932 the fix was #966

**Comment by mwoolweaver** [comment]
Worth noting is an old issue that's very similar https://github.com/pi-hole/web/issues/932

**Comment by mwoolweaver** [comment]
it seems the graphs shouldn't be shown when empty if I'm looking at this correctly

https://github.com/pi-hole/web/blob/e852fbb2f513cfdcf76505584068b5940031e066/scripts/pi-hole/js/index.js#L24-L32


https://github.com/pi-hole/web/blob/e852fbb2f513cfdcf76505584068b5940031e066/scripts/pi-hole/js/index.js#L136-L144

**Comment by yubiuser** [comment]
You're correct. (This shows how many of us use anything besides "Show everything").
 
The fix is simple...

**Comment by yubiuser** [comment]
Please try if `pihole checkout web fix/privacy` is fixing the issue for you

**Comment by mwoolweaver** [comment]
shows an empty graph still

![Screenshot from 2024-07-08 13-35-41](https://github.com/pi-hole/web/assets/5729320/246cdebf-716e-49df-8c9f-d216628fa358)

could this be because of 

https://github.com/pi-hole/web/blob/e852fbb2f513cfdcf76505584068b5940031e066/scripts/pi-hole/js/index.js#L295-L298


https://github.com/pi-hole/web/blob/e852fbb2f513cfdcf76505584068b5940031e066/scripts/pi-hole/js/index.js#L352-L355

**Comment by yubiuser** [comment]
Yes. But I think it's fine to show the empty table with "No data".

**Comment by mwoolweaver** [comment]
I'll close this as fixed then since it is working as intended but aesthetically it would look better if hidden when empty.

**Comment by rdwebdesign** [comment]
Just remember to return to the v6 branch using `pihole checkout web development-v6`.

**Comment by mwoolweaver** [comment]
yes i have switched back, thank you for the reminder. 

for anyone in the future that comes across this there is a work around via uBlock Origin

add the following to your custom filters

`pi.hole##div.col-lg-6:has-text(No data)`

without the filter  & privacy mode is Hide domains 
![without_uBlock](https://github.com/pi-hole/web/assets/5729320/e5a253ed-03c3-4204-8f0f-82e13f5a7ec2)


with the filter & privacy mode is Hide domains 
![with_uBlock](https://github.com/pi-hole/web/assets/5729320/b10e9ace-c350-4a89-be31-7848e89bb198)

**Comment by mwoolweaver** [comment]
> Yes. But I think it's fine to show the empty table with "No data".

@yubiuser  shouldn't all empty graphs be treated the same?? the clients over time graph gets hidden when it has no data to show (e.g. when privacy mode is `Hide domains and clients` or `Anonymous mode`)

![cot](https://github.com/pi-hole/web/assets/5729320/2fb54548-d178-49d3-a72d-79e3864c78a0)

see #3072 for more information
