### ISSUE TITLE
Use user-friendly names when selecting the language to use

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#311]
In the preferences, the language selection box uses the language code to identify each language, such as `en` for `English`:
![image](https://user-images.githubusercontent.com/4417660/60483038-addc8700-9c48-11e9-957d-bd753840b146.png)

We should use the name of the language instead of the language codes when displaying them.

This could be accomplished by modifying `scripts/generate-language-list.js` to generate a list of objects instead of just strings, so we can include more information. Then use a library like [`iso-639-1`] to lookup the name to use for each language code. The consumers of the generated language list (`i18n.tsx` and `PreferenceSettings.tsx`) would need to be modified accordingly.

Example entry in the list generated by `generate-language-list.js`:
```json
{
    "code": "en",
    "name": "English"
}
```

[`iso-639-1`]: https://www.npmjs.com/package/iso-639-1

**Comment by rajannpatel** [comment]
This is a juicy one; looking forward to jumping into this! Unable to assign this to myself, but I'll begin working on this on Sunday night as well, unless somebody else beats me to the punch!

**Comment by slavabez** [comment]
Hello there, does this issue still need help?

I'd be happy to look into it as well as the 'values too long' issue. I contributed a little for last years Hacktoberfest, would be happy to work on this some more. I helped with #94

**Comment by rajannpatel** [comment]
I'm sorry I fell behind on these, I don't want to hold things up - please feel free to jump in if you have the capacity!

**Comment by Mcat12** [comment]
@slavabez I will likely handle the changes I requested on #367 since @isdampe has not responded yet. That will close this issue.

**Comment by slavabez** [comment]
Gotcha! Hacktoberfest is happening at at the moment, so lots of people might be willing to help, especially with simple issues
