### ISSUE TITLE
UI does not suggest ICANN recommended TLD for internal networks

### ISSUE THREAD

**Issue by DaGeek247** [pi-hole/web#3122]
### Versions

  Pi-hole version is v5.18.3 (Latest: v5.18.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

- Platform:  Raspberry Pi4 2GB

### Expected behavior

ICANN finally picked a TLD to use for private internal networks. See the announcement: https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-special-meeting-of-the-icann-board-29-07-2024-en#section2.a. The WebUI should suggest .internal for the local domain name in the Settings > DNS > conditional formatting, as well as anywhere else that it is relevant.

### Actual behavior / bug

Currently, the WebUI suggests the incorrect .local (reserved for mDNS: https://en.wikipedia.org/wiki/.local ), even though we now have an actual default to use. This may also be present in other locations. I am unfamiliar with all the workings of the webui and other part of pihole.

### Steps to reproduce

1. Load the Settings > DNS page in the pihole web ui.
2. Scroll to the bottom of the page, and remove anything from the "Local domain name (optional)" section, if it exists.
3. See incorrectly suggested TLD in the grey color.

### Screenshots

![Screenshot of section of webui with incorrect TLD suggestion](https://github.com/user-attachments/assets/55b7d898-ea51-4580-b264-61e3aad4b425)

### Additional context

This was a change from ICANN made July 2024.

**Comment by yubiuser** [comment]
Pi-hole uses `lan` as local domain name when used as a DHCP server. 

The setting you mentioned is part of the conditional forwarding section and allows users to conditional forwarding queries for reverse DNS resolution. Entering a local domain is option and defines CF based on the domain name. This domain name should match what is used by the local DHCP server, which is the user's router most often. And a lot use `local` as domain name.

As the help text states

> You can also specify a local domain name (like fritz.box) to ensure queries to devices ending in your local domain name will not leave your network, however, this is optional. The local domain name must match the domain name specified in your DHCP server for this to work. You can likely find it within the DHCP settings

So, I don't see a bug here.
