### ISSUE TITLE
PHP8.3 - Pihole Admin deprecated php commands

### ISSUE THREAD

**Issue by olli3** [pi-hole/web#3176]
### Versions

  **Pi-hole version is v5.18.3 (Latest: v5.18.3)
  web version is v5.21-4-g5c8945c (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)**

### Platform

- **OS and version:  	Debian GNU/Linux 11 (bullseye)**

### Expected behavior

_A clear and concise description of what you expected to happen._

**PHP8.3  many deprecated php commands including utf8_encode**

### Actual behavior / bug

**admin interface is broken due to often bad JSON going to datatables because of php warnings / deprecation errors (if on on server)**

### Steps to reproduce

1. upograde to php8.3
2. login and navigate to admin pages 

FILES CHANGED LOCALLY TO FIX  - changed utf_encode) to mb_convert_encoding(VAR, 'UTF-8', 'ISO-8859-1')

	modified:   api_FTL.php
	modified:   api_db.php
	modified:   composer.lock
	modified:   scripts/pi-hole/php/auth.php
	modified:   scripts/pi-hole/php/groups.php

=

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
With the upcoming Pi-hole version 6 PHP is gone.

**Comment by rdwebdesign** [comment]
As explained by ***yubiuser***, the current version in development doesn't use PHP and the PHP code probably won't be fixed.

As a temporary fix, you can hide the PHP deprecation messages in your system adding `& ~E_DEPRECATED` to `error_reporting` in your `php.ini`, like this:
```
error_reporting = E_ALL & ~E_STRICT & ~E_DEPRECATED
```

**Comment by olli3** [comment]
@both acknowledged and thanks 

I’ve fixed the php code myself instead of disabling the messages in my server .. I’d rather see them myself …

Look forward to the new version 

Keep it real out there 

O
