### ISSUE TITLE
Missing file css/style.css

### ISSUE THREAD

**Issue by rrobgill** [pi-hole/web#32]
This file seems to be missing from both the master and dev branches.

I grabbed a copy from http://web.pi-hole.io/css/style.css and it made a bit happier.
![2018-06-07_21 53 33](https://user-images.githubusercontent.com/35944068/41098151-c9676dba-6a9d-11e8-86ba-fe4ab5c87723.png)
![2018-06-07_21 56 37](https://user-images.githubusercontent.com/35944068/41098150-c90b4148-6a9d-11e8-8139-be511c960913.png)

**Comment by Mcat12** [comment]
That file is generated when you run `npm run gulp sass`. I guess that should be added to the readme.
