### ISSUE TITLE
Looped page redirection on development branch

### ISSUE THREAD

**Issue by isdampe** [pi-hole/web#365]
On the development branch, using the `npm run start-fake` launches the server with fake data, opens the browser, and renders the `web` interface. However, the page continuously redirects in rapid succession.

Observed on Ubuntu 19.04 x64, Node v10.16.2

Occurs on all tested browsers below, including on fresh browser profiles

* Firefox 68.0.1 (64-bit), in both standard and private mode
* Chromium 76.0.3809.100 (64-bit), in both standard and incognito mode
* Epiphany (aka Gnome WEB) - latest bundled version

To reproduce:

```bash
git clone https://github.com/pi-hole/web.git
git checkout development
git pull
npm install
npm run start-fake
```
Example video (MKV, H.264)
[web-bug.zip](https://github.com/pi-hole/web/files/3496198/web-bug.zip)

**Comment by isdampe** [comment]
It appears this issue began with 2abb318f003f08c3fbff86afc6c78b5aadf6bf59.

Works as normal:
```bash
git checkout a091867c26f49b417700ddfb16b45d8509d70721
npm run start-fake
```
Does not work:
```bash
git checkout 2abb318f003f08c3fbff86afc6c78b5aadf6bf59
npm run start fake
```

**Comment by Mcat12** [comment]
Thanks, I've reproduced this now and am working on a solution.

**Comment by Mcat12** [comment]
@isdampe @rajannpatel In the mean time, you can manually add a cookie with the key `user_id`. This will make the web interface start up in the logged-in state.
