### ISSUE TITLE
Add lgtm in the repo

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/web#446]
https://lgtm.com/ is owned by GitHub and IMHO it can give great insights for issues the usual linters can't catch. I suggest that you guys add it to the repo as an extra precautionary step :)

For the default branch you can check the current warnings here: https://lgtm.com/projects/g/pi-hole/web/?mode=list

PS. the same could be done for the AdminLTE repo; I already submitted [a PR](https://github.com/pi-hole/AdminLTE/pull/1064) for some of the issues but being that this repo will replace that one maybe you guys don't want to do it.

**Comment by dschaper** [comment]
Enabled and installed for AdminLTE and NGWeb.
