### ISSUE TITLE
Serious Vulnerabilities after Build

### ISSUE THREAD

**Issue by Pazekal90** [pi-hole/web#448]
Serious Vulnerabilities after Build. Should be fixed really soon before this software is used in production. 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/25208775/70571985-2a33a880-1b9f-11ea-81d5-c98bdc9e93ad.png">

**Comment by XhmikosR** [comment]
@PromoFaux @dschaper can you guys enable automated security fixes for this repo and the AdminLTE repo if you haven't already?

**Comment by DL6ER** [comment]
@Pazekal90 Did you observe this when building `master` or `development` ?
The `master` branch is currently lacking a good amount behind as we're doing all the development on other branches.

**Comment by Pazekal90** [comment]
@DL6ER I have just forked the web repo with master branch and did npm run start-fake. I will have a look on the development one.

**Comment by dschaper** [comment]
Automated security alerts have been enabled for a while. I don't see anything coming up though.

**Comment by XhmikosR** [comment]
All good then. master is just behind.

**Comment by Pazekal90** [comment]
Thats the status in development-FTL branch
<img width="565" alt="image" src="https://user-images.githubusercontent.com/25208775/70573187-b5ae3900-1ba1-11ea-954f-73e2c287f8ee.png">

**Comment by XhmikosR** [comment]
That's nothing to worry about, they'll be solved after the open deps PR are merged. I also plan to make a new deps PR later, but since we have automated security fixes we don't need to worry about at this point.
