### ISSUE TITLE
MAC address in 'Currently Active DHCP leases' have incorrect formatting

### ISSUE THREAD

**Issue by aled** [pi-hole/web#505]
In Settings -> DHCP -> DHCP leases, some of the MAC addresses are shown in a weird format.

Instead of the normal format (e.g. 68:00:E4:53:12:4F), they just have numbers, (e.g. 87099222).  This looks like it happens for IPv6 addresses only.

**Comment by dschaper** [comment]
IPv6 uses DUID instead of MAC addresses. It's part of the privacy features.

**Comment by aled** [comment]
Ah, I see, thanks. Couple more questions if I may?
  - Some of the DUIDs are showing as '0' - is this normal?
  - Is it possible to configure a static IPv6 lease?

**Comment by XhmikosR** [comment]
Closing since this isn't really a bug. I also have the above questions so I think it will benefit everyone if you asked in the forum.
