### ISSUE TITLE
Option to allow integration of the web ui in a iframe

### ISSUE THREAD

**Issue by gsemet** [pi-hole/web#67]
Currently, PiHole web interface prevents integration inside an iframe (for example, in a panel on home assistant). The lighttpd hardcodes `X-Frame-Options` option, that needs to be commented in ordre to enable Phiole in iframe:
```
X-Frame-Options" => "DENY"
```
Is is possible to add an option to allow users to disable this settings and keep it accross updates?

**Comment by Mcat12** [comment]
Yes, that might be good. However, you should also post this feature request on Discourse in the feature request section.

**Comment by gsemet** [comment]
Indeed. Done in: https://discourse.pi-hole.net/t/option-to-allow-integration-of-the-web-ui-in-a-iframe/10797

**Comment by Macley-Kun** [comment]
Is there an update on this? Trying out the same aswell.

Is there a way to set this explict in: /etc/lighttpd/external.conf ? So it survives updates aswell :-) ?

**Comment by Mcat12** [comment]
Closing as this is not an issue with the PHP web interface, not this web interface, and as a feature request it has been moved to Discourse.
