### ISSUE TITLE
Don't Show Versions In Footer

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#83]
The footer (`Footer.js`) currently has fake values for the versions of Core and Web. As per #12, the footer should be simplified to only show "Update Available" when updates are available, otherwise nothing (experimenting with the design showed that having nothing in the corner when up-to-date looks best, but this can be debated).

Because checking for updates is not yet implemented, the footer should not show anything in the bottom right corner.

**Comment by miro1091** [comment]
Hi, can I solve this issue ?

**Comment by Mcat12** [comment]
Sure, I'm available for mentoring.

**Comment by miro1091** [comment]
hi :) I have forked repo and i have  cloned it, after that switch to development branch, but in that branch i cant find Footer.js in component folder, but in master branch is it, can you help me with that ? thanks

**Comment by Mcat12** [comment]
It is in the `components/common` folder.

**Comment by miro1091** [comment]
#97

**Comment by Mcat12** [comment]
Closed by #97
