### ISSUE TITLE
Validate Regex in Blacklist (Regex)

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/web#85]
Validate the input regex in blacklist (regex) before trying to add it. This can be done by trying to compile the regex in a try/catch block (this is effectively what the API does): https://stackoverflow.com/a/17250859

**Comment by miro1091** [comment]
Can I work on this ? :)

**Comment by Mcat12** [comment]
Sure, any "good first issue" can be worked on by anyone.

**Comment by bgalek** [comment]
@miro1091 hope you didn't start yet ;)

**Comment by miro1091** [comment]
I did it on localhost, but only on master branch, because development branch doesn't contain any js files :), can i still work on it ?
